// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_JitBlue_Runtime_114570_runtime_114570 = coreclr_test({
    name: "Runtime_114570",
    srcs: ["Runtime_114570.cs"],
    optimize: true,
});
