// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_Regression_JitBlue_GitHub_23861_gitHub_23861 = CoreClr.coreclr_test({
    name: "GitHub_23861",
    srcs: ["GitHub_23861.cs"],
    optimize: true,
});
