// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const ilasm_ilasm_tests = CoreClr.coreclr_test({
    name: "ilasm_tests",
    srcs: ["PortablePdb/IlasmPortablePdbTester.cs", "PortablePdb/IlasmPortablePdbTesterCommon.cs", "PortablePdb/IlasmPortablePdbTesterTypes.cs", "MethodImplOptions/MethodImplOptionsTests.cs"],
    tags: ["manual"],
});
