<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Needed for NativeAotIncompatible -->
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <RequiresMockHostPolicy>true</RequiresMockHostPolicy>
    <CLRTestTargetUnsupported Condition="'$(RuntimeFlavor)' == 'coreclr' and '$(TargetOS)' == 'browser'">true</CLRTestTargetUnsupported>
    <!-- AssemblyDependencyResolver is not supported -->
    <NativeAotIncompatible>true</NativeAotIncompatible>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="AssemblyDependencyResolverTests.cs" />
    <Compile Include="NativeDependencyTests.cs" />
    <Compile Include="TestBase.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="$(TestLibraryProjectPath)" />
  </ItemGroup>
</Project>
