// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_HardwareIntrinsics_General_ConstantFolding_staticReadonlySimd = CoreClr.coreclr_test({
    name: "StaticReadonlySimd",
    srcs: ["StaticReadonlySimd.cs"],
    optimize: true,
});

@@public
export const jIT_HardwareIntrinsics_General_ConstantFolding_scalarConstantFoldings = CoreClr.coreclr_test({
    name: "ScalarConstantFoldings",
    srcs: ["ScalarConstantFoldings.cs"],
    optimize: true,
});

@@public
export const jIT_HardwareIntrinsics_General_ConstantFolding_simdConstantFoldings = CoreClr.coreclr_test({
    name: "SimdConstantFoldings",
    srcs: ["SimdConstantFoldings.cs"],
    optimize: true,
});
