// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_JitBlue_Runtime_77636_runtime_77636 = coreclr_test({
    name: "Runtime_77636",
    srcs: ["Runtime_77636.cs"],
    allowUnsafe: true,
    optimize: true,
});
