// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_CLR_x86_EJIT_v1_m10_b02353_b02353 = coreclr_test({
    name: "b02353",
    srcs: ["b02353.cs"],
    debugType: "pdbonly",
    pri: 1,
    size: "medium",
});
