<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <ReferenceXUnitWrapperGenerator>false</ReferenceXUnitWrapperGenerator>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GCStressIncompatible>true</GCStressIncompatible>
    <CLRTestTargetUnsupported Condition="'$(TargetsAppleMobile)' == 'true' or '$(TargetsAndroid)' == 'true' or '$(TargetsBrowser)' == 'true' or '$(TargetsWasi)' == 'true'">true</CLRTestTargetUnsupported>
    <CLRTestTargetUnsupported Condition="'$(RuntimeFlavor)' != 'coreclr'">true</CLRTestTargetUnsupported>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="ThreadStateDestroyed.cs" />
    <ProjectReference Include="$(TestLibraryProjectPath)" />
  </ItemGroup>
  <ItemGroup>
    <CMakeProjectReference Include="CMakeLists.txt" />
  </ItemGroup>
</Project>
