// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const loader_classloader_explicitlayout_Regressions_ASURT_ASURT150271_bigdat = CoreClr.il_coreclr_test({
    name: "bigdat",
    srcs: ["bigdat.il"],
    pri: 1,
    size: "medium",
});

@@public
export const loader_classloader_explicitlayout_Regressions_ASURT_ASURT150271_test10 = CoreClr.il_coreclr_test({
    name: "test10",
    srcs: ["test10.il"],
    pri: 1,
    size: "medium",
});

@@public
export const loader_classloader_explicitlayout_Regressions_ASURT_ASURT150271_test11 = CoreClr.il_coreclr_test({
    name: "test11",
    srcs: ["test11.il"],
    pri: 1,
    size: "medium",
});

@@public
export const loader_classloader_explicitlayout_Regressions_ASURT_ASURT150271_test13 = CoreClr.il_coreclr_test({
    name: "test13",
    srcs: ["test13.il"],
});

@@public
export const loader_classloader_explicitlayout_Regressions_ASURT_ASURT150271_test14 = CoreClr.il_coreclr_test({
    name: "test14",
    srcs: ["test14.il"],
    pri: 1,
    size: "medium",
});

@@public
export const loader_classloader_explicitlayout_Regressions_ASURT_ASURT150271_test15 = CoreClr.il_coreclr_test({
    name: "test15",
    srcs: ["test15.il"],
    pri: 1,
    size: "medium",
});

@@public
export const loader_classloader_explicitlayout_Regressions_ASURT_ASURT150271_test16 = CoreClr.il_coreclr_test({
    name: "test16",
    srcs: ["test16.il"],
    pri: 1,
    size: "medium",
    run: false,
});

@@public
export const loader_classloader_explicitlayout_Regressions_ASURT_ASURT150271_test2 = CoreClr.il_coreclr_test({
    name: "test2",
    srcs: ["test2.il"],
    pri: 1,
    size: "medium",
});

@@public
export const loader_classloader_explicitlayout_Regressions_ASURT_ASURT150271_test21 = CoreClr.il_coreclr_test({
    name: "test21",
    srcs: ["test21.il"],
    pri: 1,
    size: "medium",
    run: false,
});

@@public
export const loader_classloader_explicitlayout_Regressions_ASURT_ASURT150271_test23 = CoreClr.il_coreclr_test({
    name: "test23",
    srcs: ["test23.il"],
    pri: 1,
    size: "medium",
});

@@public
export const loader_classloader_explicitlayout_Regressions_ASURT_ASURT150271_test24 = CoreClr.il_coreclr_test({
    name: "test24",
    srcs: ["test24.il"],
    pri: 1,
    size: "medium",
});

@@public
export const loader_classloader_explicitlayout_Regressions_ASURT_ASURT150271_test3 = CoreClr.il_coreclr_test({
    name: "test3",
    srcs: ["test3.il"],
    run: false,
});

@@public
export const loader_classloader_explicitlayout_Regressions_ASURT_ASURT150271_test9 = CoreClr.il_coreclr_test({
    name: "test9",
    srcs: ["test9.il"],
    pri: 1,
    size: "medium",
    run: false,
});
