<!-- Licensed to the .NET Foundation under one or more agreements. The .NET Foundation licenses this file to you under the MIT license. -->
<Project>
  <PropertyGroup>
    <WasmNativeWorkload Condition="'$(WasmNativeWorkload)' == ''">net12.0</WasmNativeWorkload>
    <WasmNativeWorkload12>true</WasmNativeWorkload12>
  </PropertyGroup>
</Project>
