<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(NetCoreAppToolCurrent)</TargetFramework>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CS3021</NoWarn>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsAotCompatible>true</IsAotCompatible>
    <IsShipping>false</IsShipping>
    <ContractProject>$(MSBuildThisFileDirectory)ref\ILAssembler.csproj</ContractProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" Version="$(Antlr4RuntimeStandardVersion)" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="ref\**\*.cs" />
  </ItemGroup>

</Project>
