<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <UnloadabilityIncompatible>true</UnloadabilityIncompatible>
    <CLRTestPriority>1</CLRTestPriority>
    <CLRTestTargetUnsupported Condition="'$(FeatureMultithreading)' != 'true'">true</CLRTestTargetUnsupported>
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
  </PropertyGroup>
  <PropertyGroup>
    <DebugType>Full</DebugType>
    <Optimize>True</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="threads2.cs" />
    <ProjectReference Include="testlib_misc.csproj" />
  </ItemGroup>
</Project>
