#!/bin/sh
#
# Licensed to the .NET Foundation under one or more agreements.
# The .NET Foundation licenses this file to you under the MIT license.
#

PACKAGE=$1
INSTALL_DESTINATION=$2

# A temporary fix for the permissions issue(s)
chmod 755 $INSTALL_DESTINATION/dotnet
mkdir -p /etc/dotnet

# set install_location since it will be different than default on ARM64 machines
echo $INSTALL_DESTINATION | tee /etc/dotnet/install_location

# if we're running on the native architecture
if [[ "$(uname -m)" =~ amd64|x86_64 && "$(sysctl -i -n sysctl.proc_translated)" != "1" ]]; then
    # Add the installation directory to the system-wide paths
    # But first create the directory if it doesn't exist
    mkdir -p /etc/paths.d
    echo $INSTALL_DESTINATION | tee /etc/paths.d/dotnet
fi

exit 0
