// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const loader_classloader_generics_regressions_334376_b334376 = coreclr_test({
    name: "b334376",
    srcs: ["b334376.cs"],
    pri: 1,
    size: "medium",
});
