namespace System.Net.Quic.Implementations.Managed.Internal.OpenSsl
{
    internal enum SslCtrlCommand
    {
        SetTmpDh = 3,
        SetTmpEcdh = 4,
        SetTmpDhCb = 6,
        GetClientCertRequest = 9,
        GetNumRenegotiations = 10,
        ClearNumRenegotiations = 11,
        GetTotalRenegotiations = 12,
        GetFlags = 13,
        ExtraChainCert = 14,
        SetMsgCallback = 15,
        SetMsgCallbackArg = 16,
        /* only applies to datagram connections */
        SetMtu = 17,
        /* Stats */
        SessNumber = 20,
        SessConnect = 21,
        SessConnectGood = 22,
        SessConnectRenegotiate = 23,
        SessAccept = 24,
        SessAcceptGood = 25,
        SessAcceptRenegotiate = 26,
        SessHit = 27,
        SessCbHit = 28,
        SessMisses = 29,
        SessTimeouts = 30,
        SessCacheFull = 31,
        Mode = 33,
        GetReadAhead = 40,
        SetReadAhead = 41,
        SetSessCacheSize = 42,
        GetSessCacheSize = 43,
        SetSessCacheMode = 44,
        GetSessCacheMode = 45,
        GetMaxCertList = 50,
        SetMaxCertList = 51,
        SetMaxSendFragment = 52,
/* see tls1.h for macros based on these */
        SetTlsextServernameCb = 53,
        SetTlsextServernameArg = 54,
        SetTlsextHostname = 55,
        SetTlsextDebugCb = 56,
        SetTlsextDebugArg = 57,
        GetTlsextTicketKeys = 58,

        SetTlsextTicketKeys = 59,
/*, SET_TLSEXT_OPAQUE_PRF_INPUT=  60 */
/*, SET_TLSEXT_OPAQUE_PRF_INPUT_CB 61 */
/*, SET_TLSEXT_OPAQUE_PRF_INPUT_CB_ARG 62 */
        SetTlsextStatusReqCb = 63,
        SetTlsextStatusReqCbArg = 64,
        SetTlsextStatusReqType = 65,
        GetTlsextStatusReqExts = 66,
        SetTlsextStatusReqExts = 67,
        GetTlsextStatusReqIds = 68,
        SetTlsextStatusReqIds = 69,
        GetTlsextStatusReqOcspResp = 70,
        SetTlsextStatusReqOcspResp = 71,
        SetTlsextTicketKeyCb = 72,
        SetTlsExtSrpUsernameCb = 75,
        SetSrpVerifyParamCb = 76,
        SetSrpGiveClientPwdCb = 77,
        SetSrpArg = 78,
        SetTlsExtSrpUsername = 79,
        SetTlsExtSrpStrength = 80,
        SetTlsExtSrpPassword = 81,
        DtlsExtSendHeartbeat = 85,
        GetDtlsExtHeartbeatPending = 86,
        SetDtlsExtHeartbeatNoRequests = 87,
        DtlsCtrlGetTimeout = 73,
        DtlsCtrlHandleTimeout = 74,
        GetRiSupport = 76,
        ClearMode = 78,
        SetNotResumableSessCb = 79,
        GetExtraChainCerts = 82,
        ClearExtraChainCerts = 83,
        Chain = 88,
        ChainCert = 89,
        GetGroups = 90,
        SetGroups = 91,
        SetGroupsList = 92,
        GetSharedGroup = 93,
        SetSigalgs = 97,
        SetSigalgsList = 98,
        CertFlags = 99,
        ClearCertFlags = 100,
        SetClientSigalgs = 101,
        SetClientSigalgsList = 102,
        GetClientCertTypes = 103,
        SetClientCertTypes = 104,
        BuildCertChain = 105,
        SetVerifyCertStore = 106,
        SetChainCertStore = 107,
        GetPeerSignatureNid = 108,
        GetPeerTmpKey = 109,
        GetRawCipherlist = 110,
        GetEcPointFormats = 111,
        GetChainCerts = 115,
        SelectCurrentCert = 116,
        SetCurrentCert = 117,
        SetDhAuto = 118,
        DtlsCtrlSetLinkMtu = 120,
        DtlsCtrlGetLinkMinMtu = 121,
        GetExtmsSupport = 122,
        SetMinProtoVersion = 123,
        SetMaxProtoVersion = 124,
        SetSplitSendFragment = 125,
        SetMaxPipelines = 126,
        GetTlsextStatusReqType = 127,
        GetTlsextStatusReqCb = 128,
        GetTlsextStatusReqCbArg = 129,
        GetMinProtoVersion = 130,
        GetMaxProtoVersion = 131,
        GetSignatureNid = 132,
        GetTmpKey = 133,
        SslCertSetFirst = 1,
        SslCertSetNext = 2,

        SslCertSetServer = 3
    }
}
