// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_JitBlue_Runtime_84693_runtime_84693 = coreclr_test({
    name: "Runtime_84693",
    srcs: ["Runtime_84693.cs"],
    optimize: true,
});
