// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_JitBlue_devdiv_815941_devdiv_815941_ = il_coreclr_test({
    name: "devdiv_815941_",
    srcs: ["devdiv_815941_.il"],
    debugType: "pdbonly",
    optimize: true,
    pri: 1,
    size: "medium",
});
