// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const coreMangLib_system_runtime_interopservices_safehandle_safeHandleDangerousAddRef_PSC = coreclr_test({
    name: "SafeHandleDangerousAddRef_PSC",
    srcs: ["safehandledangerousaddref.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const coreMangLib_system_runtime_interopservices_safehandle_safeHandleDangerousRelease_PSC = coreclr_test({
    name: "SafeHandleDangerousRelease_PSC",
    srcs: ["safehandledangerousrelease.cs"],
    pri: 1,
    size: "medium",
});
