// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_Regression_JitBlue_GitHub_65690_gitHub_65690 = CoreClr.coreclr_test({
    name: "GitHub_65690",
    srcs: ["GitHub_65690.cs"],
    allowUnsafe: true,
    optimize: true,
});
