// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_JitBlue_Runtime_64808_runtime_64808 = coreclr_test({
    name: "Runtime_64808",
    srcs: ["Runtime_64808.cs"],
    allowUnsafe: true,
    optimize: true,
});
