<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Optimize>True</Optimize>
    <!-- Needed for CLRTestEnvironmentVariable -->
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(MSBuildProjectName).cs" />
    <CLRTestEnvironmentVariable Include="DOTNET_TieredCompilation" Value="0" />
    <!-- Needed to prevent morph from folding away NotMask -->
    <CLRTestEnvironmentVariable Include="DOTNET_JitStressModeNames" Value="STRESS_MIN_OPTS STRESS_SPLIT_TREES_RANDOMLY" />
  </ItemGroup>
</Project>
