// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Performance_CodeQuality_Span_spanBench = coreclr_test({
    name: "SpanBench",
    srcs: ["SpanBench.cs"],
    debugType: "pdbonly",
    optimize: true,
});

@@public
export const jIT_Performance_CodeQuality_Span_indexer = coreclr_test({
    name: "Indexer",
    srcs: ["Indexer.cs"],
    allowUnsafe: true,
    debugType: "pdbonly",
    optimize: true,
});
