#!/bin/bash
#
# Licensed to the .NET Foundation under one or more agreements.
# The .NET Foundation licenses this file to you under the MIT license.
#

PACKAGE=$1
INSTALL_DESTINATION=$2

# A temporary fix for the permissions issue(s)
chmod 755 $INSTALL_DESTINATION/dotnet

if [ -e /etc/dotnet/install_location ]; then
    # clear out any entries for this architecture if they exist
    sed -i old '/^${InstallerTargetArchitecture}=/d' /etc/dotnet/install_location
else
    mkdir -p /etc/dotnet    
fi

echo ${InstallerTargetArchitecture}=$INSTALL_DESTINATION | tee -a /etc/dotnet/install_location

# if we're running on the native architecture
if [[ "$(uname -m)" =~ "${UnameMachineRegex}" ]]; then
    # Add the installation directory to the system-wide paths
    # But first create the directory if it doesn't exist
    mkdir -p /etc/paths.d
    echo $INSTALL_DESTINATION | tee /etc/paths.d/dotnet
fi

exit 0
