<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Needed for MonoAotIncompatible -->
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <MonoAotIncompatible>true</MonoAotIncompatible>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="UnsafeAccessorsTests.cs" />
    <Compile Include="UnsafeAccessorsTests.Generics.cs" />
    <Compile Include="UnsafeAccessorsTests.Types.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="$(TestLibraryProjectPath)" />
    <ProjectReference Include="PrivateLib.csproj" />
  </ItemGroup>
</Project>
