// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Generics_Arrays_TypeParameters_MultiDim_class01_TypeParameters_MultiDim = coreclr_test({
    name: "class01_TypeParameters_MultiDim",
    srcs: ["class01.cs"],
    debugType: "pdbonly",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Generics_Arrays_TypeParameters_MultiDim_struct01_struct01_csproj = coreclr_test({
    name: "struct01_struct01.csproj",
    srcs: ["struct01.cs"],
    debugType: "pdbonly",
    pri: 1,
    size: "medium",
});
