// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_CLR_x86_JIT_v2_1_DDB_b174294_b174294 = il_coreclr_test({
    name: "b174294",
    srcs: ["b174294.il"],
    debugType: "pdbonly",
    optimize: true,
    pri: 1,
    size: "medium",
});
