// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const reflection_SetValue_trySetReadonlyStaticField = CoreClr.coreclr_test({
    name: "TrySetReadonlyStaticField",
    srcs: ["TrySetReadonlyStaticField.cs"],
    run: false,
});

@@public
export const reflection_SetValue_trySetReadonlyStaticField2 = CoreClr.coreclr_test({
    name: "TrySetReadonlyStaticField2",
    srcs: ["TrySetReadonlyStaticField2.cs"],
    run: false,
});
