<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Needed for UnloadabilityIncompatible -->
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CLRTestPriority>1</CLRTestPriority>
    <CLRTestTargetUnsupported Condition="'$(FeatureMultithreading)' != 'true'">true</CLRTestTargetUnsupported>
    <!-- This test leaves secondary threads running at exit -->
    <UnloadabilityIncompatible>true</UnloadabilityIncompatible>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="NestedException.cs" />
  </ItemGroup>
</Project>
