// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Diagnostics.CodeAnalysis;

[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetConstructor(System.Type,System.Type[])")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetConstructors(System.Type)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetConstructors(System.Type,System.Reflection.BindingFlags)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetDefaultMembers(System.Type)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetEvent(System.Type,System.String)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetEvent(System.Type,System.String,System.Reflection.BindingFlags)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetEvents(System.Type)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetEvents(System.Type,System.Reflection.BindingFlags)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetField(System.Type,System.String)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetField(System.Type,System.String,System.Reflection.BindingFlags)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetFields(System.Type)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetFields(System.Type,System.Reflection.BindingFlags)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetMember(System.Type,System.String)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetMember(System.Type,System.String,System.Reflection.BindingFlags)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetMembers(System.Type)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetMembers(System.Type,System.Reflection.BindingFlags)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetMethod(System.Type,System.String)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetMethod(System.Type,System.String,System.Reflection.BindingFlags)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetMethod(System.Type,System.String,System.Type[])")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetMethods(System.Type)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetMethods(System.Type,System.Reflection.BindingFlags)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetNestedType(System.Type,System.String,System.Reflection.BindingFlags)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetNestedTypes(System.Type,System.Reflection.BindingFlags)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetProperties(System.Type)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetProperties(System.Type,System.Reflection.BindingFlags)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetProperty(System.Type,System.String)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetProperty(System.Type,System.String,System.Reflection.BindingFlags)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetProperty(System.Type,System.String,System.Type)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Reflection.TypeExtensions.GetProperty(System.Type,System.String,System.Type,System.Type[])")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2026", Scope = "member", Target = "M:System.Reflection.AssemblyExtensions.GetExportedTypes(System.Reflection.Assembly)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2026", Scope = "member", Target = "M:System.Reflection.AssemblyExtensions.GetTypes(System.Reflection.Assembly)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Runtime.Serialization.FormatterServices.GetSafeUninitializedObject(System.Type)")]
