#!/bin/sh

# Licensed to the .NET Foundation under one or more agreements.
# The .NET Foundation licenses this file to you under the MIT license.

SCRIPT="$(readlink -f "$0")"
DIR="$(dirname "$SCRIPT")"
DOTNET="$DIR/dotnet"
SDK_VERSION=$("$DOTNET" --list-sdks | tail -1 | cut -d' ' -f1)
SDK_PATH="$DIR/sdk/$SDK_VERSION/dotnet.dll"

"$DOTNET" exec "$SDK_PATH" dnx "$@"
