#
# Defines no supported by the CMAKE build yet
#

#option (MAJOR_IN_MKDEV "Define to 1 if `major', `minor', and `makedev' are declared in <mkdev.h>.")
#option (MAJOR_IN_SYSMACROS "Define to 1 if `major', `minor', and `makedev' are declared in <sysmacros.h>.")
#option (ANDROID_UNIFIED_HEADERS "Whether Android NDK unified headers are used")
#option (MONO_DL_NEED_USCORE "Does dlsym require leading underscore.")
#option (GLIBC_BEFORE_2_3_4_SCHED_SETAFFINITY "Have GLIBC_BEFORE_2_3_4_SCHED_SETAFFINITY")
#option (GLIBC_HAS_CPU_COUNT "GLIBC has CPU_COUNT macro in sched.h")
#option (HAVE_WORKING_SIGALTSTACK "Have a working sigaltstack")
#option (HAVE_EPOLL "epoll_create1")
#option (USE_KQUEUE_FOR_THREADPOOL "Use kqueue for the threadpool")
#option (HAVE_SIOCGIFCONF "Can get interface list")
#option (MONO_XEN_OPT "Xen-specific behaviour")
#option (MONO_SMALL_CONFIG "Reduce runtime requirements (and capabilities)")
#option (MONO_JEMALLOC_ASSERT "Make jemalloc assert for mono")
#option (MONO_JEMALLOC_DEFAULT "Make jemalloc default for mono")
#option (MONO_JEMALLOC_ENABLED "Enable jemalloc usage for mono")
#option (MONO_PRIVATE_CRASHES "Do not include names of unmanaged functions in the crash dump")
#option (DISABLE_STRUCTURED_CRASH "Do not create structured crash files during unmanaged crashes")
#option (ENABLE_MONODROID "Enable runtime support for Monodroid (Xamarin.Android)")
#option (ENABLE_MONOTOUCH "Enable runtime support for Monotouch (Xamarin.iOS and Xamarin.Mac)")
#option (DEFAULT_GC_NAME "GC description")
#option (HAVE_NULL_GC "No GC support.")
#option (MONO_BIG_ARRAYS "Enable the allocation and indexing of arrays greater than Int32.MaxValue")
#option (ENABLE_DTRACE "Enable DTrace probes")
#option (MONO_ARCH_ILP32 "64 bit mode with 4 byte longs and pointers")
#option (__mono_ppc64__ "...")
#option (DISABLE_HW_TRAPS "...")
#option (ENABLE_OVERRIDABLE_ALLOCATORS "Overridable allocator support enabled")
#option (MONO_KEYWORD_THREAD "Have __thread keyword")
#option (HAVE_TLS_MODEL_ATTR "tls_model available")
#option (HAVE_ARMV5 "ARM v5")
#option (HAVE_ARMV6 "ARM v6")
#option (HAVE_ARMV7 "ARM v7")
#option (RISCV_FPABI_DOUBLE "RISC-V FPABI is double-precision")
#option (RISCV_FPABI_SINGLE "RISC-V FPABI is single-precision")
#option (RISCV_FPABI_SOFT "RISC-V FPABI is soft float")
#option (USE_MALLOC_FOR_MEMPOOLS "Use malloc for each single mempool allocation")
#option (ENABLE_EXPERIMENTS "Enable feature experiments")
#option (ENABLE_EXPERIMENT_null "Enable experiment 'null'")
#option (ENABLE_EXPERIMENT_TIERED "Enable experiment 'Tiered Compilation'")
