// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

                                                      
/**************************************************************************************
 **                                                                                  **
 ** Mscoree_tlb.idl - mscoree.idl + internal intefaces from mscorsvc.dll             **
 **                   Used for making mscoree.tlb                                    **
 **                                                                                  **
 **************************************************************************************/

#define INCLUDE_SVC_IDL
#include "mscoree.idl"

