// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const async_cse_array_index_byref_cse_array_index_byref = CoreClr.coreclr_test({
    name: "cse-array-index-byref",
    srcs: ["cse-array-index-byref.cs", "//src/tests/async:RuntimeAsyncMethodGenerationAttribute.cs"],
    compilerOptions: ["/features:runtime-async=on", "/nowarn:SYSLIB5007"],
    optimize: true,
    tags: ["manual"],
});
