// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_jit64_regress_vsw_552940_test_552940 = il_coreclr_test({
    name: "test_552940",
    srcs: ["test.il"],
    debugType: "pdbonly",
    optimize: true,
    pri: 1,
    size: "medium",
});
