<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <OutputType>Library</OutputType>
    <SkipTestRun>true</SkipTestRun>
    <TargetFramework>$(NetCoreAppToolCurrent)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ReferencedAssemblyAttribute.cs" />
  </ItemGroup>
</Project>
