// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_Generics_TypeParameters_default_struct01 = CoreClr.coreclr_test({
    name: "default_struct01",
    srcs: ["default_struct01.cs"],
    debugType: "pdbonly",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Generics_TypeParameters_default_class01 = CoreClr.coreclr_test({
    name: "default_class01",
    srcs: ["default_class01.cs"],
    debugType: "pdbonly",
    pri: 1,
    size: "medium",
});
