// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_CLR_x86_JIT_V1_M09_5_PDC_b26324_b26324a = il_coreclr_test({
    name: "b26324a",
    srcs: ["b26324a.il"],
    optimize: true,
    pri: 1,
    size: "medium",
    run: false,
});

@@public
export const jIT_Regression_CLR_x86_JIT_V1_M09_5_PDC_b26324_b26324b = il_coreclr_test({
    name: "b26324b",
    srcs: ["b26324b.il"],
    optimize: true,
    pri: 1,
    size: "medium",
    run: false,
});
