// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_JitBlue_GitHub_19910_gitHub_19910 = coreclr_test({
    name: "GitHub_19910",
    srcs: ["GitHub_19910.cs"],
    optimize: true,
});
