<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Needed for CMakeProjectReference -->
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <Optimize>True</Optimize>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <!-- These platforms do not support native test assets: https://github.com/dotnet/runtime/issues/123946
         Browser wasm on CoreCLR links the native asset into a test-specific corerun, so it is supported there. -->
    <CLRTestTargetUnsupported Condition="('$(TargetsWasm)' == 'true' or '$(TargetsMobile)' == 'true') and ('$(TargetsBrowser)' != 'true' or '$(RuntimeFlavor)' != 'coreclr')">true</CLRTestTargetUnsupported>
  </PropertyGroup>
  <ItemGroup>
    <CMakeProjectReference Include="CMakeLists.txt" />
    <Compile Include="$(MSBuildProjectName).cs" />
  </ItemGroup>
</Project>
