// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_JitBlue_DevDiv_544985_devDiv_544985 = il_coreclr_test({
    name: "DevDiv_544985",
    srcs: ["DevDiv_544985.il"],
    optimize: true,
});
