<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <CLRTestPriority>1</CLRTestPriority>
    <DebugType>PdbOnly</DebugType>
    <!-- https://github.com/dotnet/runtime/issues/132942 -->
    <MonoAotIncompatible>true</MonoAotIncompatible>
    <!-- Needed for MonoAotIncompatible -->
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="chaos65204782cs.cs" />
    <ProjectReference Include="$(TestLibraryProjectPath)" />
  </ItemGroup>
</Project>
