// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_Regression_JitBlue_GitHub_7508_vector3Test = CoreClr.coreclr_test({
    name: "Vector3Test",
    srcs: ["Vector3Test.cs"],
    optimize: true,
});
