<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <CLRTestPriority>1</CLRTestPriority>
    <!-- Needed for CLRTestEnvironmentVariable -->
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <DebugType>None</DebugType>
    <Optimize>True</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(MSBuildProjectName).cs" />

    <!-- Count must reach tier-1 with PGO data, since conditional escape
         analysis requires profile weights. -->
    <CLRTestEnvironmentVariable Include="DOTNET_TieredCompilation" Value="1" />
    <CLRTestEnvironmentVariable Include="DOTNET_TieredPGO" Value="1" />
  </ItemGroup>
</Project>
