<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <CLRTestPriority>1</CLRTestPriority>
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <DebugType>None</DebugType>
    <Optimize>True</Optimize>
    <DefineConstants>$(DefineConstants);STRUCT_ENUMERATOR</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Runtime_134605.cs" />

    <CLRTestEnvironmentVariable Include="DOTNET_TieredCompilation" Value="1" />
    <CLRTestEnvironmentVariable Include="DOTNET_TieredPGO" Value="1" />
    <CLRTestEnvironmentVariable Include="DOTNET_TC_QuickJitForLoops" Value="1" />
  </ItemGroup>
</Project>
