// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_JitBlue_Runtime_105479_runtime_105479 = coreclr_test({
    name: "Runtime_105479",
    srcs: ["Runtime_105479.cs"],
    optimize: true,
});
