<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Needed for GCSettings.LargeObjectHeapCompactionMode, GCStressIncompatible -->
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <GCStressIncompatible>true</GCStressIncompatible>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="lohalignment.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="$(TestLibraryProjectPath)" />
  </ItemGroup>
</Project>
