// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_CLR_x86_JIT_v2_1_DDB_b19679_b19679 = coreclr_test({
    name: "b19679",
    srcs: ["b19679.cs"],
    debugType: "full",
    optimize: true,
});
