// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Methodical_acceptance_Boxing_boxing001 = il_coreclr_test({
    name: "boxing001",
    srcs: ["boxing001.il"],
    optimize: true,
    pri: 1,
    size: "medium",
});
