// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_JitBlue_DevDiv_718151_devDiv_718151 = coreclr_test({
    name: "DevDiv_718151",
    srcs: ["DevDiv_718151.cs"],
    optimize: true,
});
