// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_JitBlue_Runtime_91174_runtime_91174 = coreclr_test({
    name: "Runtime_91174",
    srcs: ["Runtime_91174.cs"],
    optimize: true,
});
