// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

import "CLRPrivBinding.idl";

//=====================================================================================================================
// CLRPrivRuntime
//=====================================================================================================================
[
    uuid("EA6A2170-8F6A-4007-87A9-02429F615958")
]
library CLRPrivRuntimeBinders
{
    //=================================================================================================================
    // CLRPrivAppXBinder
    //=================================================================================================================
    [
        uuid(E990F732-2D0A-48AC-87FC-EF12B618981A),
        helpstring("Runtime-provided package-based assembly binder for AppX."),
    ]
    coclass CLRPrivAppXBinder
    {
        [default] interface ICLRPrivBinder;
    };

    //=================================================================================================================
    // CLRPrivFusionBinder
    //=================================================================================================================
    [
        uuid(E990F732-2D0A-48AC-87FC-EF12B618981C),
        helpstring("Runtime-provided binder for wrapping ICLRPrivBinder-compatible subset of fusion functionality."),
    ]
    coclass CLRPrivFusionBinder
    {
        [default] interface ICLRPrivBinder;
    };
};

