// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_jit64_regress_vsw_560402_opadd = coreclr_test({
    name: "opadd",
    srcs: ["opadd.cs"],
    allowUnsafe: true,
    debugType: "pdbonly",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_jit64_regress_vsw_560402_opsub = coreclr_test({
    name: "opsub",
    srcs: ["opsub.cs"],
    allowUnsafe: true,
    debugType: "pdbonly",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_jit64_regress_vsw_560402_opmul = coreclr_test({
    name: "opmul",
    srcs: ["opmul.cs"],
    allowUnsafe: true,
    debugType: "pdbonly",
    pri: 1,
    size: "medium",
});
