<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Optimize>False</Optimize>
    <HasMergedInTests>True</HasMergedInTests>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Regression_9\GitHub_13486.cs" />
    <Compile Include="..\Regression_9\GitHub_16443.cs" />
    <Compile Include="..\Regression_9\GitHub_6238.cs" />
    <Compile Include="..\Regression_9\Runtime_105621.cs" />
    <Compile Include="..\Regression_9\Runtime_105821.cs" />
    <Compile Include="..\Regression_9\Runtime_106020.cs" />
    <Compile Include="..\Regression_9\Runtime_112871.cs" />
    <Compile Include="..\Regression_9\Runtime_113829.cs" />
    <Compile Include="..\Regression_9\Runtime_67331.cs" />
    <Compile Include="..\Regression_9\Runtime_81356.cs" />
    <Compile Include="..\Regression_o_2\Runtime_62692.cs" />
  </ItemGroup>
  <Import Project="$(TestSourceDir)MergedTestRunner.targets" />
</Project>