<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DebugType>Full</DebugType>
    <Optimize>True</Optimize>
    <HasMergedInTests>True</HasMergedInTests>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="CLR-x86-JIT\v2.1\b561129\b561129.cs" />
    <Compile Include="CLR-x86-JIT\v2.1\b602004\Inline_Vars2.cs" />
    <Compile Include="CLR-x86-JIT\v2.1\DDB\b19679\b19679.cs" />
    <Compile Include="CLR-x86-JIT\v2.1\DDB\b33183\b33183.cs" />
    <Compile Include="..\Regression_ro_1\dev11_20929.cs" />
    <Compile Include="..\Regression_ro_1\DevDiv_876169.cs" />
    <Compile Include="..\$(MSBuildProjectName)\**\*.cs" />
    <Compile Include="..\Regression_ro_1\DevDiv_359736.cs" />
    <Compile Include="..\Regression_ro_1\DevDiv_794115.cs" />
    <Compile Include="..\Regression_ro_1\DevDiv_794631.cs" />
    <Compile Include="..\Regression_ro_1\DevDiv_815940.cs" />
    <Compile Include="..\Regression_ro_1\DevDiv_816617.cs" />
    <Compile Include="..\Regression_ro_1\DevDiv_911875.cs" />
  </ItemGroup>
  <Import Project="$(TestSourceDir)MergedTestRunner.targets" />
</Project>