//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Net.Quic.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("System.Net.Quic.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string net_securityprotocolnotsupported {
            get {
                return ResourceManager.GetString("net_securityprotocolnotsupported", resourceCulture);
            }
        }
        
        public static string net_http_httpmethod_format_error {
            get {
                return ResourceManager.GetString("net_http_httpmethod_format_error", resourceCulture);
            }
        }
        
        public static string net_http_httpmethod_notsupported_error {
            get {
                return ResourceManager.GetString("net_http_httpmethod_notsupported_error", resourceCulture);
            }
        }
        
        public static string net_http_reasonphrase_format_error {
            get {
                return ResourceManager.GetString("net_http_reasonphrase_format_error", resourceCulture);
            }
        }
        
        public static string net_http_copyto_array_too_small {
            get {
                return ResourceManager.GetString("net_http_copyto_array_too_small", resourceCulture);
            }
        }
        
        public static string net_http_headers_not_found {
            get {
                return ResourceManager.GetString("net_http_headers_not_found", resourceCulture);
            }
        }
        
        public static string net_http_headers_single_value_header {
            get {
                return ResourceManager.GetString("net_http_headers_single_value_header", resourceCulture);
            }
        }
        
        public static string net_http_headers_invalid_header_name {
            get {
                return ResourceManager.GetString("net_http_headers_invalid_header_name", resourceCulture);
            }
        }
        
        public static string net_http_headers_invalid_value {
            get {
                return ResourceManager.GetString("net_http_headers_invalid_value", resourceCulture);
            }
        }
        
        public static string net_http_headers_not_allowed_header_name {
            get {
                return ResourceManager.GetString("net_http_headers_not_allowed_header_name", resourceCulture);
            }
        }
        
        public static string net_http_headers_invalid_host_header {
            get {
                return ResourceManager.GetString("net_http_headers_invalid_host_header", resourceCulture);
            }
        }
        
        public static string net_http_headers_invalid_from_header {
            get {
                return ResourceManager.GetString("net_http_headers_invalid_from_header", resourceCulture);
            }
        }
        
        public static string net_http_headers_invalid_etag_name {
            get {
                return ResourceManager.GetString("net_http_headers_invalid_etag_name", resourceCulture);
            }
        }
        
        public static string net_http_headers_invalid_range {
            get {
                return ResourceManager.GetString("net_http_headers_invalid_range", resourceCulture);
            }
        }
        
        public static string net_http_headers_no_newlines {
            get {
                return ResourceManager.GetString("net_http_headers_no_newlines", resourceCulture);
            }
        }
        
        public static string net_http_content_buffersize_exceeded {
            get {
                return ResourceManager.GetString("net_http_content_buffersize_exceeded", resourceCulture);
            }
        }
        
        public static string net_http_content_no_task_returned {
            get {
                return ResourceManager.GetString("net_http_content_no_task_returned", resourceCulture);
            }
        }
        
        public static string net_http_content_stream_already_read {
            get {
                return ResourceManager.GetString("net_http_content_stream_already_read", resourceCulture);
            }
        }
        
        public static string net_http_content_readonly_stream {
            get {
                return ResourceManager.GetString("net_http_content_readonly_stream", resourceCulture);
            }
        }
        
        public static string net_http_content_invalid_charset {
            get {
                return ResourceManager.GetString("net_http_content_invalid_charset", resourceCulture);
            }
        }
        
        public static string net_http_content_stream_copy_error {
            get {
                return ResourceManager.GetString("net_http_content_stream_copy_error", resourceCulture);
            }
        }
        
        public static string net_http_argument_empty_string {
            get {
                return ResourceManager.GetString("net_http_argument_empty_string", resourceCulture);
            }
        }
        
        public static string net_http_client_request_already_sent {
            get {
                return ResourceManager.GetString("net_http_client_request_already_sent", resourceCulture);
            }
        }
        
        public static string net_http_operation_started {
            get {
                return ResourceManager.GetString("net_http_operation_started", resourceCulture);
            }
        }
        
        public static string net_http_client_execution_error {
            get {
                return ResourceManager.GetString("net_http_client_execution_error", resourceCulture);
            }
        }
        
        public static string net_http_client_absolute_baseaddress_required {
            get {
                return ResourceManager.GetString("net_http_client_absolute_baseaddress_required", resourceCulture);
            }
        }
        
        public static string net_http_client_invalid_requesturi {
            get {
                return ResourceManager.GetString("net_http_client_invalid_requesturi", resourceCulture);
            }
        }
        
        public static string net_http_client_http_baseaddress_required {
            get {
                return ResourceManager.GetString("net_http_client_http_baseaddress_required", resourceCulture);
            }
        }
        
        public static string net_http_parser_invalid_base64_string {
            get {
                return ResourceManager.GetString("net_http_parser_invalid_base64_string", resourceCulture);
            }
        }
        
        public static string net_http_handler_noresponse {
            get {
                return ResourceManager.GetString("net_http_handler_noresponse", resourceCulture);
            }
        }
        
        public static string net_http_handler_norequest {
            get {
                return ResourceManager.GetString("net_http_handler_norequest", resourceCulture);
            }
        }
        
        public static string net_http_message_not_success_statuscode {
            get {
                return ResourceManager.GetString("net_http_message_not_success_statuscode", resourceCulture);
            }
        }
        
        public static string net_http_content_field_too_long {
            get {
                return ResourceManager.GetString("net_http_content_field_too_long", resourceCulture);
            }
        }
        
        public static string net_http_log_headers_no_newlines {
            get {
                return ResourceManager.GetString("net_http_log_headers_no_newlines", resourceCulture);
            }
        }
        
        public static string net_http_log_headers_invalid_quality {
            get {
                return ResourceManager.GetString("net_http_log_headers_invalid_quality", resourceCulture);
            }
        }
        
        public static string net_http_log_headers_wrong_email_format {
            get {
                return ResourceManager.GetString("net_http_log_headers_wrong_email_format", resourceCulture);
            }
        }
        
        public static string net_http_handler_not_assigned {
            get {
                return ResourceManager.GetString("net_http_handler_not_assigned", resourceCulture);
            }
        }
        
        public static string net_http_invalid_enable_first {
            get {
                return ResourceManager.GetString("net_http_invalid_enable_first", resourceCulture);
            }
        }
        
        public static string net_http_content_buffersize_limit {
            get {
                return ResourceManager.GetString("net_http_content_buffersize_limit", resourceCulture);
            }
        }
        
        public static string net_http_value_not_supported {
            get {
                return ResourceManager.GetString("net_http_value_not_supported", resourceCulture);
            }
        }
        
        public static string net_http_io_read {
            get {
                return ResourceManager.GetString("net_http_io_read", resourceCulture);
            }
        }
        
        public static string net_http_io_read_incomplete {
            get {
                return ResourceManager.GetString("net_http_io_read_incomplete", resourceCulture);
            }
        }
        
        public static string net_http_io_write {
            get {
                return ResourceManager.GetString("net_http_io_write", resourceCulture);
            }
        }
        
        public static string net_http_chunked_not_allowed_with_empty_content {
            get {
                return ResourceManager.GetString("net_http_chunked_not_allowed_with_empty_content", resourceCulture);
            }
        }
        
        public static string net_http_invalid_cookiecontainer {
            get {
                return ResourceManager.GetString("net_http_invalid_cookiecontainer", resourceCulture);
            }
        }
        
        public static string net_http_invalid_proxyusepolicy {
            get {
                return ResourceManager.GetString("net_http_invalid_proxyusepolicy", resourceCulture);
            }
        }
        
        public static string net_http_invalid_proxy {
            get {
                return ResourceManager.GetString("net_http_invalid_proxy", resourceCulture);
            }
        }
        
        public static string net_http_value_must_be_greater_than {
            get {
                return ResourceManager.GetString("net_http_value_must_be_greater_than", resourceCulture);
            }
        }
        
        public static string MailHeaderFieldInvalidCharacter {
            get {
                return ResourceManager.GetString("MailHeaderFieldInvalidCharacter", resourceCulture);
            }
        }
        
        public static string MailAddressInvalidFormat {
            get {
                return ResourceManager.GetString("MailAddressInvalidFormat", resourceCulture);
            }
        }
        
        public static string MailHeaderFieldMalformedHeader {
            get {
                return ResourceManager.GetString("MailHeaderFieldMalformedHeader", resourceCulture);
            }
        }
        
        public static string InvalidHeaderName {
            get {
                return ResourceManager.GetString("InvalidHeaderName", resourceCulture);
            }
        }
        
        public static string net_cookie_attribute {
            get {
                return ResourceManager.GetString("net_cookie_attribute", resourceCulture);
            }
        }
        
        public static string ArgumentOutOfRange_FileLengthTooBig {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_FileLengthTooBig", resourceCulture);
            }
        }
        
        public static string IO_FileExists_Name {
            get {
                return ResourceManager.GetString("IO_FileExists_Name", resourceCulture);
            }
        }
        
        public static string IO_FileNotFound {
            get {
                return ResourceManager.GetString("IO_FileNotFound", resourceCulture);
            }
        }
        
        public static string IO_FileNotFound_FileName {
            get {
                return ResourceManager.GetString("IO_FileNotFound_FileName", resourceCulture);
            }
        }
        
        public static string IO_PathNotFound_NoPathName {
            get {
                return ResourceManager.GetString("IO_PathNotFound_NoPathName", resourceCulture);
            }
        }
        
        public static string IO_PathNotFound_Path {
            get {
                return ResourceManager.GetString("IO_PathNotFound_Path", resourceCulture);
            }
        }
        
        public static string IO_PathTooLong {
            get {
                return ResourceManager.GetString("IO_PathTooLong", resourceCulture);
            }
        }
        
        public static string IO_SharingViolation_File {
            get {
                return ResourceManager.GetString("IO_SharingViolation_File", resourceCulture);
            }
        }
        
        public static string IO_SharingViolation_NoFileName {
            get {
                return ResourceManager.GetString("IO_SharingViolation_NoFileName", resourceCulture);
            }
        }
        
        public static string UnauthorizedAccess_IODenied_NoPathName {
            get {
                return ResourceManager.GetString("UnauthorizedAccess_IODenied_NoPathName", resourceCulture);
            }
        }
        
        public static string UnauthorizedAccess_IODenied_Path {
            get {
                return ResourceManager.GetString("UnauthorizedAccess_IODenied_Path", resourceCulture);
            }
        }
        
        public static string net_http_content_no_concurrent_reads {
            get {
                return ResourceManager.GetString("net_http_content_no_concurrent_reads", resourceCulture);
            }
        }
        
        public static string net_http_username_empty_string {
            get {
                return ResourceManager.GetString("net_http_username_empty_string", resourceCulture);
            }
        }
        
        public static string net_http_no_concurrent_io_allowed {
            get {
                return ResourceManager.GetString("net_http_no_concurrent_io_allowed", resourceCulture);
            }
        }
        
        public static string net_http_invalid_response {
            get {
                return ResourceManager.GetString("net_http_invalid_response", resourceCulture);
            }
        }
        
        public static string net_http_invalid_response_premature_eof {
            get {
                return ResourceManager.GetString("net_http_invalid_response_premature_eof", resourceCulture);
            }
        }
        
        public static string net_http_invalid_response_missing_frame {
            get {
                return ResourceManager.GetString("net_http_invalid_response_missing_frame", resourceCulture);
            }
        }
        
        public static string net_http_invalid_response_premature_eof_bytecount {
            get {
                return ResourceManager.GetString("net_http_invalid_response_premature_eof_bytecount", resourceCulture);
            }
        }
        
        public static string net_http_invalid_response_chunk_header_invalid {
            get {
                return ResourceManager.GetString("net_http_invalid_response_chunk_header_invalid", resourceCulture);
            }
        }
        
        public static string net_http_invalid_response_chunk_extension_invalid {
            get {
                return ResourceManager.GetString("net_http_invalid_response_chunk_extension_invalid", resourceCulture);
            }
        }
        
        public static string net_http_invalid_response_chunk_terminator_invalid {
            get {
                return ResourceManager.GetString("net_http_invalid_response_chunk_terminator_invalid", resourceCulture);
            }
        }
        
        public static string net_http_invalid_response_status_line {
            get {
                return ResourceManager.GetString("net_http_invalid_response_status_line", resourceCulture);
            }
        }
        
        public static string net_http_invalid_response_status_code {
            get {
                return ResourceManager.GetString("net_http_invalid_response_status_code", resourceCulture);
            }
        }
        
        public static string net_http_invalid_response_status_reason {
            get {
                return ResourceManager.GetString("net_http_invalid_response_status_reason", resourceCulture);
            }
        }
        
        public static string net_http_invalid_response_header_folder {
            get {
                return ResourceManager.GetString("net_http_invalid_response_header_folder", resourceCulture);
            }
        }
        
        public static string net_http_invalid_response_header_line {
            get {
                return ResourceManager.GetString("net_http_invalid_response_header_line", resourceCulture);
            }
        }
        
        public static string net_http_invalid_response_header_name {
            get {
                return ResourceManager.GetString("net_http_invalid_response_header_name", resourceCulture);
            }
        }
        
        public static string net_http_request_aborted {
            get {
                return ResourceManager.GetString("net_http_request_aborted", resourceCulture);
            }
        }
        
        public static string net_http_invalid_response_pseudo_header_in_trailer {
            get {
                return ResourceManager.GetString("net_http_invalid_response_pseudo_header_in_trailer", resourceCulture);
            }
        }
        
        public static string net_http_unix_handler_disposed {
            get {
                return ResourceManager.GetString("net_http_unix_handler_disposed", resourceCulture);
            }
        }
        
        public static string net_http_buffer_insufficient_length {
            get {
                return ResourceManager.GetString("net_http_buffer_insufficient_length", resourceCulture);
            }
        }
        
        public static string net_http_response_headers_exceeded_length {
            get {
                return ResourceManager.GetString("net_http_response_headers_exceeded_length", resourceCulture);
            }
        }
        
        public static string ArgumentOutOfRange_NeedNonNegativeNum {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_NeedNonNegativeNum", resourceCulture);
            }
        }
        
        public static string ArgumentOutOfRange_NeedPosNum {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_NeedPosNum", resourceCulture);
            }
        }
        
        public static string NotSupported_UnreadableStream {
            get {
                return ResourceManager.GetString("NotSupported_UnreadableStream", resourceCulture);
            }
        }
        
        public static string NotSupported_UnwritableStream {
            get {
                return ResourceManager.GetString("NotSupported_UnwritableStream", resourceCulture);
            }
        }
        
        public static string ObjectDisposed_StreamClosed {
            get {
                return ResourceManager.GetString("ObjectDisposed_StreamClosed", resourceCulture);
            }
        }
        
        public static string net_http_feature_requires_Windows10Version1607 {
            get {
                return ResourceManager.GetString("net_http_feature_requires_Windows10Version1607", resourceCulture);
            }
        }
        
        public static string net_http_feature_UWPClientCertSupportRequiresCertInPersonalCertificateStore {
            get {
                return ResourceManager.GetString("net_http_feature_UWPClientCertSupportRequiresCertInPersonalCertificateStore", resourceCulture);
            }
        }
        
        public static string net_http_invalid_proxy_scheme {
            get {
                return ResourceManager.GetString("net_http_invalid_proxy_scheme", resourceCulture);
            }
        }
        
        public static string net_http_request_invalid_char_encoding {
            get {
                return ResourceManager.GetString("net_http_request_invalid_char_encoding", resourceCulture);
            }
        }
        
        public static string net_http_ssl_connection_failed {
            get {
                return ResourceManager.GetString("net_http_ssl_connection_failed", resourceCulture);
            }
        }
        
        public static string net_http_unsupported_chunking {
            get {
                return ResourceManager.GetString("net_http_unsupported_chunking", resourceCulture);
            }
        }
        
        public static string net_http_unsupported_version {
            get {
                return ResourceManager.GetString("net_http_unsupported_version", resourceCulture);
            }
        }
        
        public static string IO_SeekBeforeBegin {
            get {
                return ResourceManager.GetString("IO_SeekBeforeBegin", resourceCulture);
            }
        }
        
        public static string net_ssl_app_protocols_invalid {
            get {
                return ResourceManager.GetString("net_ssl_app_protocols_invalid", resourceCulture);
            }
        }
        
        public static string net_ssl_http2_requires_tls12 {
            get {
                return ResourceManager.GetString("net_ssl_http2_requires_tls12", resourceCulture);
            }
        }
        
        public static string IO_PathTooLong_Path {
            get {
                return ResourceManager.GetString("IO_PathTooLong_Path", resourceCulture);
            }
        }
        
        public static string net_http_request_no_host {
            get {
                return ResourceManager.GetString("net_http_request_no_host", resourceCulture);
            }
        }
        
        public static string net_http_winhttp_error {
            get {
                return ResourceManager.GetString("net_http_winhttp_error", resourceCulture);
            }
        }
        
        public static string net_http_http2_connection_error {
            get {
                return ResourceManager.GetString("net_http_http2_connection_error", resourceCulture);
            }
        }
        
        public static string net_http_http2_stream_error {
            get {
                return ResourceManager.GetString("net_http_http2_stream_error", resourceCulture);
            }
        }
        
        public static string net_MethodNotImplementedException {
            get {
                return ResourceManager.GetString("net_MethodNotImplementedException", resourceCulture);
            }
        }
        
        public static string event_OperationReturnedSomething {
            get {
                return ResourceManager.GetString("event_OperationReturnedSomething", resourceCulture);
            }
        }
        
        public static string net_log_operation_failed_with_error {
            get {
                return ResourceManager.GetString("net_log_operation_failed_with_error", resourceCulture);
            }
        }
        
        public static string net_completed_result {
            get {
                return ResourceManager.GetString("net_completed_result", resourceCulture);
            }
        }
        
        public static string net_invalid_enum {
            get {
                return ResourceManager.GetString("net_invalid_enum", resourceCulture);
            }
        }
        
        public static string net_auth_message_not_encrypted {
            get {
                return ResourceManager.GetString("net_auth_message_not_encrypted", resourceCulture);
            }
        }
        
        public static string net_securitypackagesupport {
            get {
                return ResourceManager.GetString("net_securitypackagesupport", resourceCulture);
            }
        }
        
        public static string SSPIInvalidHandleType {
            get {
                return ResourceManager.GetString("SSPIInvalidHandleType", resourceCulture);
            }
        }
        
        public static string net_http_authconnectionfailure {
            get {
                return ResourceManager.GetString("net_http_authconnectionfailure", resourceCulture);
            }
        }
        
        public static string net_nego_server_not_supported {
            get {
                return ResourceManager.GetString("net_nego_server_not_supported", resourceCulture);
            }
        }
        
        public static string net_nego_protection_level_not_supported {
            get {
                return ResourceManager.GetString("net_nego_protection_level_not_supported", resourceCulture);
            }
        }
        
        public static string net_context_buffer_too_small {
            get {
                return ResourceManager.GetString("net_context_buffer_too_small", resourceCulture);
            }
        }
        
        public static string net_gssapi_operation_failed_detailed {
            get {
                return ResourceManager.GetString("net_gssapi_operation_failed_detailed", resourceCulture);
            }
        }
        
        public static string net_gssapi_operation_failed {
            get {
                return ResourceManager.GetString("net_gssapi_operation_failed", resourceCulture);
            }
        }
        
        public static string net_gssapi_operation_failed_detailed_majoronly {
            get {
                return ResourceManager.GetString("net_gssapi_operation_failed_detailed_majoronly", resourceCulture);
            }
        }
        
        public static string net_gssapi_operation_failed_majoronly {
            get {
                return ResourceManager.GetString("net_gssapi_operation_failed_majoronly", resourceCulture);
            }
        }
        
        public static string net_gssapi_ntlm_missing_plugin {
            get {
                return ResourceManager.GetString("net_gssapi_ntlm_missing_plugin", resourceCulture);
            }
        }
        
        public static string net_ntlm_not_possible_default_cred {
            get {
                return ResourceManager.GetString("net_ntlm_not_possible_default_cred", resourceCulture);
            }
        }
        
        public static string net_nego_not_supported_empty_target_with_defaultcreds {
            get {
                return ResourceManager.GetString("net_nego_not_supported_empty_target_with_defaultcreds", resourceCulture);
            }
        }
        
        public static string net_http_hpack_huffman_decode_failed {
            get {
                return ResourceManager.GetString("net_http_hpack_huffman_decode_failed", resourceCulture);
            }
        }
        
        public static string net_http_hpack_incomplete_header_block {
            get {
                return ResourceManager.GetString("net_http_hpack_incomplete_header_block", resourceCulture);
            }
        }
        
        public static string net_http_hpack_late_dynamic_table_size_update {
            get {
                return ResourceManager.GetString("net_http_hpack_late_dynamic_table_size_update", resourceCulture);
            }
        }
        
        public static string net_http_hpack_bad_integer {
            get {
                return ResourceManager.GetString("net_http_hpack_bad_integer", resourceCulture);
            }
        }
        
        public static string net_http_disposed_while_in_use {
            get {
                return ResourceManager.GetString("net_http_disposed_while_in_use", resourceCulture);
            }
        }
        
        public static string net_http_hpack_large_table_size_update {
            get {
                return ResourceManager.GetString("net_http_hpack_large_table_size_update", resourceCulture);
            }
        }
        
        public static string net_http_server_shutdown {
            get {
                return ResourceManager.GetString("net_http_server_shutdown", resourceCulture);
            }
        }
        
        public static string net_http_hpack_invalid_index {
            get {
                return ResourceManager.GetString("net_http_hpack_invalid_index", resourceCulture);
            }
        }
        
        public static string net_http_hpack_unexpected_end {
            get {
                return ResourceManager.GetString("net_http_hpack_unexpected_end", resourceCulture);
            }
        }
        
        public static string net_http_hpack_encode_failure {
            get {
                return ResourceManager.GetString("net_http_hpack_encode_failure", resourceCulture);
            }
        }
        
        public static string net_http_headers_exceeded_length {
            get {
                return ResourceManager.GetString("net_http_headers_exceeded_length", resourceCulture);
            }
        }
        
        public static string net_http_invalid_header_name {
            get {
                return ResourceManager.GetString("net_http_invalid_header_name", resourceCulture);
            }
        }
        
        public static string net_http_http3_connection_error {
            get {
                return ResourceManager.GetString("net_http_http3_connection_error", resourceCulture);
            }
        }
        
        public static string net_http_http3_stream_error {
            get {
                return ResourceManager.GetString("net_http_http3_stream_error", resourceCulture);
            }
        }
        
        public static string net_http_retry_on_older_version {
            get {
                return ResourceManager.GetString("net_http_retry_on_older_version", resourceCulture);
            }
        }
        
        public static string net_http_content_write_larger_than_content_length {
            get {
                return ResourceManager.GetString("net_http_content_write_larger_than_content_length", resourceCulture);
            }
        }
        
        public static string net_http_qpack_no_dynamic_table {
            get {
                return ResourceManager.GetString("net_http_qpack_no_dynamic_table", resourceCulture);
            }
        }
        
        public static string net_http_request_timedout {
            get {
                return ResourceManager.GetString("net_http_request_timedout", resourceCulture);
            }
        }
        
        public static string net_quic_connectionaborted {
            get {
                return ResourceManager.GetString("net_quic_connectionaborted", resourceCulture);
            }
        }
        
        public static string net_quic_notsupported {
            get {
                return ResourceManager.GetString("net_quic_notsupported", resourceCulture);
            }
        }
        
        public static string net_quic_operationaborted {
            get {
                return ResourceManager.GetString("net_quic_operationaborted", resourceCulture);
            }
        }
        
        public static string net_quic_streamaborted {
            get {
                return ResourceManager.GetString("net_quic_streamaborted", resourceCulture);
            }
        }
    }
}
