// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Performance_CodeQuality_Inlining_inlineGCStruct = coreclr_test({
    name: "InlineGCStruct",
    srcs: ["InlineGCStruct.cs"],
});

@@public
export const jIT_Performance_CodeQuality_Inlining_noThrowInline = coreclr_test({
    name: "NoThrowInline",
    srcs: ["NoThrowInline.cs"],
});
