<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DebugType>None</DebugType>
    <Optimize>False</Optimize>
    <HasMergedInTests>true</HasMergedInTests>
  </PropertyGroup>
  <ItemGroup>
    <MergedWrapperProjectReference Include="ConstrainedCall\class1_r.ilproj" />
    <MergedWrapperProjectReference Include="ConstrainedCall\class2_r.ilproj" />
    <MergedWrapperProjectReference Include="ConstrainedCall\vt1_r.ilproj" />
    <MergedWrapperProjectReference Include="ConstrainedCall\vt2_r.ilproj" />
    <MergedWrapperProjectReference Include="ConstrainedCall\vt3_r.ilproj" />
    <MergedWrapperProjectReference Include="ConstrainedCall\vt4_r.ilproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="ConstrainedCall\class1.cs" />
    <Compile Include="ConstrainedCall\class2.cs" />
    <Compile Include="ConstrainedCall\vt1.cs" />
    <Compile Include="ConstrainedCall\vt2.cs" />
    <Compile Include="ConstrainedCall\vt3.cs" />
    <Compile Include="ConstrainedCall\vt4.cs" />
    <Compile Include="Constraints\Call_instance01.cs" />
  </ItemGroup>

  <Import Project="$(TestSourceDir)MergedTestRunner.targets" />
</Project>
