<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DebugType>PdbOnly</DebugType>
    <HasMergedInTests>true</HasMergedInTests>
  </PropertyGroup>
  <ItemGroup>
    <MergedWrapperProjectReference Include="Coverage\chaos65204782cs.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Arrays\ConstructedTypes\MultiDim\class01.cs" />
    <Compile Include="Arrays\ConstructedTypes\MultiDim\class01_Instance.cs" />
    <Compile Include="Arrays\ConstructedTypes\MultiDim\class01_static.cs" />
    <Compile Include="Arrays\ConstructedTypes\MultiDim\struct01.cs" />
    <Compile Include="Arrays\ConstructedTypes\MultiDim\struct01_Instance.cs" />
    <Compile Include="Arrays\ConstructedTypes\MultiDim\struct01_static.cs" />
    <Compile Include="Arrays\TypeParameters\Jagged\class01.cs" />
    <Compile Include="Arrays\TypeParameters\Jagged\struct01.cs" />
    <Compile Include="Arrays\TypeParameters\MultiDim\class01.cs" />
    <Compile Include="Arrays\TypeParameters\MultiDim\struct01.cs" />
    <Compile Include="Constraints\Call_instance01.cs" />
    <Compile Include="Constraints\Call_static01.cs" />
    <Compile Include="Constraints\Convert_instance01.cs" />
    <Compile Include="Constraints\Convert_static01.cs" />
    <Compile Include="Constraints\Transitive_instance01.cs" />
    <Compile Include="Constraints\Transitive_static01.cs" />
    <Compile Include="Conversions\Boxing\box_unbox01.cs" />
    <Compile Include="Conversions\Reference\GenToGen01.cs" />
    <Compile Include="Conversions\Reference\GenToGen02.cs" />
    <Compile Include="Conversions\Reference\GenToGen03.cs" />
    <Compile Include="Conversions\Reference\GenToNonGen01.cs" />
    <Compile Include="Conversions\Reference\GenToNonGen02.cs" />
    <Compile Include="Conversions\Reference\GenToNonGen03.cs" />
    <Compile Include="Conversions\Reference\NonGenToGen01.cs" />
    <Compile Include="Conversions\Reference\NonGenToGen02.cs" />
    <Compile Include="Conversions\Reference\NonGenToGen03.cs" />
    <Compile Include="Coverage\chaos55915408cs.cs" />
    <Compile Include="Coverage\chaos56200037cs.cs" />
    <Compile Include="Exceptions\general_class_instance01.cs" />
    <Compile Include="Exceptions\general_class_static01.cs" />
    <Compile Include="Exceptions\general_struct_instance01.cs" />
    <Compile Include="Exceptions\general_struct_static01.cs" />
    <Compile Include="Exceptions\specific_class_instance01.cs" />
    <Compile Include="Exceptions\specific_class_instance02.cs" />
    <Compile Include="Exceptions\specific_class_static01.cs" />
    <Compile Include="Exceptions\specific_class_static02.cs" />
    <Compile Include="Exceptions\specific_struct_instance01.cs" />
    <Compile Include="Exceptions\specific_struct_instance02.cs" />
    <Compile Include="Exceptions\specific_struct_static01.cs" />
    <Compile Include="Exceptions\specific_struct_static02.cs" />
    <Compile Include="Fields\getclassfrommethodparam.cs" />
    <Compile Include="Fields\instance_assignment_class01.cs" />
    <Compile Include="Fields\instance_assignment_struct01.cs" />
    <Compile Include="Fields\instance_equalnull_class01.cs" />
    <Compile Include="Fields\instance_equalnull_struct01.cs" />
    <Compile Include="Fields\instance_passing_class01.cs" />
    <Compile Include="Fields\instance_passing_struct01.cs" />
    <Compile Include="Fields\static_assignment_class01.cs" />
    <Compile Include="Fields\static_assignment_struct01.cs" />
    <Compile Include="Fields\static_equalnull_class01.cs" />
    <Compile Include="Fields\static_equalnull_struct01.cs" />
    <Compile Include="Fields\static_passing_class01.cs" />
    <Compile Include="Fields\static_passing_struct01.cs" />
    <Compile Include="Instantiation\Classes\BaseClass01.cs" />
    <Compile Include="Instantiation\Classes\BaseClass02.cs" />
    <Compile Include="Instantiation\Classes\BaseClass03.cs" />
    <Compile Include="Instantiation\Classes\Baseclass04.cs" />
    <Compile Include="Instantiation\Classes\Baseclass05.cs" />
    <Compile Include="Instantiation\Classes\class01.cs" />
    <Compile Include="Instantiation\Classes\class02.cs" />
    <Compile Include="Instantiation\Classes\class03.cs" />
    <Compile Include="Instantiation\delegates\Delegate001.cs" />
    <Compile Include="Instantiation\delegates\Delegate002.cs" />
    <Compile Include="Instantiation\delegates\Delegate003.cs" />
    <Compile Include="Instantiation\delegates\Delegate004.cs" />
    <Compile Include="Instantiation\delegates\Delegate005.cs" />
    <Compile Include="Instantiation\delegates\Delegate006.cs" />
    <Compile Include="Instantiation\delegates\Delegate007.cs" />
    <Compile Include="Instantiation\delegates\Delegate008.cs" />
    <Compile Include="Instantiation\delegates\Delegate009.cs" />
    <Compile Include="Instantiation\delegates\Delegate010.cs" />
    <Compile Include="Instantiation\delegates\Delegate011.cs" />
    <Compile Include="Instantiation\delegates\Delegate012.cs" />
    <Compile Include="Instantiation\delegates\Delegate013.cs" />
    <Compile Include="Instantiation\delegates\Delegate014.cs" />
    <Compile Include="Instantiation\delegates\Delegate015.cs" />
    <Compile Include="Instantiation\delegates\Delegate016.cs" />
    <Compile Include="Instantiation\delegates\Delegate017.cs" />
    <Compile Include="Instantiation\delegates\Delegate018.cs" />
    <Compile Include="Instantiation\delegates\Delegate019.cs" />
    <Compile Include="Instantiation\delegates\Delegate020.cs" />
    <Compile Include="Instantiation\delegates\Delegate021.cs" />
    <Compile Include="Instantiation\delegates\Delegate022.cs" />
    <Compile Include="Instantiation\delegates\Delegate023.cs" />
    <Compile Include="Instantiation\delegates\Delegate024.cs" />
    <Compile Include="Instantiation\delegates\Delegate025.cs" />
    <Compile Include="Instantiation\delegates\Delegate026.cs" />
    <Compile Include="Instantiation\delegates\Delegate027.cs" />
    <Compile Include="Instantiation\delegates\Delegate028.cs" />
    <Compile Include="Instantiation\delegates\Delegate029.cs" />
    <Compile Include="Instantiation\delegates\Delegate030.cs" />
    <Compile Include="Instantiation\delegates\Delegate031.cs" />
    <Compile Include="Instantiation\delegates\Delegate032.cs" />
    <Compile Include="Instantiation\Interfaces\Class01.cs" />
    <Compile Include="Instantiation\Interfaces\Class02.cs" />
    <Compile Include="Instantiation\Interfaces\Class03.cs" />
    <Compile Include="Instantiation\Interfaces\Class04.cs" />
    <Compile Include="Instantiation\Interfaces\Class05.cs" />
    <Compile Include="Instantiation\Interfaces\Struct01.cs" />
    <Compile Include="Instantiation\Interfaces\Struct02.cs" />
    <Compile Include="Instantiation\Interfaces\Struct03.cs" />
    <Compile Include="Instantiation\Interfaces\Struct04.cs" />
    <Compile Include="Instantiation\Interfaces\Struct05.cs" />
    <Compile Include="Instantiation\Structs\struct01.cs" />
    <Compile Include="Instantiation\Structs\struct02.cs" />
    <Compile Include="Instantiation\Structs\struct03.cs" />
    <Compile Include="Locals\instance_assignment_class01.cs" />
    <Compile Include="Locals\instance_assignment_struct01.cs" />
    <Compile Include="Locals\instance_equalnull_class01.cs" />
    <Compile Include="Locals\instance_equalnull_struct01.cs" />
    <Compile Include="Locals\instance_passing_class01.cs" />
    <Compile Include="Locals\instance_passing_struct01.cs" />
    <Compile Include="Locals\static_assignment_class01.cs" />
    <Compile Include="Locals\static_assignment_struct01.cs" />
    <Compile Include="Locals\static_equalnull_class01.cs" />
    <Compile Include="Locals\static_equalnull_struct01.cs" />
    <Compile Include="Locals\static_passing_class01.cs" />
    <Compile Include="Locals\static_passing_struct01.cs" />
    <Compile Include="MemberAccess\class_instance01.cs" />
    <Compile Include="MemberAccess\class_static01.cs" />
    <Compile Include="MemberAccess\interface_class01.cs" />
    <Compile Include="MemberAccess\interface_class02.cs" />
    <Compile Include="MemberAccess\interface_struct01.cs" />
    <Compile Include="MemberAccess\interface_struct02.cs" />
    <Compile Include="MemberAccess\struct_instance01.cs" />
    <Compile Include="MemberAccess\struct_static01.cs" />
    <Compile Include="Parameters\instance_assignment_class01.cs" />
    <Compile Include="Parameters\instance_assignment_struct01.cs" />
    <Compile Include="Parameters\instance_equalnull_class01.cs" />
    <Compile Include="Parameters\instance_equalnull_struct01.cs" />
    <Compile Include="Parameters\instance_passing_class01.cs" />
    <Compile Include="Parameters\instance_passing_struct01.cs" />
    <Compile Include="Parameters\static_assignment_class01.cs" />
    <Compile Include="Parameters\static_assignment_struct01.cs" />
    <Compile Include="Parameters\static_equalnull_class01.cs" />
    <Compile Include="Parameters\static_equalnull_struct01.cs" />
    <Compile Include="Parameters\static_passing_class01.cs" />
    <Compile Include="Parameters\static_passing_struct01.cs" />
    <Compile Include="pinvoke\instance01.cs" />
    <Compile Include="pinvoke\instance02.cs" />
    <Compile Include="pinvoke\instance03.cs" />
    <Compile Include="pinvoke\static01.cs" />
    <Compile Include="pinvoke\static02.cs" />
    <Compile Include="Typeof\class01.cs" />
    <Compile Include="Typeof\class02.cs" />
    <Compile Include="Typeof\class03.cs" />
    <Compile Include="Typeof\struct01.cs" />
    <Compile Include="Typeof\Struct02.cs" />
    <Compile Include="Typeof\struct03.cs" />
    <Compile Include="TypeParameters\default_class01.cs" />
    <Compile Include="TypeParameters\default_struct01.cs" />
    <Compile Include="Variance\variance_generic_virtual.cs" />
    <Compile Include="VirtualMethods\generic_virtual_methods.cs" />
  </ItemGroup>

  <Import Project="$(TestSourceDir)MergedTestRunner.targets" />
</Project>
