<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DebugType>None</DebugType>
    <Optimize>True</Optimize>
    <HasMergedInTests>true</HasMergedInTests>
  </PropertyGroup>
  <ItemGroup>
    <MergedWrapperProjectReference Include="regression\DDB148379\ddb148379.ilproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="ConstrainedCall\class1.cs" />
    <Compile Include="ConstrainedCall\class2.cs" />
    <Compile Include="ConstrainedCall\vt1.cs" />
    <Compile Include="ConstrainedCall\vt2.cs" />
    <Compile Include="ConstrainedCall\vt3.cs" />
    <Compile Include="ConstrainedCall\vt4.cs" />
    <Compile Include="Conversions\Boxing\box_isinst_unbox.cs" />
    <Compile Include="Coverage\chaos55915408cs.cs" />
    <Compile Include="Coverage\chaos56200037cs.cs" />
    <Compile Include="Typeof\dynamicTypes.cs" />
    <Compile Include="Typeof\objectBoxing.cs" />
    <Compile Include="Typeof\refTypesdynamic.cs" />
    <Compile Include="Typeof\valueTypeBoxing.cs" />
    <Compile Include="Variance\variance_generic_virtual.cs" />
    <Compile Include="VirtualMethods\generic_virtual_methods.cs" />
  </ItemGroup>

  <Import Project="$(TestSourceDir)MergedTestRunner.targets" />
</Project>
