<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DebugType>None</DebugType>
    <Optimize>False</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <MergedWrapperProjectReference Include="Arrays\ConstructedTypes\MultiDim\class01_ConstructedTypes_MultiDim.csproj" />
    <MergedWrapperProjectReference Include="Arrays\ConstructedTypes\MultiDim\class01_instance_MultiDim.csproj" />
    <MergedWrapperProjectReference Include="Arrays\ConstructedTypes\MultiDim\class01_static_MultiDim.csproj" />
    <MergedWrapperProjectReference Include="Arrays\ConstructedTypes\MultiDim\struct01_ConstructedTypes.csproj" />
    <MergedWrapperProjectReference Include="Arrays\ConstructedTypes\MultiDim\struct01_instance_MultiDim.csproj" />
    <MergedWrapperProjectReference Include="Arrays\ConstructedTypes\MultiDim\struct01_static_MultiDim.csproj" />
    <MergedWrapperProjectReference Include="Arrays\TypeParameters\Jagged\class01_TypeParameters_Jagged.csproj" />
    <MergedWrapperProjectReference Include="Arrays\TypeParameters\Jagged\struct01_Jagged.csproj" />
    <MergedWrapperProjectReference Include="Arrays\TypeParameters\MultiDim\class01_TypeParameters_MultiDim.csproj" />
    <MergedWrapperProjectReference Include="Arrays\TypeParameters\MultiDim\struct01_struct01.csproj.csproj" />
    <MergedWrapperProjectReference Include="ConstrainedCall\class1_cs_r.csproj" />
    <MergedWrapperProjectReference Include="ConstrainedCall\class1_r.ilproj" />
    <MergedWrapperProjectReference Include="ConstrainedCall\class2_cs_r.csproj" />
    <MergedWrapperProjectReference Include="ConstrainedCall\class2_r.ilproj" />
    <MergedWrapperProjectReference Include="ConstrainedCall\vt1_cs_r.csproj" />
    <MergedWrapperProjectReference Include="ConstrainedCall\vt1_r.ilproj" />
    <MergedWrapperProjectReference Include="ConstrainedCall\vt2_cs_r.csproj" />
    <MergedWrapperProjectReference Include="ConstrainedCall\vt2_r.ilproj" />
    <MergedWrapperProjectReference Include="ConstrainedCall\vt3_cs_r.csproj" />
    <MergedWrapperProjectReference Include="ConstrainedCall\vt3_r.ilproj" />
    <MergedWrapperProjectReference Include="ConstrainedCall\vt4_cs_r.csproj" />
    <MergedWrapperProjectReference Include="ConstrainedCall\vt4_r.ilproj" />
    <MergedWrapperProjectReference Include="Constraints\call_instance01.csproj" />
    <MergedWrapperProjectReference Include="Constraints\call_static01.csproj" />
    <MergedWrapperProjectReference Include="Constraints\convert_instance01.csproj" />
    <MergedWrapperProjectReference Include="Constraints\convert_static01.csproj" />
    <MergedWrapperProjectReference Include="Constraints\transitive_instance01.csproj" />
    <MergedWrapperProjectReference Include="Constraints\transitive_static01.csproj" />
    <MergedWrapperProjectReference Include="Conversions\Boxing\box_unbox01.csproj" />
    <MergedWrapperProjectReference Include="Conversions\Reference\gentogen01.csproj" />
    <MergedWrapperProjectReference Include="Conversions\Reference\gentogen02.csproj" />
    <MergedWrapperProjectReference Include="Conversions\Reference\gentogen03.csproj" />
    <MergedWrapperProjectReference Include="Conversions\Reference\gentonongen01.csproj" />
    <MergedWrapperProjectReference Include="Conversions\Reference\gentonongen02.csproj" />
    <MergedWrapperProjectReference Include="Conversions\Reference\gentonongen03.csproj" />
    <MergedWrapperProjectReference Include="Conversions\Reference\nongentogen01.csproj" />
    <MergedWrapperProjectReference Include="Conversions\Reference\nongentogen02.csproj" />
    <MergedWrapperProjectReference Include="Conversions\Reference\nongentogen03.csproj" />
    <MergedWrapperProjectReference Include="Coverage\chaos55915408cs.csproj" />
    <MergedWrapperProjectReference Include="Coverage\chaos56200037cs.csproj" />
    <MergedWrapperProjectReference Include="Coverage\chaos65204782cs.csproj" />
    <MergedWrapperProjectReference Include="Exceptions\general_class_instance01.csproj" />
    <MergedWrapperProjectReference Include="Exceptions\general_class_static01.csproj" />
    <MergedWrapperProjectReference Include="Exceptions\general_struct_instance01.csproj" />
    <MergedWrapperProjectReference Include="Exceptions\general_struct_static01.csproj" />
    <MergedWrapperProjectReference Include="Exceptions\specific_class_instance01.csproj" />
    <MergedWrapperProjectReference Include="Exceptions\specific_class_instance02.csproj" />
    <MergedWrapperProjectReference Include="Exceptions\specific_class_static01.csproj" />
    <MergedWrapperProjectReference Include="Exceptions\specific_class_static02.csproj" />
    <MergedWrapperProjectReference Include="Exceptions\specific_struct_instance01.csproj" />
    <MergedWrapperProjectReference Include="Exceptions\specific_struct_instance02.csproj" />
    <MergedWrapperProjectReference Include="Exceptions\specific_struct_static01.csproj" />
    <MergedWrapperProjectReference Include="Exceptions\specific_struct_static02.csproj" />
    <MergedWrapperProjectReference Include="Fields\getclassfrommethodparam.csproj" />
    <MergedWrapperProjectReference Include="Fields\instance_assignment_class01_Fields.csproj" />
    <MergedWrapperProjectReference Include="Fields\instance_assignment_struct01_Fields.csproj" />
    <MergedWrapperProjectReference Include="Fields\instance_equalnull_class01_Fields.csproj" />
    <MergedWrapperProjectReference Include="Fields\instance_equalnull_struct01_Fields.csproj" />
    <MergedWrapperProjectReference Include="Fields\instance_passing_class01_Fields.csproj" />
    <MergedWrapperProjectReference Include="Fields\instance_passing_struct01_Fields.csproj" />
    <MergedWrapperProjectReference Include="Fields\static_assignment_class01_Fields.csproj" />
    <MergedWrapperProjectReference Include="Fields\static_assignment_struct01_Fields.csproj" />
    <MergedWrapperProjectReference Include="Fields\static_equalnull_class01_Fields.csproj" />
    <MergedWrapperProjectReference Include="Fields\static_equalnull_struct01_Fields.csproj" />
    <MergedWrapperProjectReference Include="Fields\static_passing_class01_Fields.csproj" />
    <MergedWrapperProjectReference Include="Fields\static_passing_struct01_Fields.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\Classes\baseclass01.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\Classes\baseclass02.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\Classes\baseclass03.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\Classes\baseclass04.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\Classes\baseclass05.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\Classes\class01_Classes.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\Classes\class02_Classes.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\Classes\class03_Classes.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate001.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate002.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate003.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate004.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate005.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate006.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate007.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate008.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate009.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate010.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate011.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate012.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate013.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate014.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate015.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate016.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate017.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate018.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate019.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate020.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate021.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate022.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate023.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate024.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate025.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate026.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate027.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate028.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate029.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate030.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate031.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\delegates\Delegate032.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\Interfaces\class01_Interfaces.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\Interfaces\class02_Interfaces.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\Interfaces\class03_Interfaces.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\Interfaces\class04_Interfaces.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\Interfaces\class05_Interfaces.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\Interfaces\struct01_Interfaces.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\Interfaces\struct02_Interfaces.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\Interfaces\struct03_Interfaces.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\Interfaces\struct04_Interfaces.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\Interfaces\struct05_Interfaces.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\Structs\struct01_Structs.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\Structs\struct02_Structs.csproj" />
    <MergedWrapperProjectReference Include="Instantiation\Structs\struct03_Structs.csproj" />
    <MergedWrapperProjectReference Include="Locals\instance_assignment_class01_Locals.csproj" />
    <MergedWrapperProjectReference Include="Locals\instance_assignment_struct01_Locals.csproj" />
    <MergedWrapperProjectReference Include="Locals\instance_equalnull_class01_Locals.csproj" />
    <MergedWrapperProjectReference Include="Locals\instance_equalnull_struct01_Locals.csproj" />
    <MergedWrapperProjectReference Include="Locals\instance_passing_class01_Locals.csproj" />
    <MergedWrapperProjectReference Include="Locals\instance_passing_struct01_Locals.csproj" />
    <MergedWrapperProjectReference Include="Locals\static_assignment_class01_Locals.csproj" />
    <MergedWrapperProjectReference Include="Locals\static_assignment_struct01_Locals.csproj" />
    <MergedWrapperProjectReference Include="Locals\static_equalnull_class01_Locals.csproj" />
    <MergedWrapperProjectReference Include="Locals\static_equalnull_struct01_Locals.csproj" />
    <MergedWrapperProjectReference Include="Locals\static_passing_class01_Locals.csproj" />
    <MergedWrapperProjectReference Include="Locals\static_passing_struct01_Locals.csproj" />
    <MergedWrapperProjectReference Include="MemberAccess\class_instance01.csproj" />
    <MergedWrapperProjectReference Include="MemberAccess\class_static01.csproj" />
    <MergedWrapperProjectReference Include="MemberAccess\interface_class01.csproj" />
    <MergedWrapperProjectReference Include="MemberAccess\interface_class02.csproj" />
    <MergedWrapperProjectReference Include="MemberAccess\interface_struct01.csproj" />
    <MergedWrapperProjectReference Include="MemberAccess\interface_struct02.csproj" />
    <MergedWrapperProjectReference Include="MemberAccess\struct_instance01.csproj" />
    <MergedWrapperProjectReference Include="MemberAccess\struct_static01.csproj" />
    <MergedWrapperProjectReference Include="Parameters\instance_assignment_class01_Parameters.csproj" />
    <MergedWrapperProjectReference Include="Parameters\instance_assignment_struct01_Parameters.csproj" />
    <MergedWrapperProjectReference Include="Parameters\instance_equalnull_class01_Parameters.csproj" />
    <MergedWrapperProjectReference Include="Parameters\instance_equalnull_struct01_Parameters.csproj" />
    <MergedWrapperProjectReference Include="Parameters\instance_passing_class01_Parameters.csproj" />
    <MergedWrapperProjectReference Include="Parameters\instance_passing_struct01_Parameters.csproj" />
    <MergedWrapperProjectReference Include="Parameters\static_assignment_class01_Parameters.csproj" />
    <MergedWrapperProjectReference Include="Parameters\static_assignment_struct01_Parameters.csproj" />
    <MergedWrapperProjectReference Include="Parameters\static_equalnull_class01_Parameters.csproj" />
    <MergedWrapperProjectReference Include="Parameters\static_equalnull_struct01_Parameters.csproj" />
    <MergedWrapperProjectReference Include="Parameters\static_passing_class01_Parameters.csproj" />
    <MergedWrapperProjectReference Include="Parameters\static_passing_struct01_Parameters.csproj" />
    <MergedWrapperProjectReference Include="pinvoke\instance01.csproj" />
    <MergedWrapperProjectReference Include="pinvoke\instance02.csproj" />
    <MergedWrapperProjectReference Include="pinvoke\instance03.csproj" />
    <MergedWrapperProjectReference Include="pinvoke\static01.csproj" />
    <MergedWrapperProjectReference Include="pinvoke\static02.csproj" />
    <MergedWrapperProjectReference Include="Typeof\class01_Typeof.csproj" />
    <MergedWrapperProjectReference Include="Typeof\class02_Typeof.csproj" />
    <MergedWrapperProjectReference Include="Typeof\class03_Typeof.csproj" />
    <MergedWrapperProjectReference Include="Typeof\struct01_Typeof.csproj" />
    <MergedWrapperProjectReference Include="Typeof\struct02_Typeof.csproj" />
    <MergedWrapperProjectReference Include="Typeof\struct03_Typeof.csproj" />
    <MergedWrapperProjectReference Include="TypeParameters\default_class01.csproj" />
    <MergedWrapperProjectReference Include="TypeParameters\default_struct01.csproj" />
    <MergedWrapperProjectReference Include="Variance\variance_generic_virtual.csproj" />
    <MergedWrapperProjectReference Include="VirtualMethods\generic_virtual_methods.csproj" />
  </ItemGroup>

  <Import Project="$(TestSourceDir)MergedTestRunner.targets" />
</Project>
