<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DebugType>Full</DebugType>
    <Optimize>True</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <MergedWrapperProjectReference Include="ConstrainedCall\class1_cs_do.csproj" />
    <MergedWrapperProjectReference Include="ConstrainedCall\class2_cs_do.csproj" />
    <MergedWrapperProjectReference Include="ConstrainedCall\vt1_cs_do.csproj" />
    <MergedWrapperProjectReference Include="ConstrainedCall\vt2_cs_do.csproj" />
    <MergedWrapperProjectReference Include="ConstrainedCall\vt3_cs_do.csproj" />
    <MergedWrapperProjectReference Include="ConstrainedCall\vt4_cs_do.csproj" />
    <MergedWrapperProjectReference Include="Constraints\Call_instance01_do.csproj" />
  </ItemGroup>

  <Import Project="$(TestSourceDir)MergedTestRunner.targets" />
</Project>
