// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_CLR_x86_JIT_V1_M09_5_PDC_b30630_b30630 = coreclr_test({
    name: "b30630",
    srcs: ["b30630.cs"],
    debugType: "pdbonly",
    pri: 1,
    size: "medium",
});
