// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_CLR_x86_JIT_V1_M09_5_PDC_b14067_b14067b = il_coreclr_test({
    name: "b14067b",
    srcs: ["b14067b.il"],
    debugType: "pdbonly",
    optimize: true,
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Regression_CLR_x86_JIT_V1_M09_5_PDC_b14067_b14067a = il_coreclr_test({
    name: "b14067a",
    srcs: ["b14067a.il"],
    debugType: "pdbonly",
    optimize: true,
    pri: 1,
    size: "medium",
});
