// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_Regression_JitBlue_DevDiv_278365_devDiv_278365 = CoreClr.coreclr_test({
    name: "DevDiv_278365",
    srcs: ["DevDiv_278365.cs"],
    optimize: true,
    pri: 1,
    size: "medium",
});
