parameters:
  - name: platforms
    type: object
  - name: scenarios
    type: object

stages:
- stage: Libraries
  displayName: Libraries Vector ISA Stress Tests
  dependsOn: []
  jobs:
  - template: /eng/common/core-templates/job/helix-job-monitor.yml
    parameters:
      helixAccessToken: $(HelixApiAccessToken)
      timeoutInMinutes: 540
      allowNoHelixJobs: true

  - template: /eng/pipelines/common/platform-matrix.yml
    parameters:
      jobTemplate: /eng/pipelines/common/global-build-job.yml
      buildConfig: Release
      helixQueueGroup: libraries
      helixQueuesTemplate: /eng/pipelines/coreclr/templates/helix-queues-setup.yml
      platforms: ${{ parameters.platforms }}
      jobParameters:
        nameSuffix: Libraries_VectorTests
        # Default timeout is 150 minutes (2.5 hours), which is not enough for stress.
        timeoutInMinutes: 360
        buildArgs: -s clr+libs+libs.tests -rc Checked -c $(_BuildConfig) /p:ArchiveTests=true /p:RunVectorTestsOnly=true
        postBuildSteps:
          - template: /eng/pipelines/libraries/helix.yml
            parameters:
              creator: dotnet-bot
              extraHelixArguments: /maxcpucount:10
              useHelixMonitor: true
              scenarios: ${{ parameters.scenarios }}
