// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_VS_ia64_JIT_M00_b140298_b140298 = coreclr_test({
    name: "b140298",
    srcs: ["test.cs"],
    debugType: "pdbonly",
});
