// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

//
// This file is used by AsmOffsets.h to validate that our
// assembly-code offsets always match their C++ counterparts.
//
// NOTE: the offsets MUST be in hex notation WITHOUT the 0x prefix

PLAT_ASM_SIZEOF(320, ExInfo)
PLAT_ASM_OFFSET(0, ExInfo, m_pPrevExInfo)
PLAT_ASM_OFFSET(8, ExInfo, m_pExContext)
PLAT_ASM_OFFSET(10, ExInfo, m_exception)
PLAT_ASM_OFFSET(18, ExInfo, m_kind)
PLAT_ASM_OFFSET(1C, ExInfo, m_passNumber)
PLAT_ASM_OFFSET(20, ExInfo, m_idxCurClause)
PLAT_ASM_OFFSET(24, ExInfo, m_frameIter)
PLAT_ASM_OFFSET(2D8, ExInfo, m_notifyDebuggerSP)

PLAT_ASM_OFFSET(0, PInvokeTransitionFrame, m_FramePointer)
PLAT_ASM_OFFSET(8, PInvokeTransitionFrame, m_RA)
PLAT_ASM_OFFSET(10, PInvokeTransitionFrame, m_pThread)
PLAT_ASM_OFFSET(18, PInvokeTransitionFrame, m_Flags)
PLAT_ASM_OFFSET(20, PInvokeTransitionFrame, m_PreservedRegs)

PLAT_ASM_SIZEOF(268, StackFrameIterator)
PLAT_ASM_OFFSET(10, StackFrameIterator, m_FramePointer)
PLAT_ASM_OFFSET(18, StackFrameIterator, m_ControlPC)
PLAT_ASM_OFFSET(20, StackFrameIterator, m_RegDisplay)
PLAT_ASM_OFFSET(0F8, StackFrameIterator, m_OriginalControlPC)
PLAT_ASM_OFFSET(100, StackFrameIterator, m_pPreviousTransitionFrame)

PLAT_ASM_SIZEOF(120, PAL_LIMITED_CONTEXT)

PLAT_ASM_OFFSET(0, PAL_LIMITED_CONTEXT, FP)
PLAT_ASM_OFFSET(8, PAL_LIMITED_CONTEXT, RA)
PLAT_ASM_OFFSET(10, PAL_LIMITED_CONTEXT, R4)
PLAT_ASM_OFFSET(18, PAL_LIMITED_CONTEXT, R5)
PLAT_ASM_OFFSET(20, PAL_LIMITED_CONTEXT, R6)
PLAT_ASM_OFFSET(28, PAL_LIMITED_CONTEXT, R7)
PLAT_ASM_OFFSET(30, PAL_LIMITED_CONTEXT, R8)
PLAT_ASM_OFFSET(38, PAL_LIMITED_CONTEXT, R9)
PLAT_ASM_OFFSET(40, PAL_LIMITED_CONTEXT, R10)
PLAT_ASM_OFFSET(48, PAL_LIMITED_CONTEXT, R11)
PLAT_ASM_OFFSET(50, PAL_LIMITED_CONTEXT, R12)
PLAT_ASM_OFFSET(58, PAL_LIMITED_CONTEXT, R13)
PLAT_ASM_OFFSET(60, PAL_LIMITED_CONTEXT, R14)
PLAT_ASM_OFFSET(68, PAL_LIMITED_CONTEXT, R15)
PLAT_ASM_OFFSET(70, PAL_LIMITED_CONTEXT, SP)
PLAT_ASM_OFFSET(78, PAL_LIMITED_CONTEXT, TP)

PLAT_ASM_SIZEOF(128, REGDISPLAY)

PLAT_ASM_OFFSET(18, REGDISPLAY, SP)

PLAT_ASM_OFFSET(B8, REGDISPLAY, pR4)
PLAT_ASM_OFFSET(C0, REGDISPLAY, pR5)
PLAT_ASM_OFFSET(C8, REGDISPLAY, pR6)
PLAT_ASM_OFFSET(D0, REGDISPLAY, pR7)
PLAT_ASM_OFFSET(D8, REGDISPLAY, pR8)
PLAT_ASM_OFFSET(E0, REGDISPLAY, pR9)
PLAT_ASM_OFFSET(E8, REGDISPLAY, pR10)
PLAT_ASM_OFFSET(F0, REGDISPLAY, pR11)
PLAT_ASM_OFFSET(F8, REGDISPLAY, pR12)
PLAT_ASM_OFFSET(100, REGDISPLAY, pFP)
PLAT_ASM_OFFSET(108, REGDISPLAY, pRA)
PLAT_ASM_OFFSET(110, REGDISPLAY, F)
