// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_Regression_JitBlue_Runtime_4781_runtime_4781_1 = CoreClr.coreclr_test({
    name: "Runtime_4781_1",
    srcs: ["Runtime_4781_1.cs"],
    optimize: true,
});

@@public
export const jIT_Regression_JitBlue_Runtime_4781_runtime_4781 = CoreClr.coreclr_test({
    name: "Runtime_4781",
    srcs: ["Runtime_4781.cs"],
    optimize: true,
    run: false,
});
