// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Performance_CodeQuality_V8_Richards_richards = coreclr_test({
    name: "Richards",
    srcs: ["Richards.cs"],
    debugType: "pdbonly",
    optimize: true,
});
