// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_CLR_x86_JIT_V1_M12_Beta2_b56154_b56154 = coreclr_test({
    name: "b56154",
    srcs: ["b56154.cs"],
    debugType: "pdbonly",
    pri: 1,
    size: "medium",
});
