<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- This test requires uncontested process-wide GC state. -->
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <CLRTestPriority>1</CLRTestPriority>
  </PropertyGroup>
  <PropertyGroup>
    <DebugType>PdbOnly</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Collect.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="$(TestLibraryProjectPath)" />
  </ItemGroup>
</Project>
