// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_JitBlue_GitHub_19601_github_19601 = coreclr_test({
    name: "Github_19601",
    srcs: ["Github_19601.cs"],
    optimize: false,
});
