// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_JitBlue_Runtime_49780_runtime_49780 = coreclr_test({
    name: "Runtime_49780",
    srcs: ["Runtime_49780.cs"],
    optimize: true,
    pri: 1,
    size: "medium",
});
