DOTNET_ROOT=/home/steve/dotnet7
RUNTIME_PATH=$(DOTNET_ROOT)/packs/Microsoft.NETCore.App.Runtime.Mono.browser-wasm/7.0.0-alpha.1.22061.11/runtimes/browser-wasm

COMPILE_FLAGS=\
    $(WASI_BIN_DIR)/*.a \
	$(RUNTIME_PATH)/native/libSystem.Native.a \
	-I$(TOP)/src/mono

LINK_FLAGS=\
	-Wl,--export=malloc,--export=free,--export=__heap_base,--export=__data_end \
	-Wl,-z,stack-size=1048576,--initial-memory=5242880,--max-memory=52428800
