
function(append_extra_system_libs NativeLibsExtra)
    set(EXTRA_LIBS)
    
    if (CLR_CMAKE_TARGET_LINUX AND NOT CLR_CMAKE_TARGET_ANDROID)
        list(APPEND EXTRA_LIBS rt)
    elseif (CLR_CMAKE_TARGET_FREEBSD)
        list(APPEND EXTRA_LIBS pthread)
        if (HAVE_INOTIFY)
            find_library(INOTIFY_LIBRARY inotify HINTS /usr/local/lib)
            list(APPEND EXTRA_LIBS ${INOTIFY_LIBRARY})
        endif ()
    elseif (CLR_CMAKE_TARGET_SUNOS)
        list(APPEND EXTRA_LIBS socket)
    endif ()
    
    if (CLR_CMAKE_TARGET_IOS OR CLR_CMAKE_TARGET_TVOS)
        list(APPEND EXTRA_LIBS "-framework Foundation")
    endif ()
    set(${NativeLibsExtra} ${${NativeLibsExtra}} ${EXTRA_LIBS} PARENT_SCOPE)
endfunction(append_extra_system_libs)
