// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_JitBlue_Runtime_70333_runtime_70333 = coreclr_test({
    name: "Runtime_70333",
    srcs: ["Runtime_70333.cs"],
    optimize: true,
});

@@public
export const jIT_Regression_JitBlue_Runtime_70333_runtime_70333_2 = coreclr_test({
    name: "Runtime_70333_2",
    srcs: ["Runtime_70333_2.cs"],
    optimize: true,
});
