// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const reflection_DisallowAbstractConstructors_disallowAbstractConstructors = coreclr_test({
    name: "DisallowAbstractConstructors",
    srcs: ["DisallowAbstractConstructors.cs"],
});
