// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_Regression_CLR_x86_JIT_V1_M11_Beta1_b41621_b41621 = CoreClr.coreclr_test({
    name: "b41621",
    srcs: ["b41621.cs"],
    debugType: "pdbonly",
    run: false,
});
