// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_HardwareIntrinsics_X86_Sse3_sse3_handwritten_r = coreclr_test({
    name: "Sse3_handwritten_r",
    srcs: ["HandwrittenProgram.cs", "LoadAndDuplicateToVector128.cs", "LoadDquVector128.cs", "MoveAndDuplicate.cs", "MoveHighAndDuplicate.cs", "MoveLowAndDuplicate.cs"],
    allowUnsafe: true,
});

@@public
export const jIT_HardwareIntrinsics_X86_Sse3_sse3_handwritten_ro = coreclr_test({
    name: "Sse3_handwritten_ro",
    srcs: ["HandwrittenProgram.cs", "LoadAndDuplicateToVector128.cs", "LoadDquVector128.cs", "MoveAndDuplicate.cs", "MoveHighAndDuplicate.cs", "MoveLowAndDuplicate.cs"],
    allowUnsafe: true,
    optimize: true,
});
