// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_JitBlue_Runtime_107841_runtime_107841 = coreclr_test({
    name: "Runtime_107841",
    srcs: ["Runtime_107841.cs"],
    optimize: true,
});
