// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_CLR_x86_JIT_V1_M11_Beta1_b46569_b46569 = il_coreclr_test({
    name: "b46569",
    srcs: ["b46569.il"],
    debugType: "pdbonly",
    optimize: true,
});
