<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <!-- Test leaks GC handles -->
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <Compile Include="$(MSBuildProjectName).cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="$(TestLibraryProjectPath)" />
  </ItemGroup>
</Project>
