// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_JitBlue_DevDiv_487702_devDiv_487702 = il_coreclr_test({
    name: "DevDiv_487702",
    srcs: ["DevDiv_487702.il"],
    optimize: true,
    pri: 1,
    size: "medium",
});
