<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NumberOfStripesToUseInStress>8</NumberOfStripesToUseInStress>

    <GCStressIncompatible Condition="'$(TargetArchitecture)' == 'arm64' and '$(TargetOS)' == 'osx'">true</GCStressIncompatible>
    <GCStressIncompatible Condition="'$(TargetArchitecture)' == 'arm'">true</GCStressIncompatible>
    <!-- ActiveIssue https://github.com/dotnet/runtime/issues/134976 -->
    <R2RIncompatible Condition="'$(TargetArchitecture)' == 'wasm' and '$(RuntimeFlavor)' == 'coreclr'">true</R2RIncompatible>
  </PropertyGroup>

  <ItemGroup>
    <MergedWrapperProjectReference Include="$(MSBuildThisFileDirectory)General/**/*_ro.csproj" />
  </ItemGroup>

  <Import Project="$(TestSourceDir)MergedTestRunner.targets" />
</Project>
