// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_JitBlue_GitHub_15718_gitHub_15718 = coreclr_test({
    name: "GitHub_15718",
    srcs: ["GitHub_15718.cs"],
    optimize: true,
});
