// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_JitBlue_devdiv_911875_devDiv_911875_r = coreclr_test({
    name: "DevDiv_911875_r",
    srcs: ["DevDiv_911875.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Regression_JitBlue_devdiv_911875_devDiv_911875_ro = coreclr_test({
    name: "DevDiv_911875_ro",
    srcs: ["DevDiv_911875.cs"],
    optimize: true,
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Regression_JitBlue_devdiv_911875_devDiv_911875_do = coreclr_test({
    name: "DevDiv_911875_do",
    srcs: ["DevDiv_911875.cs"],
    debugType: "full",
    optimize: true,
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Regression_JitBlue_devdiv_911875_devDiv_911875_d = coreclr_test({
    name: "DevDiv_911875_d",
    srcs: ["DevDiv_911875.cs"],
    debugType: "full",
    optimize: false,
    pri: 1,
    size: "medium",
});
