// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_opt_OSR_tailrecursetry = CoreClr.coreclr_test({
    name: "tailrecursetry",
    srcs: ["tailrecursetry.cs"],
    optimize: true,
});

@@public
export const jIT_opt_OSR_tailrecurse = CoreClr.coreclr_test({
    name: "tailrecurse",
    srcs: ["tailrecurse.cs"],
    optimize: true,
});

@@public
export const jIT_opt_OSR_memoryargument = CoreClr.coreclr_test({
    name: "memoryargument",
    srcs: ["memoryargument.cs"],
    optimize: true,
});

@@public
export const jIT_opt_OSR_mainloop = CoreClr.coreclr_test({
    name: "mainloop",
    srcs: ["mainloop.cs"],
    optimize: true,
});

@@public
export const jIT_opt_OSR_livelocaladdress = CoreClr.coreclr_test({
    name: "livelocaladdress",
    srcs: ["livelocaladdress.cs"],
    allowUnsafe: true,
    optimize: true,
});

@@public
export const jIT_opt_OSR_runtime_69032 = CoreClr.coreclr_test({
    name: "Runtime_69032",
    srcs: ["Runtime_69032.cs"],
    optimize: true,
});

@@public
export const jIT_opt_OSR_largefuncletframe = CoreClr.coreclr_test({
    name: "largefuncletframe",
    srcs: ["largefuncletframe.cs"],
    allowUnsafe: true,
    optimize: true,
    run: false,
});

@@public
export const jIT_opt_OSR_twoosrmethods1 = CoreClr.coreclr_test({
    name: "twoosrmethods1",
    srcs: ["twoosrmethods1.cs"],
    optimize: true,
});

@@public
export const jIT_opt_OSR_runtime_89666 = CoreClr.coreclr_test({
    name: "Runtime_89666",
    srcs: ["Runtime_89666.cs"],
    optimize: true,
});

@@public
export const jIT_opt_OSR_tailpgo = CoreClr.coreclr_test({
    name: "tailpgo",
    srcs: ["tailpgo.cs"],
    optimize: true,
});

@@public
export const jIT_opt_OSR_handlerloop = CoreClr.coreclr_test({
    name: "handlerloop",
    srcs: ["handlerloop.cs"],
    optimize: true,
});

@@public
export const jIT_opt_OSR_osrcontainstry = CoreClr.coreclr_test({
    name: "osrcontainstry",
    srcs: ["osrcontainstry.cs"],
    allowUnsafe: true,
    optimize: true,
});

@@public
export const jIT_opt_OSR_pinnedlocal = CoreClr.coreclr_test({
    name: "pinnedlocal",
    srcs: ["pinnedlocal.cs"],
    allowUnsafe: true,
    optimize: true,
});

@@public
export const jIT_opt_OSR_genericmethodpatchpoint = CoreClr.coreclr_test({
    name: "genericmethodpatchpoint",
    srcs: ["genericmethodpatchpoint.cs"],
    optimize: true,
});

@@public
export const jIT_opt_OSR_promoted = CoreClr.coreclr_test({
    name: "promoted",
    srcs: ["promoted.cs"],
    optimize: true,
});

@@public
export const jIT_opt_OSR_invalidpromotion = CoreClr.coreclr_test({
    name: "invalidpromotion",
    srcs: ["invalidpromotion.cs"],
    optimize: true,
});

@@public
export const jIT_opt_OSR_normalizeonload = CoreClr.coreclr_test({
    name: "normalizeonload",
    srcs: ["normalizeonload.cs"],
    allowUnsafe: true,
    optimize: true,
});

@@public
export const jIT_opt_OSR_tailpgo2 = CoreClr.coreclr_test({
    name: "tailpgo2",
    srcs: ["tailpgo2.cs"],
    optimize: true,
});

@@public
export const jIT_opt_OSR_mainlooptry3 = CoreClr.coreclr_test({
    name: "mainlooptry3",
    srcs: ["mainlooptry3.cs"],
    optimize: true,
});

@@public
export const jIT_opt_OSR_mainlooptry2 = CoreClr.coreclr_test({
    name: "mainlooptry2",
    srcs: ["mainlooptry2.cs"],
    optimize: true,
});

@@public
export const jIT_opt_OSR_twoosrmethods = CoreClr.coreclr_test({
    name: "twoosrmethods",
    srcs: ["twoosrmethods.cs"],
    optimize: true,
});

@@public
export const jIT_opt_OSR_mainlooptry = CoreClr.coreclr_test({
    name: "mainlooptry",
    srcs: ["mainlooptry.cs"],
    optimize: true,
});

@@public
export const jIT_opt_OSR_exposure1 = CoreClr.coreclr_test({
    name: "exposure1",
    srcs: ["exposure1.cs"],
    optimize: true,
});

@@public
export const jIT_opt_OSR_exposure2 = CoreClr.coreclr_test({
    name: "exposure2",
    srcs: ["exposure2.cs"],
    optimize: true,
});

@@public
export const jIT_opt_OSR_originalstackalloc = CoreClr.coreclr_test({
    name: "originalstackalloc",
    srcs: ["originalstackalloc.cs"],
    allowUnsafe: true,
    optimize: true,
});

@@public
export const jIT_opt_OSR_tailrecursetry2 = CoreClr.coreclr_test({
    name: "tailrecursetry2",
    srcs: ["tailrecursetry2.cs"],
    allowUnsafe: true,
    optimize: true,
});

@@public
export const jIT_opt_OSR_integersumloop = CoreClr.coreclr_test({
    name: "integersumloop",
    srcs: ["integersumloop.cs"],
    optimize: true,
});

@@public
export const jIT_opt_OSR_example = CoreClr.coreclr_test({
    name: "example",
    srcs: ["example.cs"],
    optimize: true,
});

@@public
export const jIT_opt_OSR_shortenregisteredlocal = CoreClr.coreclr_test({
    name: "shortenregisteredlocal",
    srcs: ["shortenregisteredlocal.cs"],
    optimize: true,
});

@@public
export const jIT_opt_OSR_mainlooptry4 = CoreClr.coreclr_test({
    name: "mainlooptry4",
    srcs: ["mainlooptry4.cs"],
    optimize: true,
});

@@public
export const jIT_opt_OSR_livelocalstackalloc = CoreClr.coreclr_test({
    name: "livelocalstackalloc",
    srcs: ["livelocalstackalloc.cs"],
    allowUnsafe: true,
    optimize: true,
});

@@public
export const jIT_opt_OSR_innerloop = CoreClr.coreclr_test({
    name: "innerloop",
    srcs: ["innerloop.cs"],
    optimize: true,
});

@@public
export const jIT_opt_OSR_mainloop2 = CoreClr.coreclr_test({
    name: "mainloop2",
    srcs: ["mainloop2.cs"],
    optimize: true,
});

@@public
export const jIT_opt_OSR_synchronized_ = CoreClr.coreclr_test({
    name: "synchronized",
    srcs: ["synchronized.cs"],
    optimize: true,
});

@@public
export const jIT_opt_OSR_addressexposedlocal = CoreClr.coreclr_test({
    name: "addressexposedlocal",
    srcs: ["addressexposedlocal.cs"],
    allowUnsafe: true,
    optimize: true,
});

@@public
export const jIT_opt_OSR_nesteddoloops = CoreClr.coreclr_test({
    name: "nesteddoloops",
    srcs: ["nesteddoloops.cs"],
    optimize: true,
});

@@public
export const jIT_opt_OSR_doublestackalloc = CoreClr.coreclr_test({
    name: "doublestackalloc",
    srcs: ["doublestackalloc.cs"],
    allowUnsafe: true,
    optimize: true,
});

@@public
export const jIT_opt_OSR_shadowparam = CoreClr.coreclr_test({
    name: "shadowparam",
    srcs: ["shadowparam.cs"],
    allowUnsafe: true,
    optimize: true,
});
