// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
//

//
// GENERATED FILE, DON'T EDIT
// Generated by coreclr InterpToNativeGenerator
//

#include <interpretershared.h>
#include <interpexec.h>
#include "callhelpers.hpp"

void ExecuteInterpretedMethodWithArgs_PortableEntryPoint(PCODE portableEntrypoint, TransitionBlock* block, size_t argsSize, int8_t* retBuff);

namespace
{
    FCDECL4(void, CallInterpreter_This_S12_I32_RetS12, int32_t, int8_t*, int8_t*, int32_t);
    WASM_CALLABLE_FUNC_5(void, CallInterpreter_This_S12_I32_RetS12, int32_t arg0, int8_t* retBuf, int8_t* arg1, int32_t arg2, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[4];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        memcpy(&transitionBlock.args[1], arg1, 12);
        transitionBlock.args[3] = (int64_t)arg2;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), retBuf);
        return;
    }

    FCDECL5(void, CallInterpreter_This_I32_S12_I32_RetS12, int32_t, int8_t*, int32_t, int8_t*, int32_t);
    WASM_CALLABLE_FUNC_6(void, CallInterpreter_This_I32_S12_I32_RetS12, int32_t arg0, int8_t* retBuf, int32_t arg1, int8_t* arg2, int32_t arg3, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[5];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        memcpy(&transitionBlock.args[2], arg2, 12);
        transitionBlock.args[4] = (int64_t)arg3;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), retBuf);
        return;
    }

    FCDECL5(void, CallInterpreter_This_I32_I32_I32_RetS12, int32_t, int8_t*, int32_t, int32_t, int32_t);
    WASM_CALLABLE_FUNC_6(void, CallInterpreter_This_I32_I32_I32_RetS12, int32_t arg0, int8_t* retBuf, int32_t arg1, int32_t arg2, int32_t arg3, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[4];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        transitionBlock.args[2] = (int64_t)arg2;
        transitionBlock.args[3] = (int64_t)arg3;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), retBuf);
        return;
    }

    FCDECL4(void, CallInterpreter_This_I32_I32_RetS12, int32_t, int8_t*, int32_t, int32_t);
    WASM_CALLABLE_FUNC_5(void, CallInterpreter_This_I32_I32_RetS12, int32_t arg0, int8_t* retBuf, int32_t arg1, int32_t arg2, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[3];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        transitionBlock.args[2] = (int64_t)arg2;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), retBuf);
        return;
    }

    FCDECL2(void, CallInterpreter_This_RetS16, int32_t, int8_t*);
    WASM_CALLABLE_FUNC_3(void, CallInterpreter_This_RetS16, int32_t arg0, int8_t* retBuf, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[1];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), retBuf);
        return;
    }

    FCDECL4(void, CallInterpreter_L2_I32_RetS16, int8_t*, int64_t, int64_t, int32_t);
    WASM_CALLABLE_FUNC_5(void, CallInterpreter_L2_I32_RetS16, int8_t* retBuf, int64_t arg0Lo, int64_t arg0Hi, int32_t arg1, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[3];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = arg0Lo;
        transitionBlock.args[1] = arg0Hi;
        transitionBlock.args[2] = (int64_t)arg1;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), retBuf);
        return;
    }

    FCDECL2(void, CallInterpreter_This_RetS1, int32_t, int8_t*);
    WASM_CALLABLE_FUNC_3(void, CallInterpreter_This_RetS1, int32_t arg0, int8_t* retBuf, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[1];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), retBuf);
        return;
    }

    FCDECL5(void, CallInterpreter_This_I32_I32_I32_RetS8, int32_t, int8_t*, int32_t, int32_t, int32_t);
    WASM_CALLABLE_FUNC_6(void, CallInterpreter_This_I32_I32_I32_RetS8, int32_t arg0, int8_t* retBuf, int32_t arg1, int32_t arg2, int32_t arg3, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[4];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        transitionBlock.args[2] = (int64_t)arg2;
        transitionBlock.args[3] = (int64_t)arg3;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), retBuf);
        return;
    }

    FCDECL3(void, CallInterpreter_This_I32_RetS8, int32_t, int8_t*, int32_t);
    WASM_CALLABLE_FUNC_4(void, CallInterpreter_This_I32_RetS8, int32_t arg0, int8_t* retBuf, int32_t arg1, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[2];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), retBuf);
        return;
    }

    FCDECL2(void, CallInterpreter_This_RetS8, int32_t, int8_t*);
    WASM_CALLABLE_FUNC_3(void, CallInterpreter_This_RetS8, int32_t arg0, int8_t* retBuf, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[1];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), retBuf);
        return;
    }

    FCDECL3(double, CallInterpreter_F64_F64_F64_RetF64, double, double, double);
    WASM_CALLABLE_FUNC_4(double, CallInterpreter_F64_F64_F64_RetF64, double arg0, double arg1, double arg2, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[3];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        *(double*)&transitionBlock.args[0] = arg0;
        *(double*)&transitionBlock.args[1] = arg1;
        *(double*)&transitionBlock.args[2] = arg2;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        double result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL2(double, CallInterpreter_F64_F64_RetF64, double, double);
    WASM_CALLABLE_FUNC_3(double, CallInterpreter_F64_F64_RetF64, double arg0, double arg1, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[2];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        *(double*)&transitionBlock.args[0] = arg0;
        *(double*)&transitionBlock.args[1] = arg1;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        double result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL2(double, CallInterpreter_F64_I32_RetF64, double, int32_t);
    WASM_CALLABLE_FUNC_3(double, CallInterpreter_F64_I32_RetF64, double arg0, int32_t arg1, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[2];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        *(double*)&transitionBlock.args[0] = arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        double result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL1(double, CallInterpreter_F64_RetF64, double);
    WASM_CALLABLE_FUNC_2(double, CallInterpreter_F64_RetF64, double arg0, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[1];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        *(double*)&transitionBlock.args[0] = arg0;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        double result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL3(float, CallInterpreter_F32_F32_F32_RetF32, float, float, float);
    WASM_CALLABLE_FUNC_4(float, CallInterpreter_F32_F32_F32_RetF32, float arg0, float arg1, float arg2, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[3];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        *(float*)&transitionBlock.args[0] = arg0;
        *(float*)&transitionBlock.args[1] = arg1;
        *(float*)&transitionBlock.args[2] = arg2;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        float result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL2(float, CallInterpreter_F32_F32_RetF32, float, float);
    WASM_CALLABLE_FUNC_3(float, CallInterpreter_F32_F32_RetF32, float arg0, float arg1, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[2];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        *(float*)&transitionBlock.args[0] = arg0;
        *(float*)&transitionBlock.args[1] = arg1;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        float result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL2(float, CallInterpreter_F32_I32_RetF32, float, int32_t);
    WASM_CALLABLE_FUNC_3(float, CallInterpreter_F32_I32_RetF32, float arg0, int32_t arg1, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[2];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        *(float*)&transitionBlock.args[0] = arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        float result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL1(float, CallInterpreter_F32_RetF32, float);
    WASM_CALLABLE_FUNC_2(float, CallInterpreter_F32_RetF32, float arg0, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[1];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        *(float*)&transitionBlock.args[0] = arg0;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        float result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL1(int32_t, CallInterpreter_S8_RetI32, int8_t*);
    WASM_CALLABLE_FUNC_2(int32_t, CallInterpreter_S8_RetI32, int8_t* arg0, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[1];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        memcpy(&transitionBlock.args[0], arg0, 8);
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int32_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL3(int32_t, CallInterpreter_This_S12_I32_RetI32, int32_t, int8_t*, int32_t);
    WASM_CALLABLE_FUNC_4(int32_t, CallInterpreter_This_S12_I32_RetI32, int32_t arg0, int8_t* arg1, int32_t arg2, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[4];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        memcpy(&transitionBlock.args[1], arg1, 12);
        transitionBlock.args[3] = (int64_t)arg2;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int32_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL2(int32_t, CallInterpreter_This_S12_RetI32, int32_t, int8_t*);
    WASM_CALLABLE_FUNC_3(int32_t, CallInterpreter_This_S12_RetI32, int32_t arg0, int8_t* arg1, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[3];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        memcpy(&transitionBlock.args[1], arg1, 12);
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int32_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL3(int32_t, CallInterpreter_This_S8_S8_RetI32, int32_t, int8_t*, int8_t*);
    WASM_CALLABLE_FUNC_4(int32_t, CallInterpreter_This_S8_S8_RetI32, int32_t arg0, int8_t* arg1, int8_t* arg2, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[3];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        memcpy(&transitionBlock.args[1], arg1, 8);
        memcpy(&transitionBlock.args[2], arg2, 8);
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int32_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL5(int32_t, CallInterpreter_This_S8_I32_S8_I32_RetI32, int32_t, int8_t*, int32_t, int8_t*, int32_t);
    WASM_CALLABLE_FUNC_6(int32_t, CallInterpreter_This_S8_I32_S8_I32_RetI32, int32_t arg0, int8_t* arg1, int32_t arg2, int8_t* arg3, int32_t arg4, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[5];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        memcpy(&transitionBlock.args[1], arg1, 8);
        transitionBlock.args[2] = (int64_t)arg2;
        memcpy(&transitionBlock.args[3], arg3, 8);
        transitionBlock.args[4] = (int64_t)arg4;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int32_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL5(int32_t, CallInterpreter_This_S8_I32_I32_I32_RetI32, int32_t, int8_t*, int32_t, int32_t, int32_t);
    WASM_CALLABLE_FUNC_6(int32_t, CallInterpreter_This_S8_I32_I32_I32_RetI32, int32_t arg0, int8_t* arg1, int32_t arg2, int32_t arg3, int32_t arg4, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[5];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        memcpy(&transitionBlock.args[1], arg1, 8);
        transitionBlock.args[2] = (int64_t)arg2;
        transitionBlock.args[3] = (int64_t)arg3;
        transitionBlock.args[4] = (int64_t)arg4;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int32_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL3(int32_t, CallInterpreter_This_S8_I32_RetI32, int32_t, int8_t*, int32_t);
    WASM_CALLABLE_FUNC_4(int32_t, CallInterpreter_This_S8_I32_RetI32, int32_t arg0, int8_t* arg1, int32_t arg2, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[3];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        memcpy(&transitionBlock.args[1], arg1, 8);
        transitionBlock.args[2] = (int64_t)arg2;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int32_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL2(int32_t, CallInterpreter_This_S8_RetI32, int32_t, int8_t*);
    WASM_CALLABLE_FUNC_3(int32_t, CallInterpreter_This_S8_RetI32, int32_t arg0, int8_t* arg1, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[2];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        memcpy(&transitionBlock.args[1], arg1, 8);
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int32_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL3(int32_t, CallInterpreter_This_I32_S12_RetI32, int32_t, int32_t, int8_t*);
    WASM_CALLABLE_FUNC_4(int32_t, CallInterpreter_This_I32_S12_RetI32, int32_t arg0, int32_t arg1, int8_t* arg2, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[4];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        memcpy(&transitionBlock.args[2], arg2, 12);
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int32_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL3(int32_t, CallInterpreter_This_I32_S8_RetI32, int32_t, int32_t, int8_t*);
    WASM_CALLABLE_FUNC_4(int32_t, CallInterpreter_This_I32_S8_RetI32, int32_t arg0, int32_t arg1, int8_t* arg2, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[3];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        memcpy(&transitionBlock.args[2], arg2, 8);
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int32_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL5(int32_t, CallInterpreter_This_I32_I32_I32_I32_RetI32, int32_t, int32_t, int32_t, int32_t, int32_t);
    WASM_CALLABLE_FUNC_6(int32_t, CallInterpreter_This_I32_I32_I32_I32_RetI32, int32_t arg0, int32_t arg1, int32_t arg2, int32_t arg3, int32_t arg4, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[5];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        transitionBlock.args[2] = (int64_t)arg2;
        transitionBlock.args[3] = (int64_t)arg3;
        transitionBlock.args[4] = (int64_t)arg4;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int32_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL4(int32_t, CallInterpreter_This_I32_I32_I32_RetI32, int32_t, int32_t, int32_t, int32_t);
    WASM_CALLABLE_FUNC_5(int32_t, CallInterpreter_This_I32_I32_I32_RetI32, int32_t arg0, int32_t arg1, int32_t arg2, int32_t arg3, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[4];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        transitionBlock.args[2] = (int64_t)arg2;
        transitionBlock.args[3] = (int64_t)arg3;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int32_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL3(int32_t, CallInterpreter_This_I32_I32_RetI32, int32_t, int32_t, int32_t);
    WASM_CALLABLE_FUNC_4(int32_t, CallInterpreter_This_I32_I32_RetI32, int32_t arg0, int32_t arg1, int32_t arg2, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[3];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        transitionBlock.args[2] = (int64_t)arg2;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int32_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL2(int32_t, CallInterpreter_This_I32_RetI32, int32_t, int32_t);
    WASM_CALLABLE_FUNC_3(int32_t, CallInterpreter_This_I32_RetI32, int32_t arg0, int32_t arg1, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[2];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int32_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL1(int32_t, CallInterpreter_This_RetI32, int32_t);
    WASM_CALLABLE_FUNC_2(int32_t, CallInterpreter_This_RetI32, int32_t arg0, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[1];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int32_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL1(int32_t, CallInterpreter_F64_RetI32, double);
    WASM_CALLABLE_FUNC_2(int32_t, CallInterpreter_F64_RetI32, double arg0, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[1];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        *(double*)&transitionBlock.args[0] = arg0;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int32_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL2(int32_t, CallInterpreter_I32_S8_RetI32, int32_t, int8_t*);
    WASM_CALLABLE_FUNC_3(int32_t, CallInterpreter_I32_S8_RetI32, int32_t arg0, int8_t* arg1, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[2];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        memcpy(&transitionBlock.args[1], arg1, 8);
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int32_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL8(int32_t, CallInterpreter_I32_I32_I32_I32_I32_I32_I32_I32_RetI32, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);
    WASM_CALLABLE_FUNC_9(int32_t, CallInterpreter_I32_I32_I32_I32_I32_I32_I32_I32_RetI32, int32_t arg0, int32_t arg1, int32_t arg2, int32_t arg3, int32_t arg4, int32_t arg5, int32_t arg6, int32_t arg7, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[8];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        transitionBlock.args[2] = (int64_t)arg2;
        transitionBlock.args[3] = (int64_t)arg3;
        transitionBlock.args[4] = (int64_t)arg4;
        transitionBlock.args[5] = (int64_t)arg5;
        transitionBlock.args[6] = (int64_t)arg6;
        transitionBlock.args[7] = (int64_t)arg7;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int32_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL7(int32_t, CallInterpreter_I32_I32_I32_I32_I32_I32_I32_RetI32, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);
    WASM_CALLABLE_FUNC_8(int32_t, CallInterpreter_I32_I32_I32_I32_I32_I32_I32_RetI32, int32_t arg0, int32_t arg1, int32_t arg2, int32_t arg3, int32_t arg4, int32_t arg5, int32_t arg6, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[7];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        transitionBlock.args[2] = (int64_t)arg2;
        transitionBlock.args[3] = (int64_t)arg3;
        transitionBlock.args[4] = (int64_t)arg4;
        transitionBlock.args[5] = (int64_t)arg5;
        transitionBlock.args[6] = (int64_t)arg6;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int32_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL6(int32_t, CallInterpreter_I32_I32_I32_I32_I32_I32_RetI32, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);
    WASM_CALLABLE_FUNC_7(int32_t, CallInterpreter_I32_I32_I32_I32_I32_I32_RetI32, int32_t arg0, int32_t arg1, int32_t arg2, int32_t arg3, int32_t arg4, int32_t arg5, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[6];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        transitionBlock.args[2] = (int64_t)arg2;
        transitionBlock.args[3] = (int64_t)arg3;
        transitionBlock.args[4] = (int64_t)arg4;
        transitionBlock.args[5] = (int64_t)arg5;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int32_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL5(int32_t, CallInterpreter_I32_I32_I32_I32_I32_RetI32, int32_t, int32_t, int32_t, int32_t, int32_t);
    WASM_CALLABLE_FUNC_6(int32_t, CallInterpreter_I32_I32_I32_I32_I32_RetI32, int32_t arg0, int32_t arg1, int32_t arg2, int32_t arg3, int32_t arg4, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[5];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        transitionBlock.args[2] = (int64_t)arg2;
        transitionBlock.args[3] = (int64_t)arg3;
        transitionBlock.args[4] = (int64_t)arg4;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int32_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL4(int32_t, CallInterpreter_I32_I32_I32_I32_RetI32, int32_t, int32_t, int32_t, int32_t);
    WASM_CALLABLE_FUNC_5(int32_t, CallInterpreter_I32_I32_I32_I32_RetI32, int32_t arg0, int32_t arg1, int32_t arg2, int32_t arg3, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[4];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        transitionBlock.args[2] = (int64_t)arg2;
        transitionBlock.args[3] = (int64_t)arg3;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int32_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL3(int32_t, CallInterpreter_I32_I32_I32_RetI32, int32_t, int32_t, int32_t);
    WASM_CALLABLE_FUNC_4(int32_t, CallInterpreter_I32_I32_I32_RetI32, int32_t arg0, int32_t arg1, int32_t arg2, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[3];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        transitionBlock.args[2] = (int64_t)arg2;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int32_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL2(int32_t, CallInterpreter_I32_I32_RetI32, int32_t, int32_t);
    WASM_CALLABLE_FUNC_3(int32_t, CallInterpreter_I32_I32_RetI32, int32_t arg0, int32_t arg1, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[2];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int32_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL1(int32_t, CallInterpreter_I32_RetI32, int32_t);
    WASM_CALLABLE_FUNC_2(int32_t, CallInterpreter_I32_RetI32, int32_t arg0, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[1];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int32_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL0(int32_t, CallInterpreter_Void_RetI32);
    WASM_CALLABLE_FUNC_1(int32_t, CallInterpreter_Void_RetI32, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;

        int32_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, 0, (int8_t*)&result);
        return result;
    }

    FCDECL1(int64_t, CallInterpreter_F64_RetI64, double);
    WASM_CALLABLE_FUNC_2(int64_t, CallInterpreter_F64_RetI64, double arg0, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[1];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        *(double*)&transitionBlock.args[0] = arg0;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int64_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL3(int64_t, CallInterpreter_I32_I64_I64_RetI64, int32_t, int64_t, int64_t);
    WASM_CALLABLE_FUNC_4(int64_t, CallInterpreter_I32_I64_I64_RetI64, int32_t arg0, int64_t arg1, int64_t arg2, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[3];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        transitionBlock.args[2] = (int64_t)arg2;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int64_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL2(int64_t, CallInterpreter_I32_I64_RetI64, int32_t, int64_t);
    WASM_CALLABLE_FUNC_3(int64_t, CallInterpreter_I32_I64_RetI64, int32_t arg0, int64_t arg1, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[2];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int64_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL1(int64_t, CallInterpreter_I32_RetI64, int32_t);
    WASM_CALLABLE_FUNC_2(int64_t, CallInterpreter_I32_RetI64, int32_t arg0, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[1];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int64_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL2(int64_t, CallInterpreter_I64_I64_RetI64, int64_t, int64_t);
    WASM_CALLABLE_FUNC_3(int64_t, CallInterpreter_I64_I64_RetI64, int64_t arg0, int64_t arg1, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[2];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        int64_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return result;
    }

    FCDECL0(int64_t, CallInterpreter_Void_RetI64);
    WASM_CALLABLE_FUNC_1(int64_t, CallInterpreter_Void_RetI64, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;

        int64_t result = 0;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, 0, (int8_t*)&result);
        return result;
    }

    FCDECL2(void, CallInterpreter_This_S12_RetVoid, int32_t, int8_t*);
    WASM_CALLABLE_FUNC_3(void, CallInterpreter_This_S12_RetVoid, int32_t arg0, int8_t* arg1, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[3];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        memcpy(&transitionBlock.args[1], arg1, 12);
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        void * result = NULL;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return;
    }

    FCDECL2(void, CallInterpreter_This_S32_RetVoid, int32_t, int8_t*);
    WASM_CALLABLE_FUNC_3(void, CallInterpreter_This_S32_RetVoid, int32_t arg0, int8_t* arg1, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[5];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        memcpy(&transitionBlock.args[1], arg1, 32);
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        void * result = NULL;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return;
    }

    FCDECL3(void, CallInterpreter_This_S8_S8_RetVoid, int32_t, int8_t*, int8_t*);
    WASM_CALLABLE_FUNC_4(void, CallInterpreter_This_S8_S8_RetVoid, int32_t arg0, int8_t* arg1, int8_t* arg2, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[3];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        memcpy(&transitionBlock.args[1], arg1, 8);
        memcpy(&transitionBlock.args[2], arg2, 8);
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        void * result = NULL;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return;
    }

    FCDECL3(void, CallInterpreter_This_S8_I32_RetVoid, int32_t, int8_t*, int32_t);
    WASM_CALLABLE_FUNC_4(void, CallInterpreter_This_S8_I32_RetVoid, int32_t arg0, int8_t* arg1, int32_t arg2, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[3];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        memcpy(&transitionBlock.args[1], arg1, 8);
        transitionBlock.args[2] = (int64_t)arg2;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        void * result = NULL;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return;
    }

    FCDECL2(void, CallInterpreter_This_S8_RetVoid, int32_t, int8_t*);
    WASM_CALLABLE_FUNC_3(void, CallInterpreter_This_S8_RetVoid, int32_t arg0, int8_t* arg1, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[2];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        memcpy(&transitionBlock.args[1], arg1, 8);
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        void * result = NULL;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return;
    }

    FCDECL3(void, CallInterpreter_This_I32_S8_RetVoid, int32_t, int32_t, int8_t*);
    WASM_CALLABLE_FUNC_4(void, CallInterpreter_This_I32_S8_RetVoid, int32_t arg0, int32_t arg1, int8_t* arg2, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[3];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        memcpy(&transitionBlock.args[2], arg2, 8);
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        void * result = NULL;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return;
    }

    FCDECL7(void, CallInterpreter_This_I32_I32_S8_S8_I32_I32_RetVoid, int32_t, int32_t, int32_t, int8_t*, int8_t*, int32_t, int32_t);
    WASM_CALLABLE_FUNC_8(void, CallInterpreter_This_I32_I32_S8_S8_I32_I32_RetVoid, int32_t arg0, int32_t arg1, int32_t arg2, int8_t* arg3, int8_t* arg4, int32_t arg5, int32_t arg6, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[7];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        transitionBlock.args[2] = (int64_t)arg2;
        memcpy(&transitionBlock.args[3], arg3, 8);
        memcpy(&transitionBlock.args[4], arg4, 8);
        transitionBlock.args[5] = (int64_t)arg5;
        transitionBlock.args[6] = (int64_t)arg6;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        void * result = NULL;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return;
    }

    FCDECL6(void, CallInterpreter_This_I32_I32_I32_I32_I32_RetVoid, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);
    WASM_CALLABLE_FUNC_7(void, CallInterpreter_This_I32_I32_I32_I32_I32_RetVoid, int32_t arg0, int32_t arg1, int32_t arg2, int32_t arg3, int32_t arg4, int32_t arg5, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[6];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        transitionBlock.args[2] = (int64_t)arg2;
        transitionBlock.args[3] = (int64_t)arg3;
        transitionBlock.args[4] = (int64_t)arg4;
        transitionBlock.args[5] = (int64_t)arg5;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        void * result = NULL;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return;
    }

    FCDECL5(void, CallInterpreter_This_I32_I32_I32_I32_RetVoid, int32_t, int32_t, int32_t, int32_t, int32_t);
    WASM_CALLABLE_FUNC_6(void, CallInterpreter_This_I32_I32_I32_I32_RetVoid, int32_t arg0, int32_t arg1, int32_t arg2, int32_t arg3, int32_t arg4, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[5];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        transitionBlock.args[2] = (int64_t)arg2;
        transitionBlock.args[3] = (int64_t)arg3;
        transitionBlock.args[4] = (int64_t)arg4;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        void * result = NULL;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return;
    }

    FCDECL4(void, CallInterpreter_This_I32_I32_I32_RetVoid, int32_t, int32_t, int32_t, int32_t);
    WASM_CALLABLE_FUNC_5(void, CallInterpreter_This_I32_I32_I32_RetVoid, int32_t arg0, int32_t arg1, int32_t arg2, int32_t arg3, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[4];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        transitionBlock.args[2] = (int64_t)arg2;
        transitionBlock.args[3] = (int64_t)arg3;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        void * result = NULL;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return;
    }

    FCDECL3(void, CallInterpreter_This_I32_I32_RetVoid, int32_t, int32_t, int32_t);
    WASM_CALLABLE_FUNC_4(void, CallInterpreter_This_I32_I32_RetVoid, int32_t arg0, int32_t arg1, int32_t arg2, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[3];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        transitionBlock.args[2] = (int64_t)arg2;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        void * result = NULL;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return;
    }

    FCDECL2(void, CallInterpreter_This_I32_RetVoid, int32_t, int32_t);
    WASM_CALLABLE_FUNC_3(void, CallInterpreter_This_I32_RetVoid, int32_t arg0, int32_t arg1, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[2];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        void * result = NULL;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return;
    }

    FCDECL1(void, CallInterpreter_This_RetVoid, int32_t);
    WASM_CALLABLE_FUNC_2(void, CallInterpreter_This_RetVoid, int32_t arg0, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[1];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        void * result = NULL;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return;
    }

    FCDECL3(void, CallInterpreter_F64_I32_I32_RetVoid, double, int32_t, int32_t);
    WASM_CALLABLE_FUNC_4(void, CallInterpreter_F64_I32_I32_RetVoid, double arg0, int32_t arg1, int32_t arg2, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[3];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        *(double*)&transitionBlock.args[0] = arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        transitionBlock.args[2] = (int64_t)arg2;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        void * result = NULL;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return;
    }

    FCDECL3(void, CallInterpreter_F32_I32_I32_RetVoid, float, int32_t, int32_t);
    WASM_CALLABLE_FUNC_4(void, CallInterpreter_F32_I32_I32_RetVoid, float arg0, int32_t arg1, int32_t arg2, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[3];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        *(float*)&transitionBlock.args[0] = arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        transitionBlock.args[2] = (int64_t)arg2;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        void * result = NULL;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return;
    }

    FCDECL4(void, CallInterpreter_I32_I32_I32_I32_RetVoid, int32_t, int32_t, int32_t, int32_t);
    WASM_CALLABLE_FUNC_5(void, CallInterpreter_I32_I32_I32_I32_RetVoid, int32_t arg0, int32_t arg1, int32_t arg2, int32_t arg3, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[4];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        transitionBlock.args[2] = (int64_t)arg2;
        transitionBlock.args[3] = (int64_t)arg3;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        void * result = NULL;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return;
    }

    FCDECL3(void, CallInterpreter_I32_I32_I32_RetVoid, int32_t, int32_t, int32_t);
    WASM_CALLABLE_FUNC_4(void, CallInterpreter_I32_I32_I32_RetVoid, int32_t arg0, int32_t arg1, int32_t arg2, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[3];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        transitionBlock.args[2] = (int64_t)arg2;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        void * result = NULL;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return;
    }

    FCDECL2(void, CallInterpreter_I32_I32_RetVoid, int32_t, int32_t);
    WASM_CALLABLE_FUNC_3(void, CallInterpreter_I32_I32_RetVoid, int32_t arg0, int32_t arg1, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[2];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        transitionBlock.args[1] = (int64_t)arg1;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        void * result = NULL;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return;
    }

    FCDECL1(void, CallInterpreter_I32_RetVoid, int32_t);
    WASM_CALLABLE_FUNC_2(void, CallInterpreter_I32_RetVoid, int32_t arg0, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
            int64_t args[1];
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;
        transitionBlock.args[0] = (int64_t)arg0;
        static_assert(offsetof(decltype(transitionBlock), args) == sizeof(TransitionBlock), "Args array must be at a TransitionBlock offset from the start of the block");

        void * result = NULL;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, sizeof(transitionBlock.args), (int8_t*)&result);
        return;
    }

    FCDECL0(void, CallInterpreter_Void_RetVoid);
    WASM_CALLABLE_FUNC_1(void, CallInterpreter_Void_RetVoid, PCODE portableEntrypoint)
    {
        struct
        {
            TransitionBlock block;
        } transitionBlock;
        transitionBlock.block.m_ReturnAddress = 0;
        transitionBlock.block.m_StackPointer = callersStackPointer;

        void * result = NULL;
        ExecuteInterpretedMethodWithArgs_PortableEntryPoint(portableEntrypoint, &transitionBlock.block, 0, (int8_t*)&result);
        return;
    }

}

const StringToWasmSigThunk g_wasmGeneratedPortableEntryPointThunks[] = {
    { "IS12TS12ip", (void*)&CallInterpreter_This_S12_I32_RetS12 },
    { "IS12TiS12ip", (void*)&CallInterpreter_This_I32_S12_I32_RetS12 },
    { "IS12Tiiip", (void*)&CallInterpreter_This_I32_I32_I32_RetS12 },
    { "IS12Tiip", (void*)&CallInterpreter_This_I32_I32_RetS12 },
    { "IS16Tp", (void*)&CallInterpreter_This_RetS16 },
    { "IS16l2ip", (void*)&CallInterpreter_L2_I32_RetS16 },
    { "IS1Tp", (void*)&CallInterpreter_This_RetS1 },
    { "IS8Tiiip", (void*)&CallInterpreter_This_I32_I32_I32_RetS8 },
    { "IS8Tip", (void*)&CallInterpreter_This_I32_RetS8 },
    { "IS8Tp", (void*)&CallInterpreter_This_RetS8 },
    { "Iddddp", (void*)&CallInterpreter_F64_F64_F64_RetF64 },
    { "Idddp", (void*)&CallInterpreter_F64_F64_RetF64 },
    { "Iddip", (void*)&CallInterpreter_F64_I32_RetF64 },
    { "Iddp", (void*)&CallInterpreter_F64_RetF64 },
    { "Iffffp", (void*)&CallInterpreter_F32_F32_F32_RetF32 },
    { "Ifffp", (void*)&CallInterpreter_F32_F32_RetF32 },
    { "Iffip", (void*)&CallInterpreter_F32_I32_RetF32 },
    { "Iffp", (void*)&CallInterpreter_F32_RetF32 },
    { "IiS8p", (void*)&CallInterpreter_S8_RetI32 },
    { "IiTS12ip", (void*)&CallInterpreter_This_S12_I32_RetI32 },
    { "IiTS12p", (void*)&CallInterpreter_This_S12_RetI32 },
    { "IiTS8S8p", (void*)&CallInterpreter_This_S8_S8_RetI32 },
    { "IiTS8iS8ip", (void*)&CallInterpreter_This_S8_I32_S8_I32_RetI32 },
    { "IiTS8iiip", (void*)&CallInterpreter_This_S8_I32_I32_I32_RetI32 },
    { "IiTS8ip", (void*)&CallInterpreter_This_S8_I32_RetI32 },
    { "IiTS8p", (void*)&CallInterpreter_This_S8_RetI32 },
    { "IiTiS12p", (void*)&CallInterpreter_This_I32_S12_RetI32 },
    { "IiTiS8p", (void*)&CallInterpreter_This_I32_S8_RetI32 },
    { "IiTiiiip", (void*)&CallInterpreter_This_I32_I32_I32_I32_RetI32 },
    { "IiTiiip", (void*)&CallInterpreter_This_I32_I32_I32_RetI32 },
    { "IiTiip", (void*)&CallInterpreter_This_I32_I32_RetI32 },
    { "IiTip", (void*)&CallInterpreter_This_I32_RetI32 },
    { "IiTp", (void*)&CallInterpreter_This_RetI32 },
    { "Iidp", (void*)&CallInterpreter_F64_RetI32 },
    { "IiiS8p", (void*)&CallInterpreter_I32_S8_RetI32 },
    { "Iiiiiiiiiip", (void*)&CallInterpreter_I32_I32_I32_I32_I32_I32_I32_I32_RetI32 },
    { "Iiiiiiiiip", (void*)&CallInterpreter_I32_I32_I32_I32_I32_I32_I32_RetI32 },
    { "Iiiiiiiip", (void*)&CallInterpreter_I32_I32_I32_I32_I32_I32_RetI32 },
    { "Iiiiiiip", (void*)&CallInterpreter_I32_I32_I32_I32_I32_RetI32 },
    { "Iiiiiip", (void*)&CallInterpreter_I32_I32_I32_I32_RetI32 },
    { "Iiiiip", (void*)&CallInterpreter_I32_I32_I32_RetI32 },
    { "Iiiip", (void*)&CallInterpreter_I32_I32_RetI32 },
    { "Iiip", (void*)&CallInterpreter_I32_RetI32 },
    { "Iip", (void*)&CallInterpreter_Void_RetI32 },
    { "Ildp", (void*)&CallInterpreter_F64_RetI64 },
    { "Ilillp", (void*)&CallInterpreter_I32_I64_I64_RetI64 },
    { "Ililp", (void*)&CallInterpreter_I32_I64_RetI64 },
    { "Ilip", (void*)&CallInterpreter_I32_RetI64 },
    { "Illlp", (void*)&CallInterpreter_I64_I64_RetI64 },
    { "Ilp", (void*)&CallInterpreter_Void_RetI64 },
    { "IvTS12p", (void*)&CallInterpreter_This_S12_RetVoid },
    { "IvTS32p", (void*)&CallInterpreter_This_S32_RetVoid },
    { "IvTS8S8p", (void*)&CallInterpreter_This_S8_S8_RetVoid },
    { "IvTS8ip", (void*)&CallInterpreter_This_S8_I32_RetVoid },
    { "IvTS8p", (void*)&CallInterpreter_This_S8_RetVoid },
    { "IvTiS8p", (void*)&CallInterpreter_This_I32_S8_RetVoid },
    { "IvTiiS8S8iip", (void*)&CallInterpreter_This_I32_I32_S8_S8_I32_I32_RetVoid },
    { "IvTiiiiip", (void*)&CallInterpreter_This_I32_I32_I32_I32_I32_RetVoid },
    { "IvTiiiip", (void*)&CallInterpreter_This_I32_I32_I32_I32_RetVoid },
    { "IvTiiip", (void*)&CallInterpreter_This_I32_I32_I32_RetVoid },
    { "IvTiip", (void*)&CallInterpreter_This_I32_I32_RetVoid },
    { "IvTip", (void*)&CallInterpreter_This_I32_RetVoid },
    { "IvTp", (void*)&CallInterpreter_This_RetVoid },
    { "Ivdiip", (void*)&CallInterpreter_F64_I32_I32_RetVoid },
    { "Ivfiip", (void*)&CallInterpreter_F32_I32_I32_RetVoid },
    { "Iviiiip", (void*)&CallInterpreter_I32_I32_I32_I32_RetVoid },
    { "Iviiip", (void*)&CallInterpreter_I32_I32_I32_RetVoid },
    { "Iviip", (void*)&CallInterpreter_I32_I32_RetVoid },
    { "Ivip", (void*)&CallInterpreter_I32_RetVoid },
    { "Ivp", (void*)&CallInterpreter_Void_RetVoid },
};

const size_t g_wasmGeneratedPortableEntryPointThunksCount = sizeof(g_wasmGeneratedPortableEntryPointThunks) / sizeof(g_wasmGeneratedPortableEntryPointThunks[0]);
