parameters:
  perfBranch: 'main' # Currently only used for building the BDN App

jobs:
  # Temporarily build only macOS Arm64 while validating the M4 queue.
  - template: /eng/pipelines/performance/templates/perf-coreclr-build-jobs.yml
    parameters:
      ${{ if not(startswith(variables['Build.SourceBranch'], 'refs/heads/release')) }}:
        osx_arm64: true
