parameters:
  coreclr: false

jobs:
  - ${{ if eq(parameters.coreclr, true) }}:
    # build coreclr and libraries
    - template: /eng/pipelines/performance/templates/perf-coreclr-build-jobs.yml
      parameters:
        linux_arm64: true
        windows_arm64: true
