parameters:
  perfBranch: 'main' # Currently only used for building the BDN App
  jobsAndPlatforms: [
    'coreclr:linux_x64', 'coreclr:windows_x64', 'coreclr:windows_x86', 'coreclr:linux_musl_x64',
    'monoAot',
    'monoAndroid',
    'mono',
    'monoPacks',
    'perfBDNApp'
  ]
  mauiFramework: '' # Framework version to get versions for and build for (e.g. net9.0)

jobs:
  - ${{ if or(containsValue(parameters.jobsAndPlatforms, 'coreclr:linux_x64'), containsValue(parameters.jobsAndPlatforms, 'coreclr:windows_x64'), containsValue(parameters.jobsAndPlatforms, 'coreclr:windows_x86'), containsValue(parameters.jobsAndPlatforms, 'coreclr:linux_musl_x64')) }}:
    # build coreclr and libraries
    - template: /eng/pipelines/common/platform-matrix.yml
      parameters:
        jobTemplate: /eng/pipelines/common/global-build-job.yml
        buildConfig: release
        platforms: 
        - ${{ if containsValue(parameters.jobsAndPlatforms, 'coreclr:linux_x64') }}:
          - linux_x64
        - ${{ if containsValue(parameters.jobsAndPlatforms, 'coreclr:windows_x64') }}:
          - windows_x64
        - ${{ if containsValue(parameters.jobsAndPlatforms, 'coreclr:windows_x86') }}:
          - windows_x86
        - ${{ if containsValue(parameters.jobsAndPlatforms, 'coreclr:linux_musl_x64') }}:
          - linux_musl_x64
        jobParameters:
          nameSuffix: coreclr
          buildArgs: -s clr+libs+host+packs -c $(_BuildConfig)
          isOfficialBuild: false
          postBuildSteps:
          - template: /eng/pipelines/common/upload-artifact-step.yml
            parameters:
              rootFolder: $(Build.SourcesDirectory)/artifacts/bin
              includeRootFolder: false
              archiveType: $(archiveType)
              archiveExtension: $(archiveExtension)
              tarCompression: $(tarCompression)
              artifactName: BuildArtifacts_$(osGroup)$(osSubgroup)_$(archType)_$(_BuildConfig)_coreclr
              displayName: Build Assets

  - ${{ if containsValue(parameters.jobsAndPlatforms, 'monoAot') }}:
    # build mono for AOT
    - template: /eng/pipelines/common/platform-matrix.yml
      parameters:
        jobTemplate: /eng/pipelines/common/global-build-job.yml
        buildConfig: release
        runtimeFlavor: mono
        platforms:
        - linux_x64
        jobParameters:
          buildArgs: -s mono+libs+host+packs -c $(_BuildConfig) /p:MonoAOTEnableLLVM=true /p:MonoEnableLLVM=true /p:BuildMonoAOTCrossCompiler=true /p:AotHostArchitecture=x64 /p:AotHostOS=linux
          nameSuffix: AOT
          isOfficialBuild: false
          postBuildSteps:
            - template: /eng/pipelines/common/upload-artifact-step.yml
              parameters:
                rootFolder: '$(Build.SourcesDirectory)/artifacts/'
                includeRootFolder: true
                displayName: AOT Mono Artifacts
                artifactName: LinuxMonoAOTx64
                archiveExtension: '.tar.gz'
                archiveType: tar
                tarCompression: gz

  - ${{ if containsValue(parameters.jobsAndPlatforms, 'monoAndroid') }}:
    # build mono Android scenarios
    - template: /eng/pipelines/common/platform-matrix.yml
      parameters:
        jobTemplate: /eng/pipelines/common/global-build-job.yml
        buildConfig: release
        runtimeFlavor: mono
        platforms:
        - android_arm64
        jobParameters:
          buildArgs: -s mono+libs+host+packs -c $(_BuildConfig)
          nameSuffix: AndroidMono
          isOfficialBuild: false
          postBuildSteps:
            - template: /eng/pipelines/performance/templates/build-perf-sample-apps.yml
              parameters:
                rootFolder: '$(Build.SourcesDirectory)/artifacts/'
                includeRootFolder: true
                displayName: Android Mono Artifacts
                artifactName: AndroidMonoarm64
                archiveExtension: '.tar.gz'
                archiveType: tar
                tarCompression: gz
                
  - ${{ if containsValue(parameters.jobsAndPlatforms, 'mono') }}:
    # build mono
    - template: /eng/pipelines/common/platform-matrix.yml
      parameters:
        jobTemplate: /eng/pipelines/common/global-build-job.yml
        buildConfig: release
        runtimeFlavor: mono
        platforms:
        - linux_x64
        jobParameters:
          nameSuffix: mono
          buildArgs: -s mono+clr.iltools+clr.hosts+libs+host+packs -c $(_BuildConfig)
          isOfficialBuild: false
          postBuildSteps:
          - template: /eng/pipelines/common/upload-artifact-step.yml
            parameters:
              rootFolder: $(Build.SourcesDirectory)/artifacts/bin
              includeRootFolder: false
              archiveType: $(archiveType)
              archiveExtension: $(archiveExtension)
              tarCompression: $(tarCompression)
              artifactName: BuildArtifacts_$(osGroup)$(osSubgroup)_$(archType)_$(_BuildConfig)_mono
              displayName: Build Assets
              
  - ${{ if containsValue(parameters.jobsAndPlatforms, 'monoPacks') }}:
    # build mono runtime packs
    - template: /eng/pipelines/common/platform-matrix.yml
      parameters:
        jobTemplate: /eng/pipelines/common/global-build-job.yml
        buildConfig: release
        runtimeFlavor: mono
        platforms:
        - android_arm64
        jobParameters:
          buildArgs: -s mono+libs+host+packs -c $(_BuildConfig)
          nameSuffix: Mono_Packs
          isOfficialBuild: false
          postBuildSteps:
            - template: /eng/pipelines/common/upload-intermediate-artifacts-step.yml
              parameters:
                name: MonoRuntimePacks
                isOfficialBuild: false
                
  - ${{ if containsValue(parameters.jobsAndPlatforms, 'perfBDNApp') }}:
    # build PerfBDN app
    - template: /eng/pipelines/common/platform-matrix.yml
      parameters:
        jobTemplate: /eng/pipelines/common/global-build-job.yml
        buildConfig: release
        runtimeFlavor: mono
        platforms:
        - ios_arm64
        jobParameters:
          dependsOn:
           - Build_android_arm64_release_Mono_Packs
          buildArgs: -s mono -c $(_BuildConfig)
          nameSuffix: PerfBDNApp
          isOfficialBuild: false
          pool:
            vmImage: 'macos-13'
          postBuildSteps:
            - template: /eng/pipelines/performance/templates/build-perf-bdn-app.yml
              parameters:
                rootFolder: '$(Build.SourcesDirectory)/artifacts/'
                includeRootFolder: true
                displayName: Android BDN App Artifacts
                artifactName: PerfBDNAppArm
                archiveExtension: '.tar.gz'
                archiveType: tar
                tarCompression: gz
                perfBranch: ${{ parameters.perfBranch }}
                ${{ if parameters.mauiFramework }}:
                  framework: ${{ parameters.mauiFramework }}
