// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const gC_API_NoGCRegion_callback = CoreClr.coreclr_test({
    name: "Callback",
    srcs: ["Callback.cs"],
    run: false,
});

@@public
export const gC_API_NoGCRegion_callback_Svr = CoreClr.coreclr_test({
    name: "Callback_Svr",
    srcs: ["Callback.cs"],
    run: false,
});

@@public
export const gC_API_NoGCRegion_noGC = CoreClr.coreclr_test({
    name: "NoGC",
    srcs: ["NoGC.cs"],
});
