<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="..\..\Directory.Build.props" />

  <PropertyGroup>
    <CLRTestTargetUnsupported Condition="'$(RuntimeFlavor)' == 'coreclr' and '$(TargetOS)' == 'browser'">true</CLRTestTargetUnsupported>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(TestLibraryProjectPath)" />
  </ItemGroup>
</Project>
