#!/bin/sh
#
# Licensed to the .NET Foundation under one or more agreements.
# The .NET Foundation licenses this file to you under the MIT license.
#

PACKAGE=$1
INSTALL_DESTINATION=$2

# A temporary fix for the permissions issue(s)
chmod -R 755 $INSTALL_DESTINATION/shared

exit 0
