<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Needed for GC.WaitForPendingFinalizers and to exercise the process-wide cache in isolation -->
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="GenericVirtualMethodUnloaded.csproj" />
    <Compile Include="GenericVirtualMethod.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="$(TestLibraryProjectPath)" />
  </ItemGroup>
</Project>
