// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const loader_classloader_DefaultInterfaceMethods_sharedgenerics_non_virtual_calls_to_instance_methods = il_coreclr_test({
    name: "non_virtual_calls_to_instance_methods",
    srcs: ["non_virtual_calls_to_instance_methods.il"],
});

@@public
export const loader_classloader_DefaultInterfaceMethods_sharedgenerics_sharedgenerics_d = il_coreclr_test({
    name: "sharedgenerics_d",
    srcs: ["sharedgenerics.il"],
});

@@public
export const loader_classloader_DefaultInterfaceMethods_sharedgenerics_sharedgenerics_r = il_coreclr_test({
    name: "sharedgenerics_r",
    srcs: ["sharedgenerics.il"],
});
