// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const gC_Regressions_v2_0_beta1_149926__149926 = coreclr_test({
    name: "149926",
    srcs: ["149926.cs"],
});
