// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_Directed_StructPromote_fldSeqsInPromotedCpBlk = CoreClr.coreclr_test({
    name: "FldSeqsInPromotedCpBlk",
    srcs: ["FldSeqsInPromotedCpBlk.cs"],
    optimize: true,
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Directed_StructPromote_sP1 = CoreClr.coreclr_test({
    name: "SP1",
    srcs: ["SP1.cs"],
    optimize: true,
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Directed_StructPromote_sP1a = CoreClr.coreclr_test({
    name: "SP1a",
    srcs: ["SP1a.cs"],
    optimize: true,
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Directed_StructPromote_sP1a2 = CoreClr.coreclr_test({
    name: "SP1a2",
    srcs: ["SP1a2.cs"],
    optimize: true,
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Directed_StructPromote_sP1b = CoreClr.coreclr_test({
    name: "SP1b",
    srcs: ["SP1b.cs"],
    optimize: true,
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Directed_StructPromote_sP1c = CoreClr.coreclr_test({
    name: "SP1c",
    srcs: ["SP1c.cs"],
    optimize: true,
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Directed_StructPromote_sP1d = CoreClr.coreclr_test({
    name: "SP1d",
    srcs: ["SP1d.cs"],
    optimize: true,
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Directed_StructPromote_sP2 = CoreClr.coreclr_test({
    name: "SP2",
    srcs: ["SP2.cs"],
    optimize: true,
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Directed_StructPromote_sP2a = CoreClr.coreclr_test({
    name: "SP2a",
    srcs: ["SP2a.cs"],
    optimize: true,
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Directed_StructPromote_sP2b = CoreClr.coreclr_test({
    name: "SP2b",
    srcs: ["SP2b.cs"],
    optimize: true,
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Directed_StructPromote_sP2c = CoreClr.coreclr_test({
    name: "SP2c",
    srcs: ["SP2c.cs"],
    optimize: true,
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Directed_StructPromote_spAddr = CoreClr.coreclr_test({
    name: "SpAddr",
    srcs: ["SpAddr.cs"],
    optimize: true,
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Directed_StructPromote_spAddrAT = CoreClr.coreclr_test({
    name: "SpAddrAT",
    srcs: ["SpAddrAT.cs"],
    optimize: true,
    pri: 1,
    size: "medium",
});
