// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Collections.ObjectModel.ObservableCollection<>))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Collections.ObjectModel.ReadOnlyObservableCollection<>))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Collections.Specialized.INotifyCollectionChanged))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Collections.Specialized.NotifyCollectionChangedAction))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Collections.Specialized.NotifyCollectionChangedEventArgs))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Collections.Specialized.NotifyCollectionChangedEventHandler))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.FileFormatException))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Packaging.CompressionOption))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Packaging.EncryptionOption))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Packaging.Package))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Packaging.PackagePart))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Packaging.PackagePartCollection))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Packaging.PackageProperties))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Packaging.PackageRelationship))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Packaging.PackageRelationshipCollection))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Packaging.PackageRelationshipSelector))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Packaging.PackageRelationshipSelectorType))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Packaging.PackUriHelper))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Packaging.TargetMode))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Packaging.ZipPackage))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.IO.Packaging.ZipPackagePart))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.Permissions.MediaPermission))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.Permissions.MediaPermissionAttribute))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.Permissions.MediaPermissionAudio))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.Permissions.MediaPermissionImage))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.Permissions.MediaPermissionVideo))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.Permissions.WebBrowserPermission))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.Permissions.WebBrowserPermissionAttribute))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Security.Permissions.WebBrowserPermissionLevel))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Windows.Markup.ValueSerializerAttribute))]
