// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_opt_perf_doublealign_locals = coreclr_test({
    name: "Locals",
    srcs: ["locals.cs"],
    allowUnsafe: true,
    optimize: true,
    pri: 1,
    size: "medium",
});
