// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_JitBlue_Runtime_68568_runtime_68568 = il_coreclr_test({
    name: "Runtime_68568",
    srcs: ["Runtime_68568.il"],
    optimize: true,
});
