// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_JitBlue_Runtime_55141_runtime_55141 = coreclr_test({
    name: "Runtime_55141",
    srcs: ["Runtime_55141.cs"],
    optimize: true,
});

@@public
export const jIT_Regression_JitBlue_Runtime_55141_runtime_55141_2 = coreclr_test({
    name: "Runtime_55141_2",
    srcs: ["Runtime_55141_2.cs"],
    optimize: true,
});
