// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_CLR_x86_EJIT_V1_M09_5_PDC_b12008_b12008 = coreclr_test({
    name: "b12008",
    srcs: ["b12008.cs"],
    debugType: "pdbonly",
    pri: 1,
    size: "medium",
});
