#!/bin/sh

MANAGED_CALLS=`gdb -silent $1 -pid $2 << EOF | awk '/.* in \?\? \(\)/ {printf("call print_method_from_ip(%s)\n", $2);}'
set height 0
thread apply all bt
quit
EOF`

gdb -silent $1 -pid $2 << EOF
set height 0
thread apply all bt
$MANAGED_CALLS
quit
EOF

