// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const loader_StartupHooks_Hooks_Invalid_instanceMethod = coreclr_test({
    name: "InstanceMethod",
    srcs: ["InvalidHook.cs"],
});

@@public
export const loader_StartupHooks_Hooks_Invalid_multipleIncorrectSignatures = coreclr_test({
    name: "MultipleIncorrectSignatures",
    srcs: ["InvalidHook.cs"],
});

@@public
export const loader_StartupHooks_Hooks_Invalid_noInitializeMethod = coreclr_test({
    name: "NoInitializeMethod",
    srcs: ["InvalidHook.cs"],
});

@@public
export const loader_StartupHooks_Hooks_Invalid_nonVoidReturn = coreclr_test({
    name: "NonVoidReturn",
    srcs: ["InvalidHook.cs"],
});

@@public
export const loader_StartupHooks_Hooks_Invalid_notParameterless = coreclr_test({
    name: "NotParameterless",
    srcs: ["InvalidHook.cs"],
});
