<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="TestUtilities.Shared.props" />

  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.XUnitExtensions" Version="$(MicrosoftDotNetXUnitExtensionsVersion)" />
    <PackageReference Include="xunit.core" Version="$(XUnitVersion)" ExcludeAssets="build" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETCoreApp'">
    <!-- Use the arcade fork of xunit.assert for AOT-compat -->
    <PackageReference Include="Microsoft.DotNet.XUnitAssert" Version="$(MicrosoftDotNetXUnitAssertVersion)" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'">
    <PackageReference Include="xunit.assert" Version="$(XUnitVersion)" />
  </ItemGroup>

</Project>
