<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>TestUtilities</AssemblyName>
    <RootNamespace>TestUtilities</RootNamespace>
    <DefineConstants>$(DefineConstants);XUNIT_V3</DefineConstants>
  </PropertyGroup>

  <Import Project="TestUtilities.Shared.props" />

  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.XUnitV3Extensions" Version="$(MicrosoftDotNetXUnitExtensionsVersion)" />
    <PackageReference Include="xunit.v3.assert" Version="$(XUnitV3Version)" />
    <PackageReference Include="xunit.v3.extensibility.core" Version="$(XUnitV3Version)" ExcludeAssets="build" />
  </ItemGroup>

</Project>
