<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <CLRTestPriority>1</CLRTestPriority>
    <!-- TODO: Re-enable when browser OOP host actions can run parallel crashing children and managed threads are available.
         Tracked by https://github.com/dotnet/runtime/issues/131321. -->
    <CLRTestTargetUnsupported Condition="'$(RuntimeFlavor)' == 'coreclr' and '$(TargetOS)' == 'browser'">true</CLRTestTargetUnsupported>
    <!-- Needed for CLRTestTargetUnsupported, NativeAotIncompatible, ProjectReference CopyToOutputDirectory, and Process.Start -->
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <!-- Test expects corerun -->
    <NativeAotIncompatible>true</NativeAotIncompatible>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="ParallelCrashTester.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="$(TestLibraryProjectPath)" />
    <ProjectReference Include="ParallelCrash.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <OutputItemType>Content</OutputItemType>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </ProjectReference>
  </ItemGroup>
</Project>
