<Project>
  <PropertyGroup>
    <linux_ChromeVersion>153.0.8010.36</linux_ChromeVersion>
    <linux_ChromeRevision>1681091</linux_ChromeRevision>
    <linux_ChromeBaseSnapshotUrl>https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/1681097</linux_ChromeBaseSnapshotUrl>
    <linux_V8Version>15.3.76</linux_V8Version>
    <macos_ChromeVersion>154.0.8037.17</macos_ChromeVersion>
    <macos_ChromeRevision>1689415</macos_ChromeRevision>
    <macos_ChromeBaseSnapshotUrl>https://storage.googleapis.com/chromium-browser-snapshots/Mac_Arm/1689421</macos_ChromeBaseSnapshotUrl>
    <macos_V8Version>15.4.80</macos_V8Version>
    <win_ChromeVersion>154.0.8037.17</win_ChromeVersion>
    <win_ChromeRevision>1689415</win_ChromeRevision>
    <win_ChromeBaseSnapshotUrl>https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/1689481</win_ChromeBaseSnapshotUrl>
    <win_V8Version>15.4.80</win_V8Version>
    <linux_FirefoxRevision>140.11.0esr</linux_FirefoxRevision>
    <linux_GeckoDriverRevision>0.37.0</linux_GeckoDriverRevision>
    <win_FirefoxRevision>140.11.0esr</win_FirefoxRevision>
    <win_GeckoDriverRevision>0.37.0</win_GeckoDriverRevision>
  </PropertyGroup>
</Project>