// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_Regression_JitBlue_Runtime_54842_runtime_54842 = CoreClr.coreclr_test({
    name: "Runtime_54842",
    srcs: ["Runtime_54842.cs"],
    optimize: true,
    run: false,
});
