// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_CLR_x86_JIT_v2_2_ddb_b429039_b429039 = il_coreclr_test({
    name: "b429039",
    srcs: ["b429039.il"],
    debugType: "pdbonly",
    optimize: true,
});
