// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Collections.Generic;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Tests;

namespace System.Text.Json.SourceGeneration.Tests
{
    public sealed partial class StructuralJsonTypeClassifierTests_Metadata : StructuralJsonTypeClassifierTests
    {
        public StructuralJsonTypeClassifierTests_Metadata()
            : base(new StringSerializerWrapper(StructuralJsonTypeClassifierTestsContext_Metadata.Default))
        {
        }

        [JsonSourceGenerationOptions(GenerationMode = JsonSourceGenerationMode.Metadata)]
        [JsonSerializable(typeof(ArrayOrDictionaryUnion))]
        [JsonSerializable(typeof(Batch<StatusReading>))]
        [JsonSerializable(typeof(Batch<TemperatureReading>))]
        [JsonSerializable(typeof(BatchUnion))]
        [JsonSerializable(typeof(BooleanUnion))]
        [JsonSerializable(typeof(CaseSensitiveDiscriminatorUnion))]
        [JsonSerializable(typeof(Cat))]
        [JsonSerializable(typeof(CustomNullableConverterUnion))]
        [JsonSerializable(typeof(Dictionary<string, JsonElement>))]
        [JsonSerializable(typeof(Dictionary<string, int>))]
        [JsonSerializable(typeof(Dictionary<string, string>))]
        [JsonSerializable(typeof(DictionaryUnion))]
        [JsonSerializable(typeof(Dog))]
        [JsonSerializable(typeof(DuplicatePropertyA))]
        [JsonSerializable(typeof(DuplicatePropertyB))]
        [JsonSerializable(typeof(DuplicatePropertyNameUnion))]
        [JsonSerializable(typeof(ExtensionDataCase))]
        [JsonSerializable(typeof(ExtensionDataFallback))]
        [JsonSerializable(typeof(ExtensionDataUnion))]
        [JsonSerializable(typeof(IdenticalCat))]
        [JsonSerializable(typeof(IdenticalDog))]
        [JsonSerializable(typeof(IdenticalPetUnion))]
        [JsonSerializable(typeof(InnerScalarUnion))]
        [JsonSerializable(typeof(JsonArray))]
        [JsonSerializable(typeof(JsonArrayOrStringUnion))]
        [JsonSerializable(typeof(JsonElement))]
        [JsonSerializable(typeof(JsonElementOrRequiredObjectUnion))]
        [JsonSerializable(typeof(JsonElementRequiredObjectCase))]
        [JsonSerializable(typeof(JsonObject))]
        [JsonSerializable(typeof(JsonObjectOrDictionaryUnion))]
        [JsonSerializable(typeof(JsonObjectOrStringUnion))]
        [JsonSerializable(typeof(JsonValue))]
        [JsonSerializable(typeof(JsonValueOrRequiredObjectUnion))]
        [JsonSerializable(typeof(LargeObjectCaseUnion))]
        [JsonSerializable(typeof(LargePropertyCase))]
        [JsonSerializable(typeof(LargePropertyUnion))]
        [JsonSerializable(typeof(Leaf))]
        [JsonSerializable(typeof(List<int>))]
        [JsonSerializable(typeof(List<string>))]
        [JsonSerializable(typeof(ListUnion))]
        [JsonSerializable(typeof(LongPropertyCase))]
        [JsonSerializable(typeof(LongPropertyUnion))]
        [JsonSerializable(typeof(Loose))]
        [JsonSerializable(typeof(LowercaseDiscriminatorBase))]
        [JsonSerializable(typeof(LowercaseDiscriminatorDerived))]
        [JsonSerializable(typeof(ManyObjectCasesUnion))]
        [JsonSerializable(typeof(MisconfiguredPolymorphicBase))]
        [JsonSerializable(typeof(MisconfiguredPolymorphicDerived))]
        [JsonSerializable(typeof(NumberHandlingUnion))]
        [JsonSerializable(typeof(NumericStringUnion))]
        [JsonSerializable(typeof(NumericUnion))]
        [JsonSerializable(typeof(ObjectOrDictionaryUnion))]
        [JsonSerializable(typeof(OptionalSubsetBase))]
        [JsonSerializable(typeof(OptionalSubsetDerived))]
        [JsonSerializable(typeof(OptionalSubsetUnion))]
        [JsonSerializable(typeof(Order))]
        [JsonSerializable(typeof(OtherRenamedPropertyCase))]
        [JsonSerializable(typeof(OuterNestedUnion))]
        [JsonSerializable(typeof(PetUnion))]
        [JsonSerializable(typeof(Point))]
        [JsonSerializable(typeof(PolyAnimal))]
        [JsonSerializable(typeof(PolyCat))]
        [JsonSerializable(typeof(PolyDog))]
        [JsonSerializable(typeof(PolymorphicCollectionOrStringUnion))]
        [JsonSerializable(typeof(PolymorphicIntList))]
        [JsonSerializable(typeof(DerivedPolymorphicIntList))]
        [JsonSerializable(typeof(PolymorphicOrStringUnion))]
        [JsonSerializable(typeof(Quote))]
        [JsonSerializable(typeof(RenamedPropertyCase))]
        [JsonSerializable(typeof(RenamedPropertyUnion))]
        [JsonSerializable(typeof(RequiredOverlapA))]
        [JsonSerializable(typeof(RequiredOverlapB))]
        [JsonSerializable(typeof(RequiredOverlapUnion))]
        [JsonSerializable(typeof(RequiredPropertyUnion))]
        [JsonSerializable(typeof(SinglePropertyCase))]
        [JsonSerializable(typeof(StatusReading))]
        [JsonSerializable(typeof(Strict))]
        [JsonSerializable(typeof(StringUnion))]
        [JsonSerializable(typeof(SubtractionAlpha))]
        [JsonSerializable(typeof(SubtractionBeta))]
        [JsonSerializable(typeof(SubtractionDelta))]
        [JsonSerializable(typeof(SubtractionGamma))]
        [JsonSerializable(typeof(SubtractionUnion))]
        [JsonSerializable(typeof(TemperatureReading))]
        [JsonSerializable(typeof(TreeNode))]
        [JsonSerializable(typeof(TreeUnion))]
        [JsonSerializable(typeof(UnicodeOtherPropertyCase))]
        [JsonSerializable(typeof(UnicodePropertyCase))]
        [JsonSerializable(typeof(UnicodePropertyUnion))]
        [JsonSerializable(typeof(UniqueShapeUnion))]
        [JsonSerializable(typeof(UnmappedMemberUnion))]
        [JsonSerializable(typeof(UppercaseDiscriminatorBase))]
        [JsonSerializable(typeof(UppercaseDiscriminatorDerived))]
        internal sealed partial class StructuralJsonTypeClassifierTestsContext_Metadata : JsonSerializerContext
        {
        }
    }

    public sealed partial class StructuralJsonTypeClassifierTests_Default : StructuralJsonTypeClassifierTests
    {
        public StructuralJsonTypeClassifierTests_Default()
            : base(new StringSerializerWrapper(StructuralJsonTypeClassifierTestsContext_Default.Default))
        {
        }

        [JsonSerializable(typeof(ArrayOrDictionaryUnion))]
        [JsonSerializable(typeof(Batch<StatusReading>))]
        [JsonSerializable(typeof(Batch<TemperatureReading>))]
        [JsonSerializable(typeof(BatchUnion))]
        [JsonSerializable(typeof(BooleanUnion))]
        [JsonSerializable(typeof(CaseSensitiveDiscriminatorUnion))]
        [JsonSerializable(typeof(Cat))]
        [JsonSerializable(typeof(CustomNullableConverterUnion))]
        [JsonSerializable(typeof(Dictionary<string, JsonElement>))]
        [JsonSerializable(typeof(Dictionary<string, int>))]
        [JsonSerializable(typeof(Dictionary<string, string>))]
        [JsonSerializable(typeof(DictionaryUnion))]
        [JsonSerializable(typeof(Dog))]
        [JsonSerializable(typeof(DuplicatePropertyA))]
        [JsonSerializable(typeof(DuplicatePropertyB))]
        [JsonSerializable(typeof(DuplicatePropertyNameUnion))]
        [JsonSerializable(typeof(ExtensionDataCase))]
        [JsonSerializable(typeof(ExtensionDataFallback))]
        [JsonSerializable(typeof(ExtensionDataUnion))]
        [JsonSerializable(typeof(IdenticalCat))]
        [JsonSerializable(typeof(IdenticalDog))]
        [JsonSerializable(typeof(IdenticalPetUnion))]
        [JsonSerializable(typeof(InnerScalarUnion))]
        [JsonSerializable(typeof(JsonArray))]
        [JsonSerializable(typeof(JsonArrayOrStringUnion))]
        [JsonSerializable(typeof(JsonElement))]
        [JsonSerializable(typeof(JsonElementOrRequiredObjectUnion))]
        [JsonSerializable(typeof(JsonElementRequiredObjectCase))]
        [JsonSerializable(typeof(JsonObject))]
        [JsonSerializable(typeof(JsonObjectOrDictionaryUnion))]
        [JsonSerializable(typeof(JsonObjectOrStringUnion))]
        [JsonSerializable(typeof(JsonValue))]
        [JsonSerializable(typeof(JsonValueOrRequiredObjectUnion))]
        [JsonSerializable(typeof(LargeObjectCaseUnion))]
        [JsonSerializable(typeof(LargePropertyCase))]
        [JsonSerializable(typeof(LargePropertyUnion))]
        [JsonSerializable(typeof(Leaf))]
        [JsonSerializable(typeof(List<int>))]
        [JsonSerializable(typeof(List<string>))]
        [JsonSerializable(typeof(ListUnion))]
        [JsonSerializable(typeof(LongPropertyCase))]
        [JsonSerializable(typeof(LongPropertyUnion))]
        [JsonSerializable(typeof(Loose))]
        [JsonSerializable(typeof(LowercaseDiscriminatorBase))]
        [JsonSerializable(typeof(LowercaseDiscriminatorDerived))]
        [JsonSerializable(typeof(ManyObjectCasesUnion))]
        [JsonSerializable(typeof(MisconfiguredPolymorphicBase))]
        [JsonSerializable(typeof(MisconfiguredPolymorphicDerived))]
        [JsonSerializable(typeof(NumberHandlingUnion))]
        [JsonSerializable(typeof(NumericStringUnion))]
        [JsonSerializable(typeof(NumericUnion))]
        [JsonSerializable(typeof(ObjectOrDictionaryUnion))]
        [JsonSerializable(typeof(OptionalSubsetBase))]
        [JsonSerializable(typeof(OptionalSubsetDerived))]
        [JsonSerializable(typeof(OptionalSubsetUnion))]
        [JsonSerializable(typeof(Order))]
        [JsonSerializable(typeof(OtherRenamedPropertyCase))]
        [JsonSerializable(typeof(OuterNestedUnion))]
        [JsonSerializable(typeof(PetUnion))]
        [JsonSerializable(typeof(Point))]
        [JsonSerializable(typeof(PolyAnimal))]
        [JsonSerializable(typeof(PolyCat))]
        [JsonSerializable(typeof(PolyDog))]
        [JsonSerializable(typeof(PolymorphicCollectionOrStringUnion))]
        [JsonSerializable(typeof(PolymorphicIntList))]
        [JsonSerializable(typeof(DerivedPolymorphicIntList))]
        [JsonSerializable(typeof(PolymorphicOrStringUnion))]
        [JsonSerializable(typeof(Quote))]
        [JsonSerializable(typeof(RenamedPropertyCase))]
        [JsonSerializable(typeof(RenamedPropertyUnion))]
        [JsonSerializable(typeof(RequiredOverlapA))]
        [JsonSerializable(typeof(RequiredOverlapB))]
        [JsonSerializable(typeof(RequiredOverlapUnion))]
        [JsonSerializable(typeof(RequiredPropertyUnion))]
        [JsonSerializable(typeof(SinglePropertyCase))]
        [JsonSerializable(typeof(StatusReading))]
        [JsonSerializable(typeof(Strict))]
        [JsonSerializable(typeof(StringUnion))]
        [JsonSerializable(typeof(SubtractionAlpha))]
        [JsonSerializable(typeof(SubtractionBeta))]
        [JsonSerializable(typeof(SubtractionDelta))]
        [JsonSerializable(typeof(SubtractionGamma))]
        [JsonSerializable(typeof(SubtractionUnion))]
        [JsonSerializable(typeof(TemperatureReading))]
        [JsonSerializable(typeof(TreeNode))]
        [JsonSerializable(typeof(TreeUnion))]
        [JsonSerializable(typeof(UnicodeOtherPropertyCase))]
        [JsonSerializable(typeof(UnicodePropertyCase))]
        [JsonSerializable(typeof(UnicodePropertyUnion))]
        [JsonSerializable(typeof(UniqueShapeUnion))]
        [JsonSerializable(typeof(UnmappedMemberUnion))]
        [JsonSerializable(typeof(UppercaseDiscriminatorBase))]
        [JsonSerializable(typeof(UppercaseDiscriminatorDerived))]
        internal sealed partial class StructuralJsonTypeClassifierTestsContext_Default : JsonSerializerContext
        {
        }
    }
}
