// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_Regression_VS_ia64_JIT_M00_b99219_b99219 = CoreClr.coreclr_test({
    name: "b99219",
    srcs: ["b99219.cs"],
    debugType: "pdbonly",
    run: false,
});
