<Project>
  <PropertyGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'">
    <AutoGenerateBindingRedirects Condition="'$(AutoGenerateBindingRedirects)' == ''">true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType Condition="'$(GenerateBindingRedirectsOutputType)' == ''">true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>

  <!-- Run target (F5) support. -->
  <PropertyGroup>
    <RunWorkingDirectory Condition="'$(RunWorkingDirectory)' == ''">$(OutDir)</RunWorkingDirectory>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETCoreApp' and '$(RunCommand)' == ''">
    <RunCommand>$(DotNetTool)</RunCommand>
    <RunArguments>test $(TargetPath) --settings $(OutDir).runsettings</RunArguments>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'">
    <RunCommand>$(DevEnvDir)Extensions\TestPlatform\vstest.console.exe</RunCommand>
    <RunArguments>$(TargetPath) --settings:$(OutDir).runsettings</RunArguments>
  </PropertyGroup>

  <PropertyGroup Condition="'$(UseXUnitV3)' == 'true' and '$(TestSingleFile)' != 'true'">
    <UseAppHost>false</UseAppHost>
  </PropertyGroup>

  <Target Name="_XunitValidateBuild"
          BeforeTargets="BeforeBuild"
          Condition="'$(UseXUnitV3)' == 'true' and '$(TargetFramework)' != ''">
    <Error Text="xUnit.net v3 test projects must be executable (set project property '&lt;OutputType&gt;Exe&lt;/OutputType&gt;'). If this is not a test project, reference xunit.v3.extensibility.core instead."
           Condition="'$(OutputType)' != 'Exe'" />
  </Target>

  <Import Project="$(MSBuildThisFileDirectory)xunit.console.targets" Condition="'$(UseXUnitV3)' != 'true'" />
  <Import Project="$(MSBuildThisFileDirectory)xunit.console.v3.targets" Condition="'$(UseXUnitV3)' == 'true'" />
</Project>
