// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const baseservices_compilerservices_dynamicobjectproperties_dev10_535767 = coreclr_test({
    name: "Dev10_535767",
    srcs: ["dev10_535767.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_compilerservices_dynamicobjectproperties_testAPIs = coreclr_test({
    name: "TestAPIs",
    srcs: ["helper.cs", "testapis.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_compilerservices_dynamicobjectproperties_testGC = coreclr_test({
    name: "TestGC",
    srcs: ["helper.cs", "testgc.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_compilerservices_dynamicobjectproperties_testOverrides = coreclr_test({
    name: "TestOverrides",
    srcs: ["helper.cs", "testoverrides.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_compilerservices_dynamicobjectproperties_test448035 = coreclr_test({
    name: "test448035",
    srcs: ["test448035.cs"],
    pri: 1,
    size: "medium",
});
