// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

#include "asmconstants.h"
#include "unixasmmacros.inc"


LEAF_ENTRY JIT_WriteBarrier_PostGrow64, _TEXT
    nop
LEAF_END_MARKED JIT_WriteBarrier_PostGrow64, _TEXT


LEAF_ENTRY JIT_WriteBarrier_PreGrow64, _TEXT
    nop
LEAF_END_MARKED JIT_WriteBarrier_PreGrow64, _TEXT


LEAF_ENTRY JIT_WriteBarrier_SVR64, _TEXT
    nop
LEAF_END_MARKED JIT_WriteBarrier_SVR64, _TEXT


LEAF_ENTRY JIT_WriteBarrier_Byte_Region64, _TEXT
    nop
LEAF_END_MARKED JIT_WriteBarrier_Byte_Region64, _TEXT


LEAF_ENTRY JIT_WriteBarrier_Bit_Region64, _TEXT
    nop
LEAF_END_MARKED JIT_WriteBarrier_Bit_Region64, _TEXT


LEAF_ENTRY JIT_WriteBarrier_WriteWatch_PostGrow64, _TEXT
    nop
LEAF_END_MARKED JIT_WriteBarrier_WriteWatch_PostGrow64, _TEXT


LEAF_ENTRY JIT_WriteBarrier_WriteWatch_PreGrow64, _TEXT
    nop
LEAF_END_MARKED JIT_WriteBarrier_WriteWatch_PreGrow64, _TEXT


LEAF_ENTRY JIT_WriteBarrier_WriteWatch_SVR64, _TEXT
    nop
LEAF_END_MARKED JIT_WriteBarrier_WriteWatch_SVR64, _TEXT


LEAF_ENTRY JIT_WriteBarrier_WriteWatch_Byte_Region64, _TEXT
    nop
LEAF_END_MARKED JIT_WriteBarrier_WriteWatch_Byte_Region64, _TEXT


LEAF_ENTRY JIT_WriteBarrier_WriteWatch_Bit_Region64, _TEXT
    nop
LEAF_END_MARKED JIT_WriteBarrier_WriteWatch_Bit_Region64, _TEXT
