<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Optimize>True</Optimize>
    <CLRTestPriority>1</CLRTestPriority>
    <!-- Needed for CLRTestEnvironmentVariable -->
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(MSBuildProjectName).cs" />
    <!-- The switch needs profile data for a dominant case to be peeled -->
    <CLRTestEnvironmentVariable Include="DOTNET_TieredCompilation" Value="1" />
    <CLRTestEnvironmentVariable Include="DOTNET_TieredPGO" Value="1" />
  </ItemGroup>
</Project>
