// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_CLR_x86_JIT_V1_M12_Beta2_b80045_b80045 = coreclr_test({
    name: "b80045",
    srcs: ["b80045.cs"],
    debugType: "pdbonly",
});
