// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_HardwareIntrinsics_X86_Avx_Avx2_Vector128_avx2_Vector128_r = CoreClr.coreclr_test({
    name: "Avx2_Vector128_r",
    srcs: ["Program.Avx2_Vector128.cs", "//src/tests/JIT/HardwareIntrinsics/X86/Shared:Program.cs"],
});

@@public
export const jIT_HardwareIntrinsics_X86_Avx_Avx2_Vector128_avx2_Vector128_ro = CoreClr.coreclr_test({
    name: "Avx2_Vector128_ro",
    srcs: ["Program.Avx2_Vector128.cs", "//src/tests/JIT/HardwareIntrinsics/X86/Shared:Program.cs"],
    optimize: true,
});
