<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(NetCoreAppCurrent)-ios;$(NetCoreAppCurrent)-tvos</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="EnabledFileLockingSwitchTests.cs" />
  </ItemGroup>
  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.IO.DisableFileLocking" Value="false" />
  </ItemGroup>
</Project>
