<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Needed for CMakeProjectReference -->
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <Optimize>True</Optimize>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <!-- These platforms do not support native test assets: https://github.com/dotnet/runtime/issues/123946 -->
    <CLRTestTargetUnsupported Condition="'$(TargetsWasm)' == 'true' or '$(TargetsMobile)' == 'true'">true</CLRTestTargetUnsupported>
  </PropertyGroup>
  <ItemGroup>
    <CMakeProjectReference Include="CMakeLists.txt" />
    <Compile Include="$(MSBuildProjectName).cs" />
  </ItemGroup>
</Project>
