// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_HardwareIntrinsics_X86_Sse41_X64_sse41_X64_r = CoreClr.coreclr_test({
    name: "Sse41.X64_r",
    srcs: ["Program.Sse41.X64.cs", "//src/tests/JIT/HardwareIntrinsics/X86/Shared:Program.cs"],
    tags: ["manual"],
});

@@public
export const jIT_HardwareIntrinsics_X86_Sse41_X64_sse41_X64_ro = CoreClr.coreclr_test({
    name: "Sse41.X64_ro",
    srcs: ["Program.Sse41.X64.cs", "//src/tests/JIT/HardwareIntrinsics/X86/Shared:Program.cs"],
    optimize: true,
    tags: ["manual"],
});
