<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DebugType>Full</DebugType>
    <Optimize>False</Optimize>
    <!-- Managed ilasm consumes excessive amount of memory -->
    <ManagedIlasmRoundTripIncompatible>true</ManagedIlasmRoundTripIncompatible>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="HugeField1.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="$(TestLibraryProjectPath)" />
  </ItemGroup>
</Project>
