// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_JitBlue_DevDiv_280123_devDiv_280123 = coreclr_test({
    name: "DevDiv_280123",
    srcs: ["DevDiv_280123.cs"],
    optimize: true,
    pri: 1,
    size: "medium",
});
