// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.Serialization.IXmlSerializable))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.Serialization.XmlAnyAttributeAttribute))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.Serialization.XmlAnyElementAttribute))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.Serialization.XmlAnyElementAttributes))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.Serialization.XmlArrayAttribute))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.Serialization.XmlArrayItemAttribute))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.Serialization.XmlArrayItemAttributes))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.Serialization.XmlAttributeAttribute))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.Serialization.XmlAttributeOverrides))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.Serialization.XmlAttributes))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.Serialization.XmlChoiceIdentifierAttribute))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.Serialization.XmlElementAttribute))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.Serialization.XmlElementAttributes))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.Serialization.XmlEnumAttribute))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.Serialization.XmlIgnoreAttribute))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.Serialization.XmlIncludeAttribute))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.Serialization.XmlMapping))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.Serialization.XmlMappingAccess))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.Serialization.XmlNamespaceDeclarationsAttribute))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.Serialization.XmlReflectionImporter))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.Serialization.XmlRootAttribute))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.Serialization.XmlSchemaProviderAttribute))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.Serialization.XmlSerializer))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.Serialization.XmlSerializerNamespaces))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.Serialization.XmlTextAttribute))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.Serialization.XmlTypeAttribute))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.Serialization.XmlTypeMapping))]
