#include "named-intrinsic.h"

#ifdef ENABLE_LLVM

#define EMIT_MANUAL (0xffff)
#define NONE (0)

typedef struct {
  uint16_t op, c0;
  uint16_t int_op, int_c0;
  uint16_t fp_op, fp_c0;
} LlvmIntrinsicMapping;

static const LlvmInitrinsicMapping INTRINSIC_MAPPING[(int)NI_PRIMITIVE_END] = {
  // ...---===[ System.Runtime.Intrinsics ]===---...
  [NI_Vector128_Abs] = {OP_XBINOP,NONE, NONE, OP_IADD, NONE, OP_FADD},
  [NI_Vector128_Add] = {EMIT_MANUAL},
  [NI_Vector128_AndNot] = {EMIT_MANUAL},
  [NI_Vector128_As] = {EMIT_MANUAL},
  [NI_Vector128_AsByte] = {EMIT_MANUAL},
  [NI_Vector128_AsDouble] = {EMIT_MANUAL},
  [NI_Vector128_AsInt16] = {EMIT_MANUAL},
  [NI_Vector128_AsInt32] = {EMIT_MANUAL},
  [NI_Vector128_AsInt64] = {EMIT_MANUAL},
  [NI_Vector128_AsNInt] = {EMIT_MANUAL},
  [NI_Vector128_AsNUInt] = {EMIT_MANUAL},
  [NI_Vector128_AsSByte] = {EMIT_MANUAL},
  [NI_Vector128_AsSingle] = {EMIT_MANUAL},
  [NI_Vector128_AsUInt16] = {EMIT_MANUAL},
  [NI_Vector128_AsUInt32] = {EMIT_MANUAL},
  [NI_Vector128_AsUInt64] = {EMIT_MANUAL},
  [NI_Vector128_AsVector] = {EMIT_MANUAL},
  [NI_Vector128_AsVector2] = {EMIT_MANUAL},
  [NI_Vector128_AsVector3] = {EMIT_MANUAL},
  [NI_Vector128_AsVector4] = {EMIT_MANUAL},
  [NI_Vector128_AsVector128] = {EMIT_MANUAL},
  [NI_Vector128_BitwiseAnd] = {EMIT_MANUAL},
  [NI_Vector128_BitwiseOr] = {EMIT_MANUAL},
  [NI_Vector128_Ceiling] = {EMIT_MANUAL},
  [NI_Vector128_ConditionalSelect] = {EMIT_MANUAL},
  [NI_Vector128_ConvertToDouble] = {EMIT_MANUAL},
  [NI_Vector128_ConvertToInt32] = {EMIT_MANUAL},
  [NI_Vector128_ConvertToInt64] = {EMIT_MANUAL},
  [NI_Vector128_ConvertToSingle] = {EMIT_MANUAL},
  [NI_Vector128_ConvertToUInt32] = {EMIT_MANUAL},
  [NI_Vector128_ConvertToUInt64] = {EMIT_MANUAL},
  [NI_Vector128_Create] = {EMIT_MANUAL},
  [NI_Vector128_CreateScalar] = {EMIT_MANUAL},
  [NI_Vector128_CreateScalarUnsafe] = {EMIT_MANUAL},
  [NI_Vector128_Divide] = {EMIT_MANUAL},
  [NI_Vector128_Dot] = {EMIT_MANUAL},
  [NI_Vector128_Equals] = {EMIT_MANUAL},
  [NI_Vector128_EqualsAll] = {EMIT_MANUAL},
  [NI_Vector128_EqualsAny] = {EMIT_MANUAL},
  [NI_Vector128_ExtractMostSignificantBits] = {EMIT_MANUAL},
  [NI_Vector128_Floor] = {EMIT_MANUAL},
  [NI_Vector128_get_AllBitsSet] = {EMIT_MANUAL},
  [NI_Vector128_get_One] = {EMIT_MANUAL},
  [NI_Vector128_get_Zero] = {EMIT_MANUAL},
  [NI_Vector128_GetElement] = {EMIT_MANUAL},
  [NI_Vector128_GetLower] = {EMIT_MANUAL},
  [NI_Vector128_GetUpper] = {EMIT_MANUAL},
  [NI_Vector128_GreaterThan] = {EMIT_MANUAL},
  [NI_Vector128_GreaterThanAll] = {EMIT_MANUAL},
  [NI_Vector128_GreaterThanAny] = {EMIT_MANUAL},
  [NI_Vector128_GreaterThanOrEqual] = {EMIT_MANUAL},
  [NI_Vector128_GreaterThanOrEqualAll] = {EMIT_MANUAL},
  [NI_Vector128_GreaterThanOrEqualAny] = {EMIT_MANUAL},
  [NI_Vector128_LessThan] = {EMIT_MANUAL},
  [NI_Vector128_LessThanAll] = {EMIT_MANUAL},
  [NI_Vector128_LessThanAny] = {EMIT_MANUAL},
  [NI_Vector128_LessThanOrEqual] = {EMIT_MANUAL},
  [NI_Vector128_LessThanOrEqualAll] = {EMIT_MANUAL},
  [NI_Vector128_LessThanOrEqualAny] = {EMIT_MANUAL},
  [NI_Vector128_Load] = {EMIT_MANUAL},
  [NI_Vector128_LoadAligned] = {EMIT_MANUAL},
  [NI_Vector128_LoadAlignedNonTemporal] = {EMIT_MANUAL},
  [NI_Vector128_LoadUnsafe] = {EMIT_MANUAL},
  [NI_Vector128_Max] = {EMIT_MANUAL},
  [NI_Vector128_Min] = {EMIT_MANUAL},
  [NI_Vector128_Multiply] = {EMIT_MANUAL},
  [NI_Vector128_Narrow] = {EMIT_MANUAL},
  [NI_Vector128_Negate] = {EMIT_MANUAL},
  [NI_Vector128_OnesComplement] = {EMIT_MANUAL},
  [NI_Vector128_op_Addition] = {EMIT_MANUAL},
  [NI_Vector128_op_BitwiseAnd] = {EMIT_MANUAL},
  [NI_Vector128_op_BitwiseOr] = {EMIT_MANUAL},
  [NI_Vector128_op_Division] = {EMIT_MANUAL},
  [NI_Vector128_op_Equality] = {EMIT_MANUAL},
  [NI_Vector128_op_ExclusiveOr] = {EMIT_MANUAL},
  [NI_Vector128_op_Inequality] = {EMIT_MANUAL},
  [NI_Vector128_op_LeftShift] = {EMIT_MANUAL},
  [NI_Vector128_op_RightShift] = {EMIT_MANUAL},
  [NI_Vector128_op_UnsignedRightShift] = {EMIT_MANUAL},
  [NI_Vector128_op_Multiply] = {EMIT_MANUAL},
  [NI_Vector128_op_OnesComplement] = {EMIT_MANUAL},
  [NI_Vector128_op_Subtraction] = {EMIT_MANUAL},
  [NI_Vector128_op_UnaryNegation] = {EMIT_MANUAL},
  [NI_Vector128_op_UnaryPlus] = {EMIT_MANUAL},
  [NI_Vector128_ShiftLeft] = {EMIT_MANUAL},
  [NI_Vector128_ShiftRightArithmetic] = {EMIT_MANUAL},
  [NI_Vector128_ShiftRightLogical] = {EMIT_MANUAL},
  [NI_Vector128_Shuffle] = {EMIT_MANUAL},
  [NI_Vector128_Sqrt] = {EMIT_MANUAL},
  [NI_Vector128_Store] = {EMIT_MANUAL},
  [NI_Vector128_StoreAligned] = {EMIT_MANUAL},
  [NI_Vector128_StoreAlignedNonTemporal] = {EMIT_MANUAL},
  [NI_Vector128_StoreUnsafe] = {EMIT_MANUAL},
  [NI_Vector128_Subtract] = {EMIT_MANUAL},
  [NI_Vector128_Sum] = {EMIT_MANUAL},
  [NI_Vector128_ToScalar] = {EMIT_MANUAL},
  [NI_Vector128_WidenLower] = {EMIT_MANUAL},
  [NI_Vector128_WidenUpper] = {EMIT_MANUAL},
  [NI_Vector128_WithElement] = {EMIT_MANUAL},
  [NI_Vector128_WithLower] = {EMIT_MANUAL},
  [NI_Vector128_WithUpper] = {EMIT_MANUAL},
  [NI_Vector128_Xor] = {EMIT_MANUAL},

  // ...---===[ Arm64 Advanced SIMD ]===---...
  [NI_AdvSimd_Abs] = {OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_ABS, NONE, NONE, OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_FABS},
  [NI_AdvSimd_AbsSaturate] = {OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_SQABS},
  [NI_AdvSimd_AbsSaturateScalar] = {OP_XOP_OVR_SCALAR_X_X, INTRINS_AARCH64_ADV_SIMD_SQABS},
  [NI_AdvSimd_AbsScalar] = {OP_XOP_OVR_SCALAR_X_X, INTRINS_AARCH64_ADV_SIMD_ABS, NONE, NONE, OP_XOP_OVR_SCALAR_X_X, INTRINS_AARCH64_ADV_SIMD_FABS},
  //[NI_AdvSimd_AbsoluteCompareGreaterThan],
  //[NI_AdvSimd_AbsoluteCompareGreaterThanOrEqual],
  //[NI_AdvSimd_AbsoluteCompareGreaterThanOrEqualScalar],
  //[NI_AdvSimd_AbsoluteCompareGreaterThanScalar],
  //[NI_AdvSimd_AbsoluteCompareLessThan],
  //[NI_AdvSimd_AbsoluteCompareLessThanOrEqual],
  //[NI_AdvSimd_AbsoluteCompareLessThanOrEqualScalar],
  //[NI_AdvSimd_AbsoluteCompareLessThanScalar],
  [NI_AdvSimd_AbsoluteDifference] = {OP_ARM64_SABD, NONE, OP_ARM64_UABD, NONE, OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_FABD},
  [NI_AdvSimd_AbsoluteDifferenceAdd] = {OP_ARM64_SABA, NONE, OP_ARM64_UABA},
  [NI_AdvSimd_AbsoluteDifferenceScalar] = {OP_XOP_OVR_SCALAR_X_X_X, INTRINS_AARCH64_ADV_SIMD_FABD_SCALAR},
  [NI_AdvSimd_AbsoluteDifferenceWideningLower] = {OP_ARM64_SABDL, NONE, OP_ARM64_UABDL},
  [NI_AdvSimd_AbsoluteDifferenceWideningLowerAndAdd] = {OP_ARM64_SABAL, NONE, OP_ARM64_UABAL},
  [NI_AdvSimd_AbsoluteDifferenceWideningUpper] = {OP_ARM64_SABDL2, NONE, OP_ARM64_UABDL2},
  [NI_AdvSimd_AbsoluteDifferenceWideningUpperAndAdd] = {OP_ARM64_SABAL2, NONE, OP_ARM64_UABAL2},
  [NI_AdvSimd_Add] = {OP_XBINOP, OP_IADD, NONE, NONE, OP_XBINOP, OP_FADD},
  [NI_AdvSimd_AddAcross] = {OP_ARM64_XHORIZ, INTRINS_AARCH64_ADV_SIMD_SADDV, OP_ARM64_XHORIZ, INTRINS_AARCH64_ADV_SIMD_UADDV},
  [NI_AdvSimd_AddAcrossWidening] = {OP_ARM64_SADDLV, NONE, OP_ARM64_UADDLV},
  [NI_AdvSimd_AddHighNarrowingLower] = {OP_ARM64_ADDHN},
  [NI_AdvSimd_AddHighNarrowingUpper] = {OP_ARM64_ADDHN2},
  [NI_AdvSimd_AddPairwise] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_ADDP, NONE, NONE, OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_FADDP},
  [NI_AdvSimd_AddPairwiseScalar] = {OP_ARM64_ADDP_SCALAR, NONE, NONE, NONE, OP_ARM64_FADDP_SCALAR},
  [NI_AdvSimd_AddPairwiseWidening] = {OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_SADDLP, OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_UADDLP},
  [NI_AdvSimd_AddPairwiseWideningAndAdd] = {OP_ARM64_SADALP, NONE, OP_ARM64_UADALP},
  [NI_AdvSimd_AddPairwiseWideningAndAddScalar] = {OP_ARM64_SADALP, NONE, OP_ARM64_UADALP},
  [NI_AdvSimd_AddPairwiseWideningScalar] = {OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_SADDLP, OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_UADDLP},
  [NI_AdvSimd_AddRoundedHighNarrowingLower] = {OP_ARM64_RADDHN},
  [NI_AdvSimd_AddRoundedHighNarrowingUpper] = {OP_ARM64_RADDHN2},
  //[NI_AdvSimd_AddSaturate],
  //[NI_AdvSimd_AddSaturateScalar],
  [NI_AdvSimd_AddScalar] = {OP_XBINOP_SCALAR, OP_IADD, NONE, NONE, OP_XBINOP_SCALAR, OP_FADD},
  [NI_AdvSimd_AddWideningLower] = {OP_ARM64_SADD, NONE, OP_ARM64_UADD},
  [NI_AdvSimd_AddWideningUpper] = {OP_ARM64_SADD2, NONE, OP_ARM64_UADD2},
  [NI_AdvSimd_And] = {OP_XBINOP_FORCEINT, XBINOP_FORCEINT_AND},
  [NI_AdvSimd_BitwiseClear] = {OP_ARM64_BIC},
  [NI_AdvSimd_BitwiseSelect] = {OP_BSL},
  [NI_AdvSimd_Ceiling] = {OP_XOP_OVR_X_X, INTRINS_SIMD_CEIL},
  [NI_AdvSimd_CeilingScalar] = {OP_XOP_OVR_SCALAR_X_X, INTRINS_SIMD_CEIL},
  [NI_AdvSimd_CompareEqual] = {OP_XCOMPARE, CMP_EQ, OP_XCOMPARE, CMP_EQ, OP_XCOMPARE_FP, CMP_EQ},
  [NI_AdvSimd_CompareEqualScalar] = {OP_XCOMPARE_SCALAR, CMP_EQ, OP_XCOMPARE_SCALAR, CMP_EQ, OP_XCOMPARE_FP_SCALAR, CMP_EQ},
  [NI_AdvSimd_CompareGreaterThan] = {OP_XCOMPARE, CMP_GT, OP_XCOMPARE, CMP_GT_UN, OP_XCOMPARE_FP, CMP_GT},
  [NI_AdvSimd_CompareGreaterThanOrEqual] = {OP_XCOMPARE, CMP_GE, OP_XCOMPARE, CMP_GE_UN, OP_XCOMPARE_FP, CMP_GE},
  [NI_AdvSimd_CompareGreaterThanOrEqualScalar] = {OP_XCOMPARE_SCALAR, CMP_GE, OP_XCOMPARE_SCALAR, CMP_GE_UN, OP_XCOMPARE_FP_SCALAR, CMP_GE},
  [NI_AdvSimd_CompareGreaterThanScalar] = {OP_XCOMPARE_SCALAR, CMP_GT, OP_XCOMPARE_SCALAR, CMP_GT_UN, OP_XCOMPARE_FP_SCALAR, CMP_GT},
  [NI_AdvSimd_CompareLessThan] = {OP_XCOMPARE, CMP_LT, OP_XCOMPARE, CMP_LT_UN, OP_XCOMPARE_FP, CMP_LT},
  [NI_AdvSimd_CompareLessThanOrEqual] = {OP_XCOMPARE, CMP_LE, OP_XCOMPARE, CMP_LE_UN, OP_XCOMPARE_FP, CMP_LE},
  [NI_AdvSimd_CompareLessThanOrEqualScalar] = {OP_XCOMPARE_SCALAR, CMP_LE, OP_XCOMPARE_SCALAR, CMP_LE_UN, OP_XCOMPARE_FP_SCALAR, CMP_LE},
  [NI_AdvSimd_CompareLessThanScalar] = {OP_XCOMPARE_SCALAR, CMP_LT, OP_XCOMPARE_SCALAR, CMP_LT_UN, OP_XCOMPARE_FP_SCALAR, CMP_LT},
  [NI_AdvSimd_CompareTest] = {OP_ARM64_CMTST},
  [NI_AdvSimd_CompareTestScalar] = {OP_ARM64_CMTST},
  [NI_AdvSimd_ConvertToDouble] = {OP_CVT_SI_FP, NONE, OP_CVT_UI_FP, NONE, OP_SIMD_FCVTL},
  [NI_AdvSimd_ConvertToDoubleScalar] = {OP_CVT_SI_FP_SCALAR, NONE, OP_CVT_UI_FP_SCALAR},
  [NI_AdvSimd_ConvertToDoubleUpper] = {OP_SIMD_FCVTL2},
  {NI_AdvSimd_ConvertToInt32RoundAwayFromZero, OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTAS},
  {NI_AdvSimd_ConvertToInt32RoundAwayFromZeroScalar, OP_XOP_OVR_SCALAR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTAS},
  {NI_AdvSimd_ConvertToInt32RoundToEven, OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTNS},
  {NI_AdvSimd_ConvertToInt32RoundToEvenScalar, OP_XOP_OVR_SCALAR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTNS},
  {NI_AdvSimd_ConvertToInt32RoundToNegativeInfinity, OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTMS},
  {NI_AdvSimd_ConvertToInt32RoundToNegativeInfinityScalar, OP_XOP_OVR_SCALAR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTMS},
  {NI_AdvSimd_ConvertToInt32RoundToPositiveInfinity, OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTPS},
  {NI_AdvSimd_ConvertToInt32RoundToPositiveInfinityScalar, OP_XOP_OVR_SCALAR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTPS},
  {NI_AdvSimd_ConvertToInt32RoundToZero, OP_CVT_FP_SI},
  {NI_AdvSimd_ConvertToInt32RoundToZeroScalar, OP_CVT_FP_SI_SCALAR},
  {NI_AdvSimd_ConvertToInt64RoundAwayFromZero, OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTAS},
  {NI_AdvSimd_ConvertToInt64RoundAwayFromZeroScalar, OP_XOP_OVR_SCALAR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTAS},
  {NI_AdvSimd_ConvertToInt64RoundToEven, OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTNS},
  {NI_AdvSimd_ConvertToInt64RoundToEvenScalar, OP_XOP_OVR_SCALAR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTNS},
  {NI_AdvSimd_ConvertToInt64RoundToNegativeInfinity, OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTMS},
  {NI_AdvSimd_ConvertToInt64RoundToNegativeInfinityScalar, OP_XOP_OVR_SCALAR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTMS},
  {NI_AdvSimd_ConvertToInt64RoundToPositiveInfinity, OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTPS},
  {NI_AdvSimd_ConvertToInt64RoundToPositiveInfinityScalar, OP_XOP_OVR_SCALAR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTPS},
  {NI_AdvSimd_ConvertToInt64RoundToZero, OP_CVT_FP_SI},
  {NI_AdvSimd_ConvertToInt64RoundToZeroScalar, OP_CVT_FP_SI_SCALAR},
  [NI_AdvSimd_ConvertToSingle] = {OP_CVT_SI_FP, NONE, OP_CVT_UI_FP},
  [NI_AdvSimd_ConvertToSingleLower] = {OP_ARM64_FCVTN},
  [NI_AdvSimd_ConvertToSingleRoundToOddLower] = {OP_ARM64_FCVTXN},
  [NI_AdvSimd_ConvertToSingleRoundToOddUpper] = {OP_ARM64_FCVTXN2},
  [NI_AdvSimd_ConvertToSingleScalar] = {OP_CVT_SI_FP_SCALAR, NONE, OP_CVT_UI_FP_SCALAR},
  [NI_AdvSimd_ConvertToSingleUpper] = {OP_ARM64_FCVTN2},
  {NI_AdvSimd_ConvertToUInt32RoundAwayFromZero, OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTAU},
  {NI_AdvSimd_ConvertToUInt32RoundAwayFromZeroScalar, OP_XOP_OVR_SCALAR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTAU},
  {NI_AdvSimd_ConvertToUInt32RoundToEven, OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTNU},
  {NI_AdvSimd_ConvertToUInt32RoundToEvenScalar, OP_XOP_OVR_SCALAR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTNU},
  {NI_AdvSimd_ConvertToUInt32RoundToNegativeInfinity, OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTMU},
  {NI_AdvSimd_ConvertToUInt32RoundToNegativeInfinityScalar, OP_XOP_OVR_SCALAR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTMU},
  {NI_AdvSimd_ConvertToUInt32RoundToPositiveInfinity, OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTPU},
  {NI_AdvSimd_ConvertToUInt32RoundToPositiveInfinityScalar, OP_XOP_OVR_SCALAR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTPU},
  {NI_AdvSimd_ConvertToUInt32RoundToZero, OP_CVT_FP_UI},
  {NI_AdvSimd_ConvertToUInt32RoundToZeroScalar, OP_CVT_FP_UI_SCALAR},
  {NI_AdvSimd_ConvertToUInt64RoundAwayFromZero, OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTAU},
  {NI_AdvSimd_ConvertToUInt64RoundAwayFromZeroScalar, OP_XOP_OVR_SCALAR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTAU},
  {NI_AdvSimd_ConvertToUInt64RoundToEven, OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTNU},
  {NI_AdvSimd_ConvertToUInt64RoundToEvenScalar, OP_XOP_OVR_SCALAR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTNU},
  {NI_AdvSimd_ConvertToUInt64RoundToNegativeInfinity, OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTMU},
  {NI_AdvSimd_ConvertToUInt64RoundToNegativeInfinityScalar, OP_XOP_OVR_SCALAR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTMU},
  {NI_AdvSimd_ConvertToUInt64RoundToPositiveInfinity, OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTPU},
  {NI_AdvSimd_ConvertToUInt64RoundToPositiveInfinityScalar, OP_XOP_OVR_SCALAR_X_X, INTRINS_AARCH64_ADV_SIMD_FCVTPU},
  {NI_AdvSimd_ConvertToUInt64RoundToZero, OP_CVT_FP_UI},
  {NI_AdvSimd_ConvertToUInt64RoundToZeroScalar, OP_CVT_FP_UI_SCALAR},
  [NI_AdvSimd_Divide] = {OP_XBINOP, OP_FDIV},
  [NI_AdvSimd_DivideScalar] = {OP_XBINOP_SCALAR, OP_FDIV},
  {NI_AdvSimd_DuplicateSelectedScalarToVector128},
  {NI_AdvSimd_DuplicateSelectedScalarToVector64},
  {NI_AdvSimd_DuplicateToVector128},
  {NI_AdvSimd_DuplicateToVector64},
  //[NI_AdvSimd_Extract],
  [NI_AdvSimd_ExtractNarrowingLower] = {OP_ARM64_XTN},
  [NI_AdvSimd_ExtractNarrowingSaturateLower] = {OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_SQXTN, OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_UQXTN},
  [NI_AdvSimd_ExtractNarrowingSaturateScalar] = {OP_ARM64_XNARROW_SCALAR, INTRINS_AARCH64_ADV_SIMD_SQXTN, OP_ARM64_XNARROW_SCALAR, INTRINS_AARCH64_ADV_SIMD_UQXTN},
  [NI_AdvSimd_ExtractNarrowingSaturateUnsignedLower] = {OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_SQXTUN},
  [NI_AdvSimd_ExtractNarrowingSaturateUnsignedScalar] = {OP_ARM64_XNARROW_SCALAR, INTRINS_AARCH64_ADV_SIMD_SQXTUN},
  [NI_AdvSimd_ExtractNarrowingSaturateUnsignedUpper] = {OP_ARM64_SQXTUN2},
  [NI_AdvSimd_ExtractNarrowingSaturateUpper] = {OP_ARM64_SQXTN2, NONE, OP_ARM64_UQXTN2},
  [NI_AdvSimd_ExtractNarrowingUpper] = {OP_ARM64_XTN2},
  {NI_AdvSimd_ExtractVector128, OP_ARM64_EXT},
  {NI_AdvSimd_ExtractVector64, OP_ARM64_EXT},
  [NI_AdvSimd_Floor] = {OP_XOP_OVR_X_X, INTRINS_SIMD_FLOOR},
  [NI_AdvSimd_FloorScalar] = {OP_XOP_OVR_SCALAR_X_X, INTRINS_SIMD_FLOOR},
  [NI_AdvSimd_FusedAddHalving] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_SHADD, OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_UHADD},
  [NI_AdvSimd_FusedAddRoundedHalving] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_SRHADD, OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_URHADD},
  [NI_AdvSimd_FusedMultiplyAdd] = {OP_ARM64_FMADD},
  [NI_AdvSimd_FusedMultiplyAddByScalar] = {OP_ARM64_FMADD_BYSCALAR},
  //[NI_AdvSimd_FusedMultiplyAddBySelectedScalar],
  [NI_AdvSimd_FusedMultiplyAddNegatedScalar] = {OP_ARM64_FNMADD_SCALAR},
  [NI_AdvSimd_FusedMultiplyAddScalar] = {OP_ARM64_FMADD_SCALAR},
  //[NI_AdvSimd_FusedMultiplyAddScalarBySelectedScalar],
  [NI_AdvSimd_FusedMultiplySubtract] = {OP_ARM64_FMSUB},
  [NI_AdvSimd_FusedMultiplySubtractByScalar] = {OP_ARM64_FMSUB_BYSCALAR},
  //[NI_AdvSimd_FusedMultiplySubtractBySelectedScalar],
  [NI_AdvSimd_FusedMultiplySubtractNegatedScalar] = {OP_ARM64_FNMSUB_SCALAR},
  [NI_AdvSimd_FusedMultiplySubtractScalar] = {OP_ARM64_FMSUB_SCALAR},
  //[NI_AdvSimd_FusedMultiplySubtractScalarBySelectedScalar],
  [NI_AdvSimd_FusedSubtractHalving] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_SHSUB, OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_UHSUB},
  //[NI_AdvSimd_Insert],
  //[NI_AdvSimd_InsertScalar],
  //[NI_AdvSimd_InsertSelectedScalar],
  [NI_AdvSimd_LeadingSignCount] = {OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_CLS},
  [NI_AdvSimd_LeadingZeroCount] = {OP_ARM64_CLZ},
  [NI_AdvSimd_LoadAndInsertScalar] = {OP_ARM64_LD1_INSERT},
  {NI_AdvSimd_LoadAndReplicateToVector128, OP_ARM64_LD1R},
  {NI_AdvSimd_LoadAndReplicateToVector64, OP_ARM64_LD1R},
  {NI_AdvSimd_LoadPairScalarVector64, OP_ARM64_LDP_SCALAR},
  {NI_AdvSimd_LoadPairScalarVector64NonTemporal, OP_ARM64_LDNP_SCALAR},
  {NI_AdvSimd_LoadPairVector128, OP_ARM64_LDP},
  {NI_AdvSimd_LoadPairVector128NonTemporal, OP_ARM64_LDNP},
  {NI_AdvSimd_LoadPairVector64, OP_ARM64_LDP},
  {NI_AdvSimd_LoadPairVector64NonTemporal, OP_ARM64_LDNP},
  {NI_AdvSimd_LoadVector128, OP_ARM64_LD1},
  {NI_AdvSimd_LoadVector64, OP_ARM64_LD1},
  [NI_AdvSimd_Max] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_SMAX, OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_UMAX, OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_FMAX},
  [NI_AdvSimd_MaxAcross] = {OP_ARM64_XHORIZ, INTRINS_AARCH64_ADV_SIMD_SMAXV, OP_ARM64_XHORIZ, INTRINS_AARCH64_ADV_SIMD_UMAXV, OP_ARM64_XHORIZ, INTRINS_AARCH64_ADV_SIMD_FMAXV},
  [NI_AdvSimd_MaxNumber] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_FMAXNM},
  [NI_AdvSimd_MaxNumberAcross] = {OP_ARM64_XHORIZ, INTRINS_AARCH64_ADV_SIMD_FMAXNMV},
  [NI_AdvSimd_MaxNumberPairwise] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_FMAXNMP},
  [NI_AdvSimd_MaxNumberPairwiseScalar] = {OP_ARM64_XHORIZ, INTRINS_AARCH64_ADV_SIMD_FMAXNMV},
  [NI_AdvSimd_MaxNumberScalar] = {OP_XOP_OVR_SCALAR_X_X_X, INTRINS_AARCH64_ADV_SIMD_FMAXNM},
  [NI_AdvSimd_MaxPairwise] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_SMAXP, OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_UMAXP, OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_FMAXP},
  [NI_AdvSimd_MaxPairwiseScalar] = {OP_ARM64_XHORIZ, INTRINS_AARCH64_ADV_SIMD_FMAXV},
  [NI_AdvSimd_MaxScalar] = {OP_XOP_OVR_SCALAR_X_X_X, INTRINS_AARCH64_ADV_SIMD_FMAX},
  [NI_AdvSimd_Min] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_SMIN, OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_UMIN, OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_FMIN},
  [NI_AdvSimd_MinAcross] = {OP_ARM64_XHORIZ, INTRINS_AARCH64_ADV_SIMD_SMINV, OP_ARM64_XHORIZ, INTRINS_AARCH64_ADV_SIMD_UMINV, OP_ARM64_XHORIZ, INTRINS_AARCH64_ADV_SIMD_FMINV},
  [NI_AdvSimd_MinNumber] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_FMINNM},
  [NI_AdvSimd_MinNumberAcross] = {OP_ARM64_XHORIZ, INTRINS_AARCH64_ADV_SIMD_FMINNMV},
  [NI_AdvSimd_MinNumberPairwise] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_FMINNMP},
  [NI_AdvSimd_MinNumberPairwiseScalar] = {OP_ARM64_XHORIZ, INTRINS_AARCH64_ADV_SIMD_FMINNMV},
  [NI_AdvSimd_MinNumberScalar] = {OP_XOP_OVR_SCALAR_X_X_X, INTRINS_AARCH64_ADV_SIMD_FMINNM},
  [NI_AdvSimd_MinPairwise] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_SMINP, OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_UMINP, OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_FMINP},
  [NI_AdvSimd_MinPairwiseScalar] = {OP_ARM64_XHORIZ, INTRINS_AARCH64_ADV_SIMD_FMINV},
  [NI_AdvSimd_MinScalar] = {OP_XOP_OVR_SCALAR_X_X_X, INTRINS_AARCH64_ADV_SIMD_FMIN},
  [NI_AdvSimd_Multiply] = {OP_XBINOP, OP_IMUL, NONE, NONE, OP_XBINOP, OP_FMUL},
  [NI_AdvSimd_MultiplyAdd] = {OP_ARM64_MLA},
  [NI_AdvSimd_MultiplyAddByScalar] = {OP_ARM64_MLA_SCALAR},
  //[NI_AdvSimd_MultiplyAddBySelectedScalar],
  [NI_AdvSimd_MultiplyByScalar] = {OP_XBINOP_BYSCALAR, OP_IMUL, NONE, NONE, OP_XBINOP_BYSCALAR, OP_FMUL},
  //[NI_AdvSimd_MultiplyBySelectedScalar],
  //[NI_AdvSimd_MultiplyBySelectedScalarWideningLower],
  //[NI_AdvSimd_MultiplyBySelectedScalarWideningLowerAndAdd],
  //[NI_AdvSimd_MultiplyBySelectedScalarWideningLowerAndSubtract],
  //[NI_AdvSimd_MultiplyBySelectedScalarWideningUpper],
  //[NI_AdvSimd_MultiplyBySelectedScalarWideningUpperAndAdd],
  //[NI_AdvSimd_MultiplyBySelectedScalarWideningUpperAndSubtract],
  [NI_AdvSimd_MultiplyDoublingByScalarSaturateHigh] = {OP_XOP_OVR_BYSCALAR_X_X_X, INTRINS_AARCH64_ADV_SIMD_SQDMULH},
  //[NI_AdvSimd_MultiplyDoublingBySelectedScalarSaturateHigh],
  [NI_AdvSimd_MultiplyDoublingSaturateHigh] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_SQDMULH},
  [NI_AdvSimd_MultiplyDoublingSaturateHighScalar] = {OP_XOP_OVR_SCALAR_X_X_X, INTRINS_AARCH64_ADV_SIMD_SQDMULH},
  //[NI_AdvSimd_MultiplyDoublingScalarBySelectedScalarSaturateHigh],
  [NI_AdvSimd_MultiplyDoublingWideningAndAddSaturateScalar] = {OP_ARM64_SQDMLAL_SCALAR},
  [NI_AdvSimd_MultiplyDoublingWideningAndSubtractSaturateScalar] = {OP_ARM64_SQDMLSL_SCALAR},
  [NI_AdvSimd_MultiplyDoublingWideningLowerAndAddSaturate] = {OP_ARM64_SQDMLAL},
  [NI_AdvSimd_MultiplyDoublingWideningLowerAndSubtractSaturate] = {OP_ARM64_SQDMLSL},
  [NI_AdvSimd_MultiplyDoublingWideningLowerByScalarAndAddSaturate] = {OP_ARM64_SQDMLAL_BYSCALAR},
  [NI_AdvSimd_MultiplyDoublingWideningLowerByScalarAndSubtractSaturate] = {OP_ARM64_SQDMLSL_BYSCALAR},
  //[NI_AdvSimd_MultiplyDoublingWideningLowerBySelectedScalarAndAddSaturate],
  //[NI_AdvSimd_MultiplyDoublingWideningLowerBySelectedScalarAndSubtractSaturate],
  [NI_AdvSimd_MultiplyDoublingWideningSaturateLower] = {OP_ARM64_SQDMULL},
  [NI_AdvSimd_MultiplyDoublingWideningSaturateLowerByScalar] = {OP_ARM64_SQDMULL_BYSCALAR},
  //[NI_AdvSimd_MultiplyDoublingWideningSaturateLowerBySelectedScalar],
  [NI_AdvSimd_MultiplyDoublingWideningSaturateScalar] = {OP_ARM64_SQDMULL_SCALAR},
  //[NI_AdvSimd_MultiplyDoublingWideningSaturateScalarBySelectedScalar],
  [NI_AdvSimd_MultiplyDoublingWideningSaturateUpper] = {OP_ARM64_SQDMULL2},
  [NI_AdvSimd_MultiplyDoublingWideningSaturateUpperByScalar] = {OP_ARM64_SQDMULL2_BYSCALAR},
  //[NI_AdvSimd_MultiplyDoublingWideningSaturateUpperBySelectedScalar],
  //[NI_AdvSimd_MultiplyDoublingWideningScalarBySelectedScalarAndAddSaturate],
  //[NI_AdvSimd_MultiplyDoublingWideningScalarBySelectedScalarAndSubtractSaturate],
  [NI_AdvSimd_MultiplyDoublingWideningUpperAndAddSaturate] = {OP_ARM64_SQDMLAL2},
  [NI_AdvSimd_MultiplyDoublingWideningUpperAndSubtractSaturate] = {OP_ARM64_SQDMLSL2},
  [NI_AdvSimd_MultiplyDoublingWideningUpperByScalarAndAddSaturate] = {OP_ARM64_SQDMLAL2_BYSCALAR},
  [NI_AdvSimd_MultiplyDoublingWideningUpperByScalarAndSubtractSaturate] = {OP_ARM64_SQDMLSL2_BYSCALAR},
  //[NI_AdvSimd_MultiplyDoublingWideningUpperBySelectedScalarAndAddSaturate],
  //[NI_AdvSimd_MultiplyDoublingWideningUpperBySelectedScalarAndSubtractSaturate],
  [NI_AdvSimd_MultiplyExtended] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_FMULX},
  [NI_AdvSimd_MultiplyExtendedByScalar] = {OP_XOP_OVR_BYSCALAR_X_X_X, INTRINS_AARCH64_ADV_SIMD_FMULX},
  //[NI_AdvSimd_MultiplyExtendedBySelectedScalar],
  [NI_AdvSimd_MultiplyExtendedScalar] = {OP_XOP_OVR_SCALAR_X_X_X, INTRINS_AARCH64_ADV_SIMD_FMULX},
  //[NI_AdvSimd_MultiplyExtendedScalarBySelectedScalar],
  [NI_AdvSimd_MultiplyRoundedDoublingByScalarSaturateHigh] = {OP_XOP_OVR_BYSCALAR_X_X_X, INTRINS_AARCH64_ADV_SIMD_SQRDMULH},
  //[NI_AdvSimd_MultiplyRoundedDoublingBySelectedScalarSaturateHigh],
  [NI_AdvSimd_MultiplyRoundedDoublingSaturateHigh] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_SQRDMULH},
  [NI_AdvSimd_MultiplyRoundedDoublingSaturateHighScalar] = {OP_XOP_OVR_SCALAR_X_X_X, INTRINS_AARCH64_ADV_SIMD_SQRDMULH},
  //[NI_AdvSimd_MultiplyRoundedDoublingScalarBySelectedScalarSaturateHigh],
  [NI_AdvSimd_MultiplyScalar] = {OP_XBINOP_SCALAR, OP_FMUL},
  [NI_AdvSimd_MultiplyScalarBySelectedScalar] = {OP_ARM64_FMUL_SEL},
  [NI_AdvSimd_MultiplySubtract] = {OP_ARM64_MLS},
  [NI_AdvSimd_MultiplySubtractByScalar] = {OP_ARM64_MLS_SCALAR},
  //[NI_AdvSimd_MultiplySubtractBySelectedScalar],
  [NI_AdvSimd_MultiplyWideningLower] = {OP_ARM64_SMULL, NONE, OP_ARM64_UMULL},
  [NI_AdvSimd_MultiplyWideningLowerAndAdd] = {OP_ARM64_SMLAL, NONE, OP_ARM64_UMLAL},
  [NI_AdvSimd_MultiplyWideningLowerAndSubtract] = {OP_ARM64_SMLSL, NONE, OP_ARM64_UMLSL},
  [NI_AdvSimd_MultiplyWideningUpper] = {OP_ARM64_SMULL2, NONE, OP_ARM64_UMULL2},
  [NI_AdvSimd_MultiplyWideningUpperAndAdd] = {OP_ARM64_SMLAL2, NONE, OP_ARM64_UMLAL2},
  [NI_AdvSimd_MultiplyWideningUpperAndSubtract] = {OP_ARM64_SMLSL2, NONE, OP_ARM64_UMLSL2},
  [NI_AdvSimd_Negate] = {OP_NEGATION},
  [NI_AdvSimd_NegateSaturate] = {OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_SQNEG},
  [NI_AdvSimd_NegateSaturateScalar] = {OP_XOP_OVR_SCALAR_X_X, INTRINS_AARCH64_ADV_SIMD_SQNEG},
  [NI_AdvSimd_NegateScalar] = {OP_NEGATION_SCALAR},
  [NI_AdvSimd_Not] = {OP_ONES_COMPLEMENT},
  [NI_AdvSimd_Or] = {OP_XBINOP_FORCEINT, XBINOP_FORCEINT_OR},
  [NI_AdvSimd_OrNot] = {OP_XBINOP_FORCEINT, XBINOP_FORCEINT_ORNOT},
  [NI_AdvSimd_PolynomialMultiply] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_PMUL},
  [NI_AdvSimd_PolynomialMultiplyWideningLower] = {OP_ARM64_PMULL},
  [NI_AdvSimd_PolynomialMultiplyWideningUpper] = {OP_ARM64_PMULL2},
  [NI_AdvSimd_PopCount] = {OP_XOP_OVR_X_X, INTRINS_SIMD_POPCNT},
  [NI_AdvSimd_ReciprocalEstimate] = {NONE, NONE, OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_URECPE, OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_FRECPE},
  [NI_AdvSimd_ReciprocalEstimateScalar] = {OP_XOP_OVR_SCALAR_X_X, INTRINS_AARCH64_ADV_SIMD_FRECPE},
  [NI_AdvSimd_ReciprocalExponentScalar] = {OP_XOP_OVR_SCALAR_X_X, INTRINS_AARCH64_ADV_SIMD_FRECPX},
  [NI_AdvSimd_ReciprocalSquareRootEstimate] = {NONE, NONE, OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_URSQRTE, OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_FRSQRTE},
  [NI_AdvSimd_ReciprocalSquareRootEstimateScalar] = {OP_XOP_OVR_SCALAR_X_X, INTRINS_AARCH64_ADV_SIMD_FRSQRTE},
  [NI_AdvSimd_ReciprocalSquareRootStep] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_FRSQRTS},
  [NI_AdvSimd_ReciprocalSquareRootStepScalar] = {OP_XOP_OVR_SCALAR_X_X_X, INTRINS_AARCH64_ADV_SIMD_FRSQRTS},
  [NI_AdvSimd_ReciprocalStep] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_FRECPS},
  [NI_AdvSimd_ReciprocalStepScalar] = {OP_XOP_OVR_SCALAR_X_X_X, INTRINS_AARCH64_ADV_SIMD_FRECPS},
  {NI_AdvSimd_ReverseElement16, OP_ARM64_REVN, 16},
  {NI_AdvSimd_ReverseElement32, OP_ARM64_REVN, 32},
  {NI_AdvSimd_ReverseElement8, OP_ARM64_REVN, 8},
  [NI_AdvSimd_ReverseElementBits] = {OP_XOP_OVR_X_X, INTRINS_BITREVERSE},
  [NI_AdvSimd_RoundAwayFromZero] = {OP_XOP_OVR_X_X, INTRINS_SIMD_ROUND},
  [NI_AdvSimd_RoundAwayFromZeroScalar] = {OP_XOP_OVR_SCALAR_X_X, INTRINS_SIMD_ROUND},
  [NI_AdvSimd_RoundToNearest] = {OP_XOP_OVR_X_X, INTRINS_ROUNDEVEN},
  [NI_AdvSimd_RoundToNearestScalar] = {OP_XOP_OVR_SCALAR_X_X, INTRINS_ROUNDEVEN},
  [NI_AdvSimd_RoundToNegativeInfinity] = {OP_XOP_OVR_X_X, INTRINS_SIMD_FLOOR},
  [NI_AdvSimd_RoundToNegativeInfinityScalar] = {OP_XOP_OVR_SCALAR_X_X, INTRINS_SIMD_FLOOR},
  [NI_AdvSimd_RoundToPositiveInfinity] = {OP_XOP_OVR_X_X, INTRINS_SIMD_CEIL},
  [NI_AdvSimd_RoundToPositiveInfinityScalar] = {OP_XOP_OVR_SCALAR_X_X, INTRINS_SIMD_CEIL},
  [NI_AdvSimd_RoundToZero] = {OP_XOP_OVR_X_X, INTRINS_SIMD_TRUNC},
  [NI_AdvSimd_RoundToZeroScalar] = {OP_XOP_OVR_SCALAR_X_X, INTRINS_SIMD_TRUNC},
  [NI_AdvSimd_ShiftArithmetic] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_SSHL},
  [NI_AdvSimd_ShiftArithmeticRounded] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_SRSHL},
  [NI_AdvSimd_ShiftArithmeticRoundedSaturate] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_SQRSHL},
  [NI_AdvSimd_ShiftArithmeticRoundedSaturateScalar] = {OP_XOP_OVR_SCALAR_X_X_X, INTRINS_AARCH64_ADV_SIMD_SQRSHL},
  [NI_AdvSimd_ShiftArithmeticRoundedScalar] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_SRSHL},
  [NI_AdvSimd_ShiftArithmeticSaturate] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_SQSHL},
  [NI_AdvSimd_ShiftArithmeticSaturateScalar] = {OP_XOP_OVR_SCALAR_X_X_X, INTRINS_AARCH64_ADV_SIMD_SQSHL},
  [NI_AdvSimd_ShiftArithmeticScalar] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_SSHL},
  [NI_AdvSimd_ShiftLeftAndInsert] = {OP_ARM64_SLI},
  [NI_AdvSimd_ShiftLeftAndInsertScalar] = {OP_ARM64_SLI},
  [NI_AdvSimd_ShiftLeftLogical] = {OP_SIMD_SHL},
  //[NI_AdvSimd_ShiftLeftLogicalSaturate],
  //[NI_AdvSimd_ShiftLeftLogicalSaturateScalar],
  [NI_AdvSimd_ShiftLeftLogicalSaturateUnsigned] = {OP_ARM64_SQSHLU},
  [NI_AdvSimd_ShiftLeftLogicalSaturateUnsignedScalar] = {OP_ARM64_SQSHLU_SCALAR},
  [NI_AdvSimd_ShiftLeftLogicalScalar] = {OP_SIMD_SHL},
  [NI_AdvSimd_ShiftLeftLogicalWideningLower] = {OP_SIMD_SSHLL, NONE, OP_SIMD_USHLL},
  [NI_AdvSimd_ShiftLeftLogicalWideningUpper] = {OP_SIMD_SSHLL2, NONE, OP_SIMD_USHLL2},
  [NI_AdvSimd_ShiftLogical] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_USHL},
  [NI_AdvSimd_ShiftLogicalRounded] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_URSHL},
  [NI_AdvSimd_ShiftLogicalRoundedSaturate] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_UQRSHL},
  [NI_AdvSimd_ShiftLogicalRoundedSaturateScalar] = {OP_XOP_OVR_SCALAR_X_X_X, INTRINS_AARCH64_ADV_SIMD_UQRSHL},
  [NI_AdvSimd_ShiftLogicalRoundedScalar] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_URSHL},
  [NI_AdvSimd_ShiftLogicalSaturate] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_UQSHL},
  [NI_AdvSimd_ShiftLogicalSaturateScalar] = {OP_XOP_OVR_SCALAR_X_X_X, INTRINS_AARCH64_ADV_SIMD_UQSHL},
  [NI_AdvSimd_ShiftLogicalScalar] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_USHL},
  [NI_AdvSimd_ShiftRightAndInsert] = {OP_ARM64_SRI},
  [NI_AdvSimd_ShiftRightAndInsertScalar] = {OP_ARM64_SRI},
  [NI_AdvSimd_ShiftRightArithmetic] = {OP_SIMD_SSHR},
  [NI_AdvSimd_ShiftRightArithmeticAdd] = {OP_SIMD_SSRA},
  [NI_AdvSimd_ShiftRightArithmeticAddScalar] = {OP_SIMD_SSRA},
  [NI_AdvSimd_ShiftRightArithmeticNarrowingSaturateLower] = {OP_ARM64_XNSHIFT, INTRINS_AARCH64_ADV_SIMD_SQSHRN},
  [NI_AdvSimd_ShiftRightArithmeticNarrowingSaturateScalar] = {OP_ARM64_XNSHIFT_SCALAR, INTRINS_AARCH64_ADV_SIMD_SQSHRN},
  [NI_AdvSimd_ShiftRightArithmeticNarrowingSaturateUnsignedLower] = {OP_ARM64_XNSHIFT, INTRINS_AARCH64_ADV_SIMD_SQSHRUN},
  [NI_AdvSimd_ShiftRightArithmeticNarrowingSaturateUnsignedScalar] = {OP_ARM64_XNSHIFT_SCALAR, INTRINS_AARCH64_ADV_SIMD_SQSHRUN},
  [NI_AdvSimd_ShiftRightArithmeticNarrowingSaturateUnsignedUpper] = {OP_ARM64_XNSHIFT2, INTRINS_AARCH64_ADV_SIMD_SQSHRUN},
  [NI_AdvSimd_ShiftRightArithmeticNarrowingSaturateUpper] = {OP_ARM64_XNSHIFT2, INTRINS_AARCH64_ADV_SIMD_SQSHRN},
  [NI_AdvSimd_ShiftRightArithmeticRounded] = {OP_ARM64_SRSHR},
  [NI_AdvSimd_ShiftRightArithmeticRoundedAdd] = {OP_ARM64_SRSRA},
  [NI_AdvSimd_ShiftRightArithmeticRoundedAddScalar] = {OP_ARM64_SRSRA},
  [NI_AdvSimd_ShiftRightArithmeticRoundedNarrowingSaturateLower] = {OP_ARM64_XNSHIFT, INTRINS_AARCH64_ADV_SIMD_SQRSHRN},
  [NI_AdvSimd_ShiftRightArithmeticRoundedNarrowingSaturateScalar] = {OP_ARM64_XNSHIFT_SCALAR, INTRINS_AARCH64_ADV_SIMD_SQRSHRN},
  [NI_AdvSimd_ShiftRightArithmeticRoundedNarrowingSaturateUnsignedLower] = {OP_ARM64_XNSHIFT, INTRINS_AARCH64_ADV_SIMD_SQRSHRUN},
  [NI_AdvSimd_ShiftRightArithmeticRoundedNarrowingSaturateUnsignedScalar] = {OP_ARM64_XNSHIFT_SCALAR, INTRINS_AARCH64_ADV_SIMD_SQRSHRUN},
  [NI_AdvSimd_ShiftRightArithmeticRoundedNarrowingSaturateUnsignedUpper] = {OP_ARM64_XNSHIFT2, INTRINS_AARCH64_ADV_SIMD_SQRSHRUN},
  [NI_AdvSimd_ShiftRightArithmeticRoundedNarrowingSaturateUpper] = {OP_ARM64_XNSHIFT2, INTRINS_AARCH64_ADV_SIMD_SQRSHRN},
  [NI_AdvSimd_ShiftRightArithmeticRoundedScalar] = {OP_ARM64_SRSHR},
  [NI_AdvSimd_ShiftRightArithmeticScalar] = {OP_SIMD_SSHR},
  [NI_AdvSimd_ShiftRightLogical] = {OP_SIMD_USHR},
  [NI_AdvSimd_ShiftRightLogicalAdd] = {OP_SIMD_USRA},
  [NI_AdvSimd_ShiftRightLogicalAddScalar] = {OP_SIMD_USRA},
  [NI_AdvSimd_ShiftRightLogicalNarrowingLower] = {OP_ARM64_SHRN},
  [NI_AdvSimd_ShiftRightLogicalNarrowingSaturateLower] = {OP_ARM64_XNSHIFT, INTRINS_AARCH64_ADV_SIMD_UQSHRN},
  [NI_AdvSimd_ShiftRightLogicalNarrowingSaturateScalar] = {OP_ARM64_XNSHIFT_SCALAR, INTRINS_AARCH64_ADV_SIMD_UQSHRN},
  [NI_AdvSimd_ShiftRightLogicalNarrowingSaturateUpper] = {OP_ARM64_XNSHIFT2, INTRINS_AARCH64_ADV_SIMD_UQSHRN},
  [NI_AdvSimd_ShiftRightLogicalNarrowingUpper] = {OP_ARM64_SHRN2},
  [NI_AdvSimd_ShiftRightLogicalRounded] = {OP_ARM64_URSHR},
  [NI_AdvSimd_ShiftRightLogicalRoundedAdd] = {OP_ARM64_URSRA},
  [NI_AdvSimd_ShiftRightLogicalRoundedAddScalar] = {OP_ARM64_URSRA},
  [NI_AdvSimd_ShiftRightLogicalRoundedNarrowingLower] = {OP_ARM64_XNSHIFT, INTRINS_AARCH64_ADV_SIMD_RSHRN},
  [NI_AdvSimd_ShiftRightLogicalRoundedNarrowingSaturateLower] = {OP_ARM64_XNSHIFT, INTRINS_AARCH64_ADV_SIMD_UQRSHRN},
  [NI_AdvSimd_ShiftRightLogicalRoundedNarrowingSaturateScalar] = {OP_ARM64_XNSHIFT_SCALAR, INTRINS_AARCH64_ADV_SIMD_UQRSHRN},
  [NI_AdvSimd_ShiftRightLogicalRoundedNarrowingSaturateUpper] = {OP_ARM64_XNSHIFT2, INTRINS_AARCH64_ADV_SIMD_UQRSHRN},
  [NI_AdvSimd_ShiftRightLogicalRoundedNarrowingUpper] = {OP_ARM64_XNSHIFT2, INTRINS_AARCH64_ADV_SIMD_RSHRN},
  [NI_AdvSimd_ShiftRightLogicalRoundedScalar] = {OP_ARM64_URSHR},
  [NI_AdvSimd_ShiftRightLogicalScalar] = {OP_SIMD_USHR},
  [NI_AdvSimd_SignExtendWideningLower] = {OP_ARM64_SXTL},
  [NI_AdvSimd_SignExtendWideningUpper] = {OP_ARM64_SXTL2},
  [NI_AdvSimd_Sqrt] = {OP_XOP_OVR_X_X, INTRINS_AARCH64_ADV_SIMD_FSQRT},
  [NI_AdvSimd_SqrtScalar] = {OP_XOP_OVR_SCALAR_X_X, INTRINS_AARCH64_ADV_SIMD_FSQRT},
  [NI_AdvSimd_Store] = {OP_ARM64_ST1},
  [NI_AdvSimd_StorePair] = {OP_ARM64_STP},
  [NI_AdvSimd_StorePairNonTemporal] = {OP_ARM64_STNP},
  [NI_AdvSimd_StorePairScalar] = {OP_ARM64_STP_SCALAR},
  [NI_AdvSimd_StorePairScalarNonTemporal] = {OP_ARM64_STNP_SCALAR},
  [NI_AdvSimd_StoreSelectedScalar] = {OP_ARM64_ST1_SCALAR},
  [NI_AdvSimd_Subtract] = {OP_XBINOP, OP_ISUB, NONE, NONE, OP_XBINOP, OP_FSUB},
  [NI_AdvSimd_SubtractHighNarrowingLower] = {OP_ARM64_SUBHN},
  [NI_AdvSimd_SubtractHighNarrowingUpper] = {OP_ARM64_SUBHN2},
  [NI_AdvSimd_SubtractRoundedHighNarrowingLower] = {OP_ARM64_RSUBHN},
  [NI_AdvSimd_SubtractRoundedHighNarrowingUpper] = {OP_ARM64_RSUBHN2},
  [NI_AdvSimd_SubtractSaturate] = {OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_SQSUB, OP_XOP_OVR_X_X_X, INTRINS_AARCH64_ADV_SIMD_UQSUB},
  [NI_AdvSimd_SubtractSaturateScalar] = {OP_XOP_OVR_SCALAR_X_X_X, INTRINS_AARCH64_ADV_SIMD_SQSUB, OP_XOP_OVR_SCALAR_X_X_X, INTRINS_AARCH64_ADV_SIMD_UQSUB},
  [NI_AdvSimd_SubtractScalar] = {OP_XBINOP_SCALAR, OP_ISUB, NONE, NONE, OP_XBINOP_SCALAR, OP_FSUB},
  [NI_AdvSimd_SubtractWideningLower] = {OP_ARM64_SSUB, NONE, OP_ARM64_USUB},
  [NI_AdvSimd_SubtractWideningUpper] = {OP_ARM64_SSUB2, NONE, OP_ARM64_USUB2},
  [NI_AdvSimd_TransposeEven] = {OP_ARM64_TRN1},
  [NI_AdvSimd_TransposeOdd] = {OP_ARM64_TRN2},
  [NI_AdvSimd_UnzipEven] = {OP_ARM64_UZP1},
  [NI_AdvSimd_UnzipOdd] = {OP_ARM64_UZP2},
  //[NI_AdvSimd_VectorTableLookup],
  //[NI_AdvSimd_VectorTableLookupExtension],
  [NI_AdvSimd_Xor] = {OP_XBINOP_FORCEINT, XBINOP_FORCEINT_XOR},
  [NI_AdvSimd_ZeroExtendWideningLower] = {OP_ARM64_UXTL},
  [NI_AdvSimd_ZeroExtendWideningUpper] = {OP_ARM64_UXTL2},
  [NI_AdvSimd_ZipHigh] = {OP_ARM64_ZIP2},
  [NI_AdvSimd_ZipLow] = {OP_ARM64_ZIP1}
 
};

static MonoInst*
emit_manual_intrinsic (MonoCompile* cfg, NamedIntrinsic ni, MonoInst** args, MonoMethodSignature* fsig, MonoClass* klass, MonoTypeEnum arg0_type)
{
  MonoInst* ins = NULL;

  return ins;
}

MonoInst* 
emit_llvm_intrinsic (MonoCompile* cfg, NamedIntrinsic ni, MonoMethodSignature* fsig, MonoInst** args)
{
  g_assert (ni < NI_PRIMITIVE_END);

  MonoClass* klass = fsig->param_count > 0 ? args[0]->klass : cmethod->klass;
	MonoTypeEnum arg0_type = fsig->param_count > 0 ? get_underlying_type (fsig->params [0]) : MONO_TYPE_VOID;

  const LlvmInitrinsicMapping* lim = INTRINSIC_MAPPING[ni];
  
  uint16_t ret_op = NONE, ret_c0 = NONE;
  if (type_enum_is_float (arg0_type)) {
    ret_op = (lim->fp_op == NONE) ? lim->op : lim->fp_op;
    ret_c0 = (lim->fp_c0 == NONE) ? lim->c0 : lim->fp_c0;
  } else {
    ret_op = (lim->int_op == NONE) ? lim->op : lim->fp_op;
    ret_c0 = (lim->int_c0 == NONE) ? lim->c0 : lim->int_c0;
  }

  if (ret_op == NONE)
    return NULL;
  else if (ret == EMIT_MANUAL)
    return emit_manual_intrinsic (cfg, ni, args, fsig, klass, arg0_type);
  
  //TODO: return emit_simd_ins_for_sig (cfg, klass, ret_op, ret_c0, arg0_type, fsig, args);
  return NULL;
}

#else

MonoInst* 
emit_llvm_intrinsic (MonoCompile* cfg, NamedIntrinsic ni, MonoMethodSignature* fsig, MonoInst** args)
{
  g_assert_not_reached();
  return NULL;
}

#endif