METHOD2(".ctor", ctor)
METHOD(CopyTo)
METHOD(Equals)
METHOD(GreaterThan)
METHOD(GreaterThanOrEqual)
METHOD(LessThan)
METHOD(LessThanOrEqual)
METHOD(Min)
METHOD(Max)
METHOD(PopCount)
METHOD(LeadingZeroCount)
METHOD(get_Count)
METHOD(get_IsHardwareAccelerated)
METHOD(get_IsSupported)
METHOD(get_AllOnes)
METHOD(get_Item)
METHOD(get_One)
METHOD(get_Zero)
METHOD(op_Addition)
METHOD(op_BitwiseAnd)
METHOD(op_BitwiseOr)
METHOD(op_Division)
METHOD(op_Equality)
METHOD(op_ExclusiveOr)
METHOD(op_Explicit)
METHOD(op_Inequality)
METHOD(op_Multiply)
METHOD(op_Subtraction)
// Vector
METHOD(ConvertToInt32)
METHOD(ConvertToUInt32)
METHOD(ConvertToInt64)
METHOD(ConvertToUInt64)
METHOD(ConvertToSingle)
METHOD(ConvertToDouble)
METHOD(Narrow)
METHOD(Widen)
// Vector128
METHOD(AsByte)
METHOD(AsDouble)
METHOD(AsInt16)
METHOD(AsInt32)
METHOD(AsInt64)
METHOD(AsSByte)
METHOD(AsSingle)
METHOD(AsUInt16)
METHOD(AsUInt32)
METHOD(AsUInt64)
METHOD(Create)
METHOD(CreateScalarUnsafe)
// Bmi1
METHOD(AndNot)
METHOD(BitFieldExtract)
METHOD(ExtractLowestSetBit)
METHOD(GetMaskUpToLowestSetBit)
METHOD(ResetLowestSetBit)
METHOD(TrailingZeroCount)
// Bmi2
METHOD(ZeroHighBits)
METHOD(MultiplyNoFlags)
METHOD(ParallelBitDeposit)
METHOD(ParallelBitExtract)
// Sse
METHOD(Add)
METHOD(CompareNotEqual)
METHOD(Divide)
METHOD(Store)
METHOD(Subtract)
METHOD(CompareEqual)
METHOD(LoadVector128)
METHOD(MoveHighToLow)
METHOD(MoveLowToHigh)
METHOD(MoveMask)
METHOD(MoveScalar)
METHOD(Multiply)
METHOD(Shuffle)
METHOD(UnpackHigh)
METHOD(UnpackLow)
// Sse2
METHOD(AddSaturate)
METHOD(And)
METHOD(Or)
METHOD(LoadAlignedVector128)
METHOD(Xor)
METHOD(CompareGreaterThan)
METHOD(PackUnsignedSaturate)
METHOD(StoreScalar)
METHOD(StoreAligned)
METHOD(ShiftRightLogical)
METHOD(CompareLessThan)
// Sse3
METHOD(MoveAndDuplicate)
// Sse41
METHOD(Insert)
METHOD(TestZ)