<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Installs a custom signal handler. -->
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <CLRTestTargetUnsupported Condition="'$(TargetsOSX)' != 'true'">true</CLRTestTargetUnsupported>
    <CLRTestPriority>1</CLRTestPriority>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="test132581.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="$(TestLibraryProjectPath)" />
  </ItemGroup>
  <ItemGroup>
    <CMakeProjectReference Include="CMakeLists.txt" />
  </ItemGroup>
</Project>
