// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

/*****************************************************************************/
#ifndef HARDWARE_INTRINSIC
#error Define HARDWARE_INTRINSIC before including this file
#endif
/*****************************************************************************/

// clang-format off

#ifdef FEATURE_HW_INTRINSICS
// ***************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
//                 ISA            Function name                                              SIMD size  NumArg                                                                                                                 Instructions                                                                                        Category                           Flags
//                                                                                                                  {TYP_BYTE,           TYP_UBYTE,          TYP_SHORT,          TYP_USHORT,         TYP_INT,            TYP_UINT,           TYP_LONG,           TYP_ULONG,          TYP_FLOAT,          TYP_DOUBLE}
// ***************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
//  Wasm Intrinsics
// TODO-WASM: Fill in correct flags and direct mappings here for Vector128 xplat intrinsics implementation
#define FIRST_NI_Vector128        NI_Vector128_As
HARDWARE_INTRINSIC(Vector128,      As,                                                               16,      1,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      AsByte,                                                           16,      1,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      AsDouble,                                                         16,      1,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      AsInt16,                                                          16,      1,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      AsInt32,                                                          16,      1,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      AsInt64,                                                          16,      1,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      AsNInt,                                                           16,      1,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      AsNUInt,                                                          16,      1,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      AsSByte,                                                          16,      1,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      AsSingle,                                                         16,      1,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      AsUInt16,                                                         16,      1,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      AsUInt32,                                                         16,      1,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      AsUInt64,                                                         16,      1,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      AsVector128Unsafe,                                                16,      1,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_SIMD,                  HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      AsVector2,                                                        16,      1,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      AsVector3,                                                        16,      1,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      AsVector4,                                                        16,      1,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      Create,                                                           16,     -1,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Special,               HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      CreateScalar,                                                     16,      1,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      CreateScalarUnsafe,                                               16,      1,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      Dot,                                                              16,      2,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      ExtractMostSignificantBits,                                       16,      1,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      GetElement,                                                       16,      2,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      Shuffle,                                                          16,     -1,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      ShuffleNative,                                                    16,     -1,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      ShuffleNativeFallback,                                            16,     -1,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      ToScalar,                                                         16,      1,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_SIMD,                  HW_Flag_InvalidNodeId|HW_Flag_BaseTypeFromFirstArg|HW_Flag_ReturnsScalarT)
HARDWARE_INTRINSIC(Vector128,      WithElement,                                                      16,      3,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      WithLower,                                                        16,      2,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      WithUpper,                                                        16,      2,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      get_AllBitsSet,                                                   16,      0,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      get_E,                                                            16,      0,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      get_Epsilon,                                                      16,      0,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      get_NaN,                                                          16,      0,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      get_NegativeInfinity,                                             16,      0,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      get_NegativeOne,                                                  16,      0,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      get_NegativeZero,                                                 16,      0,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      get_One,                                                          16,      0,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      get_Pi,                                                           16,      0,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      get_PositiveInfinity,                                             16,      0,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      get_Tau,                                                          16,      0,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      get_Zero,                                                         16,      0,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      op_Equality,                                                      16,      2,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      op_Inequality,                                                    16,      2,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(Vector128,      op_UnaryPlus,                                                     16,      1,    {INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid,        INS_invalid},     HW_Category_Helper,                HW_Flag_InvalidNodeId)

#define LAST_NI_Vector128         NI_Vector128_op_UnaryPlus

#define FIRST_NI_PackedSimd NI_PackedSimd_Abs
HARDWARE_INTRINSIC(PackedSimd,        Abs,                                     16,        1,        {INS_i8x16_abs,                        INS_invalid,                          INS_i16x8_abs,                        INS_invalid,                          INS_i32x4_abs,                    INS_invalid,                      INS_i64x2_abs,         INS_invalid,           INS_f32x4_abs,                  INS_f64x2_abs                   },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        Add,                                     16,        2,        {INS_i8x16_add,                        INS_i8x16_add,                        INS_i16x8_add,                        INS_i16x8_add,                        INS_i32x4_add,                    INS_i32x4_add,                    INS_i64x2_add,         INS_i64x2_add,         INS_f32x4_add,                  INS_f64x2_add                   },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg|HW_Flag_Commutative)
HARDWARE_INTRINSIC(PackedSimd,        AddPairwiseWidening,                     16,        1,        {INS_i16x8_extadd_pairwise_s_i8x16,    INS_i16x8_extadd_pairwise_u_i8x16,    INS_i32x4_extadd_pairwise_s_i16x8,    INS_i32x4_extadd_pairwise_u_i16x8,    INS_invalid,                      INS_invalid,                      INS_invalid,           INS_invalid,           INS_invalid,                    INS_invalid                     },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        AddSaturate,                             16,        2,        {INS_i8x16_add_sat_s,                  INS_i8x16_add_sat_u,                  INS_i16x8_add_sat_s,                  INS_i16x8_add_sat_u,                  INS_invalid,                      INS_invalid,                      INS_invalid,           INS_invalid,           INS_invalid,                    INS_invalid                     },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg|HW_Flag_Commutative)
HARDWARE_INTRINSIC(PackedSimd,        AllTrue,                                 16,        1,        {INS_i8x16_all_true,                   INS_i8x16_all_true,                   INS_i16x8_all_true,                   INS_i16x8_all_true,                   INS_i32x4_all_true,               INS_i32x4_all_true,               INS_i64x2_all_true,    INS_i64x2_all_true,    INS_invalid,                    INS_invalid                     },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        And,                                     16,        2,        {INS_v128_and,                         INS_v128_and,                         INS_v128_and,                         INS_v128_and,                         INS_v128_and,                     INS_v128_and,                     INS_v128_and,          INS_v128_and,          INS_v128_and,                   INS_v128_and                    },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg|HW_Flag_Commutative)
HARDWARE_INTRINSIC(PackedSimd,        AndNot,                                  16,        2,        {INS_v128_andnot,                      INS_v128_andnot,                      INS_v128_andnot,                      INS_v128_andnot,                      INS_v128_andnot,                  INS_v128_andnot,                  INS_v128_andnot,       INS_v128_andnot,       INS_v128_andnot,                INS_v128_andnot                 },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        AnyTrue,                                 16,        1,        {INS_v128_any_true,                    INS_v128_any_true,                    INS_v128_any_true,                    INS_v128_any_true,                    INS_v128_any_true,                INS_v128_any_true,                INS_v128_any_true,     INS_v128_any_true,     INS_v128_any_true,              INS_v128_any_true               },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg|HW_Flag_ReturnsBoolean)
HARDWARE_INTRINSIC(PackedSimd,        AverageRounded,                          16,        2,        {INS_invalid,                          INS_i8x16_avgr_u,                     INS_invalid,                          INS_i16x8_avgr_u,                     INS_invalid,                      INS_invalid,                      INS_invalid,           INS_invalid,           INS_invalid,                    INS_invalid                     },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg|HW_Flag_Commutative)
HARDWARE_INTRINSIC(PackedSimd,        Bitmask,                                 16,        1,        {INS_i8x16_bitmask,                    INS_i8x16_bitmask,                    INS_i16x8_bitmask,                    INS_i16x8_bitmask,                    INS_i32x4_bitmask,                INS_i32x4_bitmask,                INS_i64x2_bitmask,     INS_i64x2_bitmask,     INS_invalid,                    INS_invalid                     },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        BitwiseSelect,                           16,        3,        {INS_v128_bitselect,                   INS_v128_bitselect,                   INS_v128_bitselect,                   INS_v128_bitselect,                   INS_v128_bitselect,               INS_v128_bitselect,               INS_v128_bitselect,    INS_v128_bitselect,    INS_v128_bitselect,             INS_v128_bitselect              },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        Ceiling,                                 16,        1,        {INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                      INS_invalid,                      INS_invalid,           INS_invalid,           INS_f32x4_ceil,                 INS_f64x2_ceil                  },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        CompareEqual,                            16,        2,        {INS_i8x16_eq,                         INS_i8x16_eq,                         INS_i16x8_eq,                         INS_i16x8_eq,                         INS_i32x4_eq,                     INS_i32x4_eq,                     INS_i64x2_eq,          INS_i64x2_eq,          INS_f32x4_eq,                   INS_f64x2_eq                    },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg|HW_Flag_Commutative|HW_Flag_ReturnsPerElementMask)
// NOTE: the ULONG slot in the four ordered compares below uses signed compares because the WASM SIMD spec has no
// unsigned i64x2 ordered compare. Vector128<ulong> compares are rewritten in lowering
// into the equivalent signed compare by inserting the equivalent of PackedSimd.Xor(op_i, sign_bit_64x2) around each operand 
HARDWARE_INTRINSIC(PackedSimd,        CompareGreaterThan,                      16,        2,        {INS_i8x16_gt_s,                       INS_i8x16_gt_u,                       INS_i16x8_gt_s,                       INS_i16x8_gt_u,                       INS_i32x4_gt_s,                   INS_i32x4_gt_u,                   INS_i64x2_gt_s,        INS_i64x2_gt_s,           INS_f32x4_gt,                   INS_f64x2_gt                    },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg|HW_Flag_ReturnsPerElementMask)
HARDWARE_INTRINSIC(PackedSimd,        CompareGreaterThanOrEqual,               16,        2,        {INS_i8x16_ge_s,                       INS_i8x16_ge_u,                       INS_i16x8_ge_s,                       INS_i16x8_ge_u,                       INS_i32x4_ge_s,                   INS_i32x4_ge_u,                   INS_i64x2_ge_s,        INS_i64x2_ge_s,           INS_f32x4_ge,                   INS_f64x2_ge                    },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg|HW_Flag_ReturnsPerElementMask)
HARDWARE_INTRINSIC(PackedSimd,        CompareLessThan,                         16,        2,        {INS_i8x16_lt_s,                       INS_i8x16_lt_u,                       INS_i16x8_lt_s,                       INS_i16x8_lt_u,                       INS_i32x4_lt_s,                   INS_i32x4_lt_u,                   INS_i64x2_lt_s,        INS_i64x2_lt_s,           INS_f32x4_lt,                   INS_f64x2_lt                    },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg|HW_Flag_ReturnsPerElementMask)
HARDWARE_INTRINSIC(PackedSimd,        CompareLessThanOrEqual,                  16,        2,        {INS_i8x16_le_s,                       INS_i8x16_le_u,                       INS_i16x8_le_s,                       INS_i16x8_le_u,                       INS_i32x4_le_s,                   INS_i32x4_le_u,                   INS_i64x2_le_s,        INS_i64x2_le_s,           INS_f32x4_le,                   INS_f64x2_le                    },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg|HW_Flag_ReturnsPerElementMask)

HARDWARE_INTRINSIC(PackedSimd,        CompareNotEqual,                         16,        2,        {INS_i8x16_ne,                         INS_i8x16_ne,                         INS_i16x8_ne,                         INS_i16x8_ne,                         INS_i32x4_ne,                     INS_i32x4_ne,                     INS_i64x2_ne,          INS_i64x2_ne,          INS_f32x4_ne,                   INS_f64x2_ne                    },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg|HW_Flag_Commutative|HW_Flag_ReturnsPerElementMask)
HARDWARE_INTRINSIC(PackedSimd,        ConvertNarrowingSaturateSigned,          16,        2,        {INS_invalid,                          INS_invalid,                          INS_i8x16_narrow_i16x8_s,             INS_invalid,                          INS_i16x8_narrow_i32x4_s,         INS_invalid,                      INS_invalid,           INS_invalid,           INS_invalid,                    INS_invalid                     },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        ConvertNarrowingSaturateUnsigned,        16,        2,        {INS_invalid,                          INS_invalid,                          INS_i8x16_narrow_i16x8_u,             INS_invalid,                          INS_i16x8_narrow_i32x4_u,         INS_invalid,                      INS_invalid,           INS_invalid,           INS_invalid,                    INS_invalid                     },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        ConvertToDoubleLower,                    16,        1,        {INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_f64x2_convert_low_s_i32x4,    INS_f64x2_convert_low_u_i32x4,    INS_invalid,           INS_invalid,           INS_f64x2_promote_low_f32x4,    INS_invalid                     },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        ConvertToInt32Saturate,                  16,        1,        {INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                      INS_invalid,                      INS_invalid,           INS_invalid,           INS_i32x4_trunc_sat_s_f32x4,    INS_i32x4_trunc_sat_s_f64x2_zero},       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        ConvertToSingle,                         16,        1,        {INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_f32x4_convert_s_i32x4,        INS_f32x4_convert_u_i32x4,        INS_invalid,           INS_invalid,           INS_invalid,                    INS_f32x4_demote_f64x2_zero     },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        ConvertToUInt32Saturate,                 16,        1,        {INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                      INS_invalid,                      INS_invalid,           INS_invalid,           INS_i32x4_trunc_sat_u_f32x4,    INS_i32x4_trunc_sat_u_f64x2_zero},       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        Divide,                                  16,        2,        {INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                      INS_invalid,                      INS_invalid,           INS_invalid,           INS_f32x4_div,                  INS_f64x2_div                   },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        Dot,                                     16,        2,        {INS_invalid,                          INS_invalid,                          INS_i32x4_dot_i16x8_s,                INS_invalid,                          INS_invalid,                      INS_invalid,                      INS_invalid,           INS_invalid,           INS_invalid,                    INS_invalid                     },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        ExtractScalar,                           16,        2,        {INS_i8x16_extract_lane_s,             INS_i8x16_extract_lane_u,             INS_i16x8_extract_lane_s,             INS_i16x8_extract_lane_u,             INS_i32x4_extract_lane,           INS_i32x4_extract_lane,           INS_i64x2_extract_lane,INS_i64x2_extract_lane,INS_f32x4_extract_lane,         INS_i64x2_extract_lane          },       HW_Category_IMM,         HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        Floor,                                   16,        1,        {INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                      INS_invalid,                      INS_invalid,           INS_invalid,           INS_f32x4_floor,                INS_f64x2_floor                 },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        LoadScalarAndInsert,                     16,        3,        {INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                      INS_invalid,                      INS_invalid,           INS_invalid,           INS_invalid,                    INS_invalid                     },       HW_Category_Helper,      HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(PackedSimd,        LoadScalarAndSplatVector128,             16,        1,        {INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                      INS_invalid,                      INS_invalid,           INS_invalid,           INS_invalid,                    INS_invalid                     },       HW_Category_Helper,      HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(PackedSimd,        LoadScalarVector128,                     16,        1,        {INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                      INS_invalid,                      INS_invalid,           INS_invalid,           INS_invalid,                    INS_invalid                     },       HW_Category_Helper,      HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(PackedSimd,        LoadVector128,                           16,        1,        {INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                      INS_invalid,                      INS_invalid,           INS_invalid,           INS_invalid,                    INS_invalid                     },       HW_Category_Helper,      HW_Flag_InvalidNodeId|HW_Flag_SpecialImport)
HARDWARE_INTRINSIC(PackedSimd,        LoadWideningVector128,                   16,        1,        {INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                      INS_invalid,                      INS_invalid,           INS_invalid,           INS_invalid,                    INS_invalid                     },       HW_Category_Helper,      HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(PackedSimd,        Max,                                     16,        2,        {INS_i8x16_max_s,                      INS_i8x16_max_u,                      INS_i16x8_max_s,                      INS_i16x8_max_u,                      INS_i32x4_max_s,                  INS_i32x4_max_u,                  INS_invalid,           INS_invalid,           INS_f32x4_max,                  INS_f64x2_max                   },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg|HW_Flag_Commutative)
HARDWARE_INTRINSIC(PackedSimd,        Min,                                     16,        2,        {INS_i8x16_min_s,                      INS_i8x16_min_u,                      INS_i16x8_min_s,                      INS_i16x8_min_u,                      INS_i32x4_min_s,                  INS_i32x4_min_u,                  INS_invalid,           INS_invalid,           INS_f32x4_min,                  INS_f64x2_min                   },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg|HW_Flag_Commutative)
HARDWARE_INTRINSIC(PackedSimd,        Multiply,                                16,        2,        {INS_invalid,                          INS_invalid,                          INS_i16x8_mul,                        INS_i16x8_mul,                        INS_i32x4_mul,                    INS_i32x4_mul,                    INS_i64x2_mul,         INS_i64x2_mul,         INS_f32x4_mul,                  INS_f64x2_mul                   },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg|HW_Flag_Commutative)
HARDWARE_INTRINSIC(PackedSimd,        MultiplyRoundedSaturateQ15,              16,        2,        {INS_invalid,                          INS_invalid,                          INS_i16x8_q15mulr_sat_s,              INS_invalid,                          INS_invalid,                      INS_invalid,                      INS_invalid,           INS_invalid,           INS_invalid,                    INS_invalid                     },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg|HW_Flag_Commutative)
HARDWARE_INTRINSIC(PackedSimd,        MultiplyWideningLower,                   16,        2,        {INS_i16x8_extmul_low_s_i8x16,         INS_i16x8_extmul_low_u_i8x16,         INS_i32x4_extmul_low_s_i16x8,         INS_i32x4_extmul_low_u_i16x8,         INS_i64x2_extmul_low_s_i32x4,     INS_i64x2_extmul_low_u_i32x4,     INS_invalid,           INS_invalid,           INS_invalid,                    INS_invalid                     },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        MultiplyWideningUpper,                   16,        2,        {INS_i16x8_extmul_high_s_i8x16,        INS_i16x8_extmul_high_u_i8x16,        INS_i32x4_extmul_high_s_i16x8,        INS_i32x4_extmul_high_u_i16x8,        INS_i64x2_extmul_high_s_i32x4,    INS_i64x2_extmul_high_u_i32x4,    INS_invalid,           INS_invalid,           INS_invalid,                    INS_invalid                     },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        Negate,                                  16,        1,        {INS_i8x16_neg,                        INS_i8x16_neg,                        INS_i16x8_neg,                        INS_i16x8_neg,                        INS_i32x4_neg,                    INS_i32x4_neg,                    INS_i64x2_neg,         INS_i64x2_neg,         INS_f32x4_neg,                  INS_f64x2_neg                   },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        Not,                                     16,        1,        {INS_v128_not,                         INS_v128_not,                         INS_v128_not,                         INS_v128_not,                         INS_v128_not,                     INS_v128_not,                     INS_v128_not,          INS_v128_not,          INS_v128_not,                   INS_v128_not                    },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        Or,                                      16,        2,        {INS_v128_or,                          INS_v128_or,                          INS_v128_or,                          INS_v128_or,                          INS_v128_or,                      INS_v128_or,                      INS_v128_or,           INS_v128_or,           INS_v128_or,                    INS_v128_or                     },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg|HW_Flag_Commutative)
HARDWARE_INTRINSIC(PackedSimd,        PopCount,                                16,        1,        {INS_invalid,                          INS_i8x16_popcnt,                     INS_invalid,                          INS_invalid,                          INS_invalid,                      INS_invalid,                      INS_invalid,           INS_invalid,           INS_invalid,                    INS_invalid                     },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        PseudoMax,                               16,        2,        {INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                      INS_invalid,                      INS_invalid,           INS_invalid,           INS_f32x4_pmax,                 INS_f64x2_pmax                  },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        PseudoMin,                               16,        2,        {INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                      INS_invalid,                      INS_invalid,           INS_invalid,           INS_f32x4_pmin,                 INS_f64x2_pmin                  },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        ReplaceScalar,                           16,        3,        {INS_i8x16_replace_lane,               INS_i8x16_replace_lane,               INS_i16x8_replace_lane,               INS_i16x8_replace_lane,               INS_i32x4_replace_lane,           INS_i32x4_replace_lane,           INS_i64x2_replace_lane,INS_i64x2_replace_lane,INS_f32x4_replace_lane,         INS_f64x2_replace_lane          },       HW_Category_IMM,         HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        RoundToNearest,                          16,        1,        {INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                      INS_invalid,                      INS_invalid,           INS_invalid,           INS_f32x4_nearest,              INS_f64x2_nearest               },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        ShiftLeft,                               16,        2,        {INS_i8x16_shl,                        INS_i8x16_shl,                        INS_i16x8_shl,                        INS_i16x8_shl,                        INS_i32x4_shl,                    INS_i32x4_shl,                    INS_i64x2_shl,         INS_i64x2_shl,         INS_invalid,                    INS_invalid                     },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        ShiftRightArithmetic,                    16,        2,        {INS_i8x16_shr_s,                      INS_i8x16_shr_s,                      INS_i16x8_shr_s,                      INS_i16x8_shr_s,                      INS_i32x4_shr_s,                  INS_i32x4_shr_s,                  INS_i64x2_shr_s,       INS_i64x2_shr_s,       INS_invalid,                    INS_invalid                     },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        ShiftRightLogical,                       16,        2,        {INS_i8x16_shr_u,                      INS_i8x16_shr_u,                      INS_i16x8_shr_u,                      INS_i16x8_shr_u,                      INS_i32x4_shr_u,                  INS_i32x4_shr_u,                  INS_i64x2_shr_u,       INS_i64x2_shr_u,       INS_invalid,                    INS_invalid                     },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        SignExtendWideningLower,                 16,        1,        {INS_i16x8_extend_low_s_i8x16,         INS_i16x8_extend_low_s_i8x16,         INS_i32x4_extend_low_s_i16x8,         INS_i32x4_extend_low_s_i16x8,         INS_i64x2_extend_low_s_i32x4,     INS_i64x2_extend_low_s_i32x4,     INS_invalid,           INS_invalid,           INS_invalid,                    INS_invalid                     },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        SignExtendWideningUpper,                 16,        1,        {INS_i16x8_extend_high_s_i8x16,        INS_i16x8_extend_high_s_i8x16,        INS_i32x4_extend_high_s_i16x8,        INS_i32x4_extend_high_s_i16x8,        INS_i64x2_extend_high_s_i32x4,    INS_i64x2_extend_high_s_i32x4,    INS_invalid,           INS_invalid,           INS_invalid,                    INS_invalid                     },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        Splat,                                   16,        1,        {INS_i8x16_splat,                      INS_i8x16_splat,                      INS_i16x8_splat,                      INS_i16x8_splat,                      INS_i32x4_splat,                  INS_i32x4_splat,                  INS_i64x2_splat,       INS_i64x2_splat,       INS_f32x4_splat,                INS_f64x2_splat                 },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        Sqrt,                                    16,        1,        {INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                      INS_invalid,                      INS_invalid,           INS_invalid,           INS_f32x4_sqrt,                 INS_f64x2_sqrt                  },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        Store,                                   16,        2,        {INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                      INS_invalid,                      INS_invalid,           INS_invalid,           INS_invalid,                    INS_invalid                     },       HW_Category_MemoryStore, HW_Flag_InvalidNodeId|HW_Flag_SpecialImport|HW_Flag_BaseTypeFromSecondArg)
HARDWARE_INTRINSIC(PackedSimd,        StoreSelectedScalar,                     16,        3,        {INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                      INS_invalid,                      INS_invalid,           INS_invalid,           INS_invalid,                    INS_invalid                     },       HW_Category_Helper,      HW_Flag_InvalidNodeId)
HARDWARE_INTRINSIC(PackedSimd,        Subtract,                                16,        2,        {INS_i8x16_sub,                        INS_i8x16_sub,                        INS_i16x8_sub,                        INS_i16x8_sub,                        INS_i32x4_sub,                    INS_i32x4_sub,                    INS_i64x2_sub,         INS_i64x2_sub,         INS_f32x4_sub,                  INS_f64x2_sub                   },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        SubtractSaturate,                        16,        2,        {INS_i8x16_sub_sat_s,                  INS_i8x16_sub_sat_u,                  INS_i16x8_sub_sat_s,                  INS_i16x8_sub_sat_u,                  INS_invalid,                      INS_invalid,                      INS_invalid,           INS_invalid,           INS_invalid,                    INS_invalid                     },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        Swizzle,                                 16,        2,        {INS_i8x16_swizzle,                    INS_i8x16_swizzle,                    INS_invalid,                          INS_invalid,                          INS_invalid,                      INS_invalid,                      INS_invalid,           INS_invalid,           INS_invalid,                    INS_invalid                     },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        Truncate,                                16,        1,        {INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                          INS_invalid,                      INS_invalid,                      INS_invalid,           INS_invalid,           INS_f32x4_trunc,                INS_f64x2_trunc                 },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        Xor,                                     16,        2,        {INS_v128_xor,                         INS_v128_xor,                         INS_v128_xor,                         INS_v128_xor,                         INS_v128_xor,                     INS_v128_xor,                     INS_v128_xor,          INS_v128_xor,          INS_v128_xor,                   INS_v128_xor                    },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg|HW_Flag_Commutative)
HARDWARE_INTRINSIC(PackedSimd,        ZeroExtendWideningLower,                 16,        1,        {INS_i16x8_extend_low_u_i8x16,         INS_i16x8_extend_low_u_i8x16,         INS_i32x4_extend_low_u_i16x8,         INS_i32x4_extend_low_u_i16x8,         INS_i64x2_extend_low_u_i32x4,     INS_i64x2_extend_low_u_i32x4,     INS_invalid,           INS_invalid,           INS_invalid,                    INS_invalid                     },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
HARDWARE_INTRINSIC(PackedSimd,        ZeroExtendWideningUpper,                 16,        1,        {INS_i16x8_extend_high_u_i8x16,        INS_i16x8_extend_high_u_i8x16,        INS_i32x4_extend_high_u_i16x8,        INS_i32x4_extend_high_u_i16x8,        INS_i64x2_extend_high_u_i32x4,    INS_i64x2_extend_high_u_i32x4,    INS_invalid,           INS_invalid,           INS_invalid,                    INS_invalid                     },       HW_Category_SIMD,        HW_Flag_BaseTypeFromFirstArg)
#define LAST_NI_PackedSimd NI_PackedSimd_ZeroExtendWideningUpper
#endif // FEATURE_HW_INTRINSICS

#undef HARDWARE_INTRINSIC

// clang-format on
