<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Needed for CLRTestEnvironmentVariable -->
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Optimize>true</Optimize>

    <!-- This is an explicit crossgen test -->
    <AlwaysUseCrossGen2 Condition="'$(RuntimeFlavor)' != 'coreclr' or '$(TargetOS)' != 'browser'">true</AlwaysUseCrossGen2>
    <CrossGenTest Condition="'$(RuntimeFlavor)' == 'coreclr' and '$(TargetOS)' == 'browser'">false</CrossGenTest>
    <DefineConstants>$(DefineConstants);BROWSER_WASM_COMPOSITE_R2R_TEST</DefineConstants>
    <!-- No crossgen folder under Core_Root -->
     <NativeAotIncompatible>true</NativeAotIncompatible>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="BasicTest.cs" />

    <CLRTestEnvironmentVariable Include="DOTNET_TC_QuickJit" Value="1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="$(TestLibraryProjectPath)" />
  </ItemGroup>
</Project>
