<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Test needs explicit executable and isolation as it tests crashing the runtime. -->
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <MonoAotIncompatible>true</MonoAotIncompatible>
    <NativeAotIncompatible>true</NativeAotIncompatible>
    <CLRTestExitCode>134</CLRTestExitCode>
    <CLRTestExitCode Condition="'$(TestWrapperTargetsWindows)' == 'true'">-2146233082</CLRTestExitCode>
    <CLRTestPriority>1</CLRTestPriority>
    <CLRTestTargetUnsupported Condition="'$(RuntimeFlavor)' == 'coreclr' and '$(TargetOS)' == 'browser'">true</CLRTestTargetUnsupported>
    <ReferenceXUnitWrapperGenerator>false</ReferenceXUnitWrapperGenerator>
    <GCStressIncompatible>true</GCStressIncompatible>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="UnmanagedCallersOnlyNegativeTest.cs" />
  </ItemGroup>
  <ItemGroup>
    <!-- This is needed to make sure native binary gets installed in the right location -->
    <CMakeProjectReference Include="CMakeLists.txt" />
    <ProjectReference Include="$(TestLibraryProjectPath)" />
    <ProjectReference Include="InvalidCSharp.ilproj" />
  </ItemGroup>
</Project>
