// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_JitBlue_GitHub_1323_gitHub_1323 = coreclr_test({
    name: "GitHub_1323",
    srcs: ["GitHub_1323.cs"],
    optimize: true,
    pri: 1,
    size: "medium",
});
