<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <CLRTestPriority>1</CLRTestPriority>
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <DebugType>None</DebugType>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(MSBuildThisFileName).cs">
      <HasDisasmCheck>true</HasDisasmCheck>
    </Compile>
    <CLRTestEnvironmentVariable Include="DOTNET_TieredCompilation" Value="0" />
    <CLRTestEnvironmentVariable Include="DOTNET_JITMinOpts" Value="0" />
  </ItemGroup>
</Project>
