<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <CLRTestPriority>1</CLRTestPriority>
    <Optimize>True</Optimize>
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <!-- ActiveIssue https://github.com/dotnet/runtime/issues/134169 -->
    <CLRTestTargetUnsupported Condition="'$(RuntimeFlavor)' == 'coreclr' and '$(TargetOS)' == 'browser'">true</CLRTestTargetUnsupported>
    <!-- Tiered compilation is disabled in interpreter mode. -->
    <InterpreterIncompatible>true</InterpreterIncompatible>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(MSBuildProjectName).cs" />

    <CLRTestEnvironmentVariable Include="DOTNET_TC_CallCountThreshold" Value="1" />
    <CLRTestEnvironmentVariable Include="DOTNET_TC_CallCountingDelayMs" Value="0" />
    <CLRTestEnvironmentVariable Include="DOTNET_TieredCompilation" Value="1" />
    <CLRTestEnvironmentVariable Include="DOTNET_TieredPGO" Value="1" />
  </ItemGroup>
</Project>
