# This is a wrapper yml for `runtime-extra-platforms-androidemulator.yml`,
# which has all the wasm jobs. This file is essentially so we can have
# point the pipeline in azdo UI to this, and thus avoid any scheduled
# triggers

trigger: none

variables:
  - template: /eng/pipelines/common/variables.yml
  - name: enableHelixJobMonitor
    value: false

extends:
  template:  /eng/pipelines/common/templates/pipeline-with-resources.yml
  parameters:
    stages:
    - stage: Build
      jobs:
      - template: /eng/common/core-templates/job/helix-job-monitor.yml
        parameters:
          helixAccessToken: $(HelixApiAccessToken)
          timeoutInMinutes: 540
          allowNoHelixJobs: true

      - template: /eng/pipelines/extra-platforms/runtime-extra-platforms-androidemulator.yml
        parameters:
          isExtraPlatformsBuild: ${{ variables.isExtraPlatformsBuild }}
          isAndroidEmulatorOnlyBuild: ${{ variables.isAndroidEmulatorOnlyBuild }}
          isRollingBuild: ${{ variables.isRollingBuild }}
