trigger: none

variables:
  - template: /eng/pipelines/common/variables.yml
  - name: enableHelixJobMonitor
    value: true

extends:
  template:  /eng/pipelines/common/templates/pipeline-with-resources.yml
  parameters:
    stages:
    - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      - stage: EvaluatePaths
        displayName: Evaluate Paths
        jobs:
          - template: /eng/pipelines/common/evaluate-default-paths.yml

    - stage: Build
      jobs:
      - ${{ if eq(variables['enableHelixJobMonitor'], true) }}:
        - template: /eng/common/core-templates/job/helix-job-monitor.yml
          parameters:
            helixAccessToken: $(HelixApiAccessToken)
            timeoutInMinutes: 540
            allowNoHelixJobs: true

      - template: /eng/pipelines/extra-platforms/runtime-extra-platforms-wasm.yml
        parameters:
          isExtraPlatformsBuild: ${{ variables.isExtraPlatformsBuild }}
          isWasmOnlyBuild: ${{ variables.isWasmOnlyBuild }}
          isRollingBuild: ${{ variables.isRollingBuild }}
          useHelixMonitor: ${{ variables.enableHelixJobMonitor }}
          excludeNonLibTests: true
          excludeLibTests: false
