# Wrapper for the Android emulator jobs, without scheduled triggers.

trigger: none

pr:
  branches:
    include:
    - release/11.0-rc2
  paths:
    include:
    - '*'

variables:
  - template: /eng/pipelines/common/variables.yml
  - name: enableHelixJobMonitor
    value: true

extends:
  template:  /eng/pipelines/common/templates/pipeline-with-resources.yml
  parameters:
    stages:
    - stage: Build
      jobs:
      - ${{ if eq(variables['enableHelixJobMonitor'], true) }}:
        - template: /eng/common/core-templates/job/helix-job-monitor.yml
          parameters:
            helixAccessToken: $(HelixApiAccessToken)
            timeoutInMinutes: 1800
            allowNoHelixJobs: false

      - template: /eng/pipelines/extra-platforms/runtime-extra-platforms-androidemulator.yml
        parameters:
          isExtraPlatformsBuild: ${{ variables.isExtraPlatformsBuild }}
          isAndroidEmulatorOnlyBuild: ${{ variables.isAndroidEmulatorOnlyBuild }}
          isRollingBuild: ${{ variables.isRollingBuild }}
          useHelixMonitor: ${{ variables.enableHelixJobMonitor }}
