# This is a wrapper yml for `runtime-extra-platforms-ioslike.yml`, which
# has all the iOS/tvOS jobs. This file is essentially so we can have point
# the pipeline in azdo UI to this, and thus avoid any scheduled triggers

trigger: none

# To reduce the load on the pipeline, enable it only for PRs that affect Mono LLVM related code.
pr:
  branches:
    include:
    - main
    - release/*.*

  paths:
    include:
      - src/mono/mono/mini/aot-*.*
      - src/mono/mono/mini/llvm-*.*
      - src/mono/mono/mini/mini-llvm-*.*
      - src/mono/mono/mini/intrinsics.c
      - src/mono/mono/mini/simd-*.*
      - src/mono/mono/mini/decompose.c
      - src/mono/mono/mini/method-to-ir.c
      - src/mono/mono/mini/mini.c

variables:
  - template: /eng/pipelines/common/variables.yml
  - name: enableHelixJobMonitor
    value: true

extends:
  template:  /eng/pipelines/common/templates/pipeline-with-resources.yml
  parameters:
    stages:
    - stage: Build
      jobs:
      - ${{ if eq(variables['enableHelixJobMonitor'], true) }}:
        - template: /eng/common/core-templates/job/helix-job-monitor.yml
          parameters:
            helixAccessToken: $(HelixApiAccessToken)
            timeoutInMinutes: 540
            allowNoHelixJobs: true

      - template: /eng/pipelines/extra-platforms/runtime-extra-platforms-ioslike.yml
        parameters:
          useHelixMonitor: ${{ variables.enableHelixJobMonitor }}
          isExtraPlatformsBuild: ${{ variables.isExtraPlatformsBuild }}
          isiOSLikeOnlyBuild: ${{ variables.isiOSLikeOnlyBuild }}
          isRollingBuild: ${{ variables.isRollingBuild }}
