<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Needed for CLRTestTargetUnsupported, CMakeProjectReference -->
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <CLRTestTargetUnsupported Condition="'$(RuntimeFlavor)' == 'coreclr' and '$(TargetOS)' == 'browser'">true</CLRTestTargetUnsupported>
    <!-- Test requires EH-clean Main -->
    <ReferenceXUnitWrapperGenerator>false</ReferenceXUnitWrapperGenerator>    
    <CLRTestPriority>0</CLRTestPriority>
    <MonoAotIncompatible>true</MonoAotIncompatible>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="PInvokeUnhandled.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="$(TestLibraryProjectPath)" />
  </ItemGroup>
  <ItemGroup>
    <CMakeProjectReference Include="CMakeLists.txt" />
  </ItemGroup>
</Project>
