// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_CLR_x86_JIT_V1_2_M01_b02762_b02762 = coreclr_test({
    name: "b02762",
    srcs: ["b02762.cs"],
    debugType: "pdbonly",
    pri: 1,
    size: "medium",
});
