// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
// <auto-generated />
#nullable enable

namespace WasiHttpWorld.wit.Imports.wasi.io.v0_2_8;

internal interface IStreamsImports {

    /**
    * An error for input-stream and output-stream operations.
    */

    internal class StreamError {
        internal readonly byte Tag;
        private readonly object? value;

        private StreamError(byte tag, object? value) {
            this.Tag = tag;
            this.value = value;
        }

        internal static StreamError LastOperationFailed(global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error lastOperationFailed) {
            return new StreamError(Tags.LastOperationFailed, lastOperationFailed);
        }

        internal static StreamError Closed() {
            return new StreamError(Tags.Closed, null);
        }

        internal global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error AsLastOperationFailed
        {
            get
            {
                if (Tag == Tags.LastOperationFailed)
                return (global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error)value!;
                else
                throw new global::System.ArgumentException("expected LastOperationFailed, got " + Tag);
            }
        }

        internal class Tags {
            internal const byte LastOperationFailed = 0;
            internal const byte Closed = 1;
        }
    }

    /**
    * An input bytestream.
    *
    * `input-stream`s are *non-blocking* to the extent practical on underlying
    * platforms. I/O operations always return promptly; if fewer bytes are
    * promptly available than requested, they return the number of bytes promptly
    * available, which could even be zero. To wait for data to be available,
    * use the `subscribe` function to obtain a `pollable` which can be polled
    * for using `wasi:io/poll`.
    */

    internal class InputStream: global::System.IDisposable {
        internal int Handle { get; set; }

        internal readonly record struct THandle(int Handle);

        internal InputStream(THandle handle) {
            Handle = handle.Handle;
        }

        public void Dispose() {
            Dispose(true);
        }

        [global::System.Runtime.InteropServices.DllImportAttribute("wasi:io/streams@0.2.8", EntryPoint = "[resource-drop]input-stream"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
        private static extern void wasmImportResourceDrop(int p0);

        protected virtual void Dispose(bool disposing) {
            if (disposing && Handle != 0) {
                wasmImportResourceDrop(Handle);
                Handle = 0;
            }
        }

        internal  unsafe byte[] Read(ulong len)
        {
            var handle = this.Handle;

            var retArea = stackalloc uint[4];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
            StreamsImportsInterop.InputStream.ReadWasmInterop.wasmImportRead(handle, unchecked((long)(len)), ptr);

            Result<byte[], global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError> lifted6;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    var array = new byte[new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0]];
                    new global::System.Span<byte>((void*)(new global::System.Span<nint>((void*)((byte*)ptr + 4), 1)[0]), new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0]).CopyTo(new global::System.Span<byte>(array));

                    if (new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0] > 0) {
                        global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)ptr + 4), 1)[0]);
                    }

                    lifted6 = Result<byte[], global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Ok(array);
                    break;
                }
                case 1: {

                    global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError lifted;

                    switch (new global::System.Span<byte>((byte*)ptr + 4, 1)[0]) {
                        case 0: {
                            var resource = new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error(new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error.THandle(new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0]));

                            lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.LastOperationFailed(resource);
                            break;
                        }
                        case 1: {

                            lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.Closed();
                            break;
                        }

                        default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 4, 1)[0]);
                    }

                    lifted6 = Result<byte[], global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Err(lifted);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted6.IsOk)
            {
                var tmp = lifted6.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>(lifted6.AsErr!, 0);
            }

        }

        internal  unsafe byte[] BlockingRead(ulong len)
        {
            var handle = this.Handle;

            var retArea = stackalloc uint[4];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
            StreamsImportsInterop.InputStream.BlockingReadWasmInterop.wasmImportBlockingRead(handle, unchecked((long)(len)), ptr);

            Result<byte[], global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError> lifted6;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    var array = new byte[new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0]];
                    new global::System.Span<byte>((void*)(new global::System.Span<nint>((void*)((byte*)ptr + 4), 1)[0]), new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0]).CopyTo(new global::System.Span<byte>(array));

                    if (new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0] > 0) {
                        global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)ptr + 4), 1)[0]);
                    }

                    lifted6 = Result<byte[], global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Ok(array);
                    break;
                }
                case 1: {

                    global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError lifted;

                    switch (new global::System.Span<byte>((byte*)ptr + 4, 1)[0]) {
                        case 0: {
                            var resource = new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error(new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error.THandle(new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0]));

                            lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.LastOperationFailed(resource);
                            break;
                        }
                        case 1: {

                            lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.Closed();
                            break;
                        }

                        default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 4, 1)[0]);
                    }

                    lifted6 = Result<byte[], global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Err(lifted);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted6.IsOk)
            {
                var tmp = lifted6.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>(lifted6.AsErr!, 0);
            }

        }

        internal  unsafe ulong Skip(ulong len)
        {
            var handle = this.Handle;

            var retArea = stackalloc ulong[3];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 8);
            StreamsImportsInterop.InputStream.SkipWasmInterop.wasmImportSkip(handle, unchecked((long)(len)), ptr);

            Result<ulong, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError> lifted6;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted6 = Result<ulong, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Ok(unchecked((ulong)(new global::System.Span<long>((void*)((byte*)ptr + 8), 1)[0])));
                    break;
                }
                case 1: {

                    global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError lifted;

                    switch (new global::System.Span<byte>((byte*)ptr + 8, 1)[0]) {
                        case 0: {
                            var resource = new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error(new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error.THandle(new global::System.Span<int>((void*)((byte*)ptr + 12), 1)[0]));

                            lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.LastOperationFailed(resource);
                            break;
                        }
                        case 1: {

                            lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.Closed();
                            break;
                        }

                        default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 8, 1)[0]);
                    }

                    lifted6 = Result<ulong, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Err(lifted);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted6.IsOk)
            {
                var tmp = lifted6.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>(lifted6.AsErr!, 0);
            }

        }

        internal  unsafe ulong BlockingSkip(ulong len)
        {
            var handle = this.Handle;

            var retArea = stackalloc ulong[3];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 8);
            StreamsImportsInterop.InputStream.BlockingSkipWasmInterop.wasmImportBlockingSkip(handle, unchecked((long)(len)), ptr);

            Result<ulong, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError> lifted6;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted6 = Result<ulong, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Ok(unchecked((ulong)(new global::System.Span<long>((void*)((byte*)ptr + 8), 1)[0])));
                    break;
                }
                case 1: {

                    global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError lifted;

                    switch (new global::System.Span<byte>((byte*)ptr + 8, 1)[0]) {
                        case 0: {
                            var resource = new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error(new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error.THandle(new global::System.Span<int>((void*)((byte*)ptr + 12), 1)[0]));

                            lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.LastOperationFailed(resource);
                            break;
                        }
                        case 1: {

                            lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.Closed();
                            break;
                        }

                        default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 8, 1)[0]);
                    }

                    lifted6 = Result<ulong, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Err(lifted);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted6.IsOk)
            {
                var tmp = lifted6.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>(lifted6.AsErr!, 0);
            }

        }

        internal  unsafe global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IPollImports.Pollable Subscribe()
        {
            var handle = this.Handle;
            var result =  StreamsImportsInterop.InputStream.SubscribeWasmInterop.wasmImportSubscribe(handle);
            var resource = new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IPollImports.Pollable(new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IPollImports.Pollable.THandle(result));
            return resource;

        }

    }

    /**
    * An output bytestream.
    *
    * `output-stream`s are *non-blocking* to the extent practical on
    * underlying platforms. Except where specified otherwise, I/O operations also
    * always return promptly, after the number of bytes that can be written
    * promptly, which could even be zero. To wait for the stream to be ready to
    * accept data, the `subscribe` function to obtain a `pollable` which can be
    * polled for using `wasi:io/poll`.
    *
    * Dropping an `output-stream` while there's still an active write in
    * progress may result in the data being lost. Before dropping the stream,
    * be sure to fully flush your writes.
    */

    internal class OutputStream: global::System.IDisposable {
        internal int Handle { get; set; }

        internal readonly record struct THandle(int Handle);

        internal OutputStream(THandle handle) {
            Handle = handle.Handle;
        }

        public void Dispose() {
            Dispose(true);
        }

        [global::System.Runtime.InteropServices.DllImportAttribute("wasi:io/streams@0.2.8", EntryPoint = "[resource-drop]output-stream"), global::System.Runtime.InteropServices.WasmImportLinkageAttribute]
        private static extern void wasmImportResourceDrop(int p0);

        protected virtual void Dispose(bool disposing) {
            if (disposing && Handle != 0) {
                wasmImportResourceDrop(Handle);
                Handle = 0;
            }
        }

        internal  unsafe ulong CheckWrite()
        {
            var handle = this.Handle;

            var retArea = stackalloc ulong[3];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 8);
            StreamsImportsInterop.OutputStream.CheckWriteWasmInterop.wasmImportCheckWrite(handle, ptr);

            Result<ulong, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError> lifted6;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted6 = Result<ulong, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Ok(unchecked((ulong)(new global::System.Span<long>((void*)((byte*)ptr + 8), 1)[0])));
                    break;
                }
                case 1: {

                    global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError lifted;

                    switch (new global::System.Span<byte>((byte*)ptr + 8, 1)[0]) {
                        case 0: {
                            var resource = new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error(new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error.THandle(new global::System.Span<int>((void*)((byte*)ptr + 12), 1)[0]));

                            lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.LastOperationFailed(resource);
                            break;
                        }
                        case 1: {

                            lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.Closed();
                            break;
                        }

                        default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 8, 1)[0]);
                    }

                    lifted6 = Result<ulong, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Err(lifted);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted6.IsOk)
            {
                var tmp = lifted6.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>(lifted6.AsErr!, 0);
            }

        }

        internal  unsafe void Write(byte[] contents)
        {
            var cleanups = new global::System.Collections.Generic.List<global::System.Action>();
            var handle = this.Handle;

            var gcHandle = global::System.Runtime.InteropServices.GCHandle.Alloc(contents, global::System.Runtime.InteropServices.GCHandleType.Pinned);
            var listPtr = gcHandle.AddrOfPinnedObject();
            cleanups.Add(()=> gcHandle.Free());

            var retArea = stackalloc uint[4];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
            StreamsImportsInterop.OutputStream.WriteWasmInterop.wasmImportWrite(handle, (nint)listPtr, (contents).Length, ptr);

            Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError> lifted6;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted6 = Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Ok(new global::WasiHttpWorld.None());
                    break;
                }
                case 1: {

                    global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError lifted;

                    switch (new global::System.Span<byte>((byte*)ptr + 4, 1)[0]) {
                        case 0: {
                            var resource = new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error(new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error.THandle(new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0]));

                            lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.LastOperationFailed(resource);
                            break;
                        }
                        case 1: {

                            lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.Closed();
                            break;
                        }

                        default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 4, 1)[0]);
                    }

                    lifted6 = Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Err(lifted);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }
            if (lifted6.IsOk)
            {
                var tmp = lifted6.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>(lifted6.AsErr!, 0);
            }

        }

        internal  unsafe void Write(global::System.Span<byte> contents)
        {
            fixed (void* listPtr = contents)
            {
                var handle = this.Handle;

                var retArea = stackalloc uint[4];
                var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
                StreamsImportsInterop.OutputStream.WriteWasmInterop.wasmImportWrite(handle, (nint)listPtr, (contents).Length, ptr);

                Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError> lifted6;

                switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                    case 0: {

                        lifted6 = Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Ok(new global::WasiHttpWorld.None());
                        break;
                    }
                    case 1: {

                        global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError lifted;

                        switch (new global::System.Span<byte>((byte*)ptr + 4, 1)[0]) {
                            case 0: {
                                var resource = new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error(new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error.THandle(new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0]));

                                lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.LastOperationFailed(resource);
                                break;
                            }
                            case 1: {

                                lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.Closed();
                                break;
                            }

                            default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 4, 1)[0]);
                        }

                        lifted6 = Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Err(lifted);
                        break;
                    }

                    default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
                }
                if (lifted6.IsOk)
                {
                    var tmp = lifted6.AsOk;
                    return ;
                }
                else
                {
                    throw new WitException<global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>(lifted6.AsErr!, 0);
                }
            }

        }

        internal  unsafe void Write(global::System.Memory<byte> contents)
        {
            fixed (void* listPtr = contents.Span)
            {
                var handle = this.Handle;

                var retArea = stackalloc uint[4];
                var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
                StreamsImportsInterop.OutputStream.WriteWasmInterop.wasmImportWrite(handle, (nint)listPtr, (contents).Length, ptr);

                Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError> lifted6;

                switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                    case 0: {

                        lifted6 = Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Ok(new global::WasiHttpWorld.None());
                        break;
                    }
                    case 1: {

                        global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError lifted;

                        switch (new global::System.Span<byte>((byte*)ptr + 4, 1)[0]) {
                            case 0: {
                                var resource = new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error(new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error.THandle(new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0]));

                                lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.LastOperationFailed(resource);
                                break;
                            }
                            case 1: {

                                lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.Closed();
                                break;
                            }

                            default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 4, 1)[0]);
                        }

                        lifted6 = Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Err(lifted);
                        break;
                    }

                    default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
                }
                if (lifted6.IsOk)
                {
                    var tmp = lifted6.AsOk;
                    return ;
                }
                else
                {
                    throw new WitException<global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>(lifted6.AsErr!, 0);
                }
            }

        }

        internal  unsafe void BlockingWriteAndFlush(byte[] contents)
        {
            var cleanups = new global::System.Collections.Generic.List<global::System.Action>();
            var handle = this.Handle;

            var gcHandle = global::System.Runtime.InteropServices.GCHandle.Alloc(contents, global::System.Runtime.InteropServices.GCHandleType.Pinned);
            var listPtr = gcHandle.AddrOfPinnedObject();
            cleanups.Add(()=> gcHandle.Free());

            var retArea = stackalloc uint[4];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
            StreamsImportsInterop.OutputStream.BlockingWriteAndFlushWasmInterop.wasmImportBlockingWriteAndFlush(handle, (nint)listPtr, (contents).Length, ptr);

            Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError> lifted6;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted6 = Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Ok(new global::WasiHttpWorld.None());
                    break;
                }
                case 1: {

                    global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError lifted;

                    switch (new global::System.Span<byte>((byte*)ptr + 4, 1)[0]) {
                        case 0: {
                            var resource = new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error(new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error.THandle(new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0]));

                            lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.LastOperationFailed(resource);
                            break;
                        }
                        case 1: {

                            lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.Closed();
                            break;
                        }

                        default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 4, 1)[0]);
                    }

                    lifted6 = Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Err(lifted);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }

            foreach (var cleanup in cleanups)
            {
                cleanup();
            }
            if (lifted6.IsOk)
            {
                var tmp = lifted6.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>(lifted6.AsErr!, 0);
            }

        }

        internal  unsafe void BlockingWriteAndFlush(global::System.Span<byte> contents)
        {
            fixed (void* listPtr = contents)
            {
                var handle = this.Handle;

                var retArea = stackalloc uint[4];
                var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
                StreamsImportsInterop.OutputStream.BlockingWriteAndFlushWasmInterop.wasmImportBlockingWriteAndFlush(handle, (nint)listPtr, (contents).Length, ptr);

                Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError> lifted6;

                switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                    case 0: {

                        lifted6 = Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Ok(new global::WasiHttpWorld.None());
                        break;
                    }
                    case 1: {

                        global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError lifted;

                        switch (new global::System.Span<byte>((byte*)ptr + 4, 1)[0]) {
                            case 0: {
                                var resource = new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error(new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error.THandle(new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0]));

                                lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.LastOperationFailed(resource);
                                break;
                            }
                            case 1: {

                                lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.Closed();
                                break;
                            }

                            default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 4, 1)[0]);
                        }

                        lifted6 = Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Err(lifted);
                        break;
                    }

                    default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
                }
                if (lifted6.IsOk)
                {
                    var tmp = lifted6.AsOk;
                    return ;
                }
                else
                {
                    throw new WitException<global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>(lifted6.AsErr!, 0);
                }
            }

        }

        internal  unsafe void BlockingWriteAndFlush(global::System.Memory<byte> contents)
        {
            fixed (void* listPtr = contents.Span)
            {
                var handle = this.Handle;

                var retArea = stackalloc uint[4];
                var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
                StreamsImportsInterop.OutputStream.BlockingWriteAndFlushWasmInterop.wasmImportBlockingWriteAndFlush(handle, (nint)listPtr, (contents).Length, ptr);

                Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError> lifted6;

                switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                    case 0: {

                        lifted6 = Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Ok(new global::WasiHttpWorld.None());
                        break;
                    }
                    case 1: {

                        global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError lifted;

                        switch (new global::System.Span<byte>((byte*)ptr + 4, 1)[0]) {
                            case 0: {
                                var resource = new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error(new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error.THandle(new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0]));

                                lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.LastOperationFailed(resource);
                                break;
                            }
                            case 1: {

                                lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.Closed();
                                break;
                            }

                            default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 4, 1)[0]);
                        }

                        lifted6 = Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Err(lifted);
                        break;
                    }

                    default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
                }
                if (lifted6.IsOk)
                {
                    var tmp = lifted6.AsOk;
                    return ;
                }
                else
                {
                    throw new WitException<global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>(lifted6.AsErr!, 0);
                }
            }

        }

        internal  unsafe void Flush()
        {
            var handle = this.Handle;

            var retArea = stackalloc uint[4];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
            StreamsImportsInterop.OutputStream.FlushWasmInterop.wasmImportFlush(handle, ptr);

            Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError> lifted6;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted6 = Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Ok(new global::WasiHttpWorld.None());
                    break;
                }
                case 1: {

                    global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError lifted;

                    switch (new global::System.Span<byte>((byte*)ptr + 4, 1)[0]) {
                        case 0: {
                            var resource = new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error(new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error.THandle(new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0]));

                            lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.LastOperationFailed(resource);
                            break;
                        }
                        case 1: {

                            lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.Closed();
                            break;
                        }

                        default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 4, 1)[0]);
                    }

                    lifted6 = Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Err(lifted);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted6.IsOk)
            {
                var tmp = lifted6.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>(lifted6.AsErr!, 0);
            }

        }

        internal  unsafe void BlockingFlush()
        {
            var handle = this.Handle;

            var retArea = stackalloc uint[4];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
            StreamsImportsInterop.OutputStream.BlockingFlushWasmInterop.wasmImportBlockingFlush(handle, ptr);

            Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError> lifted6;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted6 = Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Ok(new global::WasiHttpWorld.None());
                    break;
                }
                case 1: {

                    global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError lifted;

                    switch (new global::System.Span<byte>((byte*)ptr + 4, 1)[0]) {
                        case 0: {
                            var resource = new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error(new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error.THandle(new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0]));

                            lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.LastOperationFailed(resource);
                            break;
                        }
                        case 1: {

                            lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.Closed();
                            break;
                        }

                        default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 4, 1)[0]);
                    }

                    lifted6 = Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Err(lifted);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted6.IsOk)
            {
                var tmp = lifted6.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>(lifted6.AsErr!, 0);
            }

        }

        internal  unsafe global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IPollImports.Pollable Subscribe()
        {
            var handle = this.Handle;
            var result =  StreamsImportsInterop.OutputStream.SubscribeWasmInterop.wasmImportSubscribe(handle);
            var resource = new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IPollImports.Pollable(new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IPollImports.Pollable.THandle(result));
            return resource;

        }

        internal  unsafe void WriteZeroes(ulong len)
        {
            var handle = this.Handle;

            var retArea = stackalloc uint[4];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
            StreamsImportsInterop.OutputStream.WriteZeroesWasmInterop.wasmImportWriteZeroes(handle, unchecked((long)(len)), ptr);

            Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError> lifted6;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted6 = Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Ok(new global::WasiHttpWorld.None());
                    break;
                }
                case 1: {

                    global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError lifted;

                    switch (new global::System.Span<byte>((byte*)ptr + 4, 1)[0]) {
                        case 0: {
                            var resource = new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error(new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error.THandle(new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0]));

                            lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.LastOperationFailed(resource);
                            break;
                        }
                        case 1: {

                            lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.Closed();
                            break;
                        }

                        default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 4, 1)[0]);
                    }

                    lifted6 = Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Err(lifted);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted6.IsOk)
            {
                var tmp = lifted6.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>(lifted6.AsErr!, 0);
            }

        }

        internal  unsafe void BlockingWriteZeroesAndFlush(ulong len)
        {
            var handle = this.Handle;

            var retArea = stackalloc uint[4];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 4);
            StreamsImportsInterop.OutputStream.BlockingWriteZeroesAndFlushWasmInterop.wasmImportBlockingWriteZeroesAndFlush(handle, unchecked((long)(len)), ptr);

            Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError> lifted6;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted6 = Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Ok(new global::WasiHttpWorld.None());
                    break;
                }
                case 1: {

                    global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError lifted;

                    switch (new global::System.Span<byte>((byte*)ptr + 4, 1)[0]) {
                        case 0: {
                            var resource = new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error(new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error.THandle(new global::System.Span<int>((void*)((byte*)ptr + 8), 1)[0]));

                            lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.LastOperationFailed(resource);
                            break;
                        }
                        case 1: {

                            lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.Closed();
                            break;
                        }

                        default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 4, 1)[0]);
                    }

                    lifted6 = Result<None, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Err(lifted);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted6.IsOk)
            {
                var tmp = lifted6.AsOk;
                return ;
            }
            else
            {
                throw new WitException<global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>(lifted6.AsErr!, 0);
            }

        }

        internal  unsafe ulong Splice(global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.InputStream src, ulong len)
        {
            var handle = this.Handle;
            var handle0 = src.Handle;

            var retArea = stackalloc ulong[3];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 8);
            StreamsImportsInterop.OutputStream.SpliceWasmInterop.wasmImportSplice(handle, handle0, unchecked((long)(len)), ptr);

            Result<ulong, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError> lifted7;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted7 = Result<ulong, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Ok(unchecked((ulong)(new global::System.Span<long>((void*)((byte*)ptr + 8), 1)[0])));
                    break;
                }
                case 1: {

                    global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError lifted;

                    switch (new global::System.Span<byte>((byte*)ptr + 8, 1)[0]) {
                        case 0: {
                            var resource = new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error(new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error.THandle(new global::System.Span<int>((void*)((byte*)ptr + 12), 1)[0]));

                            lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.LastOperationFailed(resource);
                            break;
                        }
                        case 1: {

                            lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.Closed();
                            break;
                        }

                        default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 8, 1)[0]);
                    }

                    lifted7 = Result<ulong, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Err(lifted);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted7.IsOk)
            {
                var tmp = lifted7.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>(lifted7.AsErr!, 0);
            }

        }

        internal  unsafe ulong BlockingSplice(global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.InputStream src, ulong len)
        {
            var handle = this.Handle;
            var handle0 = src.Handle;

            var retArea = stackalloc ulong[3];
            var ptr = (nint)MemoryHelper.AlignStackPtr(retArea, 8);
            StreamsImportsInterop.OutputStream.BlockingSpliceWasmInterop.wasmImportBlockingSplice(handle, handle0, unchecked((long)(len)), ptr);

            Result<ulong, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError> lifted7;

            switch (new global::System.Span<byte>((byte*)ptr + 0, 1)[0]) {
                case 0: {

                    lifted7 = Result<ulong, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Ok(unchecked((ulong)(new global::System.Span<long>((void*)((byte*)ptr + 8), 1)[0])));
                    break;
                }
                case 1: {

                    global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError lifted;

                    switch (new global::System.Span<byte>((byte*)ptr + 8, 1)[0]) {
                        case 0: {
                            var resource = new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error(new global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IErrorImports.Error.THandle(new global::System.Span<int>((void*)((byte*)ptr + 12), 1)[0]));

                            lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.LastOperationFailed(resource);
                            break;
                        }
                        case 1: {

                            lifted = global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError.Closed();
                            break;
                        }

                        default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 8, 1)[0]);
                    }

                    lifted7 = Result<ulong, global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>.Err(lifted);
                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant:" + new global::System.Span<byte>((byte*)ptr + 0, 1)[0]);
            }
            if (lifted7.IsOk)
            {
                var tmp = lifted7.AsOk;
                return tmp;
            }
            else
            {
                throw new WitException<global::WasiHttpWorld.wit.Imports.wasi.io.v0_2_8.IStreamsImports.StreamError>(lifted7.AsErr!, 0);
            }

        }

    }

}
