// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_JitBlue_Runtime_105618_runtime_105618 = coreclr_test({
    name: "Runtime_105618",
    srcs: ["Runtime_105618.cs"],
    optimize: true,
});
