<!-- Licensed to the .NET Foundation under one or more agreements. The .NET Foundation licenses this file to you under the MIT license. -->
<Project>
  <PropertyGroup>
    <WasiNativeWorkload Condition="'$(WasiNativeWorkload)' == ''">net12.0</WasiNativeWorkload>
    <WasiNativeWorkload12>true</WasiNativeWorkload12>
  </PropertyGroup>
</Project>
