<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <_Net8TargetFramework Condition="'$(NetCoreAppCurrent)' != 'net8.0' and '$(NetCoreAppPrevious)' != 'net8.0' and '$(NetCoreAppMinimum)' != 'net8.0'">net8.0;</_Net8TargetFramework>
    <TargetFrameworks>$(NetCoreAppCurrent);$(NetCoreAppPrevious);$(NetCoreAppMinimum);$(_Net8TargetFramework)netstandard2.0;$(NetFrameworkMinimum)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Microsoft.Extensions.FileSystemGlobbing.cs" />
  </ItemGroup>
</Project>
