// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

import "oaidl.idl";
import "ocidl.idl";

[
    object,
    uuid(f7199267-9821-4f5b-924b-ab5246b455cd)
]
interface INested : IDispatch
{
};

[
    uuid(f7c46a13-a1fc-4bf1-a61d-4502215c24e9)
]
library ComLibrary
{
    importlib("stdole2.tlb");
    [
        uuid(c82e4585-58bd-46e0-a76d-c0b6975e5984)
    ]
    coclass ComVisible_Nested
    {
        [default] interface INested;
    }
}
