// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

import "oaidl.idl";
import "ocidl.idl";

[
    object,
    uuid(27293cc8-7933-4fdf-9fde-653cbf9b55df)
]
interface IServer : IDispatch
{
};

[
    uuid(20151109-a0e8-46ae-b28e-8ff2c0e72166)
]
library ComLibrary
{
    importlib("stdole2.tlb");
    [
        uuid(438968CE-5950-4FBC-90B0-E64691350DF5)
    ]
    coclass Server
    {
        [default] interface IServer;
    }
}
