# This contains only iOS-simulator-specific jobs
# These are run as part of runtime-extra-platforms by default.
# But can also be triggered manually via `runtime-ioslikesimulator` name
#   /azp run runtime-ioslikesimulator

parameters:
  isExtraPlatformsBuild: false
  isiOSLikeSimulatorOnlyBuild: false
  isRollingBuild: false

jobs:

#
# iOSSimulator interp - requires AOT Compilation and Interp flags
# Build the whole product using Mono and run libraries tests
#
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/common/global-build-job.yml
    helixQueuesTemplate: /eng/pipelines/libraries/helix-queues-setup.yml
    buildConfig: Release
    runtimeFlavor: mono
    isExtraPlatformsBuild: ${{ parameters.isExtraPlatformsBuild }}
    isiOSLikeSimulatorOnlyBuild: ${{ parameters.isiOSLikeSimulatorOnlyBuild }}
    platforms:
    - iossimulator_x64
    - iossimulator_arm64
    variables:
      # map dependencies variables to local variables
      - name: librariesContainsChange
        value: $[ stageDependencies.EvaluatePaths.evaluate_paths.outputs['SetPathVars_libraries.containsChange'] ]
      - name: monoContainsChange
        value: $[ stageDependencies.EvaluatePaths.evaluate_paths.outputs['SetPathVars_mono_excluding_wasm.containsChange'] ]
    jobParameters:
      testGroup: innerloop
      nameSuffix: AllSubsets_Mono
      buildArgs: -s mono+libs+host+packs+libs.tests -c $(_BuildConfig) /p:ArchiveTests=true $(_runSmokeTestsOnlyArg) /p:RunAOTCompilation=true /p:MonoForceInterpreter=true
      timeoutInMinutes: 240
      # extra steps, run tests
      postBuildSteps:
        - template: /eng/pipelines/libraries/helix.yml
          parameters:
            creator: dotnet-bot
            interpreter: true
            testRunNamePrefixSuffix: Mono_$(_BuildConfig)

#
# iOSSimulator
# Build the whole product using Mono and run runtime tests
#
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/common/global-build-job.yml
    helixQueuesTemplate: /eng/pipelines/coreclr/templates/helix-queues-setup.yml
    buildConfig: Release
    runtimeFlavor: mono
    isExtraPlatformsBuild: ${{ parameters.isExtraPlatformsBuild }}
    isiOSLikeOnlyBuild: ${{ parameters.isiOSLikeOnlyBuild }}
    platforms:
      - iossimulator_arm64
    variables:
      - ${{ if and(eq(variables['System.TeamProject'], 'public'), eq(variables['Build.Reason'], 'PullRequest')) }}:
        - name: _HelixSource
          value: pr/dotnet/runtime/$(Build.SourceBranch)
      - ${{ if and(eq(variables['System.TeamProject'], 'public'), ne(variables['Build.Reason'], 'PullRequest')) }}:
        - name: _HelixSource
          value: ci/dotnet/runtime/$(Build.SourceBranch)
      - name: timeoutPerTestInMinutes
        value: 60
      - name: timeoutPerTestCollectionInMinutes
        value: 180
    jobParameters:
      testGroup: innerloop
      nameSuffix: AllSubsets_Mono_RuntimeTests
      buildArgs: -s mono+libs -c $(_BuildConfig)
      timeoutInMinutes: 240
      # extra steps, run tests
      extraVariablesTemplates:
        - template: /eng/pipelines/common/templates/runtimes/test-variables.yml
          parameters:
            testGroup: innerloop
      postBuildSteps:
        - template: /eng/pipelines/common/templates/runtimes/build-runtime-tests-and-send-to-helix.yml
          parameters:
            creator: dotnet-bot
            testBuildArgs: /p:DevTeamProvisioning=- /p:RunAOTCompilation=true /p:MonoForceInterpreter=true /p:BuildTestsOnHelix=true
            testRunNamePrefixSuffix: Mono_$(_BuildConfig)
            extraHelixArguments: /p:NeedsToBuildAppsOnHelix=true

#
# iOSSimulator
# Build the whole product using Native AOT and run libraries tests
#
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/common/global-build-job.yml
    helixQueuesTemplate: /eng/pipelines/libraries/helix-queues-setup.yml
    buildConfig: Release
    runtimeFlavor: coreclr
    isExtraPlatformsBuild: ${{ parameters.isExtraPlatformsBuild }}
    isiOSLikeOnlyBuild: ${{ parameters.isiOSLikeOnlyBuild }}
    platforms:
      - iossimulator_x64
      - iossimulator_arm64
    variables:
      # map dependencies variables to local variables
      - name: librariesContainsChange
        value: $[ stageDependencies.EvaluatePaths.evaluate_paths.outputs['SetPathVars_libraries.containsChange'] ]
      - name: coreclrContainsChange
        value: $[ stageDependencies.EvaluatePaths.evaluate_paths.outputs['SetPathVars_coreclr.containsChange'] ]
    jobParameters:
      testGroup: innerloop
      nameSuffix: AllSubsets_NativeAOT_Smoke
      buildArgs: --cross -s clr.alljits+clr.tools+clr.nativeaotruntime+clr.nativeaotlibs+libs+libs.tests -c $(_BuildConfig) /p:ArchiveTests=true /p:RunSmokeTestsOnly=true /p:DevTeamProvisioning=- /p:BuildTestsOnHelix=true /p:UseNativeAOTRuntime=true /p:RunAOTCompilation=false /p:ContinuousIntegrationBuild=true
      timeoutInMinutes: 180
      # extra steps, run tests
      postBuildSteps:
        - template: /eng/pipelines/libraries/helix.yml
          parameters:
            creator: dotnet-bot
            testRunNamePrefixSuffix: NativeAOT_$(_BuildConfig)
            extraHelixArguments: /p:NeedsToBuildAppsOnHelix=true

#
# iOSSimulator
# Build the whole product using CoreCLR and run libraries tests
#
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/common/global-build-job.yml
    helixQueuesTemplate: /eng/pipelines/libraries/helix-queues-setup.yml
    buildConfig: Release
    runtimeFlavor: coreclr
    isExtraPlatformsBuild: ${{ parameters.isExtraPlatformsBuild }}
    isiOSLikeSimulatorOnlyBuild: ${{ parameters.isiOSLikeSimulatorOnlyBuild }}
    platforms:
      - iossimulator_x64
      - iossimulator_arm64
    variables:
      # map dependencies variables to local variables
      - name: librariesContainsChange
        value: $[ stageDependencies.EvaluatePaths.evaluate_paths.outputs['SetPathVars_libraries.containsChange'] ]
      - name: coreclrContainsChange
        value: $[ stageDependencies.EvaluatePaths.evaluate_paths.outputs['SetPathVars_coreclr.containsChange'] ]
      - name: illinkContainsChange
        value: $[ stageDependencies.EvaluatePaths.evaluate_paths.outputs['SetPathVars_tools_illink.containsChange'] ]
    jobParameters:
      testGroup: innerloop
      nameSuffix: AllSubsets_CoreCLR
      buildArgs: -s clr+clr.runtime+libs+packs+libs.tests -c $(_BuildConfig) /p:ArchiveTests=true $(_runSmokeTestsOnlyArg) /p:UseMonoRuntime=false /p:UseNativeAOTRuntime=false /p:BuildTestsOnHelix=true /p:EnableAdditionalTimezoneChecks=true /p:EnableAggressiveTrimming=true
      timeoutInMinutes: 240
      # extra steps, run tests
      postBuildSteps:
        - template: /eng/pipelines/libraries/helix.yml
          parameters:
            creator: dotnet-bot
            testRunNamePrefixSuffix: CoreCLR_$(_BuildConfig)
            extraHelixArguments: /p:NeedsToBuildAppsOnHelix=true

#
# iOSSimulator
# Build the whole product using CoreCLR and run runtime tests
#
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/common/global-build-job.yml
    helixQueuesTemplate: /eng/pipelines/coreclr/templates/helix-queues-setup.yml
    buildConfig: Release
    runtimeFlavor: coreclr
    isExtraPlatformsBuild: ${{ parameters.isExtraPlatformsBuild }}
    isiOSLikeOnlyBuild: ${{ parameters.isiOSLikeOnlyBuild }}
    platforms:
      - iossimulator_arm64
    variables:
      - ${{ if and(eq(variables['System.TeamProject'], 'public'), eq(variables['Build.Reason'], 'PullRequest')) }}:
        - name: _HelixSource
          value: pr/dotnet/runtime/$(Build.SourceBranch)
      - ${{ if and(eq(variables['System.TeamProject'], 'public'), ne(variables['Build.Reason'], 'PullRequest')) }}:
        - name: _HelixSource
          value: ci/dotnet/runtime/$(Build.SourceBranch)
      - name: timeoutPerTestInMinutes
        value: 60
      - name: timeoutPerTestCollectionInMinutes
        value: 180
    jobParameters:
      testGroup: innerloop
      nameSuffix: AllSubsets_CoreCLR_RuntimeTests
      buildArgs: -s clr+libs -c $(_BuildConfig)
      timeoutInMinutes: 360
      # extra steps, run tests
      extraVariablesTemplates:
        - template: /eng/pipelines/common/templates/runtimes/test-variables.yml
          parameters:
            testGroup: innerloop
      postBuildSteps:
        - template: /eng/pipelines/common/templates/runtimes/build-runtime-tests-and-send-to-helix.yml
          parameters:
            creator: dotnet-bot
            testBuildArgs: /p:DevTeamProvisioning=- /p:UseMonoRuntime=false /p:UseNativeAOTRuntime=false /p:BuildTestsOnHelix=true
            testRunNamePrefixSuffix: CoreCLR_$(_BuildConfig)
            extraHelixArguments: /p:NeedsToBuildAppsOnHelix=true

#
# iOSSimulator
# Build the whole product using CoreCLR and run libraries smoke tests (Debug)
# Tracked in https://github.com/dotnet/runtime/issues/124344
#
# - template: /eng/pipelines/common/platform-matrix.yml
#   parameters:
#     jobTemplate: /eng/pipelines/common/global-build-job.yml
#     helixQueuesTemplate: /eng/pipelines/libraries/helix-queues-setup.yml
#     buildConfig: Debug
#     runtimeFlavor: coreclr
#     isExtraPlatformsBuild: ${{ parameters.isExtraPlatformsBuild }}
#     isiOSLikeSimulatorOnlyBuild: ${{ parameters.isiOSLikeSimulatorOnlyBuild }}
#     platforms:
#       - iossimulator_arm64
#     variables:
#       # map dependencies variables to local variables
#       - name: librariesContainsChange
#         value: $[ stageDependencies.EvaluatePaths.evaluate_paths.outputs['SetPathVars_libraries.containsChange'] ]
#       - name: coreclrContainsChange
#         value: $[ stageDependencies.EvaluatePaths.evaluate_paths.outputs['SetPathVars_coreclr.containsChange'] ]
#       - name: illinkContainsChange
#         value: $[ stageDependencies.EvaluatePaths.evaluate_paths.outputs['SetPathVars_tools_illink.containsChange'] ]
#     jobParameters:
#       testGroup: innerloop
#       nameSuffix: AllSubsets_CoreCLR_Smoke
#       buildArgs: -s clr+clr.runtime+libs+packs+libs.tests -c $(_BuildConfig) /p:ArchiveTests=true $(_runSmokeTestsOnlyArg) /p:UseMonoRuntime=false /p:UseNativeAOTRuntime=false /p:BuildTestsOnHelix=true /p:EnableAdditionalTimezoneChecks=true /p:EnableAggressiveTrimming=true
#       timeoutInMinutes: 240
#       # extra steps, run tests
#       postBuildSteps:
#         - template: /eng/pipelines/libraries/helix.yml
#           parameters:
#             creator: dotnet-bot
#             testRunNamePrefixSuffix: CoreCLR_$(_BuildConfig)
#             extraHelixArguments: /p:NeedsToBuildAppsOnHelix=true
