# This contains only Android-specific jobs
# These are run as part of runtime-extra-platforms by default.
# But can also be triggered manually via `runtime-android` name
#   /azp run runtime-android

parameters:
  isExtraPlatformsBuild: false
  isAndroidOnlyBuild: false
  isRollingBuild: false

jobs:

#
# Android devices
# Build the whole product using CoreCLR and run libraries tests
#
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/common/global-build-job.yml
    helixQueuesTemplate: /eng/pipelines/libraries/helix-queues-setup.yml
    buildConfig: Release
    runtimeFlavor: coreclr
    platforms:
    - android_arm
    - android_arm64
    variables:
      # map dependencies variables to local variables
      - name: librariesContainsChange
        value: $[ stageDependencies.EvaluatePaths.evaluate_paths.outputs['SetPathVars_libraries.containsChange'] ]
      - name: coreclrContainsChange
        value: $[ stageDependencies.EvaluatePaths.evaluate_paths.outputs['SetPathVars_coreclr.containsChange'] ]
    jobParameters:
      testGroup: innerloop
      nameSuffix: AllSubsets_CoreCLR
      isExtraPlatforms: ${{ parameters.isExtraPlatformsBuild }}
      buildArgs: -s clr.runtime+clr.alljits+clr.corelib+clr.nativecorelib+clr.tools+clr.packages+libs+libs.tests+host+packs -c $(_BuildConfig) /p:ArchiveTests=true $(_runSmokeTestsOnlyArg)
      timeoutInMinutes: 240
      # extra steps, run tests
      postBuildSteps:
        - template: /eng/pipelines/libraries/helix.yml
          parameters:
            creator: dotnet-bot
            testRunNamePrefixSuffix: CoreCLR_$(_BuildConfig)

#
# Android arm64 devices and x64 emulators
# Build the whole product using NativeAOT and run functional tests
#
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/common/global-build-job.yml
    helixQueuesTemplate: /eng/pipelines/libraries/helix-queues-setup.yml
    buildConfig: Release
    runtimeFlavor: coreclr
    platforms:
    - android_arm64
    variables:
      # map dependencies variables to local variables
      - name: librariesContainsChange
        value: $[ stageDependencies.EvaluatePaths.evaluate_paths.outputs['SetPathVars_libraries.containsChange'] ]
      - name: coreclrContainsChange
        value: $[ stageDependencies.EvaluatePaths.evaluate_paths.outputs['SetPathVars_coreclr.containsChange'] ]
    jobParameters:
      testGroup: innerloop
      nameSuffix: NativeAOT
      isExtraPlatforms: ${{ parameters.isExtraPlatformsBuild }}
      buildArgs: -s clr.aot+libs+libs.tests -c $(_BuildConfig) /p:ArchiveTests=true /p:UseNativeAOTRuntime=true /p:RuntimeFlavor=coreclr /p:TestNativeAOT=true
      timeoutInMinutes: 240
      # extra steps, run tests
      postBuildSteps:
        - template: /eng/pipelines/libraries/helix.yml
          parameters:
            creator: dotnet-bot
            testRunNamePrefixSuffix: NativeAOT_$(_BuildConfig)
