<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <CLRTestPriority>1</CLRTestPriority>
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <Optimize>True</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Runtime_134150.cs" />
    <CLRTestEnvironmentVariable Include="DOTNET_EnableAVX2" Value="0" />
    <CLRTestEnvironmentVariable Include="DOTNET_TieredCompilation" Value="0" />
  </ItemGroup>
</Project>
