// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as Rules from "Sdk.Rules";

export const nullabletypesDesktopSharedSrcs = Rules.getProvider<Rules.FilegroupResult>(Rules.filegroup({
    name: "nullabletypes_desktop_shared",
    srcs: ["StructDefinitions.cs"],
}), "FilegroupResult");

@@public
export const jIT_Directed_nullabletypes_Desktop_nullcomparaison_r = coreclr_test({
    name: "nullcomparaison_r",
    srcs: ["nullcomparaison.cs", "StructDefinitions.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Directed_nullabletypes_Desktop_boxunboxvaluetype_do = coreclr_test({
    name: "boxunboxvaluetype_do",
    srcs: ["boxunboxvaluetype.cs", "StructDefinitions.cs"],
    debugType: "full",
    optimize: true,
});

@@public
export const jIT_Directed_nullabletypes_Desktop_nullcomparaison_d = coreclr_test({
    name: "nullcomparaison_d",
    srcs: ["nullcomparaison.cs", "StructDefinitions.cs"],
    debugType: "full",
    optimize: false,
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Directed_nullabletypes_Desktop_nullcomparaison_ro = coreclr_test({
    name: "nullcomparaison_ro",
    srcs: ["nullcomparaison.cs", "StructDefinitions.cs"],
    optimize: true,
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Directed_nullabletypes_Desktop_boxunboxvaluetype_r = coreclr_test({
    name: "boxunboxvaluetype_r",
    srcs: ["boxunboxvaluetype.cs", "StructDefinitions.cs"],
});

@@public
export const jIT_Directed_nullabletypes_Desktop_nullcomparaison_do = coreclr_test({
    name: "nullcomparaison_do",
    srcs: ["nullcomparaison.cs", "StructDefinitions.cs"],
    debugType: "full",
    optimize: true,
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Directed_nullabletypes_Desktop_boxunboxvaluetype_ro = coreclr_test({
    name: "boxunboxvaluetype_ro",
    srcs: ["boxunboxvaluetype.cs", "StructDefinitions.cs"],
    optimize: true,
});
