// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
// <auto-generated />
#nullable enable

namespace WasiPollWorld.wit.Imports.wasi.clocks.v0_2_8;

internal interface IMonotonicClockImports {

    internal static unsafe ulong Now()
    {
        var result =  MonotonicClockImportsInterop.NowWasmInterop.wasmImportNow();
        return unchecked((ulong)(result));

    }

    internal static unsafe ulong Resolution()
    {
        var result =  MonotonicClockImportsInterop.ResolutionWasmInterop.wasmImportResolution();
        return unchecked((ulong)(result));

    }

    internal static unsafe global::WasiPollWorld.wit.Imports.wasi.io.v0_2_8.IPollImports.Pollable SubscribeInstant(ulong when)
    {
        var result =  MonotonicClockImportsInterop.SubscribeInstantWasmInterop.wasmImportSubscribeInstant(unchecked((long)(when)));
        var resource = new global::WasiPollWorld.wit.Imports.wasi.io.v0_2_8.IPollImports.Pollable(new global::WasiPollWorld.wit.Imports.wasi.io.v0_2_8.IPollImports.Pollable.THandle(result));
        return resource;

    }

    internal static unsafe global::WasiPollWorld.wit.Imports.wasi.io.v0_2_8.IPollImports.Pollable SubscribeDuration(ulong when)
    {
        var result =  MonotonicClockImportsInterop.SubscribeDurationWasmInterop.wasmImportSubscribeDuration(unchecked((long)(when)));
        var resource = new global::WasiPollWorld.wit.Imports.wasi.io.v0_2_8.IPollImports.Pollable(new global::WasiPollWorld.wit.Imports.wasi.io.v0_2_8.IPollImports.Pollable.THandle(result));
        return resource;

    }

}
