<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Needed for GCStressIncompatible -->
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CLRTestPriority>1</CLRTestPriority>
    <CLRTestTargetUnsupported Condition="'$(RuntimeFlavor)' == 'coreclr' and '$(TargetOS)' == 'browser' and '$(WasmEnableThreads)' != 'true'">true</CLRTestTargetUnsupported>
    <GCStressIncompatible>true</GCStressIncompatible>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="test12224.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="$(TestLibraryProjectPath)" />
  </ItemGroup>
</Project>
