<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(NetCoreAppToolCurrent)</TargetFramework>
    <Nullable>enable</Nullable>
    <!-- These tests compile and execute generated code on the build host. -->
    <UseDefaultTestHost>true</UseDefaultTestHost>
    <NetCoreAppCurrentTestHostPath>$(DotNetRoot)</NetCoreAppCurrentTestHostPath>
    <UseLocalTargetingRuntimePack>false</UseLocalTargetingRuntimePack>
    <EnableAotAnalyzer>false</EnableAotAnalyzer>
    <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="AttributeFilteringTests.cs" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="$(MicrosoftCodeAnalysisVersion_LatestVS)" />
    <ProjectReference Include="..\XUnitWrapperGenerator\XUnitWrapperGenerator.csproj" Aliases="Generator" />
    <ProjectReference Include="..\XUnitWrapperLibrary\XUnitWrapperLibrary.csproj" />
  </ItemGroup>
</Project>
