<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <MainLibraryFileName>$(MSBuildProjectName).dll</MainLibraryFileName>
    <DefineConstants>$(DefineConstants);INPROC_SCENARIO_CONSOLEONLY</DefineConstants>
  </PropertyGroup>
  <Import Project="../Shared/InProcCrashReport.Apple.props" />
</Project>
