// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_HardwareIntrinsics_X86_Pclmulqdq_V512_pclmulqdq_V512_r = coreclr_test({
    name: "Pclmulqdq.V512_r",
    srcs: ["Program.Pclmulqdq.V512.cs", ...x86SharedProgram.srcs],
    tags: ["manual"],
});

@@public
export const jIT_HardwareIntrinsics_X86_Pclmulqdq_V512_pclmulqdq_V512_ro = coreclr_test({
    name: "Pclmulqdq.V512_ro",
    srcs: ["Program.Pclmulqdq.V512.cs", ...x86SharedProgram.srcs],
    optimize: true,
    tags: ["manual"],
});
