// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_JitBlue_GitHub_12949_gitHub_12949_6 = coreclr_test({
    name: "GitHub_12949_6",
    srcs: ["GitHub_12949_6.cs"],
    allowUnsafe: true,
    optimize: true,
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Regression_JitBlue_GitHub_12949_gitHub_12949_8 = coreclr_test({
    name: "GitHub_12949_8",
    srcs: ["GitHub_12949_8.cs"],
    allowUnsafe: true,
    optimize: true,
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Regression_JitBlue_GitHub_12949_gitHub_12949_4 = coreclr_test({
    name: "GitHub_12949_4",
    srcs: ["GitHub_12949_4.cs"],
    allowUnsafe: true,
    optimize: true,
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Regression_JitBlue_GitHub_12949_gitHub_12949_1 = coreclr_test({
    name: "GitHub_12949_1",
    srcs: ["GitHub_12949_1.cs"],
    allowUnsafe: true,
    optimize: true,
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Regression_JitBlue_GitHub_12949_gitHub_12949_2 = coreclr_test({
    name: "GitHub_12949_2",
    srcs: ["GitHub_12949_2.cs"],
    allowUnsafe: true,
    optimize: true,
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Regression_JitBlue_GitHub_12949_gitHub_12949_7 = coreclr_test({
    name: "GitHub_12949_7",
    srcs: ["GitHub_12949_7.cs"],
    allowUnsafe: true,
    optimize: true,
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Regression_JitBlue_GitHub_12949_gitHub_12949_5 = coreclr_test({
    name: "GitHub_12949_5",
    srcs: ["GitHub_12949_5.cs"],
    allowUnsafe: true,
    optimize: true,
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Regression_JitBlue_GitHub_12949_gitHub_12949_3 = coreclr_test({
    name: "GitHub_12949_3",
    srcs: ["GitHub_12949_3.cs"],
    allowUnsafe: true,
    optimize: true,
    pri: 1,
    size: "medium",
});
