// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_Regression_CLR_x86_JIT_V1_M09_5_PDC_b16335_b16335 = CoreClr.coreclr_test({
    name: "b16335",
    srcs: ["b16335.cs"],
    debugType: "pdbonly",
    run: false,
});
