// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_JitBlue_GitHub_11814_gitHub_11814 = coreclr_test({
    name: "GitHub_11814",
    srcs: ["GitHub_11814.cs"],
    allowUnsafe: true,
    optimize: true,
    pri: 1,
    size: "medium",
});
