<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <CLRTestPriority>1</CLRTestPriority>
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <NativeAotIncompatible>true</NativeAotIncompatible>
    <CLRTestTargetUnsupported Condition="'$(TargetsWindows)' != 'true'">true</CLRTestTargetUnsupported>
    <CopyDebugCRTDllsToOutputDirectory>true</CopyDebugCRTDllsToOutputDirectory>
  </PropertyGroup>
  <PropertyGroup>
    <DebugType>PdbOnly</DebugType>
    <Optimize>True</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Test-TLS.cs" />
    <CMakeProjectReference Include="CMakeLists.txt" />
    <CMakeProjectReference Include="..\..\..\Interop\IJW\ijwhostmock\CMakeLists.txt" />
  </ItemGroup>
</Project>
