// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_Methodical_explicit_funcptr_seq_funcptr_gc_d = CoreClr.il_coreclr_test({
    name: "seq_funcptr_gc_d",
    srcs: ["seq_funcptr_gc_d.il", "seq_funcptr_gc.il"],
    debugType: "full",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Methodical_explicit_funcptr_expl_funcptr_gc_d = CoreClr.il_coreclr_test({
    name: "expl_funcptr_gc_d",
    srcs: ["expl_funcptr_gc_d.il", "expl_funcptr_gc.il"],
    debugType: "full",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Methodical_explicit_funcptr_expl_funcptr_val_d = CoreClr.il_coreclr_test({
    name: "expl_funcptr_val_d",
    srcs: ["expl_funcptr_val_d.il", "expl_funcptr_val.il"],
    debugType: "full",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Methodical_explicit_funcptr_seq_funcptr_val_d = CoreClr.il_coreclr_test({
    name: "seq_funcptr_val_d",
    srcs: ["seq_funcptr_val_d.il", "seq_funcptr_val.il"],
    debugType: "full",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Methodical_explicit_funcptr_expl_funcptr_gc_r = CoreClr.il_coreclr_test({
    name: "expl_funcptr_gc_r",
    srcs: ["expl_funcptr_gc_r.il", "expl_funcptr_gc.il"],
    debugType: "pdbonly",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Methodical_explicit_funcptr_seq_funcptr_val_r = CoreClr.il_coreclr_test({
    name: "seq_funcptr_val_r",
    srcs: ["seq_funcptr_val_r.il", "seq_funcptr_val.il"],
    debugType: "pdbonly",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Methodical_explicit_funcptr_expl_funcptr_val_r = CoreClr.il_coreclr_test({
    name: "expl_funcptr_val_r",
    srcs: ["expl_funcptr_val_r.il", "expl_funcptr_val.il"],
    debugType: "pdbonly",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Methodical_explicit_funcptr_seq_funcptr_gc_r = CoreClr.il_coreclr_test({
    name: "seq_funcptr_gc_r",
    srcs: ["seq_funcptr_gc_r.il", "seq_funcptr_gc.il"],
    debugType: "pdbonly",
    pri: 1,
    size: "medium",
});
