// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const regressions_coreclr_GitHub_79022_test79022 = coreclr_test({
    name: "test79022",
    srcs: ["test79022.cs"],
    pri: 1,
    size: "medium",
});
