<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Optimize>True</Optimize>
    <HasMergedInTests>true</HasMergedInTests>
  </PropertyGroup>
  <ItemGroup>
    <MergedWrapperProjectReference Include="aliasing_retbuf\aliasing_retbuf.csproj" />
    <MergedWrapperProjectReference Include="Convert\out_of_range_fp_to_int_conversions.csproj" />
    <MergedWrapperProjectReference Include="LoopAlignment\LoopsToProcess.csproj" />
    <ProjectReference Include="PREFIX\PrimitiveVT\helper.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="gettypetypeof\gettypetypeofmatrix.cs" />
    <Compile Include="PREFIX\PrimitiveVT\callconv1.cs" />
    <Compile Include="PREFIX\PrimitiveVT\callconv2.cs" />
    <Compile Include="shift\int16.cs" />
    <Compile Include="shift\int32.cs" />
    <Compile Include="shift\int64.cs" />
    <Compile Include="shift\uint16.cs" />
    <Compile Include="shift\uint32.cs" />
    <Compile Include="shift\uint64.cs" />
    <Compile Include="shift\uint64Opt.cs" />
    <Compile Include="shift\uint8.cs" />
    <Compile Include="VectorABI\VectorMgdMgd.cs" />
    <Compile Include="VectorABI\VectorMgdMgdArray.cs" />
    <Compile Include="VectorABI\VectorMgdMgdStatic.cs" />
  </ItemGroup>

  <Import Project="$(TestSourceDir)MergedTestRunner.targets" />
</Project>
