<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DebugType>None</DebugType>
    <Optimize>True</Optimize>
    <HasMergedInTests>true</HasMergedInTests>
  </PropertyGroup>
  <ItemGroup>
    <MergedWrapperProjectReference Include="array-il\_Arrayscomplex3.ilproj" />
    <MergedWrapperProjectReference Include="array-il\_Arrayssimple3.ilproj" />
    <MergedWrapperProjectReference Include="ConstantFolding\HandlesInAddrModes.ilproj" />
    <MergedWrapperProjectReference Include="Convert\ldind_conv.ilproj" />
    <MergedWrapperProjectReference Include="coverage\compiler\FilterToHandler.ilproj" />
    <MergedWrapperProjectReference Include="coverage\flowgraph\gcpoll.csproj" />
    <MergedWrapperProjectReference Include="debugging\debuginfo\tester.csproj" />
    <MergedWrapperProjectReference Include="ExcepFilters\excepobj\excepobj.ilproj" />
    <MergedWrapperProjectReference Include="ExcepFilters\fault\fault.ilproj" />
    <MergedWrapperProjectReference Include="ExcepFilters\mixed\mixed.ilproj" />
    <MergedWrapperProjectReference Include="ExcepFilters\mixed3\mixed3.ilproj" />
    <MergedWrapperProjectReference Include="FaultHandlers\CallOrder\CallOrder.ilproj" />
    <MergedWrapperProjectReference Include="FaultHandlers\Nesting\Nesting.ilproj" />
    <MergedWrapperProjectReference Include="FaultHandlers\Simple\Simple.ilproj" />
    <MergedWrapperProjectReference Include="IL\leave\leave1.ilproj" />
    <MergedWrapperProjectReference Include="IL\mutualrecur-tailcall\MutualRecur-TailCall.ilproj" />
    <MergedWrapperProjectReference Include="IL\PInvokeTail\PInvokeTail.ilproj" />
    <MergedWrapperProjectReference Include="IL\PInvokeTail\TailWinApi.ilproj" />
    <MergedWrapperProjectReference Include="IL\rethrow\Rethrow1.ilproj" />
    <MergedWrapperProjectReference Include="IL\rethrow\Rethrow2.ilproj" />
    <MergedWrapperProjectReference Include="IL\Tailcall\ExplicitTailCallNoSO.ilproj" />
    <MergedWrapperProjectReference Include="IL\Tailcall\jitTailcall1.ilproj" />
    <MergedWrapperProjectReference Include="IL\Tailcall\JitTailcall2.ilproj" />
    <MergedWrapperProjectReference Include="Misc\function_pointer\funcptrtest.ilproj" />
    <MergedWrapperProjectReference Include="Misc\SIDEEFFECTS\BadRegArgs.ilproj" />
    <MergedWrapperProjectReference Include="Misc\SIDEEFFECTS\SideEffects.ilproj" />
    <MergedWrapperProjectReference Include="pinning\object-pin\object-pin.ilproj" />
    <MergedWrapperProjectReference Include="pinvoke\calli_excep.ilproj" />
    <MergedWrapperProjectReference Include="pinvoke\jump.ilproj" />
    <MergedWrapperProjectReference Include="pinvoke\sysinfo_il.ilproj" />
    <MergedWrapperProjectReference Include="pinvoke\tail_pinvoke.ilproj" />
    <ProjectReference Include="PREFIX\PrimitiveVT\helper.csproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\1\array_tests_unaligned_1.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\1\Box_Unbox_unaligned_1.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\1\cpblk_unaligned_1.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\1\cpobj_unaligned_1.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\1\Desktop\add_Desktop_unaligned_1.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\1\field_tests_unaligned_1.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\1\fielda_tests_unaligned_1.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\1\initblk_unaligned_1.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\1\initobj_unaligned_1.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\1\ldind_stind_unaligned_1.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\1\ldloca_unaligned_1.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\1\ldobj_unaligned_1.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\1\localloc_unaligned_1.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\2\add_unaligned_2.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\2\array_tests_unaligned_2.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\2\Box_Unbox_unaligned_2.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\2\cpblk_unaligned_2.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\2\cpobj_unaligned_2.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\2\field_tests_unaligned_2.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\2\fielda_tests_unaligned_2.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\2\initblk_unaligned_2.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\2\initobj_unaligned_2.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\2\ldind_stind_unaligned_2.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\2\ldloca_unaligned_2.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\2\ldobj_unaligned_2.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\2\localloc_unaligned_2.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\4\array_tests_unaligned_4.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\4\Box_Unbox_unaligned_4.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\4\cpblk_unaligned_4.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\4\cpobj_unaligned_4.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\4\Desktop\add_Desktop_unaligned_4.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\4\field_tests_unaligned_4.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\4\fielda_tests_unaligned_4.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\4\initblk_unaligned_4.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\4\initobj_unaligned_4.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\4\ldind_stind_unaligned_4.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\4\ldloca_unaligned_4.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\4\ldobj_unaligned_4.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\4\localloc_unaligned_4.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\volatile\1\array_tests_volatile.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\volatile\1\Box_Unbox_volatile.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\volatile\1\cpblk_volatile.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\volatile\1\cpobj_volatile.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\volatile\1\Desktop\add_Desktop_volatile.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\volatile\1\field_tests_volatile.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\volatile\1\fielda_tests_volatile.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\volatile\1\initblk_volatile.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\volatile\1\initobj_volatile.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\volatile\1\ldind_stind_volatile.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\volatile\1\ldloca_volatile.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\volatile\1\ldobj_volatile.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\volatile\1\localloc_volatile.ilproj" />
    <MergedWrapperProjectReference Include="PrimitiveABI\PrimitiveABI.csproj" />
    <MergedWrapperProjectReference Include="RVAInit\extended.ilproj" />
    <MergedWrapperProjectReference Include="RVAInit\gcref1.ilproj" />
    <MergedWrapperProjectReference Include="RVAInit\gcref2.ilproj" />
    <MergedWrapperProjectReference Include="RVAInit\nested.ilproj" />
    <MergedWrapperProjectReference Include="RVAInit\oddsize.ilproj" />
    <MergedWrapperProjectReference Include="RVAInit\overlap.ilproj" />
    <MergedWrapperProjectReference Include="RVAInit\simple.ilproj" />
    <MergedWrapperProjectReference Include="RVAInit\simplearg.ilproj" />
    <MergedWrapperProjectReference Include="rvastatics\RVAOrderingTest.ilproj" />
    <MergedWrapperProjectReference Include="rvastatics\rvastatic1.ilproj" />
    <MergedWrapperProjectReference Include="rvastatics\rvastatic2.ilproj" />
    <MergedWrapperProjectReference Include="rvastatics\rvastatic3.ilproj" />
    <MergedWrapperProjectReference Include="rvastatics\rvastatic4.ilproj" />
    <MergedWrapperProjectReference Include="rvastatics\rvastatic5.ilproj" />
    <MergedWrapperProjectReference Include="StructABI\EmptyStructs.csproj" />
    <MergedWrapperProjectReference Include="StructABI\StructABI.csproj" />
    <MergedWrapperProjectReference Include="tailcall\more_tailcalls.ilproj" />
    <MergedWrapperProjectReference Include="tailcall\tailcall.ilproj" />
    <MergedWrapperProjectReference Include="throwbox\fault_throwbox.ilproj" />
    <MergedWrapperProjectReference Include="throwbox\filter.ilproj" />
    <MergedWrapperProjectReference Include="throwbox\finally.ilproj" />
    <MergedWrapperProjectReference Include="throwbox\rethrow.ilproj" />
    <MergedWrapperProjectReference Include="tls\mutualrecurthd-tls.ilproj" />
    <MergedWrapperProjectReference Include="tls\test-tls.ilproj" />
    <MergedWrapperProjectReference Include="tls\TestTLSWithLoadedDlls.csproj" />
    <MergedWrapperProjectReference Include="UnrollLoop\loop2_cs_ro.csproj" />
    <MergedWrapperProjectReference Include="zeroinit\Dev10_863995.ilproj" />
    <MergedWrapperProjectReference Include="zeroinit\init_byte.ilproj" />
    <MergedWrapperProjectReference Include="zeroinit\init_int32.ilproj" />
    <MergedWrapperProjectReference Include="zeroinit\init_int64.ilproj" />
    <MergedWrapperProjectReference Include="zeroinit\init_struct.ilproj" />
    <MergedWrapperProjectReference Include="zeroinit\init_uint32.ilproj" />
    <MergedWrapperProjectReference Include="zeroinit\init_uint64.ilproj" />
    <MergedWrapperProjectReference Include="zeroinit\tail_zeroinit.ilproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Arrays\complex1.cs" />
    <Compile Include="Arrays\complex2.cs" />
    <Compile Include="Arrays\LoopCloning.cs" />
    <Compile Include="Arrays\simple1.cs" />
    <Compile Include="Arrays\simple2.cs" />
    <Compile Include="BitTest\BitTest.cs" />
    <Compile Include="cmov\Bool_And_Op.cs" />
    <Compile Include="cmov\Bool_No_Op.cs" />
    <Compile Include="cmov\Bool_Or_Op.cs" />
    <Compile Include="cmov\Bool_Xor_Op.cs" />
    <Compile Include="cmov\Double_And_Op.cs" />
    <Compile Include="cmov\Double_No_Op.cs" />
    <Compile Include="cmov\Double_Or_Op.cs" />
    <Compile Include="cmov\Double_Xor_Op.cs" />
    <Compile Include="cmov\Float_And_Op.cs" />
    <Compile Include="cmov\Float_No_Op.cs" />
    <Compile Include="cmov\Float_Or_Op.cs" />
    <Compile Include="cmov\Float_Xor_Op.cs" />
    <Compile Include="cmov\Int_And_Op.cs" />
    <Compile Include="cmov\Int_No_Op.cs" />
    <Compile Include="cmov\Int_Or_Op.cs" />
    <Compile Include="cmov\Int_Xor_Op.cs" />
    <Compile Include="compare\cmp_int32.cs" />
    <Compile Include="ConstantFolding\FloatNaNCompareFolding.cs" />
    <Compile Include="ConstantFolding\folding_extends_int32_on_64_bit_hosts.cs" />
    <Compile Include="ConstantFolding\value_numbering_checked_integer_arithmetic_with_constants.cs" />
    <Compile Include="ConstantFolding\value_numbering_unordered_comparisons_of_constants.cs" />
    <Compile Include="Convert\FPZero.cs" />
    <Compile Include="Convert\value_numbering_checked_casts_of_constants_byte.cs" />
    <Compile Include="Convert\value_numbering_checked_casts_of_constants_double.cs" />
    <Compile Include="Convert\value_numbering_checked_casts_of_constants_float.cs" />
    <Compile Include="Convert\value_numbering_checked_casts_of_constants_int.cs" />
    <Compile Include="Convert\value_numbering_checked_casts_of_constants_long.cs" />
    <Compile Include="Convert\value_numbering_checked_casts_of_constants_short.cs" />
    <Compile Include="Convert\value_numbering_checked_casts_of_constants.cs" />
    <Compile Include="coverage\flowgraph\xaddmuly.cs" />
    <Compile Include="coverage\oldtests\33objref.cs" />
    <Compile Include="coverage\oldtests\cse1.cs" />
    <Compile Include="coverage\oldtests\cse2.cs" />
    <Compile Include="coverage\oldtests\lclfldadd.cs" />
    <Compile Include="coverage\oldtests\lclflddiv.cs" />
    <Compile Include="coverage\oldtests\lclfldmul.cs" />
    <Compile Include="coverage\oldtests\lclfldrem.cs" />
    <Compile Include="coverage\oldtests\lclfldsub.cs" />
    <Compile Include="forceinlining\LargeNumberOfArgs.cs" />
    <Compile Include="forceinlining\NoMetaData.cs" />
    <Compile Include="forceinlining\Recursion.cs" />
    <Compile Include="intrinsic\interlocked\cse_cmpxchg.cs" />
    <Compile Include="intrinsic\interlocked\IntrinsicTest_Overflow.cs" />
    <Compile Include="intrinsic\interlocked\nullchecksuppress.cs" />
    <Compile Include="intrinsic\interlocked\regalloc1.cs" />
    <Compile Include="intrinsic\interlocked\regalloc2.cs" />
    <Compile Include="intrinsic\pow\pow0.cs" />
    <Compile Include="intrinsic\pow\pow2.cs" />
    <Compile Include="intrinsic\pow\pow3.cs" />
    <Compile Include="lifetime\ObjBlkMemLiveness.cs" />
    <Compile Include="lifetime\PartialDefLiveness.cs" />
    <Compile Include="localloc\localloc3.cs" />
    <Compile Include="Misc\Concat\ConcatTest.cs" />
    <Compile Include="Misc\gettype\gettypetypeofmatrix.cs" />
    <Compile Include="newarr\newarr.cs" />
    <Compile Include="nullabletypes\boxunboxenum.cs" />
    <Compile Include="nullabletypes\boxunboxinterface.cs" />
    <Compile Include="nullabletypes\castclassenum.cs" />
    <Compile Include="nullabletypes\castclassinterface.cs" />
    <Compile Include="nullabletypes\castclassvaluetype.cs" />
    <Compile Include="nullabletypes\constructor.cs" />
    <Compile Include="nullabletypes\Desktop\boxunboxvaluetype.cs" />
    <Compile Include="nullabletypes\Desktop\nullcomparaison.cs" />
    <Compile Include="nullabletypes\Desktop\StructDefinitions.cs" />
    <Compile Include="nullabletypes\gettype.cs" />
    <Compile Include="nullabletypes\hashcode.cs" />
    <Compile Include="nullabletypes\hasvalue.cs" />
    <Compile Include="nullabletypes\invocation.cs" />
    <Compile Include="nullabletypes\invokecommon.cs" />
    <Compile Include="nullabletypes\isinst.cs" />
    <Compile Include="nullabletypes\isinst2.cs" />
    <Compile Include="nullabletypes\isinstboxed.cs" />
    <Compile Include="nullabletypes\isinstenum.cs" />
    <Compile Include="nullabletypes\isinstgenerics.cs" />
    <Compile Include="nullabletypes\isinstinterface.cs" />
    <Compile Include="nullabletypes\isinstvaluetype.cs" />
    <Compile Include="nullabletypes\tostring.cs" />
    <Compile Include="nullabletypes\unboxnullable.cs" />
    <Compile Include="nullabletypes\value.cs" />
    <Compile Include="perffix\commutativecse\CCSE.cs" />
    <Compile Include="perffix\primitivevt\callconv1.cs" />
    <Compile Include="perffix\primitivevt\callconv2.cs" />
    <Compile Include="perffix\primitivevt\mixed1.cs" />
    <Compile Include="perffix\primitivevt\mixed2.cs" />
    <Compile Include="shift\int16.cs" />
    <Compile Include="shift\int32.cs" />
    <Compile Include="shift\uint16.cs" />
    <Compile Include="shift\uint32.cs" />
    <Compile Include="shift\uint8.cs" />
    <Compile Include="StrAccess\straccess1.cs" />
    <Compile Include="StrAccess\straccess2.cs" />
    <Compile Include="StrAccess\straccess3.cs" />
    <Compile Include="StructABI\FieldListByteNodeTypeMismatchX86.cs" />
    <Compile Include="StructABI\MisSizedStructs_ArmArch.cs" />
    <Compile Include="StructABI\MisSizedStructs.cs" />
    <Compile Include="StructABI\SevenByteStruct.cs" />
    <Compile Include="StructABI\StraddlingVtypeAbi.cs" />
    <Compile Include="StructABI\structfieldparam.cs" />
    <Compile Include="StructABI\structreturn.cs" />
    <Compile Include="StructABI\StructWithOverlappingFields.cs" />
    <Compile Include="StructABI\TypeMismatchedArgs.cs" />
    <Compile Include="StructPromote\FldSeqsInPromotedCpBlk.cs" />
    <Compile Include="StructPromote\SP1.cs" />
    <Compile Include="StructPromote\SP1a.cs" />
    <Compile Include="StructPromote\SP1a2.cs" />
    <Compile Include="StructPromote\SP1b.cs" />
    <Compile Include="StructPromote\SP1c.cs" />
    <Compile Include="StructPromote\SP1d.cs" />
    <Compile Include="StructPromote\SP2.cs" />
    <Compile Include="StructPromote\SP2a.cs" />
    <Compile Include="StructPromote\SP2b.cs" />
    <Compile Include="StructPromote\SP2c.cs" />
    <Compile Include="StructPromote\SpAddr.cs" />
    <Compile Include="StructPromote\SpAddrAT.cs" />
    <Compile Include="StructPromote\Unsafe\AccessInvalidFieldOffset.cs" />
    <Compile Include="StructPromote\Unsafe\ReadDoubleFromIntOffset.cs" />
    <Compile Include="StructPromote\Unsafe\ReadStructAsAnotherType.cs" />
    <Compile Include="TypedReference\TypedReference.cs" />
    <Compile Include="UnrollLoop\loop1.cs" />
    <Compile Include="UnrollLoop\loop4.cs" />
    <Compile Include="UnrollLoop\loop6.cs" />
  </ItemGroup>

  <Import Project="$(TestSourceDir)MergedTestRunner.targets" />
</Project>
