<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DebugType>PdbOnly</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <MergedWrapperProjectReference Include="arglist\vararg_TargetWindows.csproj" />
    <MergedWrapperProjectReference Include="Arrays\Complex1.csproj" />
    <MergedWrapperProjectReference Include="Arrays\Complex2.csproj" />
    <MergedWrapperProjectReference Include="Arrays\LoopCloning.csproj" />
    <MergedWrapperProjectReference Include="Arrays\Simple1.csproj" />
    <MergedWrapperProjectReference Include="Arrays\Simple2.csproj" />
    <MergedWrapperProjectReference Include="Convert\implicitConv.ilproj" />
    <MergedWrapperProjectReference Include="Convert\minopts_convu1.ilproj" />
    <MergedWrapperProjectReference Include="Convert\signed_overflow_conversions_are_not_treated_as_unsigned.ilproj" />
    <MergedWrapperProjectReference Include="forceinlining\AttributeConflict.ilproj" />
    <MergedWrapperProjectReference Include="forceinlining\LargeNumberOfArgs.csproj" />
    <MergedWrapperProjectReference Include="forceinlining\NegativeCases.ilproj" />
    <MergedWrapperProjectReference Include="forceinlining\NoMetaData.csproj" />
    <MergedWrapperProjectReference Include="forceinlining\PositiveCases.ilproj" />
    <MergedWrapperProjectReference Include="forceinlining\Recursion.csproj" />
    <MergedWrapperProjectReference Include="intrinsic\interlocked\rva_rvastatic1.ilproj" />
    <MergedWrapperProjectReference Include="intrinsic\interlocked\rva_rvastatic2.ilproj" />
    <MergedWrapperProjectReference Include="intrinsic\interlocked\rva_rvastatic3.ilproj" />
    <MergedWrapperProjectReference Include="intrinsic\interlocked\rva_rvastatic4.ilproj" />
    <MergedWrapperProjectReference Include="Misc\function_pointer\MutualThdRecur-fptr.ilproj" />
    <MergedWrapperProjectReference Include="newarr\newarr.csproj" />
    <MergedWrapperProjectReference Include="pinvoke\pinvoke-bug.csproj" />
    <MergedWrapperProjectReference Include="pinvoke\pinvoke-examples.csproj" />
    <MergedWrapperProjectReference Include="pinvoke\preemptive_cooperative.ilproj" />
    <MergedWrapperProjectReference Include="pinvoke\sin.csproj" />
    <MergedWrapperProjectReference Include="pinvoke\sysinfo_cs.csproj" />
  </ItemGroup>

  <Import Project="$(TestSourceDir)MergedTestRunner.targets" />
</Project>
