<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Optimize>False</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <MergedWrapperProjectReference Include="debugging\debuginfo\attribute.csproj" />
    <MergedWrapperProjectReference Include="PREFIX\PrimitiveVT\callconv1_PREFIX_cs_r.csproj" />
    <MergedWrapperProjectReference Include="PREFIX\PrimitiveVT\callconv2_PREFIX_cs_r.csproj" />
  </ItemGroup>

  <Import Project="$(TestSourceDir)MergedTestRunner.targets" />
</Project>
