<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DebugType>None</DebugType>
    <Optimize>True</Optimize>
    <HasMergedInTests>true</HasMergedInTests>
  </PropertyGroup>
  <ItemGroup>
    <MergedWrapperProjectReference Include="Convert\ldind_conv.ilproj" />
    <MergedWrapperProjectReference Include="coverage\flowgraph\gcpoll.csproj" />
    <ProjectReference Include="PREFIX\PrimitiveVT\helper.csproj" />
    <MergedWrapperProjectReference Include="UnrollLoop\loop2_cs_ro.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="BitTest\BitTest.cs" />
    <Compile Include="cmov\Bool_And_Op.cs" />
    <Compile Include="cmov\Bool_No_Op.cs" />
    <Compile Include="cmov\Bool_Or_Op.cs" />
    <Compile Include="cmov\Bool_Xor_Op.cs" />
    <Compile Include="cmov\Double_And_Op.cs" />
    <Compile Include="cmov\Double_No_Op.cs" />
    <Compile Include="cmov\Double_Or_Op.cs" />
    <Compile Include="cmov\Double_Xor_Op.cs" />
    <Compile Include="cmov\Float_And_Op.cs" />
    <Compile Include="cmov\Float_No_Op.cs" />
    <Compile Include="cmov\Float_Or_Op.cs" />
    <Compile Include="cmov\Float_Xor_Op.cs" />
    <Compile Include="cmov\Int_And_Op.cs" />
    <Compile Include="cmov\Int_No_Op.cs" />
    <Compile Include="cmov\Int_Or_Op.cs" />
    <Compile Include="cmov\Int_Xor_Op.cs" />
    <Compile Include="compare\cmp_int32.cs" />
    <Compile Include="ConstantFolding\FloatNaNCompareFolding.cs" />
    <Compile Include="ConstantFolding\folding_extends_int32_on_64_bit_hosts.cs" />
    <Compile Include="ConstantFolding\value_numbering_checked_integer_arithmetic_with_constants.cs" />
    <Compile Include="ConstantFolding\value_numbering_unordered_comparisons_of_constants.cs" />
    <Compile Include="Convert\value_numbering_checked_casts_of_constants_byte.cs" />
    <Compile Include="Convert\value_numbering_checked_casts_of_constants_double.cs" />
    <Compile Include="Convert\value_numbering_checked_casts_of_constants_float.cs" />
    <Compile Include="Convert\value_numbering_checked_casts_of_constants_int.cs" />
    <Compile Include="Convert\value_numbering_checked_casts_of_constants_long.cs" />
    <Compile Include="Convert\value_numbering_checked_casts_of_constants_short.cs" />
    <Compile Include="Convert\value_numbering_checked_casts_of_constants.cs" />
    <Compile Include="coverage\flowgraph\xaddmuly.cs" />
    <Compile Include="coverage\oldtests\33objref.cs" />
    <Compile Include="coverage\oldtests\cse1.cs" />
    <Compile Include="coverage\oldtests\cse2.cs" />
    <Compile Include="coverage\oldtests\lclfldadd.cs" />
    <Compile Include="coverage\oldtests\lclflddiv.cs" />
    <Compile Include="coverage\oldtests\lclfldmul.cs" />
    <Compile Include="coverage\oldtests\lclfldrem.cs" />
    <Compile Include="coverage\oldtests\lclfldsub.cs" />
    <Compile Include="intrinsic\pow\pow0.cs" />
    <Compile Include="intrinsic\pow\pow2.cs" />
    <Compile Include="intrinsic\pow\pow3.cs" />
    <Compile Include="lifetime\ObjBlkMemLiveness.cs" />
    <Compile Include="lifetime\PartialDefLiveness.cs" />
    <Compile Include="localloc\localloc3.cs" />
    <Compile Include="nullabletypes\boxunboxenum.cs" />
    <Compile Include="nullabletypes\boxunboxinterface.cs" />
    <Compile Include="nullabletypes\castclassenum.cs" />
    <Compile Include="nullabletypes\castclassinterface.cs" />
    <Compile Include="nullabletypes\castclassvaluetype.cs" />
    <Compile Include="nullabletypes\constructor.cs" />
    <Compile Include="nullabletypes\Desktop\boxunboxvaluetype.cs" />
    <Compile Include="nullabletypes\Desktop\nullcomparaison.cs" />
    <Compile Include="nullabletypes\Desktop\StructDefinitions.cs" />
    <Compile Include="nullabletypes\gettype.cs" />
    <Compile Include="nullabletypes\hashcode.cs" />
    <Compile Include="nullabletypes\hasvalue.cs" />
    <Compile Include="nullabletypes\invocation.cs" />
    <Compile Include="nullabletypes\invokecommon.cs" />
    <Compile Include="nullabletypes\isinst.cs" />
    <Compile Include="nullabletypes\isinst2.cs" />
    <Compile Include="nullabletypes\isinstboxed.cs" />
    <Compile Include="nullabletypes\isinstenum.cs" />
    <Compile Include="nullabletypes\isinstgenerics.cs" />
    <Compile Include="nullabletypes\isinstinterface.cs" />
    <Compile Include="nullabletypes\isinstvaluetype.cs" />
    <Compile Include="nullabletypes\tostring.cs" />
    <Compile Include="nullabletypes\unboxnullable.cs" />
    <Compile Include="nullabletypes\value.cs" />
    <Compile Include="perffix\commutativecse\CCSE.cs" />
    <Compile Include="perffix\primitivevt\callconv1.cs" />
    <Compile Include="perffix\primitivevt\callconv2.cs" />
    <Compile Include="perffix\primitivevt\mixed1.cs" />
    <Compile Include="perffix\primitivevt\mixed2.cs" />
    <Compile Include="shift\int16.cs" />
    <Compile Include="shift\int32.cs" />
    <Compile Include="shift\uint16.cs" />
    <Compile Include="shift\uint32.cs" />
    <Compile Include="shift\uint8.cs" />
    <Compile Include="StrAccess\straccess1.cs" />
    <Compile Include="StrAccess\straccess2.cs" />
    <Compile Include="StrAccess\straccess3.cs" />
    <Compile Include="StructABI\FieldListByteNodeTypeMismatchX86.cs" />
    <Compile Include="StructABI\structfieldparam.cs" />
    <Compile Include="StructPromote\FldSeqsInPromotedCpBlk.cs" />
    <Compile Include="StructPromote\SP1.cs" />
    <Compile Include="StructPromote\SP1a.cs" />
    <Compile Include="StructPromote\SP1a2.cs" />
    <Compile Include="StructPromote\SP1b.cs" />
    <Compile Include="StructPromote\SP1c.cs" />
    <Compile Include="StructPromote\SP1d.cs" />
    <Compile Include="StructPromote\SP2.cs" />
    <Compile Include="StructPromote\SP2a.cs" />
    <Compile Include="StructPromote\SP2b.cs" />
    <Compile Include="StructPromote\SP2c.cs" />
    <Compile Include="StructPromote\SpAddr.cs" />
    <Compile Include="StructPromote\SpAddrAT.cs" />
    <Compile Include="StructPromote\Unsafe\AccessInvalidFieldOffset.cs" />
    <Compile Include="StructPromote\Unsafe\ReadDoubleFromIntOffset.cs" />
    <Compile Include="StructPromote\Unsafe\ReadStructAsAnotherType.cs" />
    <Compile Include="UnrollLoop\loop1.cs" />
    <Compile Include="UnrollLoop\loop4.cs" />
    <Compile Include="UnrollLoop\loop6.cs" />
  </ItemGroup>

  <Import Project="$(TestSourceDir)MergedTestRunner.targets" />
</Project>
