<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DebugType>None</DebugType>
    <Optimize />
    <HasMergedInTests>true</HasMergedInTests>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="PREFIX\PrimitiveVT\helper.csproj" />
    <MergedWrapperProjectReference Include="UnrollLoop\loop2_cs_r.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="nullabletypes\constructor.cs" />
    <Compile Include="nullabletypes\hashcode.cs" />
    <Compile Include="nullabletypes\hasvalue.cs" />
    <Compile Include="nullabletypes\invocation.cs" />
    <Compile Include="nullabletypes\invokecommon.cs" />
    <Compile Include="nullabletypes\tostring.cs" />
    <Compile Include="nullabletypes\value.cs" />
    <Compile Include="perffix\primitivevt\callconv1.cs" />
    <Compile Include="perffix\primitivevt\callconv2.cs" />
  </ItemGroup>

  <Import Project="$(TestSourceDir)MergedTestRunner.targets" />
</Project>
