<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DebugType>PdbOnly</DebugType>
    <Optimize>True</Optimize>
    <HasMergedInTests>true</HasMergedInTests>
  </PropertyGroup>
  <ItemGroup>
    <MergedWrapperProjectReference Include="PREFIX\unaligned\4\Desktop\add_Desktop_unaligned_4.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\4\field_tests_unaligned_4.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\4\fielda_tests_unaligned_4.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\4\initblk_unaligned_4.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\4\initobj_unaligned_4.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\4\ldind_stind_unaligned_4.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\4\ldloca_unaligned_4.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\4\ldobj_unaligned_4.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\unaligned\4\localloc_unaligned_4.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\volatile\1\array_tests_volatile.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\volatile\1\Box_Unbox_volatile.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\volatile\1\cpblk_volatile.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\volatile\1\cpobj_volatile.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\volatile\1\Desktop\add_Desktop_volatile.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\volatile\1\field_tests_volatile.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\volatile\1\fielda_tests_volatile.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\volatile\1\initblk_volatile.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\volatile\1\initobj_volatile.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\volatile\1\ldind_stind_volatile.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\volatile\1\ldloca_volatile.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\volatile\1\ldobj_volatile.ilproj" />
    <MergedWrapperProjectReference Include="PREFIX\volatile\1\localloc_volatile.ilproj" />
    <MergedWrapperProjectReference Include="PrimitiveABI\PrimitiveABI.csproj" />
    <MergedWrapperProjectReference Include="RVAInit\extended.ilproj" />
    <MergedWrapperProjectReference Include="RVAInit\gcref1.ilproj" />
    <MergedWrapperProjectReference Include="RVAInit\gcref2.ilproj" />
    <MergedWrapperProjectReference Include="RVAInit\nested.ilproj" />
    <MergedWrapperProjectReference Include="RVAInit\oddsize.ilproj" />
    <MergedWrapperProjectReference Include="RVAInit\overlap.ilproj" />
    <MergedWrapperProjectReference Include="RVAInit\simple.ilproj" />
    <MergedWrapperProjectReference Include="RVAInit\simplearg.ilproj" />
    <MergedWrapperProjectReference Include="rvastatics\RVAOrderingTest.ilproj" />
    <MergedWrapperProjectReference Include="rvastatics\rvastatic1.ilproj" />
    <MergedWrapperProjectReference Include="rvastatics\rvastatic2.ilproj" />
    <MergedWrapperProjectReference Include="rvastatics\rvastatic3.ilproj" />
    <MergedWrapperProjectReference Include="rvastatics\rvastatic4.ilproj" />
    <MergedWrapperProjectReference Include="rvastatics\rvastatic5.ilproj" />
    <MergedWrapperProjectReference Include="StructABI\EmptyStructs.csproj" />
    <MergedWrapperProjectReference Include="StructABI\StructABI.csproj" />
    <MergedWrapperProjectReference Include="tailcall\more_tailcalls.ilproj" />
    <MergedWrapperProjectReference Include="tailcall\tailcall.ilproj" />
    <MergedWrapperProjectReference Include="throwbox\fault_throwbox.ilproj" />
    <MergedWrapperProjectReference Include="throwbox\filter.ilproj" />
    <MergedWrapperProjectReference Include="throwbox\finally.ilproj" />
    <MergedWrapperProjectReference Include="throwbox\rethrow.ilproj" />
    <MergedWrapperProjectReference Include="tls\mutualrecurthd-tls.ilproj" />
    <MergedWrapperProjectReference Include="tls\test-tls.ilproj" />
    <MergedWrapperProjectReference Include="tls\TestTLSWithLoadedDlls.csproj" />
    <MergedWrapperProjectReference Include="zeroinit\Dev10_863995.ilproj" />
    <MergedWrapperProjectReference Include="zeroinit\init_byte.ilproj" />
    <MergedWrapperProjectReference Include="zeroinit\init_int32.ilproj" />
    <MergedWrapperProjectReference Include="zeroinit\init_int64.ilproj" />
    <MergedWrapperProjectReference Include="zeroinit\init_struct.ilproj" />
    <MergedWrapperProjectReference Include="zeroinit\init_uint32.ilproj" />
    <MergedWrapperProjectReference Include="zeroinit\init_uint64.ilproj" />
    <MergedWrapperProjectReference Include="zeroinit\tail_zeroinit.ilproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="StructABI\MisSizedStructs_ArmArch.cs" />
    <Compile Include="StructABI\MisSizedStructs.cs" />
    <Compile Include="StructABI\SevenByteStruct.cs" />
    <Compile Include="StructABI\StraddlingVtypeAbi.cs" />
    <Compile Include="StructABI\structreturn.cs" />
    <Compile Include="StructABI\StructWithOverlappingFields.cs" />
    <Compile Include="StructABI\TypeMismatchedArgs.cs" />
    <Compile Include="TypedReference\TypedReference.cs" />
  </ItemGroup>

  <Import Project="$(TestSourceDir)MergedTestRunner.targets" />
</Project>
