<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DebugType>None</DebugType>
    <Optimize>True</Optimize>
    <HasMergedInTests>true</HasMergedInTests>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="PREFIX\PrimitiveVT\helper.csproj" />
    <MergedWrapperProjectReference Include="UnrollLoop\loop2_cs_ro.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="nullabletypes\Desktop\StructDefinitions.cs" />
    <Compile Include="nullabletypes\hashcode.cs" />
    <Compile Include="nullabletypes\hasvalue.cs" />
    <Compile Include="nullabletypes\invocation.cs" />
    <Compile Include="nullabletypes\invokecommon.cs" />
    <Compile Include="nullabletypes\isinst.cs" />
    <Compile Include="nullabletypes\isinst2.cs" />
    <Compile Include="nullabletypes\isinstboxed.cs" />
    <Compile Include="nullabletypes\isinstenum.cs" />
    <Compile Include="nullabletypes\isinstgenerics.cs" />
    <Compile Include="nullabletypes\isinstinterface.cs" />
    <Compile Include="nullabletypes\isinstvaluetype.cs" />
    <Compile Include="nullabletypes\tostring.cs" />
    <Compile Include="nullabletypes\unboxnullable.cs" />
    <Compile Include="nullabletypes\value.cs" />
    <Compile Include="perffix\commutativecse\CCSE.cs" />
    <Compile Include="perffix\primitivevt\callconv1.cs" />
    <Compile Include="perffix\primitivevt\callconv2.cs" />
    <Compile Include="perffix\primitivevt\mixed1.cs" />
    <Compile Include="perffix\primitivevt\mixed2.cs" />
    <Compile Include="shift\int16.cs" />
    <Compile Include="shift\int32.cs" />
    <Compile Include="shift\uint16.cs" />
    <Compile Include="shift\uint32.cs" />
    <Compile Include="shift\uint8.cs" />
    <Compile Include="StrAccess\straccess1.cs" />
    <Compile Include="StrAccess\straccess2.cs" />
    <Compile Include="StrAccess\straccess3.cs" />
    <Compile Include="StructABI\FieldListByteNodeTypeMismatchX86.cs" />
    <Compile Include="StructABI\structfieldparam.cs" />
    <Compile Include="StructPromote\FldSeqsInPromotedCpBlk.cs" />
    <Compile Include="StructPromote\SP1.cs" />
    <Compile Include="StructPromote\SP1a.cs" />
    <Compile Include="StructPromote\SP1a2.cs" />
    <Compile Include="StructPromote\SP1b.cs" />
    <Compile Include="StructPromote\SP1c.cs" />
    <Compile Include="StructPromote\SP1d.cs" />
    <Compile Include="StructPromote\SP2.cs" />
    <Compile Include="StructPromote\SP2a.cs" />
    <Compile Include="StructPromote\SP2b.cs" />
    <Compile Include="StructPromote\SP2c.cs" />
    <Compile Include="StructPromote\SpAddr.cs" />
    <Compile Include="StructPromote\SpAddrAT.cs" />
    <Compile Include="StructPromote\Unsafe\AccessInvalidFieldOffset.cs" />
    <Compile Include="StructPromote\Unsafe\ReadDoubleFromIntOffset.cs" />
    <Compile Include="StructPromote\Unsafe\ReadStructAsAnotherType.cs" />
    <Compile Include="UnrollLoop\loop1.cs" />
    <Compile Include="UnrollLoop\loop4.cs" />
    <Compile Include="UnrollLoop\loop6.cs" />
  </ItemGroup>

  <Import Project="$(TestSourceDir)MergedTestRunner.targets" />
</Project>
