<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DebugType>Full</DebugType>
    <Optimize>False</Optimize>
    <HasMergedInTests>true</HasMergedInTests>
  </PropertyGroup>
  <ItemGroup>
    <MergedWrapperProjectReference Include="coverage\importer\badendfinally.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\badtailcall.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\byrefsubbyref1.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\calli2.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\ceeillegal.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\ldelemnullarr2.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\ldfldunboxedvt.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\ldvirtftnsideeffect.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\nullsdarr.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\refanytype1.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\volatilldind.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\volatilstind.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\callipinvoke.ilproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="CheckedCtor\Generic_Test_CSharp_Base_1.cs" />
    <Compile Include="CheckedCtor\Generic_Test_CSharp_Base_2.cs" />
    <Compile Include="CheckedCtor\Generic_Test_CSharp_Base_3.cs" />
    <Compile Include="CheckedCtor\Generic_Test_CSharp_Base_4.cs" />
    <Compile Include="CheckedCtor\Generic_Test_CSharp_Base_6.cs" />
    <Compile Include="CheckedCtor\Generic_Test_CSharp_Peer_1.cs" />
    <Compile Include="CheckedCtor\Generic_Test_CSharp_Peer_2.cs" />
    <Compile Include="CheckedCtor\Generic_Test_CSharp_Peer_3.cs" />
    <Compile Include="CheckedCtor\Generic_Test_CSharp_Peer_4.cs" />
    <Compile Include="CheckedCtor\Generic_Test_CSharp_Peer_6.cs" />
    <Compile Include="CheckedCtor\Test_CSharp_Base_1.cs" />
    <Compile Include="CheckedCtor\Test_CSharp_Base_2.cs" />
    <Compile Include="CheckedCtor\Test_CSharp_Base_3.cs" />
    <Compile Include="CheckedCtor\Test_CSharp_Base_4.cs" />
    <Compile Include="CheckedCtor\Test_CSharp_Peer_1.cs" />
    <Compile Include="CheckedCtor\Test_CSharp_Peer_2.cs" />
    <Compile Include="CheckedCtor\Test_CSharp_Peer_3.cs" />
    <Compile Include="CheckedCtor\Test_CSharp_Peer_4.cs" />
    <Compile Include="cmov\Bool_And_Op.cs" />
    <Compile Include="cmov\Bool_No_Op.cs" />
    <Compile Include="cmov\Bool_Or_Op.cs" />
    <Compile Include="cmov\Bool_Xor_Op.cs" />
    <Compile Include="cmov\Double_And_Op.cs" />
    <Compile Include="cmov\Double_No_Op.cs" />
    <Compile Include="cmov\Double_Or_Op.cs" />
    <Compile Include="cmov\Double_Xor_Op.cs" />
    <Compile Include="cmov\Float_And_Op.cs" />
    <Compile Include="cmov\Float_No_Op.cs" />
    <Compile Include="cmov\Float_Or_Op.cs" />
    <Compile Include="cmov\Float_Xor_Op.cs" />
    <Compile Include="cmov\Int_And_Op.cs" />
    <Compile Include="cmov\Int_No_Op.cs" />
    <Compile Include="cmov\Int_Or_Op.cs" />
    <Compile Include="cmov\Int_Xor_Op.cs" />
    <Compile Include="compare\cmp_int32.cs" />
    <Compile Include="coverage\flowgraph\xaddmuly.cs" />
    <Compile Include="coverage\oldtests\33objref.cs" />
    <Compile Include="coverage\oldtests\cse1.cs" />
  </ItemGroup>

  <Import Project="$(TestSourceDir)MergedTestRunner.targets" />
</Project>
