<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DebugType>None</DebugType>
    <Optimize>False</Optimize>
    <HasMergedInTests>true</HasMergedInTests>
  </PropertyGroup>
  <ItemGroup>
    <MergedWrapperProjectReference Include="arglist\vararg_TargetWindows.csproj" />
    <MergedWrapperProjectReference Include="Convert\implicitConv.ilproj" />
    <MergedWrapperProjectReference Include="Convert\minopts_convu1.ilproj" />
    <MergedWrapperProjectReference Include="Convert\signed_overflow_conversions_are_not_treated_as_unsigned.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\badendfinally_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\badldsfld_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\badtailcall_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\byrefsubbyref1_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\calli2_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\ceeillegal_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\ldelemnullarr2_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\ldfldr4_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\ldfldstatic1_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\ldfldunboxedvt_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\ldvirtftnsideeffect_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\nullsdarr_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\refanytype1_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\stfldstatic1_Desktop_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\subovfun1_Desktop_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\volatilldind_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\volatilstind_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\arrgetlen_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\Desktop\callipinvoke_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\lcliimpl_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\ldfldstatic_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\ldsshrstsfld_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\ldvirtftncalli_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\ovfldiv1_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\ovfldiv2_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\ovflrem1_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\ovflrem2_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\stfldstatic1_oldtests_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\stfldstatic2_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\subbyref_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\switchdefaultonly1_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\switchdefaultonly2_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\switchdefaultonly3_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\tlstest_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\trashreg_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\volatilecpobj_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\zeroinit_r.ilproj" />
    <MergedWrapperProjectReference Include="debugging\poisoning\poison.csproj" />
    <MergedWrapperProjectReference Include="forceinlining\AttributeConflict.ilproj" />
    <MergedWrapperProjectReference Include="forceinlining\NegativeCases.ilproj" />
    <MergedWrapperProjectReference Include="forceinlining\PositiveCases.ilproj" />
    <MergedWrapperProjectReference Include="intrinsic\interlocked\rva_rvastatic1.ilproj" />
    <MergedWrapperProjectReference Include="intrinsic\interlocked\rva_rvastatic2.ilproj" />
    <MergedWrapperProjectReference Include="intrinsic\interlocked\rva_rvastatic3.ilproj" />
    <MergedWrapperProjectReference Include="intrinsic\interlocked\rva_rvastatic4.ilproj" />
    <MergedWrapperProjectReference Include="leave\catch1_r.ilproj" />
    <MergedWrapperProjectReference Include="leave\catch2_r.ilproj" />
    <MergedWrapperProjectReference Include="leave\catch3_r.ilproj" />
    <MergedWrapperProjectReference Include="leave\filter1_r.ilproj" />
    <MergedWrapperProjectReference Include="leave\filter2_r.ilproj" />
    <MergedWrapperProjectReference Include="leave\filter3_r.ilproj" />
    <MergedWrapperProjectReference Include="leave\try1_r.ilproj" />
    <MergedWrapperProjectReference Include="leave\try2_r.ilproj" />
    <MergedWrapperProjectReference Include="leave\try3_r.ilproj" />
    <MergedWrapperProjectReference Include="Misc\function_pointer\MutualThdRecur-fptr.ilproj" />
    <MergedWrapperProjectReference Include="perffix\primitivevt\callconv3_r.ilproj" />
    <MergedWrapperProjectReference Include="perffix\primitivevt\identity3_r.ilproj" />
    <MergedWrapperProjectReference Include="pinvoke\pinvoke-bug.csproj" />
    <MergedWrapperProjectReference Include="pinvoke\pinvoke-examples.csproj" />
    <MergedWrapperProjectReference Include="pinvoke\preemptive_cooperative.ilproj" />
    <MergedWrapperProjectReference Include="pinvoke\sin.csproj" />
    <MergedWrapperProjectReference Include="pinvoke\sysinfo_cs.csproj" />
    <ProjectReference Include="PREFIX\PrimitiveVT\helper.csproj" />
    <MergedWrapperProjectReference Include="refbyref\byref2iu_r.ilproj" />
    <MergedWrapperProjectReference Include="refbyref\byrefconvert_r.ilproj" />
    <MergedWrapperProjectReference Include="refbyref\ref2byref_r.ilproj" />
    <MergedWrapperProjectReference Include="refbyref\ref2iu_r.ilproj" />
    <MergedWrapperProjectReference Include="refbyref\refpinned2iu_r.ilproj" />
    <MergedWrapperProjectReference Include="shift\int8_r.ilproj" />
    <MergedWrapperProjectReference Include="shift\nativeint_r.ilproj" />
    <MergedWrapperProjectReference Include="shift\nativeuint_r.ilproj" />
    <MergedWrapperProjectReference Include="UnrollLoop\loop2_cs_r.csproj" />
    <MergedWrapperProjectReference Include="UnrollLoop\loop3_r.ilproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Arrays\complex1.cs" />
    <Compile Include="Arrays\complex2.cs" />
    <Compile Include="Arrays\LoopCloning.cs" />
    <Compile Include="Arrays\simple1.cs" />
    <Compile Include="Arrays\simple2.cs" />
    <Compile Include="cmov\Bool_And_Op.cs" />
    <Compile Include="cmov\Bool_No_Op.cs" />
    <Compile Include="cmov\Bool_Or_Op.cs" />
    <Compile Include="cmov\Bool_Xor_Op.cs" />
    <Compile Include="cmov\Double_And_Op.cs" />
    <Compile Include="cmov\Double_No_Op.cs" />
    <Compile Include="cmov\Double_Or_Op.cs" />
    <Compile Include="cmov\Double_Xor_Op.cs" />
    <Compile Include="cmov\Float_And_Op.cs" />
    <Compile Include="cmov\Float_No_Op.cs" />
    <Compile Include="cmov\Float_Or_Op.cs" />
    <Compile Include="cmov\Float_Xor_Op.cs" />
    <Compile Include="cmov\Int_And_Op.cs" />
    <Compile Include="cmov\Int_No_Op.cs" />
    <Compile Include="cmov\Int_Or_Op.cs" />
    <Compile Include="cmov\Int_Xor_Op.cs" />
    <Compile Include="compare\cmp_int32.cs" />
    <Compile Include="coverage\flowgraph\xaddmuly.cs" />
    <Compile Include="coverage\oldtests\33objref.cs" />
    <Compile Include="coverage\oldtests\cse1.cs" />
    <Compile Include="coverage\oldtests\cse2.cs" />
    <Compile Include="coverage\oldtests\lclfldadd.cs" />
    <Compile Include="coverage\oldtests\lclflddiv.cs" />
    <Compile Include="coverage\oldtests\lclfldmul.cs" />
    <Compile Include="coverage\oldtests\lclfldrem.cs" />
    <Compile Include="coverage\oldtests\lclfldsub.cs" />
    <Compile Include="forceinlining\LargeNumberOfArgs.cs" />
    <Compile Include="forceinlining\NoMetaData.cs" />
    <Compile Include="forceinlining\Recursion.cs" />
    <Compile Include="intrinsic\pow\pow0.cs" />
    <Compile Include="intrinsic\pow\pow2.cs" />
    <Compile Include="intrinsic\pow\pow3.cs" />
    <Compile Include="localloc\localloc3.cs" />
    <Compile Include="Misc\Concat\ConcatTest.cs" />
    <Compile Include="Misc\gettype\gettypetypeofmatrix.cs" />
    <Compile Include="newarr\newarr.cs" />
    <Compile Include="nullabletypes\boxunboxenum.cs" />
    <Compile Include="nullabletypes\boxunboxinterface.cs" />
    <Compile Include="nullabletypes\castclassenum.cs" />
    <Compile Include="nullabletypes\castclassinterface.cs" />
    <Compile Include="nullabletypes\castclassvaluetype.cs" />
    <Compile Include="nullabletypes\constructor.cs" />
    <Compile Include="nullabletypes\Desktop\boxunboxvaluetype.cs" />
    <Compile Include="nullabletypes\Desktop\nullcomparaison.cs" />
    <Compile Include="nullabletypes\Desktop\StructDefinitions.cs" />
    <Compile Include="nullabletypes\gettype.cs" />
    <Compile Include="nullabletypes\hashcode.cs" />
    <Compile Include="nullabletypes\hasvalue.cs" />
    <Compile Include="nullabletypes\invocation.cs" />
    <Compile Include="nullabletypes\invokecommon.cs" />
    <Compile Include="nullabletypes\isinst.cs" />
    <Compile Include="nullabletypes\isinst2.cs" />
    <Compile Include="nullabletypes\isinstboxed.cs" />
    <Compile Include="nullabletypes\isinstenum.cs" />
    <Compile Include="nullabletypes\isinstgenerics.cs" />
    <Compile Include="nullabletypes\isinstinterface.cs" />
    <Compile Include="nullabletypes\isinstvaluetype.cs" />
    <Compile Include="nullabletypes\tostring.cs" />
    <Compile Include="nullabletypes\unboxnullable.cs" />
    <Compile Include="nullabletypes\value.cs" />
    <Compile Include="perffix\commutativecse\CCSE.cs" />
    <Compile Include="perffix\primitivevt\callconv1.cs" />
    <Compile Include="perffix\primitivevt\callconv2.cs" />
    <Compile Include="perffix\primitivevt\mixed1.cs" />
    <Compile Include="perffix\primitivevt\mixed2.cs" />
    <Compile Include="shift\int16.cs" />
    <Compile Include="shift\int32.cs" />
    <Compile Include="shift\uint16.cs" />
    <Compile Include="shift\uint32.cs" />
    <Compile Include="shift\uint8.cs" />
    <Compile Include="StrAccess\straccess1.cs" />
    <Compile Include="StrAccess\straccess2.cs" />
    <Compile Include="StrAccess\straccess3.cs" />
    <Compile Include="StructABI\structfieldparam.cs" />
    <Compile Include="UnrollLoop\loop1.cs" />
    <Compile Include="UnrollLoop\loop4.cs" />
    <Compile Include="UnrollLoop\loop6.cs" />
  </ItemGroup>

  <Import Project="$(TestSourceDir)MergedTestRunner.targets" />
</Project>
