<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DebugType>Full</DebugType>
    <Optimize>False</Optimize>
    <HasMergedInTests>true</HasMergedInTests>
  </PropertyGroup>
  <ItemGroup>
    <MergedWrapperProjectReference Include="coverage\importer\badendfinally.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\badtailcall.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\byrefsubbyref1.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\calli2.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\ceeillegal.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\badendfinally_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\badldsfld_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\badtailcall_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\byrefsubbyref1_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\calli2_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\ceeillegal_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\ldelemnullarr2_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\ldfldr4_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\ldfldstatic1_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\ldfldunboxedvt_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\ldvirtftnsideeffect_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\nullsdarr_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\refanytype1_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\stfldstatic1_Desktop_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\subovfun1_Desktop_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\volatilldind_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\volatilstind_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\ldelemnullarr2.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\ldfldunboxedvt.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\ldvirtftnsideeffect.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\nullsdarr.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\refanytype1.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\stfldstatic1_importer_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\subovfun1_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\volatilldind.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\volatilstind.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\arrgetlen_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\callipinvoke.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\Desktop\callipinvoke_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\lcliimpl_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\ldfldstatic_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\ldsshrstsfld_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\ldvirtftncalli_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\ovfldiv1_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\ovfldiv2_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\ovflrem1_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\ovflrem2_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\stfldstatic1_oldtests_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\stfldstatic2_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\subbyref_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\switchdefaultonly1_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\switchdefaultonly2_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\switchdefaultonly3_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\tlstest_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\trashreg_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\volatilecpobj_d.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\zeroinit_d.ilproj" />
    <ProjectReference Include="debugging\debuginfo\attribute.csproj" />
    <ProjectReference Include="jmp\genericjmp.ilproj" />
    <MergedWrapperProjectReference Include="leave\catch1_d.ilproj" />
    <MergedWrapperProjectReference Include="leave\catch2_d.ilproj" />
    <MergedWrapperProjectReference Include="leave\catch3_d.ilproj" />
    <MergedWrapperProjectReference Include="leave\filter1_d.ilproj" />
    <MergedWrapperProjectReference Include="leave\filter2_d.ilproj" />
    <MergedWrapperProjectReference Include="leave\filter3_d.ilproj" />
    <MergedWrapperProjectReference Include="leave\try1_d.ilproj" />
    <MergedWrapperProjectReference Include="leave\try2_d.ilproj" />
    <MergedWrapperProjectReference Include="leave\try3_d.ilproj" />
    <MergedWrapperProjectReference Include="lifetime\lifetime1.csproj" />
    <MergedWrapperProjectReference Include="perffix\primitivevt\callconv3_d.ilproj" />
    <MergedWrapperProjectReference Include="perffix\primitivevt\identity3_d.ilproj" />
    <MergedWrapperProjectReference Include="perffix\primitivevt\nativeinthelper.ilproj" />
    <ProjectReference Include="PREFIX\PrimitiveVT\helper.csproj" />
    <MergedWrapperProjectReference Include="PREFIX\volatile\1\add_volatile.ilproj" />
    <MergedWrapperProjectReference Include="refbyref\byref2iu_d.ilproj" />
    <MergedWrapperProjectReference Include="refbyref\byrefconvert_d.ilproj" />
    <MergedWrapperProjectReference Include="refbyref\ref2byref_d.ilproj" />
    <MergedWrapperProjectReference Include="refbyref\ref2iu_d.ilproj" />
    <MergedWrapperProjectReference Include="refbyref\refpinned2iu_d.ilproj" />
    <MergedWrapperProjectReference Include="shift\int8_d.ilproj" />
    <MergedWrapperProjectReference Include="shift\nativeint_d.ilproj" />
    <MergedWrapperProjectReference Include="shift\nativeuint_d.ilproj" />
    <MergedWrapperProjectReference Include="UnrollLoop\loop2_cs_d.csproj" />
    <MergedWrapperProjectReference Include="UnrollLoop\loop3_d.ilproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="CheckedCtor\Generic_Test_CSharp_Base_1.cs" />
    <Compile Include="CheckedCtor\Generic_Test_CSharp_Base_2.cs" />
    <Compile Include="CheckedCtor\Generic_Test_CSharp_Base_3.cs" />
    <Compile Include="CheckedCtor\Generic_Test_CSharp_Base_4.cs" />
    <Compile Include="CheckedCtor\Generic_Test_CSharp_Base_6.cs" />
    <Compile Include="CheckedCtor\Generic_Test_CSharp_Peer_1.cs" />
    <Compile Include="CheckedCtor\Generic_Test_CSharp_Peer_2.cs" />
    <Compile Include="CheckedCtor\Generic_Test_CSharp_Peer_3.cs" />
    <Compile Include="CheckedCtor\Generic_Test_CSharp_Peer_4.cs" />
    <Compile Include="CheckedCtor\Generic_Test_CSharp_Peer_6.cs" />
    <Compile Include="CheckedCtor\Test_CSharp_Base_1.cs" />
    <Compile Include="CheckedCtor\Test_CSharp_Base_2.cs" />
    <Compile Include="CheckedCtor\Test_CSharp_Base_3.cs" />
    <Compile Include="CheckedCtor\Test_CSharp_Base_4.cs" />
    <Compile Include="CheckedCtor\Test_CSharp_Peer_1.cs" />
    <Compile Include="CheckedCtor\Test_CSharp_Peer_2.cs" />
    <Compile Include="CheckedCtor\Test_CSharp_Peer_3.cs" />
    <Compile Include="CheckedCtor\Test_CSharp_Peer_4.cs" />
    <Compile Include="cmov\Bool_And_Op.cs" />
    <Compile Include="cmov\Bool_No_Op.cs" />
    <Compile Include="cmov\Bool_Or_Op.cs" />
    <Compile Include="cmov\Bool_Xor_Op.cs" />
    <Compile Include="cmov\Double_And_Op.cs" />
    <Compile Include="cmov\Double_No_Op.cs" />
    <Compile Include="cmov\Double_Or_Op.cs" />
    <Compile Include="cmov\Double_Xor_Op.cs" />
    <Compile Include="cmov\Float_And_Op.cs" />
    <Compile Include="cmov\Float_No_Op.cs" />
    <Compile Include="cmov\Float_Or_Op.cs" />
    <Compile Include="cmov\Float_Xor_Op.cs" />
    <Compile Include="cmov\Int_And_Op.cs" />
    <Compile Include="cmov\Int_No_Op.cs" />
    <Compile Include="cmov\Int_Or_Op.cs" />
    <Compile Include="cmov\Int_Xor_Op.cs" />
    <Compile Include="compare\cmp_int32.cs" />
    <Compile Include="coverage\flowgraph\xaddmuly.cs" />
    <Compile Include="coverage\oldtests\33objref.cs" />
    <Compile Include="coverage\oldtests\cse1.cs" />
    <Compile Include="coverage\oldtests\cse2.cs" />
    <Compile Include="coverage\oldtests\lclfldadd.cs" />
    <Compile Include="coverage\oldtests\lclflddiv.cs" />
    <Compile Include="coverage\oldtests\lclfldmul.cs" />
    <Compile Include="coverage\oldtests\lclfldrem.cs" />
    <Compile Include="coverage\oldtests\lclfldsub.cs" />
    <Compile Include="intrinsic\interlocked\cmpxchg.cs" />
    <Compile Include="intrinsic\pow\pow0.cs" />
    <Compile Include="intrinsic\pow\pow1.cs" />
    <Compile Include="intrinsic\pow\pow2.cs" />
    <Compile Include="intrinsic\pow\pow3.cs" />
    <Compile Include="localloc\localloc3.cs" />
    <Compile Include="nullabletypes\boxunboxenum.cs" />
    <Compile Include="nullabletypes\boxunboxinterface.cs" />
    <Compile Include="nullabletypes\castclassenum.cs" />
    <Compile Include="nullabletypes\castclassinterface.cs" />
    <Compile Include="nullabletypes\castclassvaluetype.cs" />
    <Compile Include="nullabletypes\constructor.cs" />
    <Compile Include="nullabletypes\Desktop\nullcomparaison.cs" />
    <Compile Include="nullabletypes\Desktop\StructDefinitions.cs" />
    <Compile Include="nullabletypes\gettype.cs" />
    <Compile Include="nullabletypes\hashcode.cs" />
    <Compile Include="nullabletypes\hasvalue.cs" />
    <Compile Include="nullabletypes\invocation.cs" />
    <Compile Include="nullabletypes\invokecommon.cs" />
    <Compile Include="nullabletypes\isinst.cs" />
    <Compile Include="nullabletypes\isinst2.cs" />
    <Compile Include="nullabletypes\isinstboxed.cs" />
    <Compile Include="nullabletypes\isinstenum.cs" />
    <Compile Include="nullabletypes\isinstgenerics.cs" />
    <Compile Include="nullabletypes\isinstinterface.cs" />
    <Compile Include="nullabletypes\isinstvaluetype.cs" />
    <Compile Include="nullabletypes\tostring.cs" />
    <Compile Include="nullabletypes\unboxnullable.cs" />
    <Compile Include="nullabletypes\value.cs" />
    <Compile Include="perffix\commutativecse\CCSE.cs" />
    <Compile Include="perffix\primitivevt\callconv1.cs" />
    <Compile Include="perffix\primitivevt\callconv2.cs" />
    <Compile Include="perffix\primitivevt\mixed1.cs" />
    <Compile Include="perffix\primitivevt\mixed2.cs" />
    <Compile Include="PREFIX\PrimitiveVT\callconv1.cs" />
    <Compile Include="PREFIX\PrimitiveVT\callconv2.cs" />
    <Compile Include="shift\int16.cs" />
    <Compile Include="shift\int32.cs" />
    <Compile Include="shift\int64.cs" />
    <Compile Include="shift\uint16.cs" />
    <Compile Include="shift\uint32.cs" />
    <Compile Include="shift\uint64.cs" />
    <Compile Include="shift\uint64Opt.cs" />
    <Compile Include="shift\uint8.cs" />
    <Compile Include="StrAccess\straccess1.cs" />
    <Compile Include="StrAccess\straccess2.cs" />
    <Compile Include="StrAccess\straccess3.cs" />
    <Compile Include="UnrollLoop\Dev10_846218.cs" />
    <Compile Include="UnrollLoop\loop1.cs" />
    <Compile Include="UnrollLoop\loop4.cs" />
    <Compile Include="UnrollLoop\loop6.cs" />
    <Compile Include="VectorABI\VectorMgdMgd.cs" />
    <Compile Include="VectorABI\VectorMgdMgdArray.cs" />
    <Compile Include="VectorABI\VectorMgdMgdStatic.cs" />
  </ItemGroup>

  <Import Project="$(TestSourceDir)MergedTestRunner.targets" />
</Project>
