<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DebugType>PdbOnly</DebugType>
    <Optimize>False</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\badendfinally_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\badldsfld_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\badtailcall_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\byrefsubbyref1_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\calli2_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\ceeillegal_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\ldelemnullarr2_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\ldfldr4_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\ldfldstatic1_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\ldfldunboxedvt_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\ldvirtftnsideeffect_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\nullsdarr_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\refanytype1_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\stfldstatic1_Desktop_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\subovfun1_Desktop_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\volatilldind_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\importer\Desktop\volatilstind_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\arrgetlen_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\Desktop\callipinvoke_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\lcliimpl_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\ldfldstatic_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\ldsshrstsfld_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\ldvirtftncalli_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\ovfldiv1_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\ovfldiv2_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\ovflrem1_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\ovflrem2_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\stfldstatic1_oldtests_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\stfldstatic2_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\subbyref_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\switchdefaultonly1_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\switchdefaultonly2_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\switchdefaultonly3_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\tlstest_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\trashreg_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\volatilecpobj_r.ilproj" />
    <MergedWrapperProjectReference Include="coverage\oldtests\zeroinit_r.ilproj" />
    <MergedWrapperProjectReference Include="debugging\poisoning\poison.csproj" />
    <MergedWrapperProjectReference Include="leave\catch1_r.ilproj" />
    <MergedWrapperProjectReference Include="leave\catch2_r.ilproj" />
    <MergedWrapperProjectReference Include="leave\catch3_r.ilproj" />
    <MergedWrapperProjectReference Include="leave\filter1_r.ilproj" />
    <MergedWrapperProjectReference Include="leave\filter2_r.ilproj" />
    <MergedWrapperProjectReference Include="leave\filter3_r.ilproj" />
    <MergedWrapperProjectReference Include="leave\try1_r.ilproj" />
    <MergedWrapperProjectReference Include="leave\try2_r.ilproj" />
    <MergedWrapperProjectReference Include="leave\try3_r.ilproj" />
    <MergedWrapperProjectReference Include="perffix\primitivevt\callconv3_r.ilproj" />
    <MergedWrapperProjectReference Include="perffix\primitivevt\identity3_r.ilproj" />
    <MergedWrapperProjectReference Include="refbyref\byref2iu_r.ilproj" />
    <MergedWrapperProjectReference Include="refbyref\byrefconvert_r.ilproj" />
    <MergedWrapperProjectReference Include="refbyref\ref2byref_r.ilproj" />
    <MergedWrapperProjectReference Include="refbyref\ref2iu_r.ilproj" />
    <MergedWrapperProjectReference Include="refbyref\refpinned2iu_r.ilproj" />
    <MergedWrapperProjectReference Include="shift\int8_r.ilproj" />
    <MergedWrapperProjectReference Include="shift\nativeint_r.ilproj" />
    <MergedWrapperProjectReference Include="shift\nativeuint_r.ilproj" />
    <MergedWrapperProjectReference Include="UnrollLoop\loop3_r.ilproj" />
  </ItemGroup>

  <Import Project="$(TestSourceDir)MergedTestRunner.targets" />
</Project>
