// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_CLR_x86_JIT_V1_M12_Beta2_b49104_b49104 = il_coreclr_test({
    name: "b49104",
    srcs: ["b49104.il"],
    debugType: "pdbonly",
    optimize: true,
});
