// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.
//

#pragma warning disable

using System;
class testout1
{
    static bool static_field_bool;
    static bool sfb_false;
    static bool sfb_true;
    bool mfb;
    bool mfb_false;
    bool mfb_true;
    static bool simple_func_bool()
    {
        return true;
    }
    static bool func_sb_true()
    {
        return true;
    }
    static bool func_sb_false()
    {
        return false;
    }

    static int Sub_Funclet_0()
    {
        int True_Sum = 0;
        int False_Sum = 0;
        int index = 1;
        bool local_bool = true;
        bool lb_false = false;
        bool lb_true = true;
        testout1 t1_i = new testout1();
        bool[] ab_false = new bool[3];
        bool[] ab_true = new bool[3];
        ab_true[0] = true;
        ab_true[1] = true;
        ab_true[2] = true;

        static_field_bool = true;
        sfb_false = false;
        sfb_true = true;

        t1_i.mfb = true;
        t1_i.mfb_false = false;
        t1_i.mfb_true = true;
        if (true ? true : true) True_Sum++; else False_Sum++;
        if (true ? true : false) True_Sum++; else False_Sum++;
        if (true ? true : local_bool) True_Sum++; else False_Sum++;
        if (true ? true : static_field_bool) True_Sum++; else False_Sum++;
        if (true ? true : t1_i.mfb) True_Sum++; else False_Sum++;
        if (true ? true : simple_func_bool()) True_Sum++; else False_Sum++;
        if (true ? true : ab_true[index]) True_Sum++; else False_Sum++;
        if (true ? true : ab_false[index]) True_Sum++; else False_Sum++;
        if (true ? false : true) True_Sum++; else False_Sum++;
        if (true ? false : false) True_Sum++; else False_Sum++;
        if (true ? false : local_bool) True_Sum++; else False_Sum++;
        if (true ? false : static_field_bool) True_Sum++; else False_Sum++;
        if (true ? false : t1_i.mfb) True_Sum++; else False_Sum++;
        if (true ? false : simple_func_bool()) True_Sum++; else False_Sum++;
        if (true ? false : ab_true[index]) True_Sum++; else False_Sum++;
        if (true ? false : ab_false[index]) True_Sum++; else False_Sum++;
        if (true ? local_bool : true) True_Sum++; else False_Sum++;
        if (true ? local_bool : false) True_Sum++; else False_Sum++;
        if (true ? local_bool : local_bool) True_Sum++; else False_Sum++;
        if (true ? local_bool : static_field_bool) True_Sum++; else False_Sum++;
        if (true ? local_bool : t1_i.mfb) True_Sum++; else False_Sum++;
        if (true ? local_bool : simple_func_bool()) True_Sum++; else False_Sum++;
        if (true ? local_bool : ab_true[index]) True_Sum++; else False_Sum++;
        if (true ? local_bool : ab_false[index]) True_Sum++; else False_Sum++;
        if (true ? static_field_bool : true) True_Sum++; else False_Sum++;
        if (true ? static_field_bool : false) True_Sum++; else False_Sum++;
        if (true ? static_field_bool : local_bool) True_Sum++; else False_Sum++;
        if (true ? static_field_bool : static_field_bool) True_Sum++; else False_Sum++;
        if (true ? static_field_bool : t1_i.mfb) True_Sum++; else False_Sum++;
        if (true ? static_field_bool : simple_func_bool()) True_Sum++; else False_Sum++;
        if (true ? static_field_bool : ab_true[index]) True_Sum++; else False_Sum++;
        if (true ? static_field_bool : ab_false[index]) True_Sum++; else False_Sum++;
        if (true ? t1_i.mfb : true) True_Sum++; else False_Sum++;
        if (true ? t1_i.mfb : false) True_Sum++; else False_Sum++;
        if (true ? t1_i.mfb : local_bool) True_Sum++; else False_Sum++;
        if (true ? t1_i.mfb : static_field_bool) True_Sum++; else False_Sum++;
        if (true ? t1_i.mfb : t1_i.mfb) True_Sum++; else False_Sum++;
        if (true ? t1_i.mfb : simple_func_bool()) True_Sum++; else False_Sum++;
        if (true ? t1_i.mfb : ab_true[index]) True_Sum++; else False_Sum++;
        if (true ? t1_i.mfb : ab_false[index]) True_Sum++; else False_Sum++;
        if (true ? simple_func_bool() : true) True_Sum++; else False_Sum++;
        if (true ? simple_func_bool() : false) True_Sum++; else False_Sum++;
        if (true ? simple_func_bool() : local_bool) True_Sum++; else False_Sum++;
        if (true ? simple_func_bool() : static_field_bool) True_Sum++; else False_Sum++;
        if (true ? simple_func_bool() : t1_i.mfb) True_Sum++; else False_Sum++;
        if (true ? simple_func_bool() : simple_func_bool()) True_Sum++; else False_Sum++;
        if (true ? simple_func_bool() : ab_true[index]) True_Sum++; else False_Sum++;
        if (true ? simple_func_bool() : ab_false[index]) True_Sum++; else False_Sum++;
        if (true ? ab_true[index] : true) True_Sum++; else False_Sum++;
        if (true ? ab_true[index] : false) True_Sum++; else False_Sum++;
        if (true ? ab_true[index] : local_bool) True_Sum++; else False_Sum++;
        if (true ? ab_true[index] : static_field_bool) True_Sum++; else False_Sum++;
        if (true ? ab_true[index] : t1_i.mfb) True_Sum++; else False_Sum++;
        if (true ? ab_true[index] : simple_func_bool()) True_Sum++; else False_Sum++;
        if (true ? ab_true[index] : ab_true[index]) True_Sum++; else False_Sum++;
        if (true ? ab_true[index] : ab_false[index]) True_Sum++; else False_Sum++;
        if (true ? ab_false[index] : true) True_Sum++; else False_Sum++;
        if (true ? ab_false[index] : false) True_Sum++; else False_Sum++;
        if (true ? ab_false[index] : local_bool) True_Sum++; else False_Sum++;
        if (true ? ab_false[index] : static_field_bool) True_Sum++; else False_Sum++;
        if (true ? ab_false[index] : t1_i.mfb) True_Sum++; else False_Sum++;
        if (true ? ab_false[index] : simple_func_bool()) True_Sum++; else False_Sum++;
        if (true ? ab_false[index] : ab_true[index]) True_Sum++; else False_Sum++;
        if (true ? ab_false[index] : ab_false[index]) True_Sum++; else False_Sum++;
        if (false ? true : true) True_Sum++; else False_Sum++;
        if (false ? true : false) True_Sum++; else False_Sum++;
        if (false ? true : local_bool) True_Sum++; else False_Sum++;
        if (false ? true : static_field_bool) True_Sum++; else False_Sum++;
        if (false ? true : t1_i.mfb) True_Sum++; else False_Sum++;
        if (false ? true : simple_func_bool()) True_Sum++; else False_Sum++;
        if (false ? true : ab_true[index]) True_Sum++; else False_Sum++;
        if (false ? true : ab_false[index]) True_Sum++; else False_Sum++;
        if (false ? false : true) True_Sum++; else False_Sum++;
        if (false ? false : false) True_Sum++; else False_Sum++;
        if (false ? false : local_bool) True_Sum++; else False_Sum++;
        if (false ? false : static_field_bool) True_Sum++; else False_Sum++;
        if (false ? false : t1_i.mfb) True_Sum++; else False_Sum++;
        if (false ? false : simple_func_bool()) True_Sum++; else False_Sum++;
        if (false ? false : ab_true[index]) True_Sum++; else False_Sum++;
        if (false ? false : ab_false[index]) True_Sum++; else False_Sum++;
        if (false ? local_bool : true) True_Sum++; else False_Sum++;
        if (false ? local_bool : false) True_Sum++; else False_Sum++;
        if (false ? local_bool : local_bool) True_Sum++; else False_Sum++;
        if (false ? local_bool : static_field_bool) True_Sum++; else False_Sum++;
        if (false ? local_bool : t1_i.mfb) True_Sum++; else False_Sum++;
        if (false ? local_bool : simple_func_bool()) True_Sum++; else False_Sum++;
        if (false ? local_bool : ab_true[index]) True_Sum++; else False_Sum++;
        if (false ? local_bool : ab_false[index]) True_Sum++; else False_Sum++;
        if (false ? static_field_bool : true) True_Sum++; else False_Sum++;
        if (false ? static_field_bool : false) True_Sum++; else False_Sum++;
        if (false ? static_field_bool : local_bool) True_Sum++; else False_Sum++;
        if (false ? static_field_bool : static_field_bool) True_Sum++; else False_Sum++;
        if (false ? static_field_bool : t1_i.mfb) True_Sum++; else False_Sum++;
        if (false ? static_field_bool : simple_func_bool()) True_Sum++; else False_Sum++;
        if (false ? static_field_bool : ab_true[index]) True_Sum++; else False_Sum++;
        if (false ? static_field_bool : ab_false[index]) True_Sum++; else False_Sum++;
        if (false ? t1_i.mfb : true) True_Sum++; else False_Sum++;
        if (false ? t1_i.mfb : false) True_Sum++; else False_Sum++;
        if (false ? t1_i.mfb : local_bool) True_Sum++; else False_Sum++;
        if (false ? t1_i.mfb : static_field_bool) True_Sum++; else False_Sum++;
        if (false ? t1_i.mfb : t1_i.mfb) True_Sum++; else False_Sum++;
        if (false ? t1_i.mfb : simple_func_bool()) True_Sum++; else False_Sum++;
        if (false ? t1_i.mfb : ab_true[index]) True_Sum++; else False_Sum++;
        if (false ? t1_i.mfb : ab_false[index]) True_Sum++; else False_Sum++;
        if (false ? simple_func_bool() : true) True_Sum++; else False_Sum++;
        if (false ? simple_func_bool() : false) True_Sum++; else False_Sum++;
        if (false ? simple_func_bool() : local_bool) True_Sum++; else False_Sum++;
        if (false ? simple_func_bool() : static_field_bool) True_Sum++; else False_Sum++;
        if (false ? simple_func_bool() : t1_i.mfb) True_Sum++; else False_Sum++;
        if (false ? simple_func_bool() : simple_func_bool()) True_Sum++; else False_Sum++;
        if (false ? simple_func_bool() : ab_true[index]) True_Sum++; else False_Sum++;
        if (false ? simple_func_bool() : ab_false[index]) True_Sum++; else False_Sum++;
        if (false ? ab_true[index] : true) True_Sum++; else False_Sum++;
        if (false ? ab_true[index] : false) True_Sum++; else False_Sum++;
        if (false ? ab_true[index] : local_bool) True_Sum++; else False_Sum++;
        if (false ? ab_true[index] : static_field_bool) True_Sum++; else False_Sum++;
        if (false ? ab_true[index] : t1_i.mfb) True_Sum++; else False_Sum++;
        if (false ? ab_true[index] : simple_func_bool()) True_Sum++; else False_Sum++;
        if (false ? ab_true[index] : ab_true[index]) True_Sum++; else False_Sum++;
        if (false ? ab_true[index] : ab_false[index]) True_Sum++; else False_Sum++;
        if (false ? ab_false[index] : true) True_Sum++; else False_Sum++;
        if (false ? ab_false[index] : false) True_Sum++; else False_Sum++;
        if (false ? ab_false[index] : local_bool) True_Sum++; else False_Sum++;
        if (false ? ab_false[index] : static_field_bool) True_Sum++; else False_Sum++;
        if (false ? ab_false[index] : t1_i.mfb) True_Sum++; else False_Sum++;
        if (false ? ab_false[index] : simple_func_bool()) True_Sum++; else False_Sum++;
        if (false ? ab_false[index] : ab_true[index]) True_Sum++; else False_Sum++;
        if (false ? ab_false[index] : ab_false[index]) True_Sum++; else False_Sum++;
        if (lb_true ? true : true) True_Sum++; else False_Sum++;
        if (lb_true ? true : false) True_Sum++; else False_Sum++;
        if (lb_true ? true : local_bool) True_Sum++; else False_Sum++;
        if (lb_true ? true : static_field_bool) True_Sum++; else False_Sum++;
        if (lb_true ? true : t1_i.mfb) True_Sum++; else False_Sum++;
        if (lb_true ? true : simple_func_bool()) True_Sum++; else False_Sum++;
        if (lb_true ? true : ab_true[index]) True_Sum++; else False_Sum++;
        if (lb_true ? true : ab_false[index]) True_Sum++; else False_Sum++;
        if (lb_true ? false : true) True_Sum++; else False_Sum++;
        if (lb_true ? false : false) True_Sum++; else False_Sum++;
        if (lb_true ? false : local_bool) True_Sum++; else False_Sum++;
        if (lb_true ? false : static_field_bool) True_Sum++; else False_Sum++;
        if (lb_true ? false : t1_i.mfb) True_Sum++; else False_Sum++;
        if (lb_true ? false : simple_func_bool()) True_Sum++; else False_Sum++;
        if (lb_true ? false : ab_true[index]) True_Sum++; else False_Sum++;
        if (lb_true ? false : ab_false[index]) True_Sum++; else False_Sum++;
        if (lb_true ? local_bool : true) True_Sum++; else False_Sum++;
        if (lb_true ? local_bool : false) True_Sum++; else False_Sum++;
        if (lb_true ? local_bool : local_bool) True_Sum++; else False_Sum++;
        if (lb_true ? local_bool : static_field_bool) True_Sum++; else False_Sum++;
        if (lb_true ? local_bool : t1_i.mfb) True_Sum++; else False_Sum++;
        if (lb_true ? local_bool : simple_func_bool()) True_Sum++; else False_Sum++;
        if (lb_true ? local_bool : ab_true[index]) True_Sum++; else False_Sum++;
        if (lb_true ? local_bool : ab_false[index]) True_Sum++; else False_Sum++;
        if (lb_true ? static_field_bool : true) True_Sum++; else False_Sum++;
        if (lb_true ? static_field_bool : false) True_Sum++; else False_Sum++;
        if (lb_true ? static_field_bool : local_bool) True_Sum++; else False_Sum++;
        if (lb_true ? static_field_bool : static_field_bool) True_Sum++; else False_Sum++;
        if (lb_true ? static_field_bool : t1_i.mfb) True_Sum++; else False_Sum++;
        if (lb_true ? static_field_bool : simple_func_bool()) True_Sum++; else False_Sum++;
        if (lb_true ? static_field_bool : ab_true[index]) True_Sum++; else False_Sum++;
        if (lb_true ? static_field_bool : ab_false[index]) True_Sum++; else False_Sum++;
        if (lb_true ? t1_i.mfb : true) True_Sum++; else False_Sum++;
        if (lb_true ? t1_i.mfb : false) True_Sum++; else False_Sum++;
        if (lb_true ? t1_i.mfb : local_bool) True_Sum++; else False_Sum++;
        if (lb_true ? t1_i.mfb : static_field_bool) True_Sum++; else False_Sum++;
        if (lb_true ? t1_i.mfb : t1_i.mfb) True_Sum++; else False_Sum++;
        if (lb_true ? t1_i.mfb : simple_func_bool()) True_Sum++; else False_Sum++;
        if (lb_true ? t1_i.mfb : ab_true[index]) True_Sum++; else False_Sum++;
        if (lb_true ? t1_i.mfb : ab_false[index]) True_Sum++; else False_Sum++;
        if (lb_true ? simple_func_bool() : true) True_Sum++; else False_Sum++;
        if (lb_true ? simple_func_bool() : false) True_Sum++; else False_Sum++;
        if (lb_true ? simple_func_bool() : local_bool) True_Sum++; else False_Sum++;
        if (lb_true ? simple_func_bool() : static_field_bool) True_Sum++; else False_Sum++;
        if (lb_true ? simple_func_bool() : t1_i.mfb) True_Sum++; else False_Sum++;
        if (lb_true ? simple_func_bool() : simple_func_bool()) True_Sum++; else False_Sum++;
        if (lb_true ? simple_func_bool() : ab_true[index]) True_Sum++; else False_Sum++;
        if (lb_true ? simple_func_bool() : ab_false[index]) True_Sum++; else False_Sum++;
        if (lb_true ? ab_true[index] : true) True_Sum++; else False_Sum++;
        if (lb_true ? ab_true[index] : false) True_Sum++; else False_Sum++;
        if (lb_true ? ab_true[index] : local_bool) True_Sum++; else False_Sum++;
        if (lb_true ? ab_true[index] : static_field_bool) True_Sum++; else False_Sum++;
        if (lb_true ? ab_true[index] : t1_i.mfb) True_Sum++; else False_Sum++;
        if (lb_true ? ab_true[index] : simple_func_bool()) True_Sum++; else False_Sum++;
        if (lb_true ? ab_true[index] : ab_true[index]) True_Sum++; else False_Sum++;
        if (lb_true ? ab_true[index] : ab_false[index]) True_Sum++; else False_Sum++;
        if (lb_true ? ab_false[index] : true) True_Sum++; else False_Sum++;
        if (lb_true ? ab_false[index] : false) True_Sum++; else False_Sum++;
        if (lb_true ? ab_false[index] : local_bool) True_Sum++; else False_Sum++;
        if (lb_true ? ab_false[index] : static_field_bool) True_Sum++; else False_Sum++;
        if (lb_true ? ab_false[index] : t1_i.mfb) True_Sum++; else False_Sum++;
        if (lb_true ? ab_false[index] : simple_func_bool()) True_Sum++; else False_Sum++;
        if (lb_true ? ab_false[index] : ab_true[index]) True_Sum++; else False_Sum++;
        if (lb_true ? ab_false[index] : ab_false[index]) True_Sum++; else False_Sum++;
        if (lb_false ? true : true) True_Sum++; else False_Sum++;
        if (lb_false ? true : false) True_Sum++; else False_Sum++;
        if (lb_false ? true : local_bool) True_Sum++; else False_Sum++;
        if (lb_false ? true : static_field_bool) True_Sum++; else False_Sum++;
        if (lb_false ? true : t1_i.mfb) True_Sum++; else False_Sum++;
        if (lb_false ? true : simple_func_bool()) True_Sum++; else False_Sum++;
        if (lb_false ? true : ab_true[index]) True_Sum++; else False_Sum++;
        if (lb_false ? true : ab_false[index]) True_Sum++; else False_Sum++;
        if (lb_false ? false : true) True_Sum++; else False_Sum++;
        if (lb_false ? false : false) True_Sum++; else False_Sum++;
        if (lb_false ? false : local_bool) True_Sum++; else False_Sum++;
        if (lb_false ? false : static_field_bool) True_Sum++; else False_Sum++;
        if (lb_false ? false : t1_i.mfb) True_Sum++; else False_Sum++;
        if (lb_false ? false : simple_func_bool()) True_Sum++; else False_Sum++;
        if (lb_false ? false : ab_true[index]) True_Sum++; else False_Sum++;
        if (lb_false ? false : ab_false[index]) True_Sum++; else False_Sum++;
        if (lb_false ? local_bool : true) True_Sum++; else False_Sum++;
        if (lb_false ? local_bool : false) True_Sum++; else False_Sum++;
        if (lb_false ? local_bool : local_bool) True_Sum++; else False_Sum++;
        if (lb_false ? local_bool : static_field_bool) True_Sum++; else False_Sum++;
        if (lb_false ? local_bool : t1_i.mfb) True_Sum++; else False_Sum++;
        if (lb_false ? local_bool : simple_func_bool()) True_Sum++; else False_Sum++;
        if (lb_false ? local_bool : ab_true[index]) True_Sum++; else False_Sum++;
        if (lb_false ? local_bool : ab_false[index]) True_Sum++; else False_Sum++;
        if (lb_false ? static_field_bool : true) True_Sum++; else False_Sum++;
        if (lb_false ? static_field_bool : false) True_Sum++; else False_Sum++;
        if (lb_false ? static_field_bool : local_bool) True_Sum++; else False_Sum++;
        if (lb_false ? static_field_bool : static_field_bool) True_Sum++; else False_Sum++;
        if (lb_false ? static_field_bool : t1_i.mfb) True_Sum++; else False_Sum++;
        if (lb_false ? static_field_bool : simple_func_bool()) True_Sum++; else False_Sum++;
        if (lb_false ? static_field_bool : ab_true[index]) True_Sum++; else False_Sum++;
        if (lb_false ? static_field_bool : ab_false[index]) True_Sum++; else False_Sum++;
        if (lb_false ? t1_i.mfb : true) True_Sum++; else False_Sum++;
        if (lb_false ? t1_i.mfb : false) True_Sum++; else False_Sum++;
        if (lb_false ? t1_i.mfb : local_bool) True_Sum++; else False_Sum++;
        if (lb_false ? t1_i.mfb : static_field_bool) True_Sum++; else False_Sum++;
        if (lb_false ? t1_i.mfb : t1_i.mfb) True_Sum++; else False_Sum++;
        if (lb_false ? t1_i.mfb : simple_func_bool()) True_Sum++; else False_Sum++;
        if (lb_false ? t1_i.mfb : ab_true[index]) True_Sum++; else False_Sum++;
        if (lb_false ? t1_i.mfb : ab_false[index]) True_Sum++; else False_Sum++;
        if (lb_false ? simple_func_bool() : true) True_Sum++; else False_Sum++;
        if (lb_false ? simple_func_bool() : false) True_Sum++; else False_Sum++;
        if (lb_false ? simple_func_bool() : local_bool) True_Sum++; else False_Sum++;
        if (lb_false ? simple_func_bool() : static_field_bool) True_Sum++; else False_Sum++;
        if (lb_false ? simple_func_bool() : t1_i.mfb) True_Sum++; else False_Sum++;
        if (lb_false ? simple_func_bool() : simple_func_bool()) True_Sum++; else False_Sum++;
        if (lb_false ? simple_func_bool() : ab_true[index]) True_Sum++; else False_Sum++;
        if (lb_false ? simple_func_bool() : ab_false[index]) True_Sum++; else False_Sum++;
        if (lb_false ? ab_true[index] : true) True_Sum++; else False_Sum++;
        if (lb_false ? ab_true[index] : false) True_Sum++; else False_Sum++;
        if (lb_false ? ab_true[index] : local_bool) True_Sum++; else False_Sum++;
        if (lb_false ? ab_true[index] : static_field_bool) True_Sum++; else False_Sum++;
        if (lb_false ? ab_true[index] : t1_i.mfb) True_Sum++; else False_Sum++;
        if (lb_false ? ab_true[index] : simple_func_bool()) True_Sum++; else False_Sum++;
        if (lb_false ? ab_true[index] : ab_true[index]) True_Sum++; else False_Sum++;
        if (lb_false ? ab_true[index] : ab_false[index]) True_Sum++; else False_Sum++;
        if (lb_false ? ab_false[index] : true) True_Sum++; else False_Sum++;
        if (lb_false ? ab_false[index] : false) True_Sum++; else False_Sum++;
        if (lb_false ? ab_false[index] : local_bool) True_Sum++; else False_Sum++;
        if (lb_false ? ab_false[index] : static_field_bool) True_Sum++; else False_Sum++;
        if (lb_false ? ab_false[index] : t1_i.mfb) True_Sum++; else False_Sum++;
        if (lb_false ? ab_false[index] : simple_func_bool()) True_Sum++; else False_Sum++;
        if (lb_false ? ab_false[index] : ab_true[index]) True_Sum++; else False_Sum++;
        if (lb_false ? ab_false[index] : ab_false[index]) True_Sum++; else False_Sum++;
        return (True_Sum * 2) - False_Sum;
    }
    static int Sub_Funclet_1()
    {
        int True_Sum = 0;
        int False_Sum = 0;
        int index = 1;
        bool local_bool = true;
        bool lb_false = false;
        bool lb_true = true;
        testout1 t1_i = new testout1();
        bool[] ab_false = new bool[3];
        bool[] ab_true = new bool[3];
        ab_true[0] = true;
        ab_true[1] = true;
        ab_true[2] = true;

        static_field_bool = true;
        sfb_false = false;
        sfb_true = true;

        t1_i.mfb = true;
        t1_i.mfb_false = false;
        t1_i.mfb_true = true;
        if (sfb_true ? true : true) True_Sum++; else False_Sum++;
        if (sfb_true ? true : false) True_Sum++; else False_Sum++;
        if (sfb_true ? true : local_bool) True_Sum++; else False_Sum++;
        if (sfb_true ? true : static_field_bool) True_Sum++; else False_Sum++;
        if (sfb_true ? true : t1_i.mfb) True_Sum++; else False_Sum++;
        if (sfb_true ? true : simple_func_bool()) True_Sum++; else False_Sum++;
        if (sfb_true ? true : ab_true[index]) True_Sum++; else False_Sum++;
        if (sfb_true ? true : ab_false[index]) True_Sum++; else False_Sum++;
        if (sfb_true ? false : true) True_Sum++; else False_Sum++;
        if (sfb_true ? false : false) True_Sum++; else False_Sum++;
        if (sfb_true ? false : local_bool) True_Sum++; else False_Sum++;
        if (sfb_true ? false : static_field_bool) True_Sum++; else False_Sum++;
        if (sfb_true ? false : t1_i.mfb) True_Sum++; else False_Sum++;
        if (sfb_true ? false : simple_func_bool()) True_Sum++; else False_Sum++;
        if (sfb_true ? false : ab_true[index]) True_Sum++; else False_Sum++;
        if (sfb_true ? false : ab_false[index]) True_Sum++; else False_Sum++;
        if (sfb_true ? local_bool : true) True_Sum++; else False_Sum++;
        if (sfb_true ? local_bool : false) True_Sum++; else False_Sum++;
        if (sfb_true ? local_bool : local_bool) True_Sum++; else False_Sum++;
        if (sfb_true ? local_bool : static_field_bool) True_Sum++; else False_Sum++;
        if (sfb_true ? local_bool : t1_i.mfb) True_Sum++; else False_Sum++;
        if (sfb_true ? local_bool : simple_func_bool()) True_Sum++; else False_Sum++;
        if (sfb_true ? local_bool : ab_true[index]) True_Sum++; else False_Sum++;
        if (sfb_true ? local_bool : ab_false[index]) True_Sum++; else False_Sum++;
        if (sfb_true ? static_field_bool : true) True_Sum++; else False_Sum++;
        if (sfb_true ? static_field_bool : false) True_Sum++; else False_Sum++;
        if (sfb_true ? static_field_bool : local_bool) True_Sum++; else False_Sum++;
        if (sfb_true ? static_field_bool : static_field_bool) True_Sum++; else False_Sum++;
        if (sfb_true ? static_field_bool : t1_i.mfb) True_Sum++; else False_Sum++;
        if (sfb_true ? static_field_bool : simple_func_bool()) True_Sum++; else False_Sum++;
        if (sfb_true ? static_field_bool : ab_true[index]) True_Sum++; else False_Sum++;
        if (sfb_true ? static_field_bool : ab_false[index]) True_Sum++; else False_Sum++;
        if (sfb_true ? t1_i.mfb : true) True_Sum++; else False_Sum++;
        if (sfb_true ? t1_i.mfb : false) True_Sum++; else False_Sum++;
        if (sfb_true ? t1_i.mfb : local_bool) True_Sum++; else False_Sum++;
        if (sfb_true ? t1_i.mfb : static_field_bool) True_Sum++; else False_Sum++;
        if (sfb_true ? t1_i.mfb : t1_i.mfb) True_Sum++; else False_Sum++;
        if (sfb_true ? t1_i.mfb : simple_func_bool()) True_Sum++; else False_Sum++;
        if (sfb_true ? t1_i.mfb : ab_true[index]) True_Sum++; else False_Sum++;
        if (sfb_true ? t1_i.mfb : ab_false[index]) True_Sum++; else False_Sum++;
        if (sfb_true ? simple_func_bool() : true) True_Sum++; else False_Sum++;
        if (sfb_true ? simple_func_bool() : false) True_Sum++; else False_Sum++;
        if (sfb_true ? simple_func_bool() : local_bool) True_Sum++; else False_Sum++;
        if (sfb_true ? simple_func_bool() : static_field_bool) True_Sum++; else False_Sum++;
        if (sfb_true ? simple_func_bool() : t1_i.mfb) True_Sum++; else False_Sum++;
        if (sfb_true ? simple_func_bool() : simple_func_bool()) True_Sum++; else False_Sum++;
        if (sfb_true ? simple_func_bool() : ab_true[index]) True_Sum++; else False_Sum++;
        if (sfb_true ? simple_func_bool() : ab_false[index]) True_Sum++; else False_Sum++;
        if (sfb_true ? ab_true[index] : true) True_Sum++; else False_Sum++;
        if (sfb_true ? ab_true[index] : false) True_Sum++; else False_Sum++;
        if (sfb_true ? ab_true[index] : local_bool) True_Sum++; else False_Sum++;
        if (sfb_true ? ab_true[index] : static_field_bool) True_Sum++; else False_Sum++;
        if (sfb_true ? ab_true[index] : t1_i.mfb) True_Sum++; else False_Sum++;
        if (sfb_true ? ab_true[index] : simple_func_bool()) True_Sum++; else False_Sum++;
        if (sfb_true ? ab_true[index] : ab_true[index]) True_Sum++; else False_Sum++;
        if (sfb_true ? ab_true[index] : ab_false[index]) True_Sum++; else False_Sum++;
        if (sfb_true ? ab_false[index] : true) True_Sum++; else False_Sum++;
        if (sfb_true ? ab_false[index] : false) True_Sum++; else False_Sum++;
        if (sfb_true ? ab_false[index] : local_bool) True_Sum++; else False_Sum++;
        if (sfb_true ? ab_false[index] : static_field_bool) True_Sum++; else False_Sum++;
        if (sfb_true ? ab_false[index] : t1_i.mfb) True_Sum++; else False_Sum++;
        if (sfb_true ? ab_false[index] : simple_func_bool()) True_Sum++; else False_Sum++;
        if (sfb_true ? ab_false[index] : ab_true[index]) True_Sum++; else False_Sum++;
        if (sfb_true ? ab_false[index] : ab_false[index]) True_Sum++; else False_Sum++;
        if (sfb_false ? true : true) True_Sum++; else False_Sum++;
        if (sfb_false ? true : false) True_Sum++; else False_Sum++;
        if (sfb_false ? true : local_bool) True_Sum++; else False_Sum++;
        if (sfb_false ? true : static_field_bool) True_Sum++; else False_Sum++;
        if (sfb_false ? true : t1_i.mfb) True_Sum++; else False_Sum++;
        if (sfb_false ? true : simple_func_bool()) True_Sum++; else False_Sum++;
        if (sfb_false ? true : ab_true[index]) True_Sum++; else False_Sum++;
        if (sfb_false ? true : ab_false[index]) True_Sum++; else False_Sum++;
        if (sfb_false ? false : true) True_Sum++; else False_Sum++;
        if (sfb_false ? false : false) True_Sum++; else False_Sum++;
        if (sfb_false ? false : local_bool) True_Sum++; else False_Sum++;
        if (sfb_false ? false : static_field_bool) True_Sum++; else False_Sum++;
        if (sfb_false ? false : t1_i.mfb) True_Sum++; else False_Sum++;
        if (sfb_false ? false : simple_func_bool()) True_Sum++; else False_Sum++;
        if (sfb_false ? false : ab_true[index]) True_Sum++; else False_Sum++;
        if (sfb_false ? false : ab_false[index]) True_Sum++; else False_Sum++;
        if (sfb_false ? local_bool : true) True_Sum++; else False_Sum++;
        if (sfb_false ? local_bool : false) True_Sum++; else False_Sum++;
        if (sfb_false ? local_bool : local_bool) True_Sum++; else False_Sum++;
        if (sfb_false ? local_bool : static_field_bool) True_Sum++; else False_Sum++;
        if (sfb_false ? local_bool : t1_i.mfb) True_Sum++; else False_Sum++;
        if (sfb_false ? local_bool : simple_func_bool()) True_Sum++; else False_Sum++;
        if (sfb_false ? local_bool : ab_true[index]) True_Sum++; else False_Sum++;
        if (sfb_false ? local_bool : ab_false[index]) True_Sum++; else False_Sum++;
        if (sfb_false ? static_field_bool : true) True_Sum++; else False_Sum++;
        if (sfb_false ? static_field_bool : false) True_Sum++; else False_Sum++;
        if (sfb_false ? static_field_bool : local_bool) True_Sum++; else False_Sum++;
        if (sfb_false ? static_field_bool : static_field_bool) True_Sum++; else False_Sum++;
        if (sfb_false ? static_field_bool : t1_i.mfb) True_Sum++; else False_Sum++;
        if (sfb_false ? static_field_bool : simple_func_bool()) True_Sum++; else False_Sum++;
        if (sfb_false ? static_field_bool : ab_true[index]) True_Sum++; else False_Sum++;
        if (sfb_false ? static_field_bool : ab_false[index]) True_Sum++; else False_Sum++;
        if (sfb_false ? t1_i.mfb : true) True_Sum++; else False_Sum++;
        if (sfb_false ? t1_i.mfb : false) True_Sum++; else False_Sum++;
        if (sfb_false ? t1_i.mfb : local_bool) True_Sum++; else False_Sum++;
        if (sfb_false ? t1_i.mfb : static_field_bool) True_Sum++; else False_Sum++;
        if (sfb_false ? t1_i.mfb : t1_i.mfb) True_Sum++; else False_Sum++;
        if (sfb_false ? t1_i.mfb : simple_func_bool()) True_Sum++; else False_Sum++;
        if (sfb_false ? t1_i.mfb : ab_true[index]) True_Sum++; else False_Sum++;
        if (sfb_false ? t1_i.mfb : ab_false[index]) True_Sum++; else False_Sum++;
        if (sfb_false ? simple_func_bool() : true) True_Sum++; else False_Sum++;
        if (sfb_false ? simple_func_bool() : false) True_Sum++; else False_Sum++;
        if (sfb_false ? simple_func_bool() : local_bool) True_Sum++; else False_Sum++;
        if (sfb_false ? simple_func_bool() : static_field_bool) True_Sum++; else False_Sum++;
        if (sfb_false ? simple_func_bool() : t1_i.mfb) True_Sum++; else False_Sum++;
        if (sfb_false ? simple_func_bool() : simple_func_bool()) True_Sum++; else False_Sum++;
        if (sfb_false ? simple_func_bool() : ab_true[index]) True_Sum++; else False_Sum++;
        if (sfb_false ? simple_func_bool() : ab_false[index]) True_Sum++; else False_Sum++;
        if (sfb_false ? ab_true[index] : true) True_Sum++; else False_Sum++;
        if (sfb_false ? ab_true[index] : false) True_Sum++; else False_Sum++;
        if (sfb_false ? ab_true[index] : local_bool) True_Sum++; else False_Sum++;
        if (sfb_false ? ab_true[index] : static_field_bool) True_Sum++; else False_Sum++;
        if (sfb_false ? ab_true[index] : t1_i.mfb) True_Sum++; else False_Sum++;
        if (sfb_false ? ab_true[index] : simple_func_bool()) True_Sum++; else False_Sum++;
        if (sfb_false ? ab_true[index] : ab_true[index]) True_Sum++; else False_Sum++;
        if (sfb_false ? ab_true[index] : ab_false[index]) True_Sum++; else False_Sum++;
        if (sfb_false ? ab_false[index] : true) True_Sum++; else False_Sum++;
        if (sfb_false ? ab_false[index] : false) True_Sum++; else False_Sum++;
        if (sfb_false ? ab_false[index] : local_bool) True_Sum++; else False_Sum++;
        if (sfb_false ? ab_false[index] : static_field_bool) True_Sum++; else False_Sum++;
        if (sfb_false ? ab_false[index] : t1_i.mfb) True_Sum++; else False_Sum++;
        if (sfb_false ? ab_false[index] : simple_func_bool()) True_Sum++; else False_Sum++;
        if (sfb_false ? ab_false[index] : ab_true[index]) True_Sum++; else False_Sum++;
        if (sfb_false ? ab_false[index] : ab_false[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? true : true) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? true : false) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? true : local_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? true : static_field_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? true : t1_i.mfb) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? true : simple_func_bool()) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? true : ab_true[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? true : ab_false[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? false : true) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? false : false) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? false : local_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? false : static_field_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? false : t1_i.mfb) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? false : simple_func_bool()) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? false : ab_true[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? false : ab_false[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? local_bool : true) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? local_bool : false) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? local_bool : local_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? local_bool : static_field_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? local_bool : t1_i.mfb) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? local_bool : simple_func_bool()) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? local_bool : ab_true[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? local_bool : ab_false[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? static_field_bool : true) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? static_field_bool : false) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? static_field_bool : local_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? static_field_bool : static_field_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? static_field_bool : t1_i.mfb) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? static_field_bool : simple_func_bool()) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? static_field_bool : ab_true[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? static_field_bool : ab_false[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? t1_i.mfb : true) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? t1_i.mfb : false) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? t1_i.mfb : local_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? t1_i.mfb : static_field_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? t1_i.mfb : t1_i.mfb) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? t1_i.mfb : simple_func_bool()) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? t1_i.mfb : ab_true[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? t1_i.mfb : ab_false[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? simple_func_bool() : true) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? simple_func_bool() : false) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? simple_func_bool() : local_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? simple_func_bool() : static_field_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? simple_func_bool() : t1_i.mfb) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? simple_func_bool() : simple_func_bool()) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? simple_func_bool() : ab_true[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? simple_func_bool() : ab_false[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? ab_true[index] : true) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? ab_true[index] : false) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? ab_true[index] : local_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? ab_true[index] : static_field_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? ab_true[index] : t1_i.mfb) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? ab_true[index] : simple_func_bool()) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? ab_true[index] : ab_true[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? ab_true[index] : ab_false[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? ab_false[index] : true) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? ab_false[index] : false) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? ab_false[index] : local_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? ab_false[index] : static_field_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? ab_false[index] : t1_i.mfb) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? ab_false[index] : simple_func_bool()) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? ab_false[index] : ab_true[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_true ? ab_false[index] : ab_false[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? true : true) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? true : false) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? true : local_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? true : static_field_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? true : t1_i.mfb) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? true : simple_func_bool()) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? true : ab_true[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? true : ab_false[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? false : true) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? false : false) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? false : local_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? false : static_field_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? false : t1_i.mfb) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? false : simple_func_bool()) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? false : ab_true[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? false : ab_false[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? local_bool : true) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? local_bool : false) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? local_bool : local_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? local_bool : static_field_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? local_bool : t1_i.mfb) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? local_bool : simple_func_bool()) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? local_bool : ab_true[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? local_bool : ab_false[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? static_field_bool : true) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? static_field_bool : false) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? static_field_bool : local_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? static_field_bool : static_field_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? static_field_bool : t1_i.mfb) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? static_field_bool : simple_func_bool()) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? static_field_bool : ab_true[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? static_field_bool : ab_false[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? t1_i.mfb : true) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? t1_i.mfb : false) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? t1_i.mfb : local_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? t1_i.mfb : static_field_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? t1_i.mfb : t1_i.mfb) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? t1_i.mfb : simple_func_bool()) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? t1_i.mfb : ab_true[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? t1_i.mfb : ab_false[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? simple_func_bool() : true) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? simple_func_bool() : false) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? simple_func_bool() : local_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? simple_func_bool() : static_field_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? simple_func_bool() : t1_i.mfb) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? simple_func_bool() : simple_func_bool()) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? simple_func_bool() : ab_true[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? simple_func_bool() : ab_false[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? ab_true[index] : true) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? ab_true[index] : false) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? ab_true[index] : local_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? ab_true[index] : static_field_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? ab_true[index] : t1_i.mfb) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? ab_true[index] : simple_func_bool()) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? ab_true[index] : ab_true[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? ab_true[index] : ab_false[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? ab_false[index] : true) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? ab_false[index] : false) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? ab_false[index] : local_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? ab_false[index] : static_field_bool) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? ab_false[index] : t1_i.mfb) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? ab_false[index] : simple_func_bool()) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? ab_false[index] : ab_true[index]) True_Sum++; else False_Sum++;
        if (t1_i.mfb_false ? ab_false[index] : ab_false[index]) True_Sum++; else False_Sum++;
        return (True_Sum * 2) - False_Sum;
    }
    static int Sub_Funclet_2()
    {
        int True_Sum = 0;
        int False_Sum = 0;
        int index = 1;
        bool local_bool = true;
        bool lb_false = false;
        bool lb_true = true;
        testout1 t1_i = new testout1();
        bool[] ab_false = new bool[3];
        bool[] ab_true = new bool[3];
        ab_true[0] = true;
        ab_true[1] = true;
        ab_true[2] = true;

        static_field_bool = true;
        sfb_false = false;
        sfb_true = true;

        t1_i.mfb = true;
        t1_i.mfb_false = false;
        t1_i.mfb_true = true;
        if (func_sb_true() ? true : true) True_Sum++; else False_Sum++;
        if (func_sb_true() ? true : false) True_Sum++; else False_Sum++;
        if (func_sb_true() ? true : local_bool) True_Sum++; else False_Sum++;
        if (func_sb_true() ? true : static_field_bool) True_Sum++; else False_Sum++;
        if (func_sb_true() ? true : t1_i.mfb) True_Sum++; else False_Sum++;
        if (func_sb_true() ? true : simple_func_bool()) True_Sum++; else False_Sum++;
        if (func_sb_true() ? true : ab_true[index]) True_Sum++; else False_Sum++;
        if (func_sb_true() ? true : ab_false[index]) True_Sum++; else False_Sum++;
        if (func_sb_true() ? false : true) True_Sum++; else False_Sum++;
        if (func_sb_true() ? false : false) True_Sum++; else False_Sum++;
        if (func_sb_true() ? false : local_bool) True_Sum++; else False_Sum++;
        if (func_sb_true() ? false : static_field_bool) True_Sum++; else False_Sum++;
        if (func_sb_true() ? false : t1_i.mfb) True_Sum++; else False_Sum++;
        if (func_sb_true() ? false : simple_func_bool()) True_Sum++; else False_Sum++;
        if (func_sb_true() ? false : ab_true[index]) True_Sum++; else False_Sum++;
        if (func_sb_true() ? false : ab_false[index]) True_Sum++; else False_Sum++;
        if (func_sb_true() ? local_bool : true) True_Sum++; else False_Sum++;
        if (func_sb_true() ? local_bool : false) True_Sum++; else False_Sum++;
        if (func_sb_true() ? local_bool : local_bool) True_Sum++; else False_Sum++;
        if (func_sb_true() ? local_bool : static_field_bool) True_Sum++; else False_Sum++;
        if (func_sb_true() ? local_bool : t1_i.mfb) True_Sum++; else False_Sum++;
        if (func_sb_true() ? local_bool : simple_func_bool()) True_Sum++; else False_Sum++;
        if (func_sb_true() ? local_bool : ab_true[index]) True_Sum++; else False_Sum++;
        if (func_sb_true() ? local_bool : ab_false[index]) True_Sum++; else False_Sum++;
        if (func_sb_true() ? static_field_bool : true) True_Sum++; else False_Sum++;
        if (func_sb_true() ? static_field_bool : false) True_Sum++; else False_Sum++;
        if (func_sb_true() ? static_field_bool : local_bool) True_Sum++; else False_Sum++;
        if (func_sb_true() ? static_field_bool : static_field_bool) True_Sum++; else False_Sum++;
        if (func_sb_true() ? static_field_bool : t1_i.mfb) True_Sum++; else False_Sum++;
        if (func_sb_true() ? static_field_bool : simple_func_bool()) True_Sum++; else False_Sum++;
        if (func_sb_true() ? static_field_bool : ab_true[index]) True_Sum++; else False_Sum++;
        if (func_sb_true() ? static_field_bool : ab_false[index]) True_Sum++; else False_Sum++;
        if (func_sb_true() ? t1_i.mfb : true) True_Sum++; else False_Sum++;
        if (func_sb_true() ? t1_i.mfb : false) True_Sum++; else False_Sum++;
        if (func_sb_true() ? t1_i.mfb : local_bool) True_Sum++; else False_Sum++;
        if (func_sb_true() ? t1_i.mfb : static_field_bool) True_Sum++; else False_Sum++;
        if (func_sb_true() ? t1_i.mfb : t1_i.mfb) True_Sum++; else False_Sum++;
        if (func_sb_true() ? t1_i.mfb : simple_func_bool()) True_Sum++; else False_Sum++;
        if (func_sb_true() ? t1_i.mfb : ab_true[index]) True_Sum++; else False_Sum++;
        if (func_sb_true() ? t1_i.mfb : ab_false[index]) True_Sum++; else False_Sum++;
        if (func_sb_true() ? simple_func_bool() : true) True_Sum++; else False_Sum++;
        if (func_sb_true() ? simple_func_bool() : false) True_Sum++; else False_Sum++;
        if (func_sb_true() ? simple_func_bool() : local_bool) True_Sum++; else False_Sum++;
        if (func_sb_true() ? simple_func_bool() : static_field_bool) True_Sum++; else False_Sum++;
        if (func_sb_true() ? simple_func_bool() : t1_i.mfb) True_Sum++; else False_Sum++;
        if (func_sb_true() ? simple_func_bool() : simple_func_bool()) True_Sum++; else False_Sum++;
        if (func_sb_true() ? simple_func_bool() : ab_true[index]) True_Sum++; else False_Sum++;
        if (func_sb_true() ? simple_func_bool() : ab_false[index]) True_Sum++; else False_Sum++;
        if (func_sb_true() ? ab_true[index] : true) True_Sum++; else False_Sum++;
        if (func_sb_true() ? ab_true[index] : false) True_Sum++; else False_Sum++;
        if (func_sb_true() ? ab_true[index] : local_bool) True_Sum++; else False_Sum++;
        if (func_sb_true() ? ab_true[index] : static_field_bool) True_Sum++; else False_Sum++;
        if (func_sb_true() ? ab_true[index] : t1_i.mfb) True_Sum++; else False_Sum++;
        if (func_sb_true() ? ab_true[index] : simple_func_bool()) True_Sum++; else False_Sum++;
        if (func_sb_true() ? ab_true[index] : ab_true[index]) True_Sum++; else False_Sum++;
        if (func_sb_true() ? ab_true[index] : ab_false[index]) True_Sum++; else False_Sum++;
        if (func_sb_true() ? ab_false[index] : true) True_Sum++; else False_Sum++;
        if (func_sb_true() ? ab_false[index] : false) True_Sum++; else False_Sum++;
        if (func_sb_true() ? ab_false[index] : local_bool) True_Sum++; else False_Sum++;
        if (func_sb_true() ? ab_false[index] : static_field_bool) True_Sum++; else False_Sum++;
        if (func_sb_true() ? ab_false[index] : t1_i.mfb) True_Sum++; else False_Sum++;
        if (func_sb_true() ? ab_false[index] : simple_func_bool()) True_Sum++; else False_Sum++;
        if (func_sb_true() ? ab_false[index] : ab_true[index]) True_Sum++; else False_Sum++;
        if (func_sb_true() ? ab_false[index] : ab_false[index]) True_Sum++; else False_Sum++;
        if (func_sb_false() ? true : true) True_Sum++; else False_Sum++;
        if (func_sb_false() ? true : false) True_Sum++; else False_Sum++;
        if (func_sb_false() ? true : local_bool) True_Sum++; else False_Sum++;
        if (func_sb_false() ? true : static_field_bool) True_Sum++; else False_Sum++;
        if (func_sb_false() ? true : t1_i.mfb) True_Sum++; else False_Sum++;
        if (func_sb_false() ? true : simple_func_bool()) True_Sum++; else False_Sum++;
        if (func_sb_false() ? true : ab_true[index]) True_Sum++; else False_Sum++;
        if (func_sb_false() ? true : ab_false[index]) True_Sum++; else False_Sum++;
        if (func_sb_false() ? false : true) True_Sum++; else False_Sum++;
        if (func_sb_false() ? false : false) True_Sum++; else False_Sum++;
        if (func_sb_false() ? false : local_bool) True_Sum++; else False_Sum++;
        if (func_sb_false() ? false : static_field_bool) True_Sum++; else False_Sum++;
        if (func_sb_false() ? false : t1_i.mfb) True_Sum++; else False_Sum++;
        if (func_sb_false() ? false : simple_func_bool()) True_Sum++; else False_Sum++;
        if (func_sb_false() ? false : ab_true[index]) True_Sum++; else False_Sum++;
        if (func_sb_false() ? false : ab_false[index]) True_Sum++; else False_Sum++;
        if (func_sb_false() ? local_bool : true) True_Sum++; else False_Sum++;
        if (func_sb_false() ? local_bool : false) True_Sum++; else False_Sum++;
        if (func_sb_false() ? local_bool : local_bool) True_Sum++; else False_Sum++;
        if (func_sb_false() ? local_bool : static_field_bool) True_Sum++; else False_Sum++;
        if (func_sb_false() ? local_bool : t1_i.mfb) True_Sum++; else False_Sum++;
        if (func_sb_false() ? local_bool : simple_func_bool()) True_Sum++; else False_Sum++;
        if (func_sb_false() ? local_bool : ab_true[index]) True_Sum++; else False_Sum++;
        if (func_sb_false() ? local_bool : ab_false[index]) True_Sum++; else False_Sum++;
        if (func_sb_false() ? static_field_bool : true) True_Sum++; else False_Sum++;
        if (func_sb_false() ? static_field_bool : false) True_Sum++; else False_Sum++;
        if (func_sb_false() ? static_field_bool : local_bool) True_Sum++; else False_Sum++;
        if (func_sb_false() ? static_field_bool : static_field_bool) True_Sum++; else False_Sum++;
        if (func_sb_false() ? static_field_bool : t1_i.mfb) True_Sum++; else False_Sum++;
        if (func_sb_false() ? static_field_bool : simple_func_bool()) True_Sum++; else False_Sum++;
        if (func_sb_false() ? static_field_bool : ab_true[index]) True_Sum++; else False_Sum++;
        if (func_sb_false() ? static_field_bool : ab_false[index]) True_Sum++; else False_Sum++;
        if (func_sb_false() ? t1_i.mfb : true) True_Sum++; else False_Sum++;
        if (func_sb_false() ? t1_i.mfb : false) True_Sum++; else False_Sum++;
        if (func_sb_false() ? t1_i.mfb : local_bool) True_Sum++; else False_Sum++;
        if (func_sb_false() ? t1_i.mfb : static_field_bool) True_Sum++; else False_Sum++;
        if (func_sb_false() ? t1_i.mfb : t1_i.mfb) True_Sum++; else False_Sum++;
        if (func_sb_false() ? t1_i.mfb : simple_func_bool()) True_Sum++; else False_Sum++;
        if (func_sb_false() ? t1_i.mfb : ab_true[index]) True_Sum++; else False_Sum++;
        if (func_sb_false() ? t1_i.mfb : ab_false[index]) True_Sum++; else False_Sum++;
        if (func_sb_false() ? simple_func_bool() : true) True_Sum++; else False_Sum++;
        if (func_sb_false() ? simple_func_bool() : false) True_Sum++; else False_Sum++;
        if (func_sb_false() ? simple_func_bool() : local_bool) True_Sum++; else False_Sum++;
        if (func_sb_false() ? simple_func_bool() : static_field_bool) True_Sum++; else False_Sum++;
        if (func_sb_false() ? simple_func_bool() : t1_i.mfb) True_Sum++; else False_Sum++;
        if (func_sb_false() ? simple_func_bool() : simple_func_bool()) True_Sum++; else False_Sum++;
        if (func_sb_false() ? simple_func_bool() : ab_true[index]) True_Sum++; else False_Sum++;
        if (func_sb_false() ? simple_func_bool() : ab_false[index]) True_Sum++; else False_Sum++;
        if (func_sb_false() ? ab_true[index] : true) True_Sum++; else False_Sum++;
        if (func_sb_false() ? ab_true[index] : false) True_Sum++; else False_Sum++;
        if (func_sb_false() ? ab_true[index] : local_bool) True_Sum++; else False_Sum++;
        if (func_sb_false() ? ab_true[index] : static_field_bool) True_Sum++; else False_Sum++;
        if (func_sb_false() ? ab_true[index] : t1_i.mfb) True_Sum++; else False_Sum++;
        if (func_sb_false() ? ab_true[index] : simple_func_bool()) True_Sum++; else False_Sum++;
        if (func_sb_false() ? ab_true[index] : ab_true[index]) True_Sum++; else False_Sum++;
        if (func_sb_false() ? ab_true[index] : ab_false[index]) True_Sum++; else False_Sum++;
        if (func_sb_false() ? ab_false[index] : true) True_Sum++; else False_Sum++;
        if (func_sb_false() ? ab_false[index] : false) True_Sum++; else False_Sum++;
        if (func_sb_false() ? ab_false[index] : local_bool) True_Sum++; else False_Sum++;
        if (func_sb_false() ? ab_false[index] : static_field_bool) True_Sum++; else False_Sum++;
        if (func_sb_false() ? ab_false[index] : t1_i.mfb) True_Sum++; else False_Sum++;
        if (func_sb_false() ? ab_false[index] : simple_func_bool()) True_Sum++; else False_Sum++;
        if (func_sb_false() ? ab_false[index] : ab_true[index]) True_Sum++; else False_Sum++;
        if (func_sb_false() ? ab_false[index] : ab_false[index]) True_Sum++; else False_Sum++;
        if (ab_true[index] ? true : true) True_Sum++; else False_Sum++;
        if (ab_true[index] ? true : false) True_Sum++; else False_Sum++;
        if (ab_true[index] ? true : local_bool) True_Sum++; else False_Sum++;
        if (ab_true[index] ? true : static_field_bool) True_Sum++; else False_Sum++;
        if (ab_true[index] ? true : t1_i.mfb) True_Sum++; else False_Sum++;
        if (ab_true[index] ? true : simple_func_bool()) True_Sum++; else False_Sum++;
        if (ab_true[index] ? true : ab_true[index]) True_Sum++; else False_Sum++;
        if (ab_true[index] ? true : ab_false[index]) True_Sum++; else False_Sum++;
        if (ab_true[index] ? false : true) True_Sum++; else False_Sum++;
        if (ab_true[index] ? false : false) True_Sum++; else False_Sum++;
        if (ab_true[index] ? false : local_bool) True_Sum++; else False_Sum++;
        if (ab_true[index] ? false : static_field_bool) True_Sum++; else False_Sum++;
        if (ab_true[index] ? false : t1_i.mfb) True_Sum++; else False_Sum++;
        if (ab_true[index] ? false : simple_func_bool()) True_Sum++; else False_Sum++;
        if (ab_true[index] ? false : ab_true[index]) True_Sum++; else False_Sum++;
        if (ab_true[index] ? false : ab_false[index]) True_Sum++; else False_Sum++;
        if (ab_true[index] ? local_bool : true) True_Sum++; else False_Sum++;
        if (ab_true[index] ? local_bool : false) True_Sum++; else False_Sum++;
        if (ab_true[index] ? local_bool : local_bool) True_Sum++; else False_Sum++;
        if (ab_true[index] ? local_bool : static_field_bool) True_Sum++; else False_Sum++;
        if (ab_true[index] ? local_bool : t1_i.mfb) True_Sum++; else False_Sum++;
        if (ab_true[index] ? local_bool : simple_func_bool()) True_Sum++; else False_Sum++;
        if (ab_true[index] ? local_bool : ab_true[index]) True_Sum++; else False_Sum++;
        if (ab_true[index] ? local_bool : ab_false[index]) True_Sum++; else False_Sum++;
        if (ab_true[index] ? static_field_bool : true) True_Sum++; else False_Sum++;
        if (ab_true[index] ? static_field_bool : false) True_Sum++; else False_Sum++;
        if (ab_true[index] ? static_field_bool : local_bool) True_Sum++; else False_Sum++;
        if (ab_true[index] ? static_field_bool : static_field_bool) True_Sum++; else False_Sum++;
        if (ab_true[index] ? static_field_bool : t1_i.mfb) True_Sum++; else False_Sum++;
        if (ab_true[index] ? static_field_bool : simple_func_bool()) True_Sum++; else False_Sum++;
        if (ab_true[index] ? static_field_bool : ab_true[index]) True_Sum++; else False_Sum++;
        if (ab_true[index] ? static_field_bool : ab_false[index]) True_Sum++; else False_Sum++;
        if (ab_true[index] ? t1_i.mfb : true) True_Sum++; else False_Sum++;
        if (ab_true[index] ? t1_i.mfb : false) True_Sum++; else False_Sum++;
        if (ab_true[index] ? t1_i.mfb : local_bool) True_Sum++; else False_Sum++;
        if (ab_true[index] ? t1_i.mfb : static_field_bool) True_Sum++; else False_Sum++;
        if (ab_true[index] ? t1_i.mfb : t1_i.mfb) True_Sum++; else False_Sum++;
        if (ab_true[index] ? t1_i.mfb : simple_func_bool()) True_Sum++; else False_Sum++;
        if (ab_true[index] ? t1_i.mfb : ab_true[index]) True_Sum++; else False_Sum++;
        if (ab_true[index] ? t1_i.mfb : ab_false[index]) True_Sum++; else False_Sum++;
        if (ab_true[index] ? simple_func_bool() : true) True_Sum++; else False_Sum++;
        if (ab_true[index] ? simple_func_bool() : false) True_Sum++; else False_Sum++;
        if (ab_true[index] ? simple_func_bool() : local_bool) True_Sum++; else False_Sum++;
        if (ab_true[index] ? simple_func_bool() : static_field_bool) True_Sum++; else False_Sum++;
        if (ab_true[index] ? simple_func_bool() : t1_i.mfb) True_Sum++; else False_Sum++;
        if (ab_true[index] ? simple_func_bool() : simple_func_bool()) True_Sum++; else False_Sum++;
        if (ab_true[index] ? simple_func_bool() : ab_true[index]) True_Sum++; else False_Sum++;
        if (ab_true[index] ? simple_func_bool() : ab_false[index]) True_Sum++; else False_Sum++;
        if (ab_true[index] ? ab_true[index] : true) True_Sum++; else False_Sum++;
        if (ab_true[index] ? ab_true[index] : false) True_Sum++; else False_Sum++;
        if (ab_true[index] ? ab_true[index] : local_bool) True_Sum++; else False_Sum++;
        if (ab_true[index] ? ab_true[index] : static_field_bool) True_Sum++; else False_Sum++;
        if (ab_true[index] ? ab_true[index] : t1_i.mfb) True_Sum++; else False_Sum++;
        if (ab_true[index] ? ab_true[index] : simple_func_bool()) True_Sum++; else False_Sum++;
        if (ab_true[index] ? ab_true[index] : ab_true[index]) True_Sum++; else False_Sum++;
        if (ab_true[index] ? ab_true[index] : ab_false[index]) True_Sum++; else False_Sum++;
        if (ab_true[index] ? ab_false[index] : true) True_Sum++; else False_Sum++;
        if (ab_true[index] ? ab_false[index] : false) True_Sum++; else False_Sum++;
        if (ab_true[index] ? ab_false[index] : local_bool) True_Sum++; else False_Sum++;
        if (ab_true[index] ? ab_false[index] : static_field_bool) True_Sum++; else False_Sum++;
        if (ab_true[index] ? ab_false[index] : t1_i.mfb) True_Sum++; else False_Sum++;
        if (ab_true[index] ? ab_false[index] : simple_func_bool()) True_Sum++; else False_Sum++;
        if (ab_true[index] ? ab_false[index] : ab_true[index]) True_Sum++; else False_Sum++;
        if (ab_true[index] ? ab_false[index] : ab_false[index]) True_Sum++; else False_Sum++;
        if (ab_false[index] ? true : true) True_Sum++; else False_Sum++;
        if (ab_false[index] ? true : false) True_Sum++; else False_Sum++;
        if (ab_false[index] ? true : local_bool) True_Sum++; else False_Sum++;
        if (ab_false[index] ? true : static_field_bool) True_Sum++; else False_Sum++;
        if (ab_false[index] ? true : t1_i.mfb) True_Sum++; else False_Sum++;
        if (ab_false[index] ? true : simple_func_bool()) True_Sum++; else False_Sum++;
        if (ab_false[index] ? true : ab_true[index]) True_Sum++; else False_Sum++;
        if (ab_false[index] ? true : ab_false[index]) True_Sum++; else False_Sum++;
        if (ab_false[index] ? false : true) True_Sum++; else False_Sum++;
        if (ab_false[index] ? false : false) True_Sum++; else False_Sum++;
        if (ab_false[index] ? false : local_bool) True_Sum++; else False_Sum++;
        if (ab_false[index] ? false : static_field_bool) True_Sum++; else False_Sum++;
        if (ab_false[index] ? false : t1_i.mfb) True_Sum++; else False_Sum++;
        if (ab_false[index] ? false : simple_func_bool()) True_Sum++; else False_Sum++;
        if (ab_false[index] ? false : ab_true[index]) True_Sum++; else False_Sum++;
        if (ab_false[index] ? false : ab_false[index]) True_Sum++; else False_Sum++;
        if (ab_false[index] ? local_bool : true) True_Sum++; else False_Sum++;
        if (ab_false[index] ? local_bool : false) True_Sum++; else False_Sum++;
        if (ab_false[index] ? local_bool : local_bool) True_Sum++; else False_Sum++;
        if (ab_false[index] ? local_bool : static_field_bool) True_Sum++; else False_Sum++;
        if (ab_false[index] ? local_bool : t1_i.mfb) True_Sum++; else False_Sum++;
        if (ab_false[index] ? local_bool : simple_func_bool()) True_Sum++; else False_Sum++;
        if (ab_false[index] ? local_bool : ab_true[index]) True_Sum++; else False_Sum++;
        if (ab_false[index] ? local_bool : ab_false[index]) True_Sum++; else False_Sum++;
        if (ab_false[index] ? static_field_bool : true) True_Sum++; else False_Sum++;
        if (ab_false[index] ? static_field_bool : false) True_Sum++; else False_Sum++;
        if (ab_false[index] ? static_field_bool : local_bool) True_Sum++; else False_Sum++;
        if (ab_false[index] ? static_field_bool : static_field_bool) True_Sum++; else False_Sum++;
        if (ab_false[index] ? static_field_bool : t1_i.mfb) True_Sum++; else False_Sum++;
        if (ab_false[index] ? static_field_bool : simple_func_bool()) True_Sum++; else False_Sum++;
        if (ab_false[index] ? static_field_bool : ab_true[index]) True_Sum++; else False_Sum++;
        if (ab_false[index] ? static_field_bool : ab_false[index]) True_Sum++; else False_Sum++;
        if (ab_false[index] ? t1_i.mfb : true) True_Sum++; else False_Sum++;
        if (ab_false[index] ? t1_i.mfb : false) True_Sum++; else False_Sum++;
        if (ab_false[index] ? t1_i.mfb : local_bool) True_Sum++; else False_Sum++;
        if (ab_false[index] ? t1_i.mfb : static_field_bool) True_Sum++; else False_Sum++;
        if (ab_false[index] ? t1_i.mfb : t1_i.mfb) True_Sum++; else False_Sum++;
        if (ab_false[index] ? t1_i.mfb : simple_func_bool()) True_Sum++; else False_Sum++;
        if (ab_false[index] ? t1_i.mfb : ab_true[index]) True_Sum++; else False_Sum++;
        if (ab_false[index] ? t1_i.mfb : ab_false[index]) True_Sum++; else False_Sum++;
        if (ab_false[index] ? simple_func_bool() : true) True_Sum++; else False_Sum++;
        if (ab_false[index] ? simple_func_bool() : false) True_Sum++; else False_Sum++;
        if (ab_false[index] ? simple_func_bool() : local_bool) True_Sum++; else False_Sum++;
        if (ab_false[index] ? simple_func_bool() : static_field_bool) True_Sum++; else False_Sum++;
        if (ab_false[index] ? simple_func_bool() : t1_i.mfb) True_Sum++; else False_Sum++;
        if (ab_false[index] ? simple_func_bool() : simple_func_bool()) True_Sum++; else False_Sum++;
        if (ab_false[index] ? simple_func_bool() : ab_true[index]) True_Sum++; else False_Sum++;
        if (ab_false[index] ? simple_func_bool() : ab_false[index]) True_Sum++; else False_Sum++;
        if (ab_false[index] ? ab_true[index] : true) True_Sum++; else False_Sum++;
        if (ab_false[index] ? ab_true[index] : false) True_Sum++; else False_Sum++;
        if (ab_false[index] ? ab_true[index] : local_bool) True_Sum++; else False_Sum++;
        if (ab_false[index] ? ab_true[index] : static_field_bool) True_Sum++; else False_Sum++;
        if (ab_false[index] ? ab_true[index] : t1_i.mfb) True_Sum++; else False_Sum++;
        if (ab_false[index] ? ab_true[index] : simple_func_bool()) True_Sum++; else False_Sum++;
        if (ab_false[index] ? ab_true[index] : ab_true[index]) True_Sum++; else False_Sum++;
        if (ab_false[index] ? ab_true[index] : ab_false[index]) True_Sum++; else False_Sum++;
        if (ab_false[index] ? ab_false[index] : true) True_Sum++; else False_Sum++;
        if (ab_false[index] ? ab_false[index] : false) True_Sum++; else False_Sum++;
        if (ab_false[index] ? ab_false[index] : local_bool) True_Sum++; else False_Sum++;
        if (ab_false[index] ? ab_false[index] : static_field_bool) True_Sum++; else False_Sum++;
        if (ab_false[index] ? ab_false[index] : t1_i.mfb) True_Sum++; else False_Sum++;
        if (ab_false[index] ? ab_false[index] : simple_func_bool()) True_Sum++; else False_Sum++;
        if (ab_false[index] ? ab_false[index] : ab_true[index]) True_Sum++; else False_Sum++;
        if (ab_false[index] ? ab_false[index] : ab_false[index]) True_Sum++; else False_Sum++;
        return (True_Sum * 2) - False_Sum;
    }
    static int Sub_Funclet_3()
    {
        int True_Sum = 0;
        int False_Sum = 0;
        int index = 1;
        bool local_bool = true;
        bool lb_false = false;
        bool lb_true = true;
        testout1 t1_i = new testout1();
        bool[] ab_false = new bool[3];
        bool[] ab_true = new bool[3];
        ab_true[0] = true;
        ab_true[1] = true;
        ab_true[2] = true;

        static_field_bool = true;
        sfb_false = false;
        sfb_true = true;

        t1_i.mfb = true;
        t1_i.mfb_false = false;
        t1_i.mfb_true = true;
        return (True_Sum * 2) - False_Sum;
    }

    public static int Main()
    {
        int Sum = 0;
        Sum += Sub_Funclet_0();
        Sum += Sub_Funclet_1();
        Sum += Sub_Funclet_2();
        Sum += Sub_Funclet_3();

        if (Sum == 960)
        {
            Console.WriteLine("PASSED");
            return 100;
        }
        else
        {
            Console.WriteLine("FAILED");
            return 1;
        }
    }
}
