// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_CLR_x86_JIT_V1_M12_Beta2_b53942_b53942b = il_coreclr_test({
    name: "b53942b",
    srcs: ["b53942b.il"],
    debugType: "pdbonly",
    optimize: true,
});

@@public
export const jIT_Regression_CLR_x86_JIT_V1_M12_Beta2_b53942_b53942a = il_coreclr_test({
    name: "b53942a",
    srcs: ["b53942a.il"],
    debugType: "pdbonly",
    optimize: true,
});
