<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Covariant returns of Task-derived types in runtime async methods are not yet supported on NativeAOT. -->
    <DisableProjectBuild Condition="'$(TestBuildMode)' == 'nativeaot'">true</DisableProjectBuild>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(MSBuildProjectName).cs" />
    <ProjectReference Include="$(TestLibraryProjectPath)" />
  </ItemGroup>
</Project>
