<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <CLRTestTargetUnsupported Condition="'$(RuntimeFlavor)' == 'coreclr' and '$(TargetOS)' == 'browser'">true</CLRTestTargetUnsupported>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="115178.cs" />
    <ProjectReference Include="$(TestLibraryProjectPath)" />
  </ItemGroup>
</Project>
