
macro(append_extra_system_libs NativeLibsExtra)
    if (CLR_CMAKE_TARGET_LINUX AND NOT CLR_CMAKE_TARGET_ANDROID)
        list(APPEND ${NativeLibsExtra} rt)
        find_library(LIBUTIL_LIBRARY util)
        if (LIBUTIL_LIBRARY)
            list(APPEND ${NativeLibsExtra} ${LIBUTIL_LIBRARY})
        endif()
    elseif (CLR_CMAKE_TARGET_FREEBSD)
        list(APPEND ${NativeLibsExtra} pthread)
        find_library(INOTIFY_LIBRARY inotify HINTS ${CROSS_ROOTFS}/usr/local/lib)
        list(APPEND ${NativeLibsExtra} ${INOTIFY_LIBRARY})
    elseif (CLR_CMAKE_TARGET_OPENBSD)
        list(APPEND ${NativeLibsExtra} pthread util)
    elseif (CLR_CMAKE_TARGET_SUNOS)
        list(APPEND ${NativeLibsExtra} socket nsl)
    elseif (CLR_CMAKE_TARGET_HAIKU)
        list (APPEND ${NativeLibsExtra} network bsd)
    endif ()

    if (CLR_CMAKE_TARGET_APPLE)
        find_library(FOUNDATION Foundation REQUIRED)
        list(APPEND ${NativeLibsExtra} ${FOUNDATION})
    endif ()
endmacro()
