// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Methodical_int64_arrays_hugedim_d = il_coreclr_test({
    name: "hugedim_d",
    srcs: ["hugedim_d.il", "hugedim.il"],
    debugType: "full",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Methodical_int64_arrays_lcs_long_il_r = il_coreclr_test({
    name: "lcs_long_il_r",
    srcs: ["lcs_long_r.il", "lcs_long.il"],
    debugType: "pdbonly",
});

@@public
export const jIT_Methodical_int64_arrays_lcs_ulong_il_r = il_coreclr_test({
    name: "lcs_ulong_il_r",
    srcs: ["lcs_ulong_r.il", "lcs_ulong.il"],
    debugType: "pdbonly",
});

@@public
export const jIT_Methodical_int64_arrays_lcs_long_il_d = il_coreclr_test({
    name: "lcs_long_il_d",
    srcs: ["lcs_long_d.il", "lcs_long.il"],
    debugType: "full",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Methodical_int64_arrays_hugedim_r = il_coreclr_test({
    name: "hugedim_r",
    srcs: ["hugedim_r.il", "hugedim.il"],
    debugType: "pdbonly",
});

@@public
export const jIT_Methodical_int64_arrays_lcs_ulong_il_d = il_coreclr_test({
    name: "lcs_ulong_il_d",
    srcs: ["lcs_ulong_d.il", "lcs_ulong.il"],
    debugType: "full",
    pri: 1,
    size: "medium",
});
