<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworkIdentifier>.NETCoreApp</TargetFrameworkIdentifier>
    <OutputType>exe</OutputType>
    <Optimize>true</Optimize>
    <Features>$(Features);runtime-async=on</Features>
    <!--
      This profiler test relies on JIT hooks firing, so it does not validate the same behavior when
      the runtime is executed in interpreter or ReadyToRun modes. Skip those non-fully-JITed paths
      until ActiveIssue https://github.com/dotnet/runtime/issues/132810 is fixed.
    -->
    <InterpreterIncompatible>true</InterpreterIncompatible>
    <R2RIncompatible>true</R2RIncompatible>
    <UnloadabilityIncompatible>true</UnloadabilityIncompatible>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(MSBuildProjectName).cs" />
    <ProjectReference Include="$(TestLibraryProjectPath)" />
    <ProjectReference Include="../common/profiler_common.csproj" />
    <CMakeProjectReference Include="$(MSBuildThisFileDirectory)/../native/CMakeLists.txt" />
  </ItemGroup>
</Project>
