// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_JitBlue_Runtime_100466_runtime_100466 = coreclr_test({
    name: "Runtime_100466",
    srcs: ["Runtime_100466.cs"],
});
