// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const loader_classloader_generics_regressions_536564_vsw536564 = coreclr_test({
    name: "vsw536564",
    srcs: ["vsw536564.cs"],
    pri: 1,
    size: "medium",
});
