// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const async_valuetask_valuetask = coreclr_test({
    name: "valuetask",
    srcs: ["valuetask.cs", ...asyncSharedSrcs.srcs],
    compilerOptions: ["/features:runtime-async=on", "/nowarn:SYSLIB5007"],
    optimize: true,
    tags: ["manual"],
});
