#!/bin/bash

set -o nounset
set -o errexit
set -o verbose

source ../common.sh

MONO_RUNTIME_BASE=../runtime${TARGET_BIT_PREFIX}
MONO_BASE=../compiler
MONO="${MONO_BASE}/bin/nacl${TARGET_BIT_PREFIX}-mono"
CC=$NACLCC
AS=$NACLAS
MODE=nacl
COMPILE_AOT=0
AOT_OBJS=
CC_DEFINES=
MONO_SNAPSHOT=mono-normal-build
RELOCATE_RODATA="-Wl,--section-start=.rodata=0x2000000"
export NACL_ALLOW_DYNCODE_REPLACEMENT=1

if [ $# -gt 0 ]; then
  while [ -n "$*" ]
  do
    if [ $1 == "normal" ]; then
      MONO_RUNTIME_BASE=../normal-mono
      MONO_BASE=../normal-mono
      MONO=${MONO_BASE}/bin/mono
      CC=gcc
      AS=as
      MODE=normal
    elif [ $1 == "aot" ]; then
      COMPILE_AOT=1
      CC_DEFINES=-DAOT_VERSION
      RELOCATE_RODATA=
    elif [ $1 == "regression" ]; then
      MODE=regression
    else
      echo "Unrecognized option '$1'"
      exit -1
    fi
    shift
  done
fi

readonly MONO_NORMAL_BASE=../normal-mono
readonly NCVAL=ncval

# add nacl-gcc to path (from NaCl SDK)
export PATH=${NACL_BIN_PATH}:$PATH

# add sel_ldr to path (from NaCl dev tree)
export PATH=${NACL_DEV}/native_client/scons-out/dbg-${OS_SUBDIR}-x86-${TARGET_BITSIZE}/staging:$PATH

# add nacl-mono to path
export PATH=../normal-mono/bin:$PATH

# echo version of nacl-gcc
$CC --version

echo $PATH
which sel_ldr

# echo version of gmcs 
which gmcs
../normal-mono/bin/gmcs --version

# echo version of nacl-mono
${MONO} --version

# add MONO_PATH so mono can crank on local directory
export MONO_PATH=$(pwd)
echo ${MONO_PATH}

#-----
# enable the appropriate set of AOT options below.

readonly AOT_OPTIONS=full,static,nodebug
#-----

# make a temp copy of mscorlib.dll in this directory
cp ${MONO_NORMAL_BASE}/lib/mono/2.0/mscorlib.dll .

# compile c-sharp file with gmcs
MONO_PATH=. ../normal-mono/bin/gmcs -lib:. -warn:0 hw.cs

# convert .exe to .exe.o assembly files
# convert mscorlib to a .dll.o file
if [ $COMPILE_AOT = "1" ]; then
  MONO_PATH=. ${MONO} --aot=${AOT_OPTIONS} mscorlib.dll
  MONO_PATH=. ${MONO} --aot=${AOT_OPTIONS} hw.exe
  AOT_OBJS="hw.exe.o mscorlib.dll.o"
fi

# compile c and assembly into a.out, all statically linked
# different options for normal and nacl-mono
if [ $MODE = "normal" ]; then
  $CC -g -static my.c ${CC_DEFINES} ${AOT_OBJS} -o hw-test -lmono-2.0 -lpthread -lm -ldl -lrt -I${MONO_RUNTIME_BASE}/include -I${MONO_RUNTIME_BASE}/include/mono-2.0 -L${MONO_RUNTIME_BASE}/lib
elif [ $MODE = "nacl" ]; then
  $CC -static my.c ${CC_DEFINES} ${AOT_OBJS} -o hw-test.nexe -lmono-2.0 -lpthread -lm -lnosys -I${MONO_RUNTIME_BASE}/include -I${MONO_RUNTIME_BASE}/include/mono-2.0 -L${MONO_RUNTIME_BASE}/lib ${RELOCATE_RODATA}
fi

readonly fsatests="basic.exe basic-float.exe basic-long.exe basic-calls.exe objects.exe arrays.exe basic-math.exe exceptions.exe devirtualization.exe basic-simd.exe gc-stress.exe imt_big_iface_test.exe generics.exe iltests.exe nacl.exe"
if [ $MODE = "regression" ]; then
  #rm -rf fsa-tmp
  mkdir -p fsa-tmp
  DIR=$(pwd)
  cd ../${MONO_SNAPSHOT}/mono/mini/
   make $fsatests generics-variant-types.dll TestDriver.dll
   cp $fsatests generics-variant-types.dll TestDriver.dll $DIR/fsa-tmp
  cd -
 
  CLASS=${MONO_NORMAL_BASE}/lib/mono/2.0
  cp $CLASS/System.Core.dll $CLASS/System.dll $CLASS/Mono.Posix.dll $CLASS/System.Configuration.dll $CLASS/System.Security.dll $CLASS/System.Xml.dll $CLASS/Mono.Security.dll $CLASS/Mono.Simd.dll fsa-tmp
  cp mscorlib.dll fsa-tmp

  AOT_OBJS=""
  if [ $COMPILE_AOT = "1" ]; then
    for t in $fsatests; do
      MONO_PATH=fsa-tmp ${MONO} --aot=${AOT_OPTIONS} fsa-tmp/$t
      AOT_OBJS="${AOT_OBJS} fsa-tmp/$t.o" 
    done
    for d in fsa-tmp/*.dll; do
      MONO_PATH=fsa-tmp ${MONO} --aot=${AOT_OPTIONS} $d
      AOT_OBJS="${AOT_OBJS} $d.o" 
    done  
  fi

  $CC -o fsa-tmp/fsacheck.nexe -g -static ../../mono/mini/fsacheck.c ${CC_DEFINES} ${AOT_OBJS} -lmono-2.0 -lpthread -lm -lnosys -L${MONO_RUNTIME_BASE}/lib -I${MONO_RUNTIME_BASE}/include/mono-2.0  -I${MONO_RUNTIME_BASE}/include ${RELOCATE_RODATA}
fi

# only actually run the tests if we are on the target platform
if [ $TARGET_BITSIZE = $HOST_BITSIZE ]; then
  if [ $MODE = "regression" ]; then
    cd fsa-tmp
    ${NCVAL} -readwrite_sfi fsacheck.nexe 2> validator_out || echo "fsacheck.nexe invalid: continuing anyway"
    nacl-objdump -d fsacheck.nexe > fsacheck.disasm
    for t in $fsatests; do
      sel_ldr -a -c fsacheck.nexe $t || true
    done
  else
    export MONO_PATH=$(pwd)
    # run generated test(select one or more below)
    if [ $MODE = "normal" ]; then
      ./hw-test
    else
      ${NCVAL} -readwrite_sfi hw-test.nexe 2> validator_out || echo "hw-test.nexe invalid: continuing anyway"
      nacl-objdump -d hw-test.nexe > hw-test.disasm
      sel_ldr -a -c hw-test.nexe
    fi
  fi
fi

exit 0

