// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Methodical_VT_callconv_calli_r = il_coreclr_test({
    name: "calli_r",
    srcs: ["calli_r.il", "calli.il"],
    debugType: "pdbonly",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Methodical_VT_callconv_jumper5_d = il_coreclr_test({
    name: "jumper5_d",
    srcs: ["jumper5_d.il", "jumper5.il"],
    debugType: "full",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Methodical_VT_callconv_aa_d = il_coreclr_test({
    name: "aa_d",
    srcs: ["aa_d.il", "aa.il"],
    debugType: "full",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Methodical_VT_callconv_jumper5_r = il_coreclr_test({
    name: "jumper5_r",
    srcs: ["jumper5_r.il", "jumper5.il"],
    debugType: "pdbonly",
});

@@public
export const jIT_Methodical_VT_callconv_jumper4_d = il_coreclr_test({
    name: "jumper4_d",
    srcs: ["jumper4_d.il", "jumper4.il"],
    debugType: "full",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Methodical_VT_callconv_jumps2_d = il_coreclr_test({
    name: "jumps2_d",
    srcs: ["jumps2_d.il", "jumps2.il"],
    debugType: "full",
});

@@public
export const jIT_Methodical_VT_callconv_jumps1_r = il_coreclr_test({
    name: "jumps1_r",
    srcs: ["jumps1_r.il", "jumps1.il"],
    debugType: "pdbonly",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Methodical_VT_callconv_ee_r = il_coreclr_test({
    name: "ee_r",
    srcs: ["ee_r.il", "ee.il"],
    debugType: "pdbonly",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Methodical_VT_callconv_vtret_il_r = il_coreclr_test({
    name: "vtret_il_r",
    srcs: ["vtret_r.il", "vtret.il"],
    debugType: "pdbonly",
});

@@public
export const jIT_Methodical_VT_callconv_jumps1_d = il_coreclr_test({
    name: "jumps1_d",
    srcs: ["jumps1_d.il", "jumps1.il"],
    debugType: "full",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Methodical_VT_callconv_vtret2_r = il_coreclr_test({
    name: "vtret2_r",
    srcs: ["vtret2_r.il", "vtret2.il"],
    debugType: "pdbonly",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Methodical_VT_callconv_jumps4_d = il_coreclr_test({
    name: "jumps4_d",
    srcs: ["jumps4_d.il", "jumps4.il"],
    debugType: "full",
});

@@public
export const jIT_Methodical_VT_callconv_jumps4_r = il_coreclr_test({
    name: "jumps4_r",
    srcs: ["jumps4_r.il", "jumps4.il"],
    debugType: "pdbonly",
});

@@public
export const jIT_Methodical_VT_callconv_calli_d = il_coreclr_test({
    name: "calli_d",
    srcs: ["calli_d.il", "calli.il"],
    debugType: "full",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Methodical_VT_callconv_dd_r = il_coreclr_test({
    name: "dd_r",
    srcs: ["dd_r.il", "dd.il"],
    debugType: "pdbonly",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Methodical_VT_callconv_jumper2_d = il_coreclr_test({
    name: "jumper2_d",
    srcs: ["jumper2_d.il", "jumper2.il"],
    debugType: "full",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Methodical_VT_callconv_jumps2_r = il_coreclr_test({
    name: "jumps2_r",
    srcs: ["jumps2_r.il", "jumps2.il"],
    debugType: "pdbonly",
});

@@public
export const jIT_Methodical_VT_callconv_jumper1_d = il_coreclr_test({
    name: "jumper1_d",
    srcs: ["jumper1_d.il", "jumper1.il"],
    debugType: "full",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Methodical_VT_callconv_vtret_il_d = il_coreclr_test({
    name: "vtret_il_d",
    srcs: ["vtret_d.il", "vtret.il"],
    debugType: "full",
});

@@public
export const jIT_Methodical_VT_callconv_dd_d = il_coreclr_test({
    name: "dd_d",
    srcs: ["dd_d.il", "dd.il"],
    debugType: "full",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Methodical_VT_callconv_ee_d = il_coreclr_test({
    name: "ee_d",
    srcs: ["ee_d.il", "ee.il"],
    debugType: "full",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Methodical_VT_callconv_jumps3_d = il_coreclr_test({
    name: "jumps3_d",
    srcs: ["jumps3_d.il", "jumps3.il"],
    debugType: "full",
});

@@public
export const jIT_Methodical_VT_callconv_aa_r = il_coreclr_test({
    name: "aa_r",
    srcs: ["aa_r.il", "aa.il"],
    debugType: "pdbonly",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Methodical_VT_callconv_jumps3_r = il_coreclr_test({
    name: "jumps3_r",
    srcs: ["jumps3_r.il", "jumps3.il"],
    debugType: "pdbonly",
});

@@public
export const jIT_Methodical_VT_callconv_vtret2_d = il_coreclr_test({
    name: "vtret2_d",
    srcs: ["vtret2_d.il", "vtret2.il"],
    debugType: "full",
});

@@public
export const jIT_Methodical_VT_callconv_jumper3_r = il_coreclr_test({
    name: "jumper3_r",
    srcs: ["jumper3_r.il", "jumper3.il"],
    debugType: "pdbonly",
});

@@public
export const jIT_Methodical_VT_callconv_jumper3_d = il_coreclr_test({
    name: "jumper3_d",
    srcs: ["jumper3_d.il", "jumper3.il"],
    debugType: "full",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Methodical_VT_callconv_jumps5_d = il_coreclr_test({
    name: "jumps5_d",
    srcs: ["jumps5_d.il", "jumps5.il"],
    debugType: "full",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Methodical_VT_callconv_jumper4_r = il_coreclr_test({
    name: "jumper4_r",
    srcs: ["jumper4_r.il", "jumper4.il"],
    debugType: "pdbonly",
});

@@public
export const jIT_Methodical_VT_callconv_jumps5_r = il_coreclr_test({
    name: "jumps5_r",
    srcs: ["jumps5_r.il", "jumps5.il"],
    debugType: "pdbonly",
    pri: 1,
    size: "medium",
});

@@public
export const jIT_Methodical_VT_callconv_jumper2_r = il_coreclr_test({
    name: "jumper2_r",
    srcs: ["jumper2_r.il", "jumper2.il"],
    debugType: "pdbonly",
});

@@public
export const jIT_Methodical_VT_callconv_jumper1_r = il_coreclr_test({
    name: "jumper1_r",
    srcs: ["jumper1_r.il", "jumper1.il"],
    debugType: "pdbonly",
});
