// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_opt_JitMinOpts_Regression_gitHub_42719_ro = il_coreclr_test({
    name: "GitHub_42719_ro",
    srcs: ["GitHub_42719_ro.il", "GitHub_42719.il"],
    optimize: true,
});

@@public
export const jIT_opt_JitMinOpts_Regression_gitHub_42719_r = il_coreclr_test({
    name: "GitHub_42719_r",
    srcs: ["GitHub_42719_r.il", "GitHub_42719.il"],
});
