.\" 
.\" monodis manual page.
.\" (C) Ximian, Inc. 
.\" Author:
.\"   Miguel de Icaza (miguel@gnu.org)
.\"
.TH Mono "Mono 1.0"
.SH NAME
monodis \- CIL image content dumper and disassembler.
.SH SYNOPSIS
.PP
.B monodis
[\-hd] [\-\-help] 
[\-\-mscorlib]
[\-\-assembly]
[\-\-assemblyref]
[\-\-classlayout]
[\-\-constant]
[\-\-event]
[\-\-fields]
[\-\-file]
[\-\-interface]
[\-\-memberref]
[\-\-method]
[\-\-methodsem]
[\-\-moduleref]
[\-\-param]
[\-\-property]
[\-\-propertymap]
[\-\-typedef]
[\-\-typeref]
[FILES...]
.SH DESCRIPTION
The \fImonodis\fP program is used to dump the contents a CIL image
(contained in .EXE files that contain extended PE/COFF CIL code).  
.SH OPTIONS
The following Generic options are supported:
.TP
.I "--help", "-h"
Displays usage instructions.
.TP
.I "--mscorlib"
For non-corlib assemblies, use "mscorlib" as the assembly name. This
is useful for round-tripping the IL with ilasm.
.I "--assembly"
Dumps the contents of the assembly table
.I "--assemblyref"
Dumps the contents of the assemblyref table
.I "--classlayout"
Dumps the contents of the classlayout table
.I "--constant"
Dumps the contents of the constant table
.I "--event"
Dumps the contents of the event table
.I "--fields"
Dumps the contents of the fields table
.I "--file"
Dumps the contents of the file table
.I "--interface"
Dumps the contents of the interface table
.I "--memberref"
Dumps the contents of the memberref table
.I "--method"
Dumps the contents of the method table
.I "--methodsem"
Dumps the contents of the methodsem table
.I "--moduleref"
Dumps the contents of the moduleref table
.I "--param"
Dumps the contents of the param table
.I "--property"
Dumps the contents of the property table
.I "--propertymap"
Dumps the contents of the propertymap table
.I "--typedef"
Dumps the contents of the typedef table
.I "--typeref"
Dumps the contents of the typeref table
.PP
If no flags are specified the program dumps the content of the image
in a format that can be used to rountrip the code. 
.SH AUTHOR
monodis was written by Miguel de Icaza, Paolo Molaro and Dietmar Maurer.
.SH SEE ALSO
.BR pedump(1)
