// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_VS_ia64_JIT_M00_b98431_b98431 = il_coreclr_test({
    name: "b98431",
    srcs: ["b98431.il"],
    debugType: "pdbonly",
    optimize: true,
    pri: 1,
    size: "medium",
});
