// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_JitBlue_Runtime_56743_runtime_56743_2 = coreclr_test({
    name: "Runtime_56743_2",
    srcs: ["Runtime_56743_2.cs"],
    allowUnsafe: true,
    optimize: true,
});

@@public
export const jIT_Regression_JitBlue_Runtime_56743_runtime_56743_1 = coreclr_test({
    name: "Runtime_56743_1",
    srcs: ["Runtime_56743_1.cs"],
    allowUnsafe: true,
    optimize: true,
});

@@public
export const jIT_Regression_JitBlue_Runtime_56743_runtime_56743_0 = coreclr_test({
    name: "Runtime_56743_0",
    srcs: ["Runtime_56743_0.cs"],
    optimize: true,
});
