// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const baseservices_threading_generics_TimerCallback_thread01_TimerCallback = coreclr_test({
    name: "thread01_TimerCallback",
    srcs: ["thread01.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread02_TimerCallback = coreclr_test({
    name: "thread02_TimerCallback",
    srcs: ["thread02.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread03_TimerCallback = coreclr_test({
    name: "thread03_TimerCallback",
    srcs: ["thread03.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread04_TimerCallback = coreclr_test({
    name: "thread04_TimerCallback",
    srcs: ["thread04.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread05_TimerCallback = coreclr_test({
    name: "thread05_TimerCallback",
    srcs: ["thread05.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread06_TimerCallback = coreclr_test({
    name: "thread06_TimerCallback",
    srcs: ["thread06.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread07_TimerCallback = coreclr_test({
    name: "thread07_TimerCallback",
    srcs: ["thread07.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread08_TimerCallback = coreclr_test({
    name: "thread08_TimerCallback",
    srcs: ["thread08.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread09_TimerCallback = coreclr_test({
    name: "thread09_TimerCallback",
    srcs: ["thread09.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread10_TimerCallback = coreclr_test({
    name: "thread10_TimerCallback",
    srcs: ["thread10.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread11_TimerCallback = coreclr_test({
    name: "thread11_TimerCallback",
    srcs: ["thread11.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread12_TimerCallback = coreclr_test({
    name: "thread12_TimerCallback",
    srcs: ["thread12.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread13_TimerCallback = coreclr_test({
    name: "thread13_TimerCallback",
    srcs: ["thread13.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread14_TimerCallback = coreclr_test({
    name: "thread14_TimerCallback",
    srcs: ["thread14.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread15_TimerCallback = coreclr_test({
    name: "thread15_TimerCallback",
    srcs: ["thread15.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread16_TimerCallback = coreclr_test({
    name: "thread16_TimerCallback",
    srcs: ["thread16.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread17_TimerCallback = coreclr_test({
    name: "thread17_TimerCallback",
    srcs: ["thread17.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread18_TimerCallback = coreclr_test({
    name: "thread18_TimerCallback",
    srcs: ["thread18.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread19_TimerCallback = coreclr_test({
    name: "thread19_TimerCallback",
    srcs: ["thread19.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread20_TimerCallback = coreclr_test({
    name: "thread20_TimerCallback",
    srcs: ["thread20.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread21_TimerCallback = coreclr_test({
    name: "thread21_TimerCallback",
    srcs: ["thread21.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread22_TimerCallback = coreclr_test({
    name: "thread22_TimerCallback",
    srcs: ["thread22.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread23_TimerCallback = coreclr_test({
    name: "thread23_TimerCallback",
    srcs: ["thread23.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread24_TimerCallback = coreclr_test({
    name: "thread24_TimerCallback",
    srcs: ["thread24.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread25_TimerCallback = coreclr_test({
    name: "thread25_TimerCallback",
    srcs: ["thread25.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread26_TimerCallback = coreclr_test({
    name: "thread26_TimerCallback",
    srcs: ["thread26.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread27_TimerCallback = coreclr_test({
    name: "thread27_TimerCallback",
    srcs: ["thread27.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread28_TimerCallback = coreclr_test({
    name: "thread28_TimerCallback",
    srcs: ["thread28.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread29_TimerCallback = coreclr_test({
    name: "thread29_TimerCallback",
    srcs: ["thread29.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_thread30_TimerCallback = coreclr_test({
    name: "thread30_TimerCallback",
    srcs: ["thread30.cs"],
    pri: 1,
    size: "medium",
});

@@public
export const baseservices_threading_generics_TimerCallback_tighttimercallback = coreclr_test({
    name: "tighttimercallback",
    srcs: ["tighttimercallback.cs"],
    pri: 1,
    size: "medium",
});
