// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Directed_FaultHandlers_Nesting_nesting = il_coreclr_test({
    name: "Nesting",
    srcs: ["Nesting.il"],
    debugType: "pdbonly",
    optimize: true,
    pri: 1,
    size: "medium",
});
