// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// ------------------------------------------------------------------------------
// Changes to this file must follow the https://aka.ms/api-review process.
// ------------------------------------------------------------------------------

using System.Runtime.CompilerServices;

[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.CipherData))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.CipherReference))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.DataObject))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.DataReference))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.DSAKeyValue))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.EncryptedData))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.EncryptedKey))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.EncryptedReference))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.EncryptedType))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.EncryptedXml))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.EncryptionMethod))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.EncryptionProperty))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.EncryptionPropertyCollection))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.IRelDecryptor))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.KeyInfo))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.KeyInfoClause))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.KeyInfoEncryptedKey))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.KeyInfoName))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.KeyInfoNode))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.KeyInfoRetrievalMethod))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.KeyInfoX509Data))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.KeyReference))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.Reference))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.ReferenceList))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.RSAKeyValue))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.Signature))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.SignedInfo))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.SignedXml))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.Transform))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.TransformChain))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.XmlDecryptionTransform))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.XmlDsigBase64Transform))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.XmlDsigC14NTransform))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.XmlDsigC14NWithCommentsTransform))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.XmlDsigEnvelopedSignatureTransform))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.XmlDsigExcC14NTransform))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.XmlDsigExcC14NWithCommentsTransform))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.XmlDsigXPathTransform))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.XmlDsigXsltTransform))]
[assembly: TypeForwardedTo(typeof(System.Security.Cryptography.Xml.XmlLicenseTransform))]
