// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const loader_classloader_regressions_208900_bug = coreclr_test({
    name: "bug",
    srcs: ["bug.cs"],
    pri: 1,
    size: "medium",
});
