// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_opt_RangeChecks_overflow = coreclr_test({
    name: "Overflow",
    srcs: ["Overflow.cs"],
    optimize: true,
});

@@public
export const jIT_opt_RangeChecks_modLength = coreclr_test({
    name: "ModLength",
    srcs: ["ModLength.cs"],
    optimize: true,
});
