<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(NetCoreAppToolCurrent)</TargetFramework>

    <PackageType>Template</PackageType>
    <PackageId>Microsoft.NET.Runtime.WebAssembly.Templates.net$(NetCoreAppCurrentVersion.Split('.')[0])</PackageId>
    <Title>WebAssembly Templates</Title>
    <Authors>Microsoft</Authors>
    <Description>Templates to create WebAssembly projects.</Description>
    <PackageTags>dotnet-new;templates</PackageTags>

    <IncludeContentInPack>true</IncludeContentInPack>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <ContentTargetFolders>content</ContentTargetFolders>
    <NoWarn>$(NoWarn);NU5128</NoWarn>
    <IsPackable>true</IsPackable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <!-- This template package uses a different PackageId per major version so we can't validate it against the baseline -->
    <DisablePackageBaselineValidation>true</DisablePackageBaselineValidation>
    <!-- TODO: Add package readme -->
    <EnableDefaultPackageReadmeFile>false</EnableDefaultPackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="browser\**\*" Exclude="browser\**\bin\**;browser\**\obj\**" PackagePath="content\templates\browser\%(RecursiveDir)%(Filename)%(Extension)" />
    <Content Include="$(IntermediateOutputPath)template.json" PackagePath="content\templates\browser\.template.config\template.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.Build.Tasks.Templating" Version="$(MicrosoftDotNetBuildTasksTemplatingVersion)" PrivateAssets="All" />
  </ItemGroup>

  <Target Name="GenerateTemplateConfig" BeforeTargets="CoreCompile">
    <GenerateFileFromTemplate
      TemplateFile="browser.template.json.in"
      Properties="NetCoreAppCurrentVersion=$(NetCoreAppCurrentVersion)"
      OutputPath="$(IntermediateOutputPath)template.json" />

    <ItemGroup>
      <FileWrites Include="$(IntermediateOutputPath)template.json" />
    </ItemGroup>
  </Target>

  <Target Name="CreateManifestResourceNames" />
  <Target Name="CoreCompile" />

</Project>
