.\" 
.\" mint manual page.
.\" (C) Ximian, Inc. 
.\" Author:
.\"   Miguel de Icaza (miguel@gnu.org)
.\"
.TH Mono "Mono 1.0"
.SH NAME
mint \- Mono ECMA-CLI interpreter.
.SH SYNOPSIS
.PP
.B mint
[\-\-help] [\-\-opcode\-count] [\-\-trace] [\-\-traceops] [\-\-profile]
[\-\-config filename] [\-\-debug method]
program.exe [arguments...]
.SH DESCRIPTION
The \fImint\fP program is an interpreter for ECMA CLI byte codes.  It
executes the bytecodes contains in 
.I program.exe
and optionally passes
the
.I arguments
to it. 
.SH OPTIONS
The following Generic options are supported:
.TP
.I "--help", "-h"
Displays usage instructions.
.TP
.I "--config filename"
Load the specified configuration file instead of the default one(s).
The default files are /etc/mono/config and ~/.mono/config or the file
specified in the MONO_CONFIG environment variable, if set.
.TP
.I "--trace"
Traces execution showing when methods are entered and left.
.I "--traceops"
Traces execution at the instruction level and displays the stack contents.
.I "--traceclassinit"
Shows when classes are initialized
.TP
.I "--noptr"
Suppresses printing of pointer addresses in trace output.
.TP
.I "--profile"
Performs runtime profiling of the code and displays statistics at the
end of execution.
.TP
.I "--opcode-count"
Displays the number of opcodes executed.
.TP
.I "--dieonex"
Aborts execution upon hitting an exception.
.TP
.I "--debug method"
Debugs the method whose name is `method'.  You can specify the method
like this: `class:method' or `class::method'
.TP
.I "--opcode-count"
Displays the number of opcodes executed
.PP
.SH ENVIRONMENT VARIABLES
.TP
.I "MONO_PATH"
Provides a search path to mono and mint where to look for library files.
Directories are separated by the platform path separator (colons on unix). Example:
.B /home/username/lib:/usr/local/mono/lib
.PP
.SH FILES
Assemblies are lodaed from the installation lib directory.  If you set
`prefix' to /usr, the assemblies will be located in /usr/lib.
.PP
/etc/mono/config, ~/.mono/config
.IP
Mono runtime configuration file.  See the mono-config(5) manual page
for more information.
.SH MAILING LISTS
Visit http://mail.ximian.com/mailman/mono-list for details.
.SH WEB SITE
Visit: http://www.go-mono.com for details
.SH SEE ALSO
.BR mono(1), monodis(1)
