// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Regression_VS_ia64_JIT_V1_2_Beta1_b91074_b91074 = coreclr_test({
    name: "b91074",
    srcs: ["pack8.cs"],
    debugType: "pdbonly",
    pri: 1,
    size: "medium",
});
