#!/bin/sh
add_h4()
{
	sed -e 's,^\(.*\)$,<h4><a name="api:\1">\1</a></h4>,'
}

dir=`dirname $0`
sh $dir/produce-lists || exit 1
cat $dir/public-api $dir/wapi > $dir/current-api
for i in `cat $dir/current-api`; do
	if grep "api:$i" $dir/sources/mono-api-*.html > /dev/null; then
		true;
	else
		echo "Missing: $i from the template";
	fi
done
