#!/bin/sh
dir=`dirname $0`

for file in $*; 
do
	perl $dir/exdoc $file | grep ^Function:  | sed -e 's/Function: //' -e 's/://' > documented
	nm `dirname $file`/.libs/`basename $file .c`.o | grep ' T ' | sed 's/.* T //' > public
	for i in `cat public`; do
		if grep $i documented > /dev/null; then
			true
		else
			echo $i is not documented | grep -v ves_icall
		fi
	done
done
