// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_Directed_throwbox_rethrow = il_coreclr_test({
    name: "rethrow",
    srcs: ["rethrow.il"],
    debugType: "pdbonly",
    optimize: true,
});

@@public
export const jIT_Directed_throwbox_finally_ = il_coreclr_test({
    name: "finally",
    srcs: ["finally.il"],
    debugType: "pdbonly",
    optimize: true,
});

@@public
export const jIT_Directed_throwbox_filter = il_coreclr_test({
    name: "filter",
    srcs: ["filter.il"],
    debugType: "pdbonly",
    optimize: true,
});

@@public
export const jIT_Directed_throwbox_fault_throwbox = il_coreclr_test({
    name: "fault_throwbox",
    srcs: ["fault.il"],
    debugType: "pdbonly",
    optimize: true,
});
