public class EntryPointMain
{
    public static int Main(string[] args)
    {
        RuntimeLibrariesTest.Internal.TestInfo[] tests = new RuntimeLibrariesTest.Internal.TestInfo[]{new RuntimeLibrariesTest.Internal.TestInfo("My.TestActivatorCreateInstance", () => global::My.TestActivatorCreateInstance(), null),
new RuntimeLibrariesTest.Internal.TestInfo("My.TestDefaultCtorInLazyGenerics", () => global::My.TestDefaultCtorInLazyGenerics(), null),
new RuntimeLibrariesTest.Internal.TestInfo("Expressions.ExpressionsTesting.TestLdTokenResults", () => global::Expressions.ExpressionsTesting.TestLdTokenResults(), null),
new RuntimeLibrariesTest.Internal.TestInfo("Expressions.ExpressionsTesting.TestLdTokenResultsWithStructTypes", () => global::Expressions.ExpressionsTesting.TestLdTokenResultsWithStructTypes(), null),
new RuntimeLibrariesTest.Internal.TestInfo("MakeGenMethod.Test.TestInstanceMethod", () => global::MakeGenMethod.Test.TestInstanceMethod(), null),
new RuntimeLibrariesTest.Internal.TestInfo("MakeGenMethod.Test.TestStaticMethod", () => global::MakeGenMethod.Test.TestStaticMethod(), null),
new RuntimeLibrariesTest.Internal.TestInfo("MakeGenMethod.Test.TestGenericMethodsWithEnumParametersHavingDefaultValues", () => global::MakeGenMethod.Test.TestGenericMethodsWithEnumParametersHavingDefaultValues(), null),
new RuntimeLibrariesTest.Internal.TestInfo("MakeGenMethod.Test.TestNoDictionaries", () => global::MakeGenMethod.Test.TestNoDictionaries(), null),
new RuntimeLibrariesTest.Internal.TestInfo("MakeGenMethod.Test.TestGenMethodOnGenType", () => global::MakeGenMethod.Test.TestGenMethodOnGenType(), null),
new RuntimeLibrariesTest.Internal.TestInfo("MakeGenMethod.Test.TestReverseLookups", () => global::MakeGenMethod.Test.TestReverseLookups(), null),
new RuntimeLibrariesTest.Internal.TestInfo("MakeGenMethod.Test.TestReverseLookupsWithArrayArg", () => global::MakeGenMethod.Test.TestReverseLookupsWithArrayArg(), null),
new RuntimeLibrariesTest.Internal.TestInfo("ArrayTests.ArrayTests.TestArrays", () => global::ArrayTests.ArrayTests.TestArrays(), null),
new RuntimeLibrariesTest.Internal.TestInfo("ArrayTests.ArrayTests.TestDynamicArrays", () => global::ArrayTests.ArrayTests.TestDynamicArrays(), null),
new RuntimeLibrariesTest.Internal.TestInfo("ArrayTests.ArrayTests.TestMDArrays", () => global::ArrayTests.ArrayTests.TestMDArrays(), null),
new RuntimeLibrariesTest.Internal.TestInfo("ArrayTests.ArrayTests.TestArrayIndexOfNullableStructOfCanon_USG", () => global::ArrayTests.ArrayTests.TestArrayIndexOfNullableStructOfCanon_USG(), null),
new RuntimeLibrariesTest.Internal.TestInfo("ArrayTests.ArrayTests.TestArrayIndexOfNullableStructOfCanon_Canon", () => global::ArrayTests.ArrayTests.TestArrayIndexOfNullableStructOfCanon_Canon(), null),
new RuntimeLibrariesTest.Internal.TestInfo("BlockedTypesTests.TestBlockedTypes", () => global::BlockedTypesTests.TestBlockedTypes(), null),
new RuntimeLibrariesTest.Internal.TestInfo("ConstraintsTests.TestInvalidInstantiations", () => global::ConstraintsTests.TestInvalidInstantiations(), null),
new RuntimeLibrariesTest.Internal.TestInfo("ConstraintsTests.TestSpecialConstraints", () => global::ConstraintsTests.TestSpecialConstraints(), null),
new RuntimeLibrariesTest.Internal.TestInfo("ConstraintsTests.TestTypeConstraints", () => global::ConstraintsTests.TestTypeConstraints(), null),
new RuntimeLibrariesTest.Internal.TestInfo("MethodConstraintsTests.TestInvalidInstantiations", () => global::MethodConstraintsTests.TestInvalidInstantiations(), null),
new RuntimeLibrariesTest.Internal.TestInfo("MethodConstraintsTests.TestSpecialConstraints", () => global::MethodConstraintsTests.TestSpecialConstraints(), null),
new RuntimeLibrariesTest.Internal.TestInfo("MethodConstraintsTests.TestTypeConstraints", () => global::MethodConstraintsTests.TestTypeConstraints(), null),
new RuntimeLibrariesTest.Internal.TestInfo("MethodConstraintsTests.TestMDTypeConstraints", () => global::MethodConstraintsTests.TestMDTypeConstraints(), null),
new RuntimeLibrariesTest.Internal.TestInfo("Dictionaries.DictionariesTest.TestBasicDictionaryEntryTypes", () => global::Dictionaries.DictionariesTest.TestBasicDictionaryEntryTypes(), null),
new RuntimeLibrariesTest.Internal.TestInfo("Dictionaries.DictionariesTest.StaticMethodFolding_Test", () => global::Dictionaries.DictionariesTest.StaticMethodFolding_Test(), null),
new RuntimeLibrariesTest.Internal.TestInfo("Dictionaries.DictionariesTest.NullableTesting", () => global::Dictionaries.DictionariesTest.NullableTesting(), null),
new RuntimeLibrariesTest.Internal.TestInfo("TypeDictTestTypes.DictionariesTest.TestGenericTypeDictionary", () => global::TypeDictTestTypes.DictionariesTest.TestGenericTypeDictionary(), null),
new RuntimeLibrariesTest.Internal.TestInfo("MethodDictionaryTest.DictionariesTest.TestMethodDictionaries", () => global::MethodDictionaryTest.DictionariesTest.TestMethodDictionaries(), null),
new RuntimeLibrariesTest.Internal.TestInfo("BaseTypeDict.Test.TestVirtCallTwoGenParams", () => global::BaseTypeDict.Test.TestVirtCallTwoGenParams(), null),
new RuntimeLibrariesTest.Internal.TestInfo("BaseTypeDict.Test.TestUsingPrimitiveTypes", () => global::BaseTypeDict.Test.TestUsingPrimitiveTypes(), null),
new RuntimeLibrariesTest.Internal.TestInfo("BaseTypeDict.Test.TestBaseTypeDictionaries", () => global::BaseTypeDict.Test.TestBaseTypeDictionaries(), null),
new RuntimeLibrariesTest.Internal.TestInfo("DictDependency.Test.TestIndirectDictionaryDependencies", () => global::DictDependency.Test.TestIndirectDictionaryDependencies(), null),
new RuntimeLibrariesTest.Internal.TestInfo("CtorDict.DictionaryTesting.TestAllocationDictionaryEntryTypes", () => global::CtorDict.DictionaryTesting.TestAllocationDictionaryEntryTypes(), null),
new RuntimeLibrariesTest.Internal.TestInfo("MethodAndUnboxingStubTesting.Test.TestNoConstraints", () => global::MethodAndUnboxingStubTesting.Test.TestNoConstraints(), null),
new RuntimeLibrariesTest.Internal.TestInfo("ExistingInstantiations.Test.TestWithExistingInst", () => global::ExistingInstantiations.Test.TestWithExistingInst(), null),
new RuntimeLibrariesTest.Internal.TestInfo("ExistingInstantiations.Test.TestInstantiationsWithExistingArrayTypeArgs", () => global::ExistingInstantiations.Test.TestInstantiationsWithExistingArrayTypeArgs(), null),
new RuntimeLibrariesTest.Internal.TestInfo("TemplateDependencyFromGenArgs.TestRunner.TemplateDependencyFromGenArgsTest", () => global::TemplateDependencyFromGenArgs.TestRunner.TemplateDependencyFromGenArgsTest(), null),
#if UNIVERSAL_GENERICS
new RuntimeLibrariesTest.Internal.TestInfo("FieldLayoutTests.TestFieldLayoutMatchesBetweenStaticAndDynamic_Long", () => global::FieldLayoutTests.TestFieldLayoutMatchesBetweenStaticAndDynamic_Long(), null),
new RuntimeLibrariesTest.Internal.TestInfo("FieldLayoutTests.TestFieldLayoutMatchesBetweenStaticAndDynamic_Int64Enum", () => global::FieldLayoutTests.TestFieldLayoutMatchesBetweenStaticAndDynamic_Int64Enum(), null),
new RuntimeLibrariesTest.Internal.TestInfo("FieldLayoutTests.TestBoxingUSGCreatedNullable", () => global::FieldLayoutTests.TestBoxingUSGCreatedNullable(), null),
#endif
new RuntimeLibrariesTest.Internal.TestInfo("FieldReflectionTests.TestInstanceFieldsOnDerivedType", () => global::FieldReflectionTests.TestInstanceFieldsOnDerivedType(), null),
new RuntimeLibrariesTest.Internal.TestInfo("FieldReflectionTests.TestInstanceFields", () => global::FieldReflectionTests.TestInstanceFields(), null),
new RuntimeLibrariesTest.Internal.TestInfo("FieldReflectionTests.TestStaticFields", () => global::FieldReflectionTests.TestStaticFields(), null),
new RuntimeLibrariesTest.Internal.TestInfo("FieldReflectionTests.TestInitializedStaticFields", () => global::FieldReflectionTests.TestInitializedStaticFields(), null),
new RuntimeLibrariesTest.Internal.TestInfo("FieldReflectionTests.TestFieldSetValueOnInstantiationsThatAlreadyExistButAreNotKnownToReflection", () => global::FieldReflectionTests.TestFieldSetValueOnInstantiationsThatAlreadyExistButAreNotKnownToReflection(), null),
new RuntimeLibrariesTest.Internal.TestInfo("InterfacesTests.TestGenericCollapsingInInterfaceMap", () => global::InterfacesTests.TestGenericCollapsingInInterfaceMap(), null),
new RuntimeLibrariesTest.Internal.TestInfo("InterfacesTests.TestImplementedInterfaces", () => global::InterfacesTests.TestImplementedInterfaces(), null),
new RuntimeLibrariesTest.Internal.TestInfo("InterfacesTests.TestBaseType", () => global::InterfacesTests.TestBaseType(), null),
new RuntimeLibrariesTest.Internal.TestInfo("InterfacesTests.TestInterfaceInvoke", () => global::InterfacesTests.TestInterfaceInvoke(), null),
new RuntimeLibrariesTest.Internal.TestInfo("InterfacesTests.TestConstrainedCall", () => global::InterfacesTests.TestConstrainedCall(), null),
#if !MULTIMODULE_BUILD
new RuntimeLibrariesTest.Internal.TestInfo("DynamicListTests.TestGetRange", () => global::DynamicListTests.TestGetRange(), null),
new RuntimeLibrariesTest.Internal.TestInfo("DynamicListTests.TestAddRange", () => global::DynamicListTests.TestAddRange(), null),
new RuntimeLibrariesTest.Internal.TestInfo("DynamicListTests.TestAddRemove", () => global::DynamicListTests.TestAddRemove(), null),
new RuntimeLibrariesTest.Internal.TestInfo("DynamicListTests.TestIListOfT", () => global::DynamicListTests.TestIListOfT(), null),
new RuntimeLibrariesTest.Internal.TestInfo("DynamicListTests.TestICollectionOfT", () => global::DynamicListTests.TestICollectionOfT(), null),
new RuntimeLibrariesTest.Internal.TestInfo("DynamicListTests.TestIList", () => global::DynamicListTests.TestIList(), null),
new RuntimeLibrariesTest.Internal.TestInfo("DynamicListTests.TestICollection", () => global::DynamicListTests.TestICollection(), null),
new RuntimeLibrariesTest.Internal.TestInfo("DynamicListTests.TestIReadOnlyListOfT", () => global::DynamicListTests.TestIReadOnlyListOfT(), null),
new RuntimeLibrariesTest.Internal.TestInfo("DynamicListTests.TestIReadOnlyCollectionOfT", () => global::DynamicListTests.TestIReadOnlyCollectionOfT(), null),
new RuntimeLibrariesTest.Internal.TestInfo("DynamicListTests.TestToArray", () => global::DynamicListTests.TestToArray(), null),
new RuntimeLibrariesTest.Internal.TestInfo("DynamicListTests.TestContains", () => global::DynamicListTests.TestContains(), null),
new RuntimeLibrariesTest.Internal.TestInfo("DynamicListTests.TestSortWithComparison", () => global::DynamicListTests.TestSortWithComparison(), null),
new RuntimeLibrariesTest.Internal.TestInfo("DynamicListTests.TestSortWithComparer", () => global::DynamicListTests.TestSortWithComparer(), null),
#endif
//new RuntimeLibrariesTest.Internal.TestInfo("RdExperienceTests.TestRdExperience", () => global::RdExperienceTests.TestRdExperience(), null),
new RuntimeLibrariesTest.Internal.TestInfo("StaticsTests.TestStatics", () => global::StaticsTests.TestStatics(), null),
new RuntimeLibrariesTest.Internal.TestInfo("ThreadLocalStatics.TLSTesting.ThreadLocalStatics_Test", () => global::ThreadLocalStatics.TLSTesting.ThreadLocalStatics_Test(), null),
#if UNIVERSAL_GENERICS
new RuntimeLibrariesTest.Internal.TestInfo("UnivConstCalls.Test.TestRefTypeCallsOnNonGenClass", () => global::UnivConstCalls.Test.TestRefTypeCallsOnNonGenClass(), null),
new RuntimeLibrariesTest.Internal.TestInfo("UnivConstCalls.Test.TestUSCCallsOnNonGenStruct", () => global::UnivConstCalls.Test.TestUSCCallsOnNonGenStruct(), null),
new RuntimeLibrariesTest.Internal.TestInfo("UnivConstCalls.Test.TestUSCCallsOnSharedGenStruct", () => global::UnivConstCalls.Test.TestUSCCallsOnSharedGenStruct(), null),
new RuntimeLibrariesTest.Internal.TestInfo("UnivConstCalls.Test.TestUSCCallsOnUSCGenStruct", () => global::UnivConstCalls.Test.TestUSCCallsOnUSCGenStruct(), null),
new RuntimeLibrariesTest.Internal.TestInfo("UnivConstCalls.Test.TestUSCNonGenInterfaceCallsOnStructs", () => global::UnivConstCalls.Test.TestUSCNonGenInterfaceCallsOnStructs(), null),
new RuntimeLibrariesTest.Internal.TestInfo("UniversalGen.Test.TestInterlockedPrimitives", () => global::UniversalGen.Test.TestInterlockedPrimitives(), null),
new RuntimeLibrariesTest.Internal.TestInfo("UniversalGen.Test.TestArraysAndGC", () => global::UniversalGen.Test.TestArraysAndGC(), null),
new RuntimeLibrariesTest.Internal.TestInfo("UniversalGen.Test.TestUSGByRefFunctionCalls", () => global::UniversalGen.Test.TestUSGByRefFunctionCalls(), null),
new RuntimeLibrariesTest.Internal.TestInfo("UniversalGen.Test.TestUSGSamples", () => global::UniversalGen.Test.TestUSGSamples(), null),
new RuntimeLibrariesTest.Internal.TestInfo("UniversalGen.Test.TestMakeGenericType", () => global::UniversalGen.Test.TestMakeGenericType(), null),
new RuntimeLibrariesTest.Internal.TestInfo("UniversalGen.Test.TestUSCInstanceFieldUsage", () => global::UniversalGen.Test.TestUSCInstanceFieldUsage(), null),
new RuntimeLibrariesTest.Internal.TestInfo("UniversalGen.Test.TestUSCStaticFieldUsage", () => global::UniversalGen.Test.TestUSCStaticFieldUsage(), null),
new RuntimeLibrariesTest.Internal.TestInfo("UniversalGen.Test.TestUSCThreadStaticFieldUsage", () => global::UniversalGen.Test.TestUSCThreadStaticFieldUsage(), null),
new RuntimeLibrariesTest.Internal.TestInfo("UniversalGen.Test.TestUSCStaticFieldLayoutCompat", () => global::UniversalGen.Test.TestUSCStaticFieldLayoutCompat(), null),
new RuntimeLibrariesTest.Internal.TestInfo("UniversalGen.Test.TestUSCClassConstructorImplicit", () => global::UniversalGen.Test.TestUSCClassConstructorImplicit(), null),
new RuntimeLibrariesTest.Internal.TestInfo("UniversalGen.Test.TestUSCClassConstructorExplicit", () => global::UniversalGen.Test.TestUSCClassConstructorExplicit(), null),
new RuntimeLibrariesTest.Internal.TestInfo("UniversalGen.Test.TestUniversalGenericsGvmCall", () => global::UniversalGen.Test.TestUniversalGenericsGvmCall(), null),
new RuntimeLibrariesTest.Internal.TestInfo("PartialUSC.Test.TestVirtualCallsPartialUSGVTableMismatch", () => global::PartialUSC.Test.TestVirtualCallsPartialUSGVTableMismatch(), null),
new RuntimeLibrariesTest.Internal.TestInfo("PartialUSC.Test.TestVirtualCalls", () => global::PartialUSC.Test.TestVirtualCalls(), null),
new RuntimeLibrariesTest.Internal.TestInfo("VirtualCalls.Test.TestVirtualCalls", () => global::VirtualCalls.Test.TestVirtualCalls(), null),
new RuntimeLibrariesTest.Internal.TestInfo("CallingConvention.Test.TestInstancesOfKnownAndUnknownSizes", () => global::CallingConvention.Test.TestInstancesOfKnownAndUnknownSizes(), null),
new RuntimeLibrariesTest.Internal.TestInfo("CallingConvention.Test.TestCallInstanceFunction", () => global::CallingConvention.Test.TestCallInstanceFunction(), null),
new RuntimeLibrariesTest.Internal.TestInfo("CallingConvention.Test.TestCallInterface", () => global::CallingConvention.Test.TestCallInterface(), null),
new RuntimeLibrariesTest.Internal.TestInfo("CallingConvention.Test.CallingConventionTest", () => global::CallingConvention.Test.CallingConventionTest(), null),
new RuntimeLibrariesTest.Internal.TestInfo("DynamicInvoke.Test.TestDynamicInvoke", () => global::DynamicInvoke.Test.TestDynamicInvoke(), null),
new RuntimeLibrariesTest.Internal.TestInfo("TypeLayout.Test.TestTypeGCDescs", () => global::TypeLayout.Test.TestTypeGCDescs(), null),
new RuntimeLibrariesTest.Internal.TestInfo("TypeLayout.Test.StructsOfPrimitives", () => global::TypeLayout.Test.StructsOfPrimitives(), null),
new RuntimeLibrariesTest.Internal.TestInfo("ActivatorCreateInstance.Test.TestCreateInstance", () => global::ActivatorCreateInstance.Test.TestCreateInstance(), null),
new RuntimeLibrariesTest.Internal.TestInfo("MultiThreadUSCCall.Test.CallsWithGCCollects", () => global::MultiThreadUSCCall.Test.CallsWithGCCollects(), null),
new RuntimeLibrariesTest.Internal.TestInfo("Heuristics.TestHeuristics.TestReflectionHeuristics", () => global::Heuristics.TestHeuristics.TestReflectionHeuristics(), null),
new RuntimeLibrariesTest.Internal.TestInfo("ArrayVarianceTest.Test.RunTest", () => global::ArrayVarianceTest.Test.RunTest(), null),
new RuntimeLibrariesTest.Internal.TestInfo("IsInstTest.TestRunner.RunIsInstAndCheckCastTest", () => global::IsInstTest.TestRunner.RunIsInstAndCheckCastTest(), null),
new RuntimeLibrariesTest.Internal.TestInfo("DelegateCallTest.TestRunner.TestCallMethodThroughUsgDelegate", () => global::DelegateCallTest.TestRunner.TestCallMethodThroughUsgDelegate(), null),
new RuntimeLibrariesTest.Internal.TestInfo("FieldLayoutBugRepro.Runner.EntryPoint", () => global::FieldLayoutBugRepro.Runner.EntryPoint(), null),
new RuntimeLibrariesTest.Internal.TestInfo("DelegateTest.TestRunner.TestMethodCellsWithUSGTargetsUsedOnNonUSGInstantiations", () => global::DelegateTest.TestRunner.TestMethodCellsWithUSGTargetsUsedOnNonUSGInstantiations(), null),
new RuntimeLibrariesTest.Internal.TestInfo("ArrayExceptionsTest.Runner.ArrayExceptionsTest_String_Object", () => global::ArrayExceptionsTest.Runner.ArrayExceptionsTest_String_Object(), null),
new RuntimeLibrariesTest.Internal.TestInfo("ArrayExceptionsTest.Runner.ArrayExceptionsTest_Int32_Int32", () => global::ArrayExceptionsTest.Runner.ArrayExceptionsTest_Int32_Int32(), null),
new RuntimeLibrariesTest.Internal.TestInfo("ArrayExceptionsTest.Runner.ArrayExceptionsTest_Int32_IntBasedEnum", () => global::ArrayExceptionsTest.Runner.ArrayExceptionsTest_Int32_IntBasedEnum(), null),
new RuntimeLibrariesTest.Internal.TestInfo("ArrayExceptionsTest.Runner.ArrayExceptionsTest_UInt32_Int32", () => global::ArrayExceptionsTest.Runner.ArrayExceptionsTest_UInt32_Int32(), null),
new RuntimeLibrariesTest.Internal.TestInfo("UnboxAnyTests.Runner.TestUnboxAnyToString", () => global::UnboxAnyTests.Runner.TestUnboxAnyToString(), null),
new RuntimeLibrariesTest.Internal.TestInfo("UnboxAnyTests.Runner.TestUnboxAnyToInt", () => global::UnboxAnyTests.Runner.TestUnboxAnyToInt(), null),
new RuntimeLibrariesTest.Internal.TestInfo("UnboxAnyTests.Runner.TestUnboxAnyToIntBasedEnum", () => global::UnboxAnyTests.Runner.TestUnboxAnyToIntBasedEnum(), null),
new RuntimeLibrariesTest.Internal.TestInfo("UnboxAnyTests.Runner.TestUnboxAnyToNullableInt", () => global::UnboxAnyTests.Runner.TestUnboxAnyToNullableInt(), null),
new RuntimeLibrariesTest.Internal.TestInfo("UnboxAnyTests.Runner.TestUnboxAnyToNullableIntBasedEnum", () => global::UnboxAnyTests.Runner.TestUnboxAnyToNullableIntBasedEnum(), null),
new RuntimeLibrariesTest.Internal.TestInfo("UnboxAnyTests.Runner.TestUnboxAnyToShort_NonUSG", () => global::UnboxAnyTests.Runner.TestUnboxAnyToShort_NonUSG(), null),
new RuntimeLibrariesTest.Internal.TestInfo("UnboxAnyTests.Runner.TestUnboxAnyToShortBasedEnum_NonUSG", () => global::UnboxAnyTests.Runner.TestUnboxAnyToShortBasedEnum_NonUSG(), null),
new RuntimeLibrariesTest.Internal.TestInfo("UnboxAnyTests.Runner.TestUnboxAnyToNullableShort_NonUSG", () => global::UnboxAnyTests.Runner.TestUnboxAnyToNullableShort_NonUSG(), null),
new RuntimeLibrariesTest.Internal.TestInfo("UnboxAnyTests.Runner.TestUnboxAnyToNullableShortBasedEnum_NonUSG", () => global::UnboxAnyTests.Runner.TestUnboxAnyToNullableShortBasedEnum_NonUSG(), null),
new RuntimeLibrariesTest.Internal.TestInfo("HFATest.Runner.HFATestEntryPoint", () => global::HFATest.Runner.HFATestEntryPoint(), null),
new RuntimeLibrariesTest.Internal.TestInfo("ComparerOfTTests.Runner.TestStructThatImplementsIComparable", () => global::ComparerOfTTests.Runner.TestStructThatImplementsIComparable(), null),
new RuntimeLibrariesTest.Internal.TestInfo("ComparerOfTTests.Runner.TestStructThatImplementsIComparableOfObject", () => global::ComparerOfTTests.Runner.TestStructThatImplementsIComparableOfObject(), null),
new RuntimeLibrariesTest.Internal.TestInfo("ComparerOfTTests.Runner.TestBoringStruct", () => global::ComparerOfTTests.Runner.TestBoringStruct(), null),
new RuntimeLibrariesTest.Internal.TestInfo("DefaultValueDelegateParameterTests.Runner.TestCallUniversalGenericDelegate", () => global::DefaultValueDelegateParameterTests.Runner.TestCallUniversalGenericDelegate(), null),
new RuntimeLibrariesTest.Internal.TestInfo("ArrayOfGenericStructGCTests.Runner.TestArrayOfGenericStructGCTests", () => global::ArrayOfGenericStructGCTests.Runner.TestArrayOfGenericStructGCTests(), null),
new RuntimeLibrariesTest.Internal.TestInfo("ArrayOfGenericStructGCTests.Runner.TestNonPointerSizedFinalField", () => global::ArrayOfGenericStructGCTests.Runner.TestNonPointerSizedFinalField(), null),
new RuntimeLibrariesTest.Internal.TestInfo("DelegatesToStructMethods.Runner.TestDelegateInvokeToMethods", () => global::DelegatesToStructMethods.Runner.TestDelegateInvokeToMethods(), null),
new RuntimeLibrariesTest.Internal.TestInfo("PartialUniversalGen.Test.TestOverrideMethodOnDerivedTypeWhereInstantiationArgsAreDifferentThanBaseType", () => global::PartialUniversalGen.Test.TestOverrideMethodOnDerivedTypeWhereInstantiationArgsAreDifferentThanBaseType(), null),
new RuntimeLibrariesTest.Internal.TestInfo("PartialUniversalGen.Test.TestUniversalGenericThatDerivesFromBaseInstantiatedOverArray", () => global::PartialUniversalGen.Test.TestUniversalGenericThatDerivesFromBaseInstantiatedOverArray(), null),
new RuntimeLibrariesTest.Internal.TestInfo("PartialUniversalGen.Test.TestUniversalGenericThatUsesCanonicalGeneric", () => global::PartialUniversalGen.Test.TestUniversalGenericThatUsesCanonicalGeneric(), null),
new RuntimeLibrariesTest.Internal.TestInfo("PartialUniversalGen.Test.TestUniversalGenericThatImplementsInterfaceOverArrayType", () => global::PartialUniversalGen.Test.TestUniversalGenericThatImplementsInterfaceOverArrayType(), null),
new RuntimeLibrariesTest.Internal.TestInfo("PartialUniversalGen.Test.TestUniversalGenericThatUsesCanonicalGenericMethod", () => global::PartialUniversalGen.Test.TestUniversalGenericThatUsesCanonicalGenericMethod(), null),
new RuntimeLibrariesTest.Internal.TestInfo("PartialUniversalGen.Test.TestUniversalGenericThatUsesCanonicalGenericMethodWithActivatorCreateInstance", () => global::PartialUniversalGen.Test.TestUniversalGenericThatUsesCanonicalGenericMethodWithActivatorCreateInstance(), null),
new RuntimeLibrariesTest.Internal.TestInfo("PartialUniversalGen.Test.TestUniversalGenericThatUsesCanonicalGenericType", () => global::PartialUniversalGen.Test.TestUniversalGenericThatUsesCanonicalGenericType(), null),
new RuntimeLibrariesTest.Internal.TestInfo("PartialUniversalGen.Test.TestUniversalGenericThatUsesCanonicalGenericMethodWithConstraints", () => global::PartialUniversalGen.Test.TestUniversalGenericThatUsesCanonicalGenericMethodWithConstraints(), null),
new RuntimeLibrariesTest.Internal.TestInfo("PartialUniversalGen.Test.TestDependenciesOfPartialUniversalCanonicalCode", () => global::PartialUniversalGen.Test.TestDependenciesOfPartialUniversalCanonicalCode(), null),
new RuntimeLibrariesTest.Internal.TestInfo("PartialUniversalGen.Test.TestCornerCaseSealedVTableSlot", () => global::PartialUniversalGen.Test.TestCornerCaseSealedVTableSlot(), null),
#endif
new RuntimeLibrariesTest.Internal.TestInfo("B282745.testIntMDArrayWithPointerLikeValues", () => global::B282745.testIntMDArrayWithPointerLikeValues(), null),
new RuntimeLibrariesTest.Internal.TestInfo("B282745.testLongMDArrayWithPointerLikeValues", () => global::B282745.testLongMDArrayWithPointerLikeValues(), null),
new RuntimeLibrariesTest.Internal.TestInfo("B282745.testMDArrayWithPointerLikeValuesOfKnownStructType", () => global::B282745.testMDArrayWithPointerLikeValuesOfKnownStructType(), null),
new RuntimeLibrariesTest.Internal.TestInfo("B282745.testMDArrayWithPointerLikeValuesOfKnownStructTypeLargerType", () => global::B282745.testMDArrayWithPointerLikeValuesOfKnownStructTypeLargerType(), null),
new RuntimeLibrariesTest.Internal.TestInfo("B282745.testMDArrayWithPointerLikeValuesOfUnknownStructTypeWithNonGCValuesAtZeroOffset", () => global::B282745.testMDArrayWithPointerLikeValuesOfUnknownStructTypeWithNonGCValuesAtZeroOffset(), null),
new RuntimeLibrariesTest.Internal.TestInfo("B282745.testMDArrayWithPointerLikeValuesOfUnknownStructReferenceType", () => global::B282745.testMDArrayWithPointerLikeValuesOfUnknownStructReferenceType(), null),
new RuntimeLibrariesTest.Internal.TestInfo("B282745.testMDArrayWithPointerLikeValuesOfUnknownStructPrimitiveType", () => global::B282745.testMDArrayWithPointerLikeValuesOfUnknownStructPrimitiveType(), null),
new RuntimeLibrariesTest.Internal.TestInfo("B282745.testMDArrayWith3Dimensions", () => global::B282745.testMDArrayWith3Dimensions(), null),
#if UNIVERSAL_GENERICS
new RuntimeLibrariesTest.Internal.TestInfo("B279085.TestB279085Repro", () => global::B279085.TestB279085Repro(), null),
#endif
new RuntimeLibrariesTest.Internal.TestInfo("GenericVirtualMethods.TestCalls", () => global::GenericVirtualMethods.TestCalls(), null),
new RuntimeLibrariesTest.Internal.TestInfo("GenericVirtualMethods.TestLdFtnToGetStaticMethodOnGenericType", () => global::GenericVirtualMethods.TestLdFtnToGetStaticMethodOnGenericType(), null),
new RuntimeLibrariesTest.Internal.TestInfo("GenericVirtualMethods.TestLdFtnToInstanceGenericMethod", () => global::GenericVirtualMethods.TestLdFtnToInstanceGenericMethod(), null),
// https://github.com/dotnet/corert/issues/3460
//new RuntimeLibrariesTest.Internal.TestInfo("GenericVirtualMethods.TestGenericExceptionType", () => global::GenericVirtualMethods.TestGenericExceptionType(), null),
new RuntimeLibrariesTest.Internal.TestInfo("GenericVirtualMethods.TestCoAndContraVariantCalls", () => global::GenericVirtualMethods.TestCoAndContraVariantCalls(), null)
};
        bool passed = RuntimeLibrariesTest.Internal.Runner.RunTests(tests, args);
        RuntimeLibrariesTest.Logger.LogInformation("Passed: {0}, Failed: {1}, Number of Tests Run: {2}", RuntimeLibrariesTest.Internal.Runner.NumPassedTests, RuntimeLibrariesTest.Internal.Runner.NumFailedTests, RuntimeLibrariesTest.Internal.Runner.NumTests);
        if (passed && RuntimeLibrariesTest.Internal.Runner.NumPassedTests > 0)
        {
            RuntimeLibrariesTest.Logger.LogInformation("All tests PASSED.");
            return 100;
        }
        else
        {
            RuntimeLibrariesTest.Logger.LogInformation("{0} tests FAILED!", RuntimeLibrariesTest.Internal.Runner.NumFailedTests);
            return RuntimeLibrariesTest.Internal.Runner.NumFailedTests == 100 ? 101 : RuntimeLibrariesTest.Internal.Runner.NumFailedTests;
        }
    }
}
