// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const jIT_HardwareIntrinsics_X86_Avx512_Avx512F_avx512F_handwritten_r = coreclr_test({
    name: "Avx512F_handwritten_r",
    srcs: ["HandwrittenProgram.cs", ...x86SharedSimpleUnOpDataTable.srcs, "ConvertToVector256Int32.Double.cs", "ConvertToVector256Single.Double.cs", "ConvertToVector256Int32WithTruncation.Double.cs", "ConvertToVector512Double.Single.cs", "ConvertToVector512Double.Int32.cs", "ConvertToVector512Int32.Byte.cs", "ConvertToVector512Int32.Int16.cs", "ConvertToVector512Int32.SByte.cs", "ConvertToVector512Int32.UInt16.cs", "ConvertToVector512Int64.Byte.cs", "ConvertToVector512Int64.Int16.cs", "ConvertToVector512Int64.Int32.cs", "ConvertToVector512Int64.SByte.cs", "ConvertToVector512Int64.UInt16.cs", "ConvertToVector512Int64.UInt32.cs", "ConvertToVector512UInt32.Byte.cs", "ConvertToVector512UInt32.Int16.cs", "ConvertToVector512UInt32.SByte.cs", "ConvertToVector512UInt32.UInt16.cs", "ConvertToVector512UInt64.Byte.cs", "ConvertToVector512UInt64.Int16.cs", "ConvertToVector512UInt64.Int32.cs", "ConvertToVector512UInt64.SByte.cs", "ConvertToVector512UInt64.UInt16.cs", "ConvertToVector512UInt64.UInt32.cs", "LoadAlignedVector512.cs", "LoadAlignedVector512NonTemporal.cs", "Sqrt.cs", "Store.cs", "StoreAligned.cs", "StoreAlignedNonTemporal.cs", "UnpackHigh.cs", "UnpackLow.cs", "EmbeddedRounding.Double.cs", "EmbeddedRounding.Single.cs"],
    tags: ["manual"],
});

@@public
export const jIT_HardwareIntrinsics_X86_Avx512_Avx512F_avx512F_handwritten_ro = coreclr_test({
    name: "Avx512F_handwritten_ro",
    srcs: ["HandwrittenProgram.cs", ...x86SharedSimpleUnOpDataTable.srcs, "ConvertToVector256Int32.Double.cs", "ConvertToVector256Single.Double.cs", "ConvertToVector256Int32WithTruncation.Double.cs", "ConvertToVector512Double.Single.cs", "ConvertToVector512Double.Int32.cs", "ConvertToVector512Int32.Byte.cs", "ConvertToVector512Int32.Int16.cs", "ConvertToVector512Int32.SByte.cs", "ConvertToVector512Int32.UInt16.cs", "ConvertToVector512Int64.Byte.cs", "ConvertToVector512Int64.Int16.cs", "ConvertToVector512Int64.Int32.cs", "ConvertToVector512Int64.SByte.cs", "ConvertToVector512Int64.UInt16.cs", "ConvertToVector512Int64.UInt32.cs", "ConvertToVector512UInt32.Byte.cs", "ConvertToVector512UInt32.Int16.cs", "ConvertToVector512UInt32.SByte.cs", "ConvertToVector512UInt32.UInt16.cs", "ConvertToVector512UInt64.Byte.cs", "ConvertToVector512UInt64.Int16.cs", "ConvertToVector512UInt64.Int32.cs", "ConvertToVector512UInt64.SByte.cs", "ConvertToVector512UInt64.UInt16.cs", "ConvertToVector512UInt64.UInt32.cs", "LoadAlignedVector512.cs", "LoadAlignedVector512NonTemporal.cs", "Sqrt.cs", "Store.cs", "StoreAligned.cs", "StoreAlignedNonTemporal.cs", "UnpackHigh.cs", "UnpackLow.cs", "EmbeddedRounding.Double.cs", "EmbeddedRounding.Single.cs"],
    optimize: true,
    tags: ["manual"],
});

@@public
export const jIT_HardwareIntrinsics_X86_Avx512_Avx512F_avx512F_r = coreclr_test({
    name: "Avx512F_r",
    srcs: ["Program.Avx512F.cs", ...x86SharedProgram.srcs],
});

@@public
export const jIT_HardwareIntrinsics_X86_Avx512_Avx512F_avx512F_ro = coreclr_test({
    name: "Avx512F_ro",
    srcs: ["Program.Avx512F.cs", ...x86SharedProgram.srcs],
    optimize: true,
});
