#ifndef VER_COMPANYNAME_STR
#define VER_COMPANYNAME_STR         ".NET Foundation"
#endif
#ifndef VER_FILEDESCRIPTION_STR
#define VER_FILEDESCRIPTION_STR     ".NET Runtime"
#endif
#ifndef VER_INTERNALNAME_STR
#define VER_INTERNALNAME_STR        VER_FILEDESCRIPTION_STR
#endif
#ifndef VER_ORIGINALFILENAME_STR
#define VER_ORIGINALFILENAME_STR    VER_FILEDESCRIPTION_STR
#endif
#ifndef VER_PRODUCTNAME_STR
#define VER_PRODUCTNAME_STR         ".NET"
#endif
#undef VER_PRODUCTVERSION
#define VER_PRODUCTVERSION          42,42,42,42424
#undef VER_PRODUCTVERSION_STR
#define VER_PRODUCTVERSION_STR      "42.42.42.42424"
#undef VER_FILEVERSION
#define VER_FILEVERSION             42,42,42,42424
#undef VER_FILEVERSION_STR
#define VER_FILEVERSION_STR         "42,42,42,42424"
#ifndef VER_LEGALCOPYRIGHT_STR
#define VER_LEGALCOPYRIGHT_STR      ".NET Foundation"
#endif
#ifndef VER_DEBUG
#define VER_DEBUG                   VS_FF_DEBUG
#endif
