// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Diagnostics.CodeAnalysis;

[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Dynamic.DynamicObject.MetaDynamic.IsOverridden(System.Reflection.MethodInfo)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Dynamic.Utils.DelegateHelpers.#cctor")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Dynamic.Utils.DelegateHelpers.GetCSharpThunk(System.Type,System.Boolean,System.Reflection.ParameterInfo[])")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Dynamic.Utils.TypeExtensions.GetAnyStaticMethodValidated(System.Type,System.String,System.Type[])")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Dynamic.Utils.TypeUtils.GetInvokeMethod(System.Type)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Dynamic.Utils.TypeUtils.GetUserDefinedCoercionMethod(System.Type,System.Type)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Compiler.AssemblyGen.DefineType(System.String,System.Type,System.Reflection.TypeAttributes)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Compiler.CompilerScope.ElementBoxStorage.#ctor(System.Linq.Expressions.Compiler.CompilerScope.Storage,System.Int32,System.Linq.Expressions.ParameterExpression)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Compiler.ILGen.EmitArray(System.Reflection.Emit.ILGenerator,System.Type)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Compiler.ILGen.EmitGetValue(System.Reflection.Emit.ILGenerator,System.Type)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Compiler.ILGen.EmitGetValueOrDefault(System.Reflection.Emit.ILGenerator,System.Type)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Compiler.ILGen.EmitHasValue(System.Reflection.Emit.ILGenerator,System.Type)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Compiler.ILGen.EmitNonNullableToNullableConversion(System.Reflection.Emit.ILGenerator,System.Type,System.Type,System.Boolean,System.Linq.Expressions.Compiler.ILocalCache)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Compiler.ILGen.EmitNullableToNullableConversion(System.Reflection.Emit.ILGenerator,System.Type,System.Type,System.Boolean,System.Linq.Expressions.Compiler.ILocalCache)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Compiler.ILGen.TryEmitILConstant(System.Reflection.Emit.ILGenerator,System.Object,System.Type)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Compiler.LambdaCompiler.AddressOf(System.Linq.Expressions.IndexExpression,System.Type)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Compiler.LambdaCompiler.AddressOf(System.Linq.Expressions.MethodCallExpression,System.Type)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Compiler.LambdaCompiler.EmitDynamicExpression(System.Linq.Expressions.Expression)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Compiler.LambdaCompiler.EmitGetArrayElement(System.Type)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Compiler.LambdaCompiler.EmitInvocationExpression(System.Linq.Expressions.Expression,System.Linq.Expressions.Compiler.LambdaCompiler.CompilationFlags)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Compiler.LambdaCompiler.EmitLift(System.Linq.Expressions.ExpressionType,System.Type,System.Linq.Expressions.MethodCallExpression,System.Linq.Expressions.ParameterExpression[],System.Linq.Expressions.Expression[])")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBinaryArithmetic(System.Linq.Expressions.ExpressionType,System.Type,System.Type,System.Type)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Compiler.LambdaCompiler.EmitSetArrayElement(System.Type)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnary(System.Linq.Expressions.UnaryExpression,System.Linq.Expressions.Compiler.LambdaCompiler.CompilationFlags)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnaryOperator(System.Linq.Expressions.ExpressionType,System.Type,System.Type)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Expression.ApplyTypeArgs(System.Reflection.MethodInfo,System.Type[])")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Expression.ArrayIndex(System.Linq.Expressions.Expression,System.Collections.Generic.IEnumerable{System.Linq.Expressions.Expression})")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Expression.CheckMethod(System.Reflection.MethodInfo,System.Reflection.MethodInfo)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Expression.Field(System.Linq.Expressions.Expression,System.String)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Expression.Field(System.Linq.Expressions.Expression,System.Type,System.String)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Expression.FindMethod(System.Type,System.String,System.Type[],System.Linq.Expressions.Expression[],System.Reflection.BindingFlags)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Expression.FindProperty(System.Type,System.String,System.Linq.Expressions.Expression[],System.Reflection.BindingFlags)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Expression.GetProperty(System.Reflection.MethodInfo,System.String,System.Int32)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Expression.New(System.Type)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Expression.Property(System.Linq.Expressions.Expression,System.String)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Expression.Property(System.Linq.Expressions.Expression,System.Type,System.String)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Expression.PropertyOrField(System.Linq.Expressions.Expression,System.String)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.ExpressionStringBuilder.VisitExtension(System.Linq.Expressions.Expression)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Interpreter.CallInstruction.GetArrayAccessor(System.Reflection.MethodInfo,System.Int32)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Interpreter.DefaultValueInstruction.Run(System.Linq.Expressions.Interpreter.InterpretedFrame)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Interpreter.InitializeLocalInstruction.MutableBox.Run(System.Linq.Expressions.Interpreter.InterpretedFrame)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Interpreter.InitializeLocalInstruction.MutableValue.Run(System.Linq.Expressions.Interpreter.InterpretedFrame)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Interpreter.LightCompiler.CompileAddress(System.Linq.Expressions.Expression,System.Int32)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Interpreter.LightCompiler.CompileIndexAssignment(System.Linq.Expressions.BinaryExpression,System.Boolean)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Interpreter.LightCompiler.CompileInvocationExpression(System.Linq.Expressions.Expression)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Interpreter.LightCompiler.CompileMultiDimArrayAccess(System.Linq.Expressions.Expression,System.Linq.Expressions.IArgumentProvider,System.Int32)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Interpreter.LightCompiler.EmitIndexGet(System.Linq.Expressions.IndexExpression)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Linq.Expressions.Interpreter.NullableMethodCallInstruction.GetValueOrDefault.Run(System.Linq.Expressions.Interpreter.InterpretedFrame)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Runtime.CompilerServices.CallSite`1.CreateCustomUpdateDelegate(System.Reflection.MethodInfo)")]
[assembly: UnconditionalSuppressMessage ("ILLinker", "IL2006", Scope = "member", Target = "M:System.Runtime.CompilerServices.CallSite`1.MakeUpdateDelegate")]
