<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Needed for CLRTestTargetUnsupported -->
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <!-- ControlledExecution is supported on CoreCLR only -->
    <CLRTestTargetUnsupported Condition="'$(RuntimeFlavor)' != 'coreclr'">true</CLRTestTargetUnsupported>
    <NativeAotIncompatible>true</NativeAotIncompatible>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="test135463.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="$(TestLibraryProjectPath)" />
  </ItemGroup>
</Project>
