// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.


@@public
export const interop_ExecInDefAppDom_InjectedCode_injectedCode = coreclr_test({
    name: "InjectedCode",
    srcs: ["InjectedCode.cs"],
});
