// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const gC_Features_Pinning_PinningOther_gCUtil_Pinning = CoreClr.coreclr_test({
    name: "GCUtil_Pinning",
    srcs: ["GCUtil.cs"],
});
