parameters:
  jobTemplate: ''
  variables: []
  osGroup: ''
  osSubgroup: ''
  archType: ''
  container: ''
  pool: ''
  platform: ''
  shouldContinueOnError: false
  jobParameters: {}

jobs:
- template: ${{ parameters.jobTemplate }}
  parameters:
    variables: ${{ parameters.variables }}
    osGroup: ${{ parameters.osGroup }}
    osSubgroup: ${{ parameters.osSubgroup }}
    archType: ${{ parameters.archType }}
    container: ${{ parameters.container }}
    pool: ${{ parameters.pool }}
    platform: ${{ parameters.platform }}
    shouldContinueOnError: ${{ parameters.shouldContinueOnError }}
    helixQueues:

    # Linux arm
    - ${{ if eq(parameters.platform, 'linux_arm') }}:
      - (Debian.13.Arm32.Open)AzureLinux.3.Arm64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-13-helix-arm32v7@sha256:7cd2e25705d98e003a2d4f2e10cbf27847f573d9548e06a72062028ed74f43a6

    # Linux arm64
    - ${{ if eq(parameters.platform, 'linux_arm64') }}:
      - (Ubuntu.2604.Arm64.Open)AzureLinux.3.Arm64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-26.04-helix-arm64v8@sha256:2a0400a4274972efa528f4447831ee25bc9f1c412868fde9152379ebcc895e42

    # Linux musl x64
    - ${{ if eq(parameters.platform, 'linux_musl_x64') }}:
      - (Alpine.324.Amd64.Open)AzureLinux.3.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.24-helix-amd64@sha256:a31c5d53a8c241bf7ad42e2dea0980e538ce1acee6968c11a61b9c23869460ed

    # Linux musl arm64
    - ${{ if and(eq(parameters.platform, 'linux_musl_arm64'), or(eq(parameters.jobParameters.isExtraPlatformsBuild, true), eq(parameters.jobParameters.includeAllPlatforms, true))) }}:
      - (Alpine.324.Arm64.Open)AzureLinux.3.Arm64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.24-helix-arm64v8@sha256:9c20e0a9728be8eebfc8aa5e096488229ffed20c6cd99c20b90637ac29284df2

    # Linux x64
    - ${{ if eq(parameters.platform, 'linux_x64') }}:
      - AzureLinux.3.Amd64.Open

    # OSX arm64
    - ${{ if eq(parameters.platform, 'osx_arm64') }}:
      - $(helix_macos_arm64)

    # OSX x64
    - ${{ if eq(parameters.platform, 'osx_x64') }}:
      - $(helix_macos_x64)

    # windows x64
    - ${{ if eq(parameters.platform, 'windows_x64') }}:
      - Windows.11.Amd64.Client.Open

    # windows x86
    - ${{ if eq(parameters.platform, 'windows_x86') }}:
      - Windows.11.Amd64.Client.Open

    # windows arm64
    - ${{ if eq(parameters.platform, 'windows_arm64') }}:
      - Windows.11.Arm64.Open

    ${{ insert }}: ${{ parameters.jobParameters }}
