parameters:
  jobTemplate: ''
  variables: []
  osGroup: ''
  osSubgroup: ''
  archType: ''
  container: ''
  pool: ''
  platform: ''
  shouldContinueOnError: false
  jobParameters: {}

jobs:
- template: ${{ parameters.jobTemplate }}
  parameters:
    variables: ${{ parameters.variables }}
    osGroup: ${{ parameters.osGroup }}
    osSubgroup: ${{ parameters.osSubgroup }}
    archType: ${{ parameters.archType }}
    container: ${{ parameters.container }}
    pool: ${{ parameters.pool }}
    platform: ${{ parameters.platform }}
    shouldContinueOnError: ${{ parameters.shouldContinueOnError }}
    helixQueues:

    # Linux arm
    - ${{ if eq(parameters.platform, 'linux_arm') }}:
      - (Debian.13.Arm32.Open)AzureLinux.3.Arm64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-13-helix-arm32v7@sha256:5782ea4fdaf8904d77a3c90b69eedbca1e6a93a6a8cef0ab77f9fcebbdcbfcd9

    # Linux arm64
    - ${{ if eq(parameters.platform, 'linux_arm64') }}:
      - (Ubuntu.2604.Arm64.Open)AzureLinux.3.Arm64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-26.04-helix-arm64v8@sha256:15dd63bebc0c199a8106d775d5b2c357e9e2856e05545acd5a719efd7aa43dba

    # Linux musl x64
    - ${{ if eq(parameters.platform, 'linux_musl_x64') }}:
      - (Alpine.324.Amd64.Open)AzureLinux.3.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.24-helix-amd64@sha256:240788457ec91460a35f6aa8d70bc1aaa7d1347d211fc5f5c0b35f648a33d7bd

    # Linux musl arm64
    - ${{ if and(eq(parameters.platform, 'linux_musl_arm64'), or(eq(parameters.jobParameters.isExtraPlatformsBuild, true), eq(parameters.jobParameters.includeAllPlatforms, true))) }}:
      - (Alpine.324.Arm64.Open)AzureLinux.3.Arm64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.24-helix-arm64v8@sha256:c0651a184147638e54b2f6a3c8f040274b1bf2deb0bf3e5c4513824598497ae0

    # Linux x64
    - ${{ if eq(parameters.platform, 'linux_x64') }}:
      - AzureLinux.3.Amd64.Open

    # OSX arm64
    - ${{ if eq(parameters.platform, 'osx_arm64') }}:
      - $(helix_macos_arm64)

    # OSX x64
    - ${{ if eq(parameters.platform, 'osx_x64') }}:
      - $(helix_macos_x64)

    # windows x64
    - ${{ if eq(parameters.platform, 'windows_x64') }}:
      - Windows.11.Amd64.Client.Open

    # windows x86
    - ${{ if eq(parameters.platform, 'windows_x86') }}:
      - Windows.11.Amd64.Client.Open

    # windows arm64
    - ${{ if eq(parameters.platform, 'windows_arm64') }}:
      - Windows.11.Arm64.Open

    ${{ insert }}: ${{ parameters.jobParameters }}
