"""Constants and parameters for the project."""

MIN_CSE = 3
MAX_CSE = 16

REWARD_SCALE = 10
REWARD_MIN = -1.0
REWARD_MAX = 1.0

FOUND_BEST_REWARD = 0.1
NO_BETTER_METHOD_REWARD = 0.01

INVALID_ACTION_PENALTY = -0.05
INVALID_ACTION_LIMIT = 20
