<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DebugType>None</DebugType>
    <Optimize>True</Optimize>
    <CLRTestPriority>1</CLRTestPriority>
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(MSBuildProjectName).cs" />
    <CLRTestEnvironmentVariable Include="DOTNET_JitDisasm" Value="Runtime_134475:*" />
  </ItemGroup>
</Project>
