trigger: none
pr:
  branches:
    include:
    - main
  paths:
    include:
    - eng/pipelines/coreclr/hardware-intrinsics-arm64.yml
    - eng/pipelines/coreclr/templates/jit-hardware-intrinsics-common.yml
    - src/coreclr/jit/*arm64*

variables:
  - template: /eng/pipelines/common/variables.yml
  - template: /eng/pipelines/helix-platforms.yml

extends:
  template:  /eng/pipelines/common/templates/pipeline-with-resources.yml
  parameters:
    isOfficialBuild: false
    stages:
    - stage: Build
      jobs:
      - template: /eng/pipelines/coreclr/templates/jit-hardware-intrinsics-common.yml
        parameters:
          platforms:
            - linux_arm64
          testBuildArgs: '-tree:JIT/HardwareIntrinsics'
