trigger: none

schedules:
- cron: "0 2 * * 0,1"
  displayName: Sat and Sun at 6:00 PM (UTC-8:00)
  branches:
    include:
    - main
  always: true

variables:
  - template: /eng/pipelines/common/variables.yml
  - name: enableHelixJobMonitor
    value: true
  - template: /eng/pipelines/helix-platforms.yml

extends:
  template:  /eng/pipelines/common/templates/pipeline-with-resources.yml
  parameters:
    stages:
    - stage: Build
      jobs:
      - ${{ if eq(variables['enableHelixJobMonitor'], true) }}:
        - template: /eng/common/core-templates/job/helix-job-monitor.yml
          parameters:
            helixAccessToken: $(HelixApiAccessToken)
            timeoutInMinutes: 900
            allowNoHelixJobs: true

      - template: /eng/pipelines/common/platform-matrix.yml
        parameters:
          jobTemplate: /eng/pipelines/common/global-build-job.yml
          helixQueuesTemplate: /eng/pipelines/coreclr/templates/helix-queues-setup.yml
          helixQueueGroup: ci
          buildConfig: checked
          platformGroup: gcstress
          platforms:
          # It is too early to include osx_arm64 in platform group gcstress
          # Adding it here will enable it also
          - osx_arm64
          jobParameters:
            buildArgs: -s clr+libs -c $(_BuildConfig) -lc Release
            testGroup: r2r-extra
            liveLibrariesBuildConfig: Release
            timeoutInMinutes: 840
            postBuildSteps:
              - template: /eng/pipelines/common/templates/runtimes/build-runtime-tests-and-send-to-helix.yml
                forwardedParameters:
                - testGroup
                parameters:
                  useHelixMonitor: ${{ variables.enableHelixJobMonitor }}
                  testBuildArgs: crossgen2
                  readyToRun: true
                  displayNameArgs: R2R
            extraVariablesTemplates:
              - template: /eng/pipelines/common/templates/runtimes/test-variables.yml
                forwardedParameters:
                - testGroup
                - liveLibrariesBuildConfig
