# This pipeline is a subset of crossgen2-outerloop.yml and is retained for manual runs.
trigger: none
pr: none

# schedules:
# - cron: "0 5 * * *"
#   displayName: Mon through Sun at 9:00 PM (UTC-8:00)
#   branches:
#     include:
#     - main
#   always: true

variables:
  - template: /eng/pipelines/common/variables.yml
  - name: enableHelixJobMonitor
    value: true
  - template: /eng/pipelines/helix-platforms.yml

extends:
  template:  /eng/pipelines/common/templates/pipeline-with-resources.yml
  parameters:
    stages:
    - stage: Build
      jobs:
      - ${{ if eq(variables['enableHelixJobMonitor'], true) }}:
        - template: /eng/common/core-templates/job/helix-job-monitor.yml
          parameters:
            helixAccessToken: $(HelixApiAccessToken)
            timeoutInMinutes: 660
            allowNoHelixJobs: true

      - template: /eng/pipelines/common/platform-matrix.yml
        parameters:
          jobTemplate: /eng/pipelines/common/global-build-job.yml
          helixQueuesTemplate: /eng/pipelines/coreclr/templates/helix-queues-setup.yml
          helixQueueGroup: ci
          buildConfig: checked
          platforms:
          - linux_arm
          - linux_arm64
          - linux_x64
          - osx_arm64
          - windows_arm64
          - windows_x64
          - windows_x86
          jobParameters:
            buildArgs: -s clr+libs -c $(_BuildConfig) -lc Release
            testGroup: outerloop
            liveLibrariesBuildConfig: Release
            timeoutInMinutes: 600
            postBuildSteps:
              - template: /eng/pipelines/common/templates/runtimes/build-runtime-tests-and-send-to-helix.yml
                forwardedParameters:
                - testGroup
                parameters:
                  useHelixMonitor: ${{ variables.enableHelixJobMonitor }}
                  testBuildArgs: crossgen2
                  readyToRun: true
                  displayNameArgs: R2R
                  timeoutPerTestInMinutes: 30
                  timeoutPerTestCollectionInMinutes: 90
            extraVariablesTemplates:
              - template: /eng/pipelines/common/templates/runtimes/test-variables.yml
                forwardedParameters:
                - testGroup
                - liveLibrariesBuildConfig
