TOP=$(realpath $(CURDIR)/../../..)
CONFIG?=Release
RUNTIME_CONFIG?=Release
WASI_SDK_VERSION=12

WASI_OBJ_DIR=$(TOP)/artifacts/obj/mono/Wasi.$(RUNTIME_CONFIG)
WASI_BIN_DIR=$(TOP)/artifacts/bin/mono/Wasi.$(RUNTIME_CONFIG)
WASI_SDK_ROOT=$(WASI_OBJ_DIR)/wasi-sdk-$(WASI_SDK_VERSION).0
WASI_SDK_CLANG=$(WASI_SDK_ROOT)/bin/clang
