<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <DisableProjectBuild Condition="'$(TargetsMobile)' == 'true' and ('$(TargetsBrowser)' != 'true' or '$(RuntimeFlavor)' != 'coreclr')">true</DisableProjectBuild>
    <Optimize>True</Optimize>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="AddressThroughFields.cs">
      <HasDisasmCheck>true</HasDisasmCheck>
    </Compile>
    <CLRTestEnvironmentVariable Include="DOTNET_TieredCompilation" Value="0" />
    <CLRTestEnvironmentVariable Include="DOTNET_JITMinOpts" Value="0" />
  </ItemGroup>
</Project>
