<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Needed for collectible AssemblyLoadContext -->
    <RequiresProcessIsolation>true</RequiresProcessIsolation>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="StaticsUnloaded.csproj" />
    <Compile Include="CollectibleTLSStaticCollection.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="$(TestLibraryProjectPath)" />
  </ItemGroup>
</Project>
