// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Generated by eng/bxl/port_bazel_tests.py from BUILD.bazel.
// Hand-edit only if you also remove the generator from this dir.

import * as CoreClr from "CoreClrTest";

@@public
export const jIT_HardwareIntrinsics_X86_Avx512_Avx512BW_avx512BW_handwritten_r = CoreClr.coreclr_test({
    name: "Avx512BW_handwritten_r",
    srcs: ["HandwrittenProgram.cs", "//src/tests/JIT/HardwareIntrinsics/X86/Shared:SimpleUnOpTest_DataTable.cs", "ConvertToVector512Int16.Byte.cs", "ConvertToVector512Int16.SByte.cs", "ConvertToVector512UInt16.Byte.cs", "ConvertToVector512UInt16.SByte.cs", "Store.cs"],
});

@@public
export const jIT_HardwareIntrinsics_X86_Avx512_Avx512BW_avx512BW_handwritten_ro = CoreClr.coreclr_test({
    name: "Avx512BW_handwritten_ro",
    srcs: ["HandwrittenProgram.cs", "//src/tests/JIT/HardwareIntrinsics/X86/Shared:SimpleUnOpTest_DataTable.cs", "ConvertToVector512Int16.Byte.cs", "ConvertToVector512Int16.SByte.cs", "ConvertToVector512UInt16.Byte.cs", "ConvertToVector512UInt16.SByte.cs", "Store.cs"],
    optimize: true,
});

@@public
export const jIT_HardwareIntrinsics_X86_Avx512_Avx512BW_avx512BW_r = CoreClr.coreclr_test({
    name: "Avx512BW_r",
    srcs: ["Program.Avx512BW.cs", "//src/tests/JIT/HardwareIntrinsics/X86/Shared:Program.cs"],
});

@@public
export const jIT_HardwareIntrinsics_X86_Avx512_Avx512BW_avx512BW_ro = CoreClr.coreclr_test({
    name: "Avx512BW_ro",
    srcs: ["Program.Avx512BW.cs", "//src/tests/JIT/HardwareIntrinsics/X86/Shared:Program.cs"],
    optimize: true,
});
