#!/bin/sh
#
# Licensed to the .NET Foundation under one or more agreements.
# The .NET Foundation licenses this file to you under the MIT license.
#

PACKAGE=$1
INSTALL_DESTINATION=$2

_machine=`uname -m`

# A temporary fix for the permissions issue(s)
chmod 755 $INSTALL_DESTINATION/dotnet

if ["$_machine" == "amd64"] || ["$_machine" == "x86_x64"]; then
    # Add the installation directory to the system-wide paths
    # But first create the directory if it doesn't exist
    mkdir -p /etc/paths.d
    echo $INSTALL_DESTINATION | tee /etc/paths.d/dotnet
fi

exit 0
